- src/util/KvAuth0.js
This also removes the unused popup login methods.
> perf: delay loading auth0 client until needed

- src/components/LoanCards/LoanCardController.vue
Helps with performance by only loading the loan card component that is going to be displayed instead of loading every possible loan card component.
> perf: dynamically load loan card components VUE-486

- src/components/LoanCards/Buttons/LendAmountButton.vue
- test/unit/specs/components/LoanCards/Buttons/LendAmountButton.spec.js
This component is getting a number from the lend-by-category page and a string from the borrower profile page, an array type was added to the prop to consider this.
> feat: decimal place was removed from the lendamountbutton component

- src/pages/Lend/LoanSearchPage.vue
**Acceptance criteria:**
1. Update the Page Header Type Styles
2. Update the Illustrations used for the “Explore/Filter” navigation
3. Ensure layout is only driven by kv-components and tailwind css
**Steps to test:**
1. Go to [http://localhost:8888/lend/filter-alpha](http://localhost:8888/lend/filter-alpha)
2. Make sure the header design matches the confluence design [https://kiva.atlassian.net/wiki/spaces/LW/pages/1553956887/Lend+filter+Hybrid](https://kiva.atlassian.net/wiki/spaces/LW/pages/1553956887/Lend+filter+Hybrid)
> fix: cleanup page frame VUE-1000

- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
**Ticket:**
[https://kiva.atlassian.net/browse/VUE-1002](https://kiva.atlassian.net/browse/VUE-1002)
**Acceptance criteria:**
1. Moving the Filter Interface into it’s own component
2. Creating a new button to control visibility of the Filter Interface on Small and Medium screens.
3. Replicate visual states of the Filter Interface for Mobile (Full Screen Lightbox) and Medium (Page Overlay)
**NOTES:**
Functionality will be added within another ticket.
> feat: Hidden + Visible version of the filter menu VUE-1002

- src/components/Lend/LoanSearch/LoanSearchFilter.vue
**AC**
Stub out the FLSS filters and the Advanced Filters container following the design mocks.
**Steps to test:**
Go to [http://localhost:8888/lend/filter-alpha](http://localhost:8888/lend/filter-alpha)
Filter menu should match the figma design
> feat: flss filter styles VUE-1004

- src/components/Checkout/SocialShareV2.vue
- src/components/Thanks/ThanksLayoutV2.vue
- src/graphql/query/thanksPage.graphql
- src/pages/Thanks/ThanksPage.vue
- Set share view as default
- Updated share links 
- Updated graphQL query to get the unreserved loan amount
- Added and updated some css styles
- Added share experiment tracking for ticket [MARS-97](https://kiva.atlassian.net/browse/MARS-97)
[MARS-96](https://kiva.atlassian.net/browse/MARS-96)
[MARS-97](https://kiva.atlassian.net/browse/MARS-97)
> feat: expand share experience

- package-lock.json
- src/pages/Donate/DonateFromMacroHero.vue
- src/pages/Donate/DonateSupportUs.vue
- test/e2e/specs/MetaInfo.spec.js
- Added meta info for donate SEO pages
> feat: donate seo page updates

- src/graphql/query/checkout/initializeCheckout.graphql
- src/graphql/query/checkout/shopBasketUpdate.graphql
- src/pages/Checkout/CheckoutPage.vue
adds promo credits to the checkout page and removes the legacy redirect.
> feat: add promo creds to checkout page

- src/components/Checkout/SocialShareV2.vue
- Fixed visual issues
https://user-images.githubusercontent.com/102815442/167918604-95056a72-1d68-465e-9061-658a634727d3.mov
> fix: fixed visual issues

- server/index.template.html
- Performance improvement
[MARS-117](https://kiva.atlassian.net/browse/MARS-117)
> feat: performance improvement

- src/components/LoanCollections/KivaClassicMultiCategoryCarousel.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
- src/util/experimentPreFetch.js
* Adds ending soon as first category on homepage carousel for users in experiment
ACK-290
> feat: lend urgency homepage experiment

- src/components/Checkout/MonthlyGoodCTA.vue
- src/components/Thanks/ThanksLayoutV2.vue
- Updated update event tracking for checkout/thanks pages
[MARS-83](https://kiva.atlassian.net/browse/MARS-83)
> feat: update event tracking for checkout/thanks pages

- src/api/localSchema.graphql
- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/graphql/mutation/updateLoanSearchState.graphql
This is mostly a temporary implementation as it hard codes and initial query. It does however provide a short path to get loans showing on the page again. And marks items in the Filter Interface for removal and cleanup or for extraction into their specific filter components.
> Vue 1006 v2 stub for loan search state watcher

- .storybook/stories/LoanSearchGenderFilter.stories.js
- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/components/Lend/LoanSearch/LoanSearchGenderFilter.vue
- test/unit/specs/components/Lend/LoanSearch/LoanSearchGenderFilter.spec.js
https://kiva.atlassian.net/browse/VUE-1010
- Implemented dedicated radio group for gender
- Added TODOs for some decisions pending new search cache + behavior (new ticket: https://kiva.atlassian.net/browse/VUE-1028)
- Radios won't be clickable until kv-components fix is merged (see other PR coming soon)
- Added new stories + test sections for loan search
> feat: dedicated new gender radio filter using KvRadio

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
Added functionality to show the filter menu within a KvLightbox component.
**Original PR:**
[https://github.com/kiva/ui/pull/3804](https://github.com/kiva/ui/pull/3804)
> KvLightbox added VUE-1021

- package-lock.json
- package.json
https://kiva.atlassian.net/browse/VUE-1010
- Fixed issue where radio buttons weren't clickable
> fix: updated elements package for radio button fix

- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/components/Lend/LoanSearch/LoanSearchGenderFilter.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
https://kiva.atlassian.net/browse/VUE-1028
- Connected gender filter to apollo cache
- Removed hard-coded initial filters
- Changing the gender filter works
> feat: connected gender filter to new apollo cache

- src/pages/Checkout/CheckoutPage.vue
adds the campaign verification form and verify remove promo credit lightbox to `CheckoutPage`
> feat: implement campaign verification form on checkout

- src/components/Checkout/KivaCardRedemption.vue
> fix: ensure redemption code amount is shown in the list

- src/pages/Checkout/CheckoutPage.vue
fixes a bug on the checkout page to ensure promo codes are working properly
> fix: fix kiva classic checkout promos

- src/pages/Lend/LendHeader.vue
This PR is to create a CTA to bring users to the personalization quiz lightbox.
> feat: help me choose in the header

- src/router/routes.js
- Added redirects for women and education pages
[MARS-122](https://kiva.atlassian.net/browse/MARS-122)
https://user-images.githubusercontent.com/102815442/168392215-b97aa015-683d-4d93-afe3-1f215edea670.mov
> feat: redirects for women and education pages

- src/pages/ContentfulPage.vue
- src/pages/Donate/DonateSupportUs.vue
- src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
These fields have been added in the dev contentful space
> feat: set page meta description and canonical url from contentful MARS-114

- src/components/Lend/LoanSearch/LoanSearchLocationFilter.vue
https://kiva.atlassian.net/browse/VUE-1024
- Last minute refactor swapped region and country names
> fix: country name was showing region name after refactor

- src/graphql/query/contentfulEntries.graphql
- src/graphql/query/wwwHeader.graphql
- src/pages/ContentfulPage.vue
This feature sets an experiment for redirecting to a new version of the paid ads landing page
[MARS-124](https://kiva.atlassian.net/browse/MARS-124?atlOrigin=eyJpIjoiYWU0ODY1OWQ3MDRkNGNkOTg4YWRiZmI3NzEzYmQzN2QiLCJwIjoiaiJ9)
> feat: redirect to new variant for paid ads lp

- src/graphql/query/checkout/checkoutSettings.graphql
- src/graphql/query/checkout/initializeCheckout.graphql
- src/pages/Checkout/CheckoutPage.vue
implements upsells a/b test on checkout page
> feat: upsells checkout a/b test

- src/components/WwwFrame/PromotionalBanner/Banners/GenericPromoBanner.vue
- src/components/WwwFrame/PromotionalBanner/GlobalPromotionalBannerContentful.vue
* Allows banner to be added with no icon
MRKT-564
> feat: remove default promo banner icon

- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/components/Lend/LoanSearch/LoanSearchSectorFilter.vue
- src/util/loanSearchUtils.js
> feat: added loan sector filter VUE-1023

- package-lock.json
- src/components/Kv/KvLoadingOverlay.vue
- src/components/Lightboxes/AddToBasketInterstitial.vue
- src/components/LoanCards/LoanCardController.vue
- src/components/LoanCards/PromoGridLoanCard.vue
- src/components/LoansByCategory/ViewToggle.vue
- src/components/WwwFrame/CookieBanner.vue
- src/components/WwwFrame/SearchBar.vue
- src/pages/Lend/LendHeader.vue
- Added cache function to Lending page components
[MARS-131](https://kiva.atlassian.net/browse/MARS-131)
> feat: add lending page components caching

- src/pages/Lend/LoanChannelCategoryControl.vue
- Fixed canonical url issues related to pagination query
[MARS-132](https://kiva.atlassian.net/browse/MARS-132)
> fix: fixed canonical url issues related to pagination query

- src/pages/BorrowerProfile/FundedBorrowerProfile.vue
This PR updates the track event information for the funded borrower profile experiment.
> fix: update track event details

- src/pages/ContentfulPage.vue
- Fix: Show Meta info just when it is defined
[MARS-146](https://kiva.atlassian.net/browse/MARS-146)
> fix: set meta information only if it defined

- src/components/Checkout/UpsellModule.vue
- src/graphql/query/checkout/upsellLoans.graphql
- src/pages/Checkout/CheckoutPage.vue
this PR implements a new feature for an upsell module on the checkout page. this module is behind an experiment / AB test.
desktop-
mobile-
> feat: upsell module on checkout page

- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
https://kiva.atlassian.net/browse/VUE-1067
https://kiva.atlassian.net/browse/VUE-1068
- Reset and advanced filters link now work
- Analytics added to both links
> Vue 1067 activate track the reset all filters link

- server/index.js
- server/live-loan-router.js
- server/util/ddTrace.js
- server/util/fetchGraphQL.js
- server/util/getGqlFragmentTypes.js
- server/util/getSessionCookies.js
- server/util/live-loan/live-loan-draw.js
- server/util/memJsUtils.js
- server/util/vueSsrCache.js
- server/vue-middleware.js
This adds a bunch of manual traces to our server functions to help identify sources of timeouts. This will need to be verified in dev.
> feat: add manual tracing

- server/sitemap/generators/static.js
- Remove redirects from the ui site map
[MARS-135](https://kiva.atlassian.net/browse/MARS-135)
> fix: remove redirect routes from site map

- package-lock.json
- package.json
- server/util/fetch.js
- src/api/HttpLink.js
- src/api/apollo.js
- src/client-entry.js
- src/main.js
- src/server-entry.js
Replace `isomorphic-fetch/node-fetch` with `make-fetch-happen` in server side and `whatwg-fetch` in client side to improve performance by using faster streams, keeping connections alive, and pooling requests.
> feat: change UI fetch implementations

- src/components/Lend/LoanSearch/LoanSearchFilterChips.vue
https://kiva.atlassian.net/browse/VUE-1101
- Added filter chip click analytics, see label format below
```
Country-Togo
Sector-Agriculture
LoanThemeFilter-Disaster recovery
Gender-Women
```
> feat: filter chip click analytics

- src/pages/BorrowerProfile/BorrowerProfile.vue
- Redirect to lend/id when loan status is not fundraising
[MARS-153](https://kiva.atlassian.net/browse/MARS-153)
> fix: redirect to lend/id when loan status is not fundraising

- src/components/BorrowerProfile/LendCta.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
update copy text for matched loans on borrower profile page as part of required deposits on matched loans experiment
> feat: update copy text for matched loans

- src/components/BorrowerProfile/LoanUse.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
- src/pages/BorrowerProfile/FundedBorrowerProfile.vue
- src/plugins/loan-use-filter.js
- test/unit/specs/plugins/loanUseFilter.spec.js
This also adds the anonymization level to the loan use filter to reduce the number of places the level had to be checked.
> fix: update copy for borrower profile share card

- src/components/Categories/MainCategoryTile.vue
- src/pages/Categories/CategoriesBeta.vue
Adding a "View all loans" button and hover effects when hovering over a category.
> feat: adding category mouseover effects

- src/components/Thanks/ThanksPageShare.vue
- Add small change to fix copy share link url params structure
> fix: fixed copy share link params structure

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
https://kiva.atlassian.net/browse/VUE-1091
- Reverts to last page if the page query param is too large for the result set
> Vue 1091 revert to last page if larger number added

- src/components/LoanCards/ListLoanCard.vue
https://kiva.atlassian.net/browse/VUE-1102
> fix: added missing loan card padding

- src/components/Kv/KvPagination.vue
https://kiva.atlassian.net/browse/VUE-1151
> feat: pager now uses new KvMaterialIcon

- src/pages/Settings/SavedSearchBeta.vue
Removed previous linting errors!
> feat: created method to get saved searches

- src/components/Checkout/MatchedLoansLightbox.vue
- src/pages/Checkout/CheckoutPage.vue
* updates lightbox copy for required deposits on matched loans 
* fix state issue with `showMatchedLoanKivaCredit`
> fix: update lightbox copy and fix info box

- src/components/Checkout/MatchedLoansLightbox.vue
updates matched loans lightbox header per product request
> fix: update matched loans lightbox header

- src/components/WwwFrame/LendMenu/LendMegaMenu.vue
Nathan recommended changing this color for accessibility contrast requirements. Also, minor formatting
ACK-340
> fix: recommended by lender menu link accessibility fix

- src/pages/Lend/LoanChannelCategoryControl.vue
- Set loans per page value according promo card availability
#Ticket
[MARS-170](https://kiva.atlassian.net/browse/MARS-170)
> fix: set loans per page value according promo card availability

- src/components/Categories/LoanSpotlight.vue
- src/components/Categories/MainCategoryTile.vue
ACK-344
I had to adjust the max height from 390px to 450px for certain photos that have the person placed very low in the image.
> fix: category page design revisions

- src/pages/Lend/LoanChannelCategoryControl.vue
https://kiva.atlassian.net/browse/VUE-1175
- The issue has to do with subtracting 1 from `loansPerPage` for the monthly good promo
- The specific issue seemed to be that the `loansPerPage` variable in memory kept getting subtracted by 1 with each render, leading to a mismatch in `loansPerPage`, both in the Apollo cache (leading to Apollo cache errors) and between `loansPerPage` and `this.limit` (leading to weird pager behavior)
- I took the opportunity to generally simplify the logic around handling the `offset`, removing several `lodash` imports
> fix: issue with montly good and loans per page

- src/components/BorrowerProfile/LendersListItem.vue
Design fix to fully round first letter image
> fix: round first name letter image

- src/components/Thanks/ThanksPageShare.vue
[MARS-197](https://kiva.atlassian.net/browse/MARS-197)
> fix: fix incorrect utm_content param

- src/components/BorrowerProfile/LendCta.vue
A couple of minor issues once everything was merged in.
> fix: various styling issues for pfp share button

- src/components/BorrowerProfile/LendCta.vue
- src/components/BorrowerProfile/SummaryCard.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
Did some more testing for various BP states. Fix some minor issues
> fix: various styling issues for borrower profiles

- src/components/Kv/KvDropdown.vue
> fix: kvdropdown menu scoped css is breaking padding

- src/components/Checkout/SocialShareV2.vue
- src/components/Thanks/ThanksPageShare.vue
- src/graphql/query/fundedBorrowerProfile.graphql
- src/pages/BorrowerProfile/BorrowerProfile.vue
- src/pages/BorrowerProfile/FundedBorrowerProfile.vue
[MARS-198](https://kiva.atlassian.net/browse/MARS-198)
> fix: added shard card experiment tracking to funded borrower profile component

- src/head/script.js
[MARS-188](https://kiva.atlassian.net/browse/MARS-188)
> feat: enable snowplow performance timing in the snowplow context

- src/pages/Thanks/ThanksPage.vue
- Trigger the share card language experiment from the share thanks page
[MARS-143](https://kiva.atlassian.net/browse/MARS-143)
> fix: move and trigger share card experiment from the share thanks page

- src/components/Settings/SaveSearchItem.vue
- src/pages/Settings/SavedSearchBeta.vue
Decided to make grid layout into cards (hopefully this does not result into an issue with Design)
The second image is here to show that the cards are responsive
> feat: create SavedSearchItem component + use for entry list

- src/components/BorrowerProfile/LendCta.vue
updates complete this loan upper limit to $75 instead of $100
> fix: update complete this loan price

- src/components/WwwFrame/TheHeader.vue
- Looks like  promise not being resolved correctly on the preFetch function
> fix: fixed promise resolve

- src/components/Checkout/UpsellModule.vue
- src/graphql/query/checkout/checkoutSettings.graphql
- src/pages/Checkout/CheckoutPage.vue
experimental updated copy for upsell loans on checkout
> feat: experiment copy for upsells on checkout

- src/pages/BorrowerProfile/BorrowerProfile.vue
- Added canonical url to borrower profile page.
[MARS-206](https://kiva.atlassian.net/browse/MARS-206)
> fix: add canonical url to Borrower Profile page

- src/head/script.js
- src/server-entry.js
Also caches head script render results to help reduce server response times.
> feat: use script tag for oneTrust loader MARS-174

- src/components/Thanks/ThanksPageShare.vue
- src/graphql/query/thanksPage.graphql
- src/pages/Thanks/ThanksPage.vue
- Added new share ask copy experiment on thanks page.
[MARS-202](https://kiva.atlassian.net/browse/MARS-202)
**_Control_**
**_Variant_**
> feat: added share ask copy experiment

- src/components/LoanCollections/KivaClassicLoanCarousel.vue
- src/components/LoanCollections/KivaClassicSingleCategoryCarousel.vue
- src/pages/Lend/LoanChannelCategoryClimateExperiment.vue
* Hide carousel if there are no loans, hide view all card
* Increase carousels to 9 loans
* display "check back later" message as last card if there are less than 9 loans
> feat: tweaks to lbc carousel experiment layout

- src/pages/Checkout/CheckoutPage.vue
show upsell module only if it is less than $100
> feat: show upsells module only if under 100

- src/components/LoanCollections/KivaClassicLoanCarousel.vue
- src/components/LoanCollections/KivaClassicSingleCategoryCarousel.vue
- src/pages/Lend/LoanChannelCategoryClimateExperiment.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
- src/plugins/loan-channel-query-map.js
- src/util/loanSearch/queryParamUtils.js
* Fix loading behavior on LBC control layout
* Add experiment routes to loan channel query map
* fix experiment creation on navigation for lbc template
* add view all loans card back to experiment layout
* modified page background color
* added better loading for category description and carousels
ACK-364
> feat: lbc experimental layout modifications

- src/components/LoanCards/KivaClassicBasicLoanCard.vue
> Revert "fix: kivaClassic Loan card should not show checkout now button"

- src/components/Checkout/SocialShareV2.vue
- Updated utm_campaign from **_social_share_checkout_scle_** to **_social_share_checkout_control_scle_**
[MARS-230](https://kiva.atlassian.net/browse/MARS-230)
> fix: update utm_campaign on current control share thanks page

- src/components/Checkout/SocialShareV2.vue
- src/components/Thanks/ThanksPageShare.vue
- src/pages/Thanks/ThanksPage.vue
- Revert previos change on the SocialShareV2.vue component
- Updated the utm_campaign parameter based on the experiment version (control or variant)
> HOTFIX: update utm_campaign in the correct place

- .storybook/stories/SocialShareButton.stories.js
- src/components/BorrowerProfile/SocialShareButton.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
* make campaign a prop so it can be used in other places besides the bp_pfp
* add referrer as medium for copy link
ACK-378
> feat: update share button component

- src/components/LoanCollections/KivaClassicSingleCategoryCarousel.vue
- src/pages/Lend/LoanChannelCategoryClimateExperiment.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
* Migrate `LoanChannelCategoryClimateExperiment.vue` to use FLSS utilities
* Migrate `KivaClassicSingleCategoryCarousel.vue` to use FLSS utilities
* Remove initial query to get eco experiment subcategory id's from urls, we'll just get them from the loan-channel-query-map
* Refactor `LoanChannelCategoryPage.vue` so that it dynamically loads the layout component on prefetch. This prevents having to run through the preFetch of both the control and experiment before deciding which one to show. 
* A little bit of spacing modifications for the eco experiment layout. 
* Change experiment tracking from 'shown' to 'b' to standardize (will update in prod admin)
> feat: improve performance of lbc eco experiment layout and use FLSS

- src/pages/ContentfulPage.vue
Once I started stacking extra meta tags into the previous approach they would not get picked up during ssr. With this "embedded" approach I could verify the additional tags were updated properly.
I also updated the default for the title which if left empty in Contentful would previous show the title as " | Kiva".
> Patch contentful description meta

- src/client-entry.js
VUE-1245
I did not like the solution of using `beforeRouteUpdate` because then the onus would be on the developer to add that hook and prefetch the components all the way down if a route with a param could possibly be navigated client side with a change in params. 
This solution leaves navigation prefetch behavior as it was unless, the route is the same and the params are different
> fix: client side routing when routing to same route, different params

- src/router/routes.js
combines with https://github.com/kiva/kiva/pull/10816
> fix: add mfa route guard to settings/payments page

- src/components/CorporateCampaign/CampaignThanks.vue
- src/components/WwwFrame/TheHeader.vue
- src/components/WwwFrame/WwwPage.vue
- src/pages/Thanks/ThanksPage.vue
- Added some updates to send data to Optimizely API correctly
[MARS-194](https://kiva.atlassian.net/browse/MARS-194)
> MARS-194: Fixed issues related to cookies and setting optimizely attribute values

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/Lend/LoanSearch/LoanSearchSavedSearch.vue
- src/graphql/mutation/createSavedSearch.graphql
- src/pages/Lend/LoanSearchPage.vue
- src/util/loanSearch/searchStateUtils.js
- test/unit/specs/util/loanSearch/mockData.js
- test/unit/specs/util/loanSearch/searchStateUtils.spec.js
modal for saved search experiment
> saved search modal

- src/assets/icons/inline/sparkles-success.svg
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/Lend/LoanSearch/LoanSearchSavedSearch.vue
- src/pages/Lend/LoanSearchPage.vue
handle success / error for creating saved search
> feat: success message for saved search

- src/pages/Lend/LoanChannelCategoryPage.vue
> feat: add new query param to force game experiment versions

- .storybook/stories/KvLoanCards.stories.js
- src/components/NewHomePage/LoanCards.vue
- src/util/loanUtils.js
- Added new Loan Card vue component 
- Added new Story book template
[MARS-239](https://kiva.atlassian.net/browse/MARS-239)
> MARS-239: new home page loan cards

- package-lock.json
- package.json
- src/components/Contentful/DynamicRichText.vue
- src/components/Contentful/SectionWithBackgroundClassic.vue
- src/components/Contentful/StoryCard.vue
- src/components/Contentful/StoryCardCarousel.vue
- src/pages/ContentfulPage.vue
Depends on kiva/kv-ui-elements#203
Large screens:
Small screens:
> feat: stylized carousel for Story Cards MARS-241

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/pages/Lend/LoanSearchPage.vue
closes success message + shows saved search notification when user updates filters
> fix: show saved search notif when user changes filters

- .storybook/stories/KivaMultiCategoryGrid.stories.js
- Updated KivaMultiCategoryGrid.vue component on story book.
> fix: update KivaMultiCategoryGrid component on story book

- src/components/LoansByCategory/CategoryRowHover.vue
- src/pages/Lend/LendByCategoryPage.vue
These Loan Cards now know when they are in the basket.
> Update lend cta lbc hover card

- src/components/Checkout/UpsellModule.vue
- src/pages/Checkout/CheckoutPage.vue
* adds a query parameter `forceDynamicUpsell` to force experience to use dynamic upsell
* adds some tracking
> feat: add query param to force dynamic upsells + tracking

- src/pages/Lend/LoanChannelCategoryPage.vue
setup a/b test for quick filters on category pages
> feat: a/b test for quick filters

- src/components/LoanCollections/HomeExp/KivaLoanCardCategory.vue
https://user-images.githubusercontent.com/102815442/192317794-95b69859-3e7a-4c81-be16-04ec59f48947.mov
> fix: added media query to fix crashing on category loan cards

- src/pages/ContentfulPage.vue
- src/pages/Homepage/Homepage.vue
- src/router/routes.js
- Added new home page experiment query
- Added new home page experiment tracking
- Load home page based on experiment version
[MARS-249](https://kiva.atlassian.net/browse/MARS-249)
> MARS-249: New home page experiment setup

- src/pages/Lend/LoanChannelCategoryClimateExperiment.vue
> feat: add how it works to LBC climate game page

- src/pages/ContentfulPage.vue
- src/pages/Homepage/Homepage.vue
- src/plugins/apollo-plugin.js
- src/util/apolloPreFetch.js
- Fixed issue while loading new home page experiment
https://user-images.githubusercontent.com/102815442/193158512-5526e202-b4fc-4ed7-bf5e-134ff38dd1f9.mov
https://user-images.githubusercontent.com/102815442/193158590-f4f080a8-c9f7-4159-b1da-8685ed3b7ae8.mov
> MARS-249: fixed flash loading home page experiment

- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/Lend/LoanSearch/LoanSearchSortBy.vue
- src/pages/Lend/LoanSearchPage.vue
- Setup Experiment Setting
- Pass `extendFlssFilters` prop into contexts that will need it
> feat: setup experiment scaffold to gate new flss filter additions

- src/pages/Checkout/CheckoutPage.vue
The `myFTDQueryUtil` and the `achievementsQuery` query were racing against each other. So it would sometimes redirect to the eco-challenge thanks page, but usually it myFTD would finish and it would redirect to the regular thanks. This makes sure that we have the achievements data before the redirect 
I'm not sure why this was the case, at first glance I thought the `await` would be enough, but I see they were getting batched by Apollo as 1 query...
> fix: eco challenge thanks redirect

- src/components/Lend/LoanSearch/LoanSearchFilter.vue
https://kiva.atlassian.net/browse/VUE-1309
- Created new accordion for advanced filters
- Only shown when exp is enabled
> feat: advanced filters accordion

- src/pages/Lend/LoanSearchPage.vue
- The `extend_flss_filters` is now set
- Setting added to dev w/ 50/50 + 100% pop
> feat: extend FLSS exp now pulled

- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
> feat: sort by on quick filters and reset

- src/components/LoansByCategory/QuickFilters/LocationSelector.vue
- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
- src/plugins/loan-channel-query-map.js
adds tracking to quick filters experiment. also fixes a bug where livestock is not using flss query by adding its activityId to the query map.
> feat: quick filters tracking + update

- build/webpack.client.base.conf.js
- src/components/Kv/KvDropdown.vue
- src/util/KvAuth0.js
- src/util/apolloPreFetch.js
- src/util/getDeepComponents.js
- test/unit/specs/util/getDeepComponents.spec.js
A mix of changes to help with performance I found while trying to minimize time-to-interactive. There is much more that could be done for that, but these are some small wins along the way.
> TTI performance enhancements

- .storybook/stories/BorrowerProfile.stories.js
> fix: storybook path was incorrect

- src/components/LoansByCategory/QuickFilters/LocationSelector.vue
> fix: update regions UI on quick filters

- src/components/WwwFrame/TheHeader.vue
- src/graphql/query/wwwHeader.graphql
Remove condition to get `hasEverLoggedIn` value for `hojtar` user attributes
> fix: avoid skipping userData query

- src/pages/Lend/LoanChannelCategoryPage.vue
This will align the loan set in the carousels with what the achievement service is using.
> fix: make sure game users see the FLSS loan results in carousel

- src/components/BorrowerProfile/FundedBorrowerProfile.vue
- src/components/BorrowerProfile/LoanProgress.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
- Removes our older FundedBorrower Profile presentation
- Sets the new Funded BP as the default
- Removes exp code
- Fixes the full profile link to navigate to `/lend-classic`
- Fixes some undefined data fields and conditional values
> Fix funded bp full profile link

- src/components/LoansByCategory/QuickFilters/LocationSelector.vue
- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
> feat: add overlay when location dropdown open quick filters

- src/components/LoansByCategory/HelpmeChoose/BorrowerSelector.vue
- src/components/LoansByCategory/HelpmeChoose/HelpmeChooseBorrowerSelector.vue
- src/components/LoansByCategory/HelpmeChoose/HelpmeChooseRecommendations.vue
- src/components/LoansByCategory/HelpmeChoose/HelpmeChooseWrapper.vue
> Core 777 hc borrower selector

- src/client-entry.js
- src/components/Contentful/HomePage/NewHomeLoansByCategoryGrid.vue
- src/server-entry.js
Detect device type to set the loan card query limit.
https://user-images.githubusercontent.com/102815442/197653310-9d4dd5a1-e44e-4dc5-ae8e-28a74d2c2c85.mov
> MARS-274: Detect device type

- src/components/WwwFrame/TheHeader.vue
Decoupled this from the other pr.
> fix: update My conversations link to lend-classic

- package-lock.json
- package.json
- src/components/LoanCards/GridLoanCard.vue
- src/components/LoanCards/HoverLoanCard/HoverLoanCard.vue
- src/components/LoanCards/LoanCardController.vue
- src/components/LoanCards/LoanTags/LoanTag.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
> feat: implement loan tags on category pages

- src/pages/LendingStats/StatsSection.vue
Matches recent change to use href. Verified in VM
> fix: update collected lend link to work with href

- src/components/WwwFrame/TheFooter.vue
> feat: added EEPR to Homepage Footer within Ui Server [VUE-1353]

- src/components/Homepage/HomeExp/KivaMultiCategoryGrid.vue
- src/components/LoanCollections/HomeExp/LoanCategorySelectorHomeExp.vue
- Small style updates for new home page variant components.
[MARS-308](https://kiva.atlassian.net/browse/MARS-308)
[MARS-309](https://kiva.atlassian.net/browse/MARS-309)
_Before_
_After_
> Hotfix: Style updates for new home page variant components MARS-308 and MARS-309

- src/components/WwwFrame/TheHeader.vue
[MARS-298](https://kiva.atlassian.net/browse/MARS-298)
[Design](https://www.figma.com/file/tiaWcJ8gDQKhpzXXwkhe97/New-user-Journey?node-id=210%3A477)
> MARS-298: Change header login button

- src/plugins/kv-analytics-plugin.js
Donation amount added as a tag to loan_share_purchase event for optimizely tracking in kv-analytics plugin
> feat: donation amount added to loan share purchase event

- src/api/localResolvers/loanSearch.js
- src/api/localSchema.graphql
- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/graphql/mutation/updateLoanSearchState.graphql
- src/graphql/query/loanSearchState.graphql
- src/util/loanSearch/filterConfig.js
- src/util/loanSearch/filters/isMatchable.js
- test/unit/fixtures/mockLoanSearchData.js
- test/unit/specs/util/loanSearch/filters/isMatchable.spec.js
https://kiva.atlassian.net/browse/VUE-1388
- Implemented `isMatchable` lend/filter filter
> feat: isMatchable lend filter

- src/pages/Categories/CategoriesPage.vue
- src/router/routes.js
- test/e2e/specs/CategoriesPage.cy.js
- test/e2e/specs/MetaInfo.cy.js
Making the categories-beta route the official categories route. And rename component and tests
> feat: make categories-beta categories page

- src/components/LoansByCategory/QuickFilters/CheckboxList.vue
- src/components/LoansByCategory/QuickFilters/LocationSelector.vue
- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
callback props were removed from some quick filter components and avoiding emitting events in a loop
the overlay was refactored and unused css code removed
> Core 820 quick filters refactor

- src/components/BorrowerProfile/LendCta.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
Experiment code for complete loan experience removed in the borrower profile becoming a feature.
> Core 791 remove complete loan exp code

- config/audit.js
- config/dev-vm.js
- config/dev.js
- config/index.js
- config/qa.js
- config/stage.js
- config/test.js
- src/head/script.js
- src/plugins/kv-analytics-plugin.js
A similar PR will be created in the monolith repo.
> Remove Quantcast, Algolia analytics, and duplicate Facebook pixel MARS-166

- src/components/Kv/KvSelectBox.vue
https://kiva.atlassian.net/browse/VUE-1418
- Mobile select box couldn't be closed
> fix: select box needs touch event

- src/components/BorrowerProfile/CompleteLoanWrapper.vue
- src/components/BorrowerProfile/LendCta.vue
fixing size for cta in borrower profile
> fix: cta size fixed in borrower profile page

- src/pages/Homepage/Homepage.vue
Due to Year in Review Share we want to conditionally set a generic image in share cards. The output is to hand over a generic share URL for fb, twitter and linkedin to marketing.
> feat: conditional share card image for new year campaign

- src/components/Thanks/ShareStepper.vue
- src/components/Thanks/ShareStepperStep.vue
- src/components/Thanks/ThanksPageShare.vue
- src/pages/Thanks/ThanksPage.vue
Winning variant tested on Optimizely. This work contains:
- Remove confetti
- Remove confirmation email banner
- Add Stepper on Thanks Page
> 'Stepper' on Focused Share Ask on Thanks page

- src/components/BorrowerProfile/LendCta.vue
margin bottom fixed for amount selector in the lendCta component
> Core 899 bp fix lend button UI

- src/pages/LoanFinding/LoanFinding.vue
Personalized welcome message added to lending home page
> feat: welcome message added to lending home page

- src/plugins/kv-analytics-plugin.js
https://kiva.atlassian.net/browse/VUE-1419
> fix: removed TransactionInfo FB event

- src/components/LoanFinding/QuickFiltersSection.vue
- src/pages/LoanFinding/LoanFinding.vue
Quick filter section component created for new lending page, logic will be added in other ticket
> Core 868 quick filters section lending page

- src/components/LoanFinding/QuickFiltersSection.vue
- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
`withCategories` prop added to QuickFilters component to include category dropdown and new design
there is some work left for data logic and new sort by dropdown design planned in other tickets
this update is not affecting our current quick filters experiment
> Core 904 extending quick filters component

- src/components/Thanks/ShareStepper.vue
> fix: stepper title style

- src/components/LoanCards/KivaClassicBasicLoanCard.vue
- src/pages/LoanFinding/LoanFinding.vue
edits kiva classic loan card to accommodate new loan card for MVP loan finding page (loan cards to be revisited later after mvp stage)
> feat: new temp loan cards for MVP loan finding page

- src/components/Checkout/DonationItem.vue
* Adds another variant
* Show contentful copy on variant a when there are no loans
ACK-482
> feat: add another donation item variant

- src/components/Checkout/KivaCardItem.vue
https://kiva.atlassian.net/browse/VUE-1369
> feat: checkout page support for lender kiva cards

- src/plugins/kv-analytics-plugin.js
- src/util/checkoutUtils.js
Validate loan total value before sending optimizely revenue tracking event
> test: optimizely only recognize in value in cents

- src/components/Thanks/ThanksPageShare.vue
- src/pages/Thanks/ThanksPage.vue
Experiment name missing for category share and fix `shareLink`
> fix: exp name

- src/components/BorrowerProfile/FundedBorrowerProfile.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
* makes MARS-143 share language the default for meta preview description and title
* cleanup funded borrower profile variables
ACK-484
> feat: improve loan meta preview

- src/components/LoanFinding/QuickFiltersSection.vue
- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
Adding default value to category options avoiding an empty state on initial load
> feat: default value added to category dropdown options

- src/components/Thanks/ShareStepper.vue
- src/components/Thanks/ThanksPageShare.vue
- src/pages/Thanks/ThanksPage.vue
> fix: copy for agriculture, show lender name in stepper within control

- src/components/Thanks/ThanksPageShare.vue
Share link overrides due to condition
> Fix category share copy

- src/components/BorrowerProfile/HeroBackground.vue
* Try to use city background, if not use state background, if not use country background, if not use placeholder
ACK-472
> feat: add support for additional bp backgrounds

- src/components/BorrowerProfile/LendCta.vue
- src/components/BorrowerProfile/LoanDescription.vue
- src/components/BorrowerProfile/LoanStory.vue
- src/components/BorrowerProfile/MoreAboutLoan.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
Track experiment to only non-depositor or non-lender users
> Fix user context exp

- src/pages/Donate/DonateForm.vue
- src/pages/Donate/DonateSupportUs.vue
* Allow setting value to select amount on donation form
* If setting is not available select 3rd amount.
ACK-490
> feat: setting for preselected amount on donation form

- src/components/LoanFinding/QuickFiltersSection.vue
kv-pagination component added to quick filter section in new lending page
tailwind grid classes added to loan grid
logic for pagination will be worked in other ticket
> feat: kvpagination component added to new quick filter section

- src/components/LoanFinding/LendingCategorySection.vue
- src/pages/LoanFinding/LoanFinding.vue
Adding a new section to lending page to show recommended loans in a carousel
*Work for data fetching, carousel and loan cards in other tickets
> feat: recommended loans section added to lending page

- src/components/LoanFinding/LendingCategorySection.vue
- src/pages/LoanFinding/LoanFinding.vue
`getRecommendedLoans` method added to get loans sorted by personalized for recommended loans row.
> feat: data fetching method added for recommeded loans in lending page

- src/pages/BorrowerProfile/BorrowerProfile.vue
https://kiva.atlassian.net/browse/VUE-1463
- I couldn't find usages of `state`, `description`, `isExpiringSoon`, or `reservedAmount`
- `my.userAccount` is used to populate the URLs/UTMs in `ShareButton`, so those were moved to `mounted`
> Vue 1463 - Move some borrower profile prefetch

- src/components/LoanFinding/LendingCategorySection.vue
- src/pages/LoanFinding/LoanFinding.vue
`kv-carousel` added to `LendingCategorySection` component to show recommended loans in lending page
> Core 896 kv carousel recommended loans

- src/components/LoanFinding/QuickFiltersSection.vue
- src/components/LoansByCategory/QuickFilters/LocationSelector.vue
- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- src/pages/LoanFinding/LoanFinding.vue
- some design and ux fixes
- flss origin context updated
> feat: design and ux updates for lending home page

- src/graphql/query/thanksPage.graphql
- src/pages/Thanks/ThanksPage.vue
- src/util/hotJarUserAttributes.js
For being able to target users in hotjar who:
- Have just made their first ever loan transaction, and 
- if their transaction contained a core or direct loan(s).
> Mars 306 user first loan hotjar

- src/plugins/unbounce-event-mixin.js
- src/router/routes.js
- Sends event trigger to GTM, which loads unbounce script
- Pop up and additional display conditions controlled through unbounce. 
Have not added GTM tag/trigger to production, added in dev.
> feat: add unbounce script for donation pop up

- src/components/LoanFinding/PartnerSpotlightSection.vue
- src/components/LoansByCategory/MFIRecommendations/MFIHero.vue
- src/components/LoansByCategory/MFIRecommendations/MfiLoanCard.vue
- src/components/LoansByCategory/MFIRecommendations/MfiLoansWrapper.vue
- src/pages/LoanFinding/LoanFinding.vue
partner spotlight section added to lending page
there is a ticket to update tracking code for data fetching
> Core 917 partner spotlight lending page

- src/components/LoanFinding/PartnerSpotlightSection.vue
tracking event added when no loans find for partner spotlight section in lending page
> feat: tracking event added when no loans find for partner spotlight

- lighthouserc-prod.js
- src/router/routes.js
Redirect `lp/support-refugees` to `/refugees`
> Mars 322 redirect refugees

- src/components/LoanCards/KivaClassicBasicLoanCard.vue
- src/components/LoanFinding/QuickFiltersSection.vue
- src/components/LoansByCategory/QuickFilters/LocationSelector.vue
- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
adds tracking for quick filters on MVP lending page. also fixes a bug with the location selector.
> feat: tracking for mvp quick filters

- src/components/LoansByCategory/QuickFilters/LocationSelector.vue
Icon added to location dropdown in quick filters component
> Core 930 location dropdown style

- src/pages/Homepage/Homepage.vue
Add year in review title for Linkedin and Twitter
> feat: add title

- src/components/WwwFrame/TheBasketBar.vue
Due to last year change in Borrower profile route, Basket Bar exclusions route needed to updated
> fix: add lend route to exclusion array

- src/pages/Checkout/CheckoutPage.vue
kv loading placeholder component added to upsell feature
> feat: loading state added to upsell feat

- src/components/Checkout/UpsellModule.vue
- src/graphql/query/checkout/checkoutSettings.graphql
- src/pages/Checkout/CheckoutPage.vue
test code for upsell copy was removed becoming part of the upsell feat
settings in admin will be removed 'til the code release on prod
> Core 943 upsell copy test cleanup

- src/components/Thanks/ThanksLayoutV2.vue
- src/graphql/query/thanksPage.graphql
- src/pages/Thanks/ThanksPage.vue
Removing auto deposit upsell experiment code from https://kiva.atlassian.net/browse/CORE-427
[CORE-427]: https://kiva.atlassian.net/browse/CORE-427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: remove auto deposit upsell

- src/components/Thanks/ThanksPageShare.vue
Small fix in thanks page copy for fully funded loans
> fix: remove question mark in copy

- src/pages/Lend/LoanChannelCategoryPage.vue
test code for quick filters feat removed in category page
> Core 927 qf test code cleanup

- src/components/BorrowerProfile/JournalUpdates.vue
> feat: add ability to link to updates section in bp

- package-lock.json
- src/pages/MonthlyGood/HowItWorks.vue
- src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
how it works section in monthlygood page was updated to be managed in contetful
> Core 543 mg how works contentful

- src/components/BorrowerProfile/UpdateDetails.vue
> feat: add read more functionality to journal entries in bp

- src/components/BorrowerProfile/UpdateDetails.vue
- src/components/Kv/KvSocialShareButton.vue
> feat: add ability to share updates on social media

- src/components/Checkout/OrderTotals.vue
- The total text moved on the page, so the test ID had to be removed (robot changes coming later in that repo)
> fix: updated order totals test ID

- src/pages/LoanFinding/LoanFinding.vue
https://kiva.atlassian.net/browse/CORE-936
- Created temp lend query to use for the matching row
> feat: use legacy for matching in lending-home

- src/components/LoanFinding/LendingCategorySection.vue
- src/components/LoanFinding/PartnerSpotlightSection.vue
- src/components/LoanFinding/QuickFiltersSection.vue
- src/components/LoansByCategory/MFIRecommendations/MfiLoansWrapper.vue
- src/pages/LoanFinding/LoanFinding.vue
- background for every section updated
- width fixed as /lend/filter page specs
> Core 948 lending home update backgrounds

- src/components/BorrowerProfile/JournalUpdates.vue
> fix: journal updates in bp should use correctly sized image

- src/pages/BorrowerProfile/BorrowerProfile.vue
ACK-499
This experiment is going permanent
> refactor: clean up bp share button experiment code

- src/components/LoansByCategory/MFIRecommendations/MfiLoansWrapper.vue
control navigation updated for partner spotlight carousel similar to other carousels in the same page
> feat: navigation updated in partner spotlight carousel

- src/components/LoanCollections/KivaClassicLoanCarouselExp.vue
- src/components/LoanFinding/LendingCategorySection.vue
- src/components/LoansByCategory/QuickFilters/LocationSelector.vue
https://kiva.atlassian.net/browse/CORE-958
https://kiva.atlassian.net/browse/CORE-967
https://kiva.atlassian.net/browse/CORE-953
https://kiva.atlassian.net/browse/CORE-965
- Scrolling issues resolved
- Medium browser window now also uses "large" location selector
> Core 953 recommended loan cards change size after scrolling

- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
> fix: mobile ui updates for quick filters

- src/components/LoanFinding/QuickFiltersSection.vue
- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
https://kiva.atlassian.net/browse/CORE-970
https://kiva.atlassian.net/browse/CORE-960
- Fixed issues with default quick filter sort
> fix: resolved issues with default sorts

- src/components/Checkout/OrderTotals.vue
- Turns out the ID I wanted was already on another element...
- This ID is not used (I added it in a recent PR)
> fix: removed unused test ID

- src/components/BorrowerProfile/UpdateDetails.vue
- src/components/Checkout/SocialShareV2.vue
- src/components/Kv/KvSocialShareButton.vue
- src/components/Thanks/ThanksPageShare.vue
- src/pages/Thanks/ThanksPageEcoChallenge.vue
* Add new action 'share' and new category 'post-checkout'
* modify sharing events to use new category and action
* add utmCampaign to sharing events
ACK-510
Action and new category added in snowplow repo.
> feat: modify sharing events

- package-lock.json
- package.json
- src/pages/LoanFinding/LoanFinding.vue
kv-toast component added to lending home page to show a welcome message once per session
> feat: welcome toast added to lending home page

- src/pages/Lend/LoanChannelCategoryControl.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
Experiment setup added to show a new loan card in the category page
Test added to active experiments setting in dev
> feat: experiment setup added to category page to show a new loan card

- src/components/LoansByCategory/MFIRecommendations/MFIHero.vue
partner spotlight hero updated for medium sizes
> Core 920 spotlight testing

- .storybook/stories/KvSocialShareButton.stories.js
- src/api/localResolvers/loan.js
- src/components/BorrowerProfile/ShareButton.vue
- src/components/Checkout/SocialShareV2.vue
- src/components/Kv/KvSocialShareButton.vue
- src/components/Thanks/ThanksPageShare.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
- test/unit/specs/api/localResolvers/loan.spec.js
* Make Bp sharing modal different and editable for borrowers vs lenders
ACK-462
Reference links for linkedin api change: https://github.com/bradvin/social-share-urls#-linkedin
> feat: personalized sharing modal

- src/components/Kv/KvSocialShareButton.vue
Copy button should also copy the message
> feat: change copy link to copy message and link in share for bp

- src/components/LoanFinding/WelcomeLightbox.vue
> fix: increase margin on loan finding page lightbox mobile

- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
> feat: hide reset on quick filters when no filters applied

- src/components/LoansByCategory/HelpmeChoose/DynamicCard.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
Help me choose feat rolled out to all category pages.
As the same condition for loan tags, this feat rolled out to all category pages too. Approved by Lauren.
Unused file component removed.
> feat: rolling out help me choose feat to all category pages

- src/pages/Lend/LoanChannelCategoryControl.vue
Pagination reset in category page when filters are updated
> feat: pagination reset added in category page

- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- src/components/LoanCards/LoanUse.vue
- test/unit/specs/components/LoanCards/LoanUse.spec.js
https://kiva.atlassian.net/browse/CORE-974
- Created a new `LoanUse` component for the cards w/ unit tests to verify use cases
> feat: updated loan card use statement

- src/pages/Lend/LoanChannelCategoryControl.vue
- src/util/loanChannelUtils.js
- test/unit/specs/util/loanChannelUtils.spec.js
Remove FLSS experiment scaffolding
> Cleanup category page flss exp vue 1235

- src/plugins/loan-channel-query-map.js
> chore: update loan channel query map

- src/components/LoansByCategory/HelpmeChoose/HelpmeChooseWrapper.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
https://kiva.atlassian.net/browse/CORE-1040
- Added tags and the new loan card exp to the help me choose exp
- Realized that the new loan cards had the wrong lend buttons, changed to better match previous loan cards on that page
> feat: use new loan card in help me choose during experiment

- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- src/components/LoanCards/LoanTags/LoanTagV2.vue
> feat: add new loan tags to new loan cards

- deploy/charts/templates/autoscale.yaml
Address Kubernetes HPA deprecation warnings
> fix: hpa deprecation warning

- src/pages/Lend/LoanChannelCategoryControl.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
Code for help me choose test removed in category page b/c the test is rolled out to 100% and implemented to all categories showed in category page
> Core 926 remove helpme choose testcode

- .storybook/stories/LendCtaExp.stories.js
- src/components/LoanCards/Buttons/LendCtaExp.vue
- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
New `LendCtaExp` component created and added to new loan card component
This new component based on this existing component https://github.com/kiva/ui/blob/main/src/components/BorrowerProfile/LendCta.vue
Stories added for diff states in the component
> Core 976 button style loan card

- src/pages/Lend/LendByCategoryPage.vue
https://kiva.atlassian.net/browse/CORE-1060
> fix: only log lending-home exp for logged-in users

- src/components/LoanCards/LoanProgressGroup.vue
> fix: updated new orange

- src/components/LoanFinding/LendingCategorySection.vue
- src/components/LoanFinding/PartnerSpotlightSection.vue
- src/components/LoanFinding/QuickFiltersSection.vue
- src/pages/LoanFinding/LoanFinding.vue
New loan card experiment setup added to lending home page
> feat: new loan card exp setup added to lending home page

- src/components/BorrowerProfile/ShareButton.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
Some more conditionals for the share modal. Also refactored switch statements for ternaries... 
ACK-516
> feat: modified bp share language for loans in pfp

- src/components/WwwFrame/LendMenu/TheLendMenu.vue
- src/components/WwwFrame/TheHeader.vue
https://kiva.atlassian.net/browse/CORE-1036
- "Lend" renamed to "Categories" and click event to navigate removed
- New "Explore loans"/"Explore" button that takes the old "Lend" click event -> LBC
- Moved experiment initialization, since I put it in the wrong component previously (oops)
https://www.loom.com/share/b3e0023c177b453d8cb1c7756139d81a
> Core 1036 split lend click and lend dropdown

- src/pages/LoanFinding/LoanFinding.vue
https://kiva.atlassian.net/browse/CORE-1087
- We've been asked to keep the LH experiment isolated, so rolling back the FLSS isMatchable work temporarily
- Code help + commented out - ticket created for follow-up
> fix: reverted FLSS isMatchable work

- src/components/WwwFrame/TheHeader.vue
https://kiva.atlassian.net/browse/CORE-1096
- Clicking now opens the menu (keeps it open) instead of navigating
> fix: categories button click behavior

- src/pages/LoanFinding/LoanFinding.vue
`LoanFinding` component updated to show a combo of Almost funded + Ending soon if there are not matched loans.
Second category row rendered until data is ready avoiding extra slots in the carousel like image above
> Core 1046 lh matched loans update

- src/pages/BorrowerProfile/BorrowerProfile.vue
> feat: move journals up on the page

- src/components/Categories/LoanSpotlight.vue
- src/components/LoanFinding/QuickFiltersSection.vue
- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- src/util/loanChannelUtils.js
- test/unit/specs/util/loanChannelUtils.spec.js
- Added some missing optional chaining based on sentry errors
- Logged when a category isn't found in the map file
> Fix some undefined issues

- src/components/LoansByCategory/FeaturedHeroLoanWrapper.vue
- Cleaning up another undefined error in DD from today
https://app.datadoghq.com/logs?query=status%3Aerror%20env%3Aprod%20service%3Akiva-ui&cols=host%2Cservice&event=AQAAAYZSVxuwbLmXKQAAAABBWVpTVnlGSUFBQ3l4ZG1KUVNGVDF3QUs&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1676404315801&to_ts=1676418715801&live=true
> fix: missing fallback array

- src/components/LoanFinding/LendingCategorySection.vue
new loan card width fixed to avoid shadow cut off in LH page
> fix: card width fixed for carousels in lh page

- src/util/loanSearch/filters/distributionModels.js
- src/util/loanSearch/filters/genders.js
- src/util/loanSearch/filters/partners.js
- src/util/loanSearch/filters/regions.js
- src/util/loanSearch/filters/sectors.js
- src/util/loanSearch/filters/tags.js
- src/util/loanSearch/filters/themes.js
- src/util/loanSearch/queryParseUtils.js
- test/unit/specs/util/loanSearch/filters/distributionModels.spec.js
- test/unit/specs/util/loanSearch/filters/genders.spec.js
- test/unit/specs/util/loanSearch/filters/partners.spec.js
- test/unit/specs/util/loanSearch/filters/regions.spec.js
- test/unit/specs/util/loanSearch/filters/sectors.spec.js
- test/unit/specs/util/loanSearch/filters/tags.spec.js
- test/unit/specs/util/loanSearch/filters/themes.spec.js
- test/unit/specs/util/loanSearch/queryParseUtils.spec.js
https://kiva.atlassian.net/browse/CORE-1159
- Noticed a sentry error related to lend/filter not handling undefined facets on route change
- Not sure why this is happening and can't repro, but adding some optional chaining, since the fallout in these cases is the user just not having filters applied in some cases, which is OK
> Resolve gender sentry error

- src/assets/data/components/LoanFinding/spotlightData.json
duplicated data replaced in spotlightData json file
> fix: duplicated data replaced in spotlightdata file

- src/assets/data/components/LoanFinding/spotlightData.json
- src/components/LoanFinding/PartnerSpotlightSection.vue
- src/pages/LoanFinding/LoanFinding.vue
tracking events added for spotlight variations views and add to basket action for each case
> Core 1037 spotlight tracking

- src/util/loanUtils.js
- test/unit/fixtures/mockLoanData.js
- test/unit/specs/util/loanUtils.spec.js
https://kiva.atlassian.net/browse/CORE-1080
- Wrote unit tests for `loanCallouts`
- Uncovered and fixed a number of edge cases
> feat: loanCallouts unit tests and associated fixes

- src/pages/LoanFinding/LoanFinding.vue
- number of loans for recommended section in lending home increased to 12
> feat: number of loans for recommended section in lh increased to 12

- src/components/LoanCards/LoanProgressGroup.vue
- test/unit/specs/components/LoanCards/LoanProgressGroup.spec.js
- copy text updated in progress bar component when loan is already funded
> feat: progress bar copy updated when loan is already funded

- src/components/LoanFinding/LendingCategorySection.vue
- src/components/LoanFinding/QuickFiltersSection.vue
- src/pages/LoanFinding/LoanFinding.vue
- white spaces reduced in lending home page for product qa
> Core 1101 lh reduce white space top

- src/util/loanSearch/filterUtils.js
- src/util/loanSearch/filters/distributionModels.js
- src/util/loanSearch/filters/genders.js
- src/util/loanSearch/filters/partners.js
- src/util/loanSearch/filters/regions.js
- src/util/loanSearch/filters/sectors.js
- src/util/loanSearch/filters/sortOptions.js
- src/util/loanSearch/filters/tags.js
- src/util/loanSearch/filters/themes.js
- test/unit/specs/util/loanSearch/filterUtils.spec.js
- test/unit/specs/util/loanSearch/filters/distributionModels.spec.js
- test/unit/specs/util/loanSearch/filters/genders.spec.js
- test/unit/specs/util/loanSearch/filters/partners.spec.js
- test/unit/specs/util/loanSearch/filters/regions.spec.js
- test/unit/specs/util/loanSearch/filters/sectors.spec.js
- test/unit/specs/util/loanSearch/filters/sortOptions.spec.js
- test/unit/specs/util/loanSearch/filters/tags.spec.js
- test/unit/specs/util/loanSearch/filters/themes.spec.js
- Noticed a couple other sentry prod errors related to undefined facets
- Not sure on the repro steps, but adding in some safe coding is fine, and the fallout for users shouldn't be noticeable
https://kiva.sentry.io/issues/3963036193/?project=1201288&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d
https://kiva.sentry.io/issues/3726872726/?project=1201288&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d
> Fix another filter sentry error

- src/pages/LoanFinding/LoanFinding.vue
https://kiva.atlassian.net/browse/CORE-1131
- Turns out the LCP score was being mostly affected by the large loan images being pulled in on mounted
- Prefetching the top 2 recommended loans ensures the images are visible on initial page load
- There are many other Lighthouse changes that we can make, but this is a good first step
> feat: server cache data for first two recommended loans

- src/pages/LoanFinding/LoanFinding.vue
lazy loading method added to spotlight section in lending home
> feat: lazy loading method added to spotlight section in lending home

- src/components/LoanCards/Buttons/LendCtaExp.vue
- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- src/components/LoanCards/LoanTags/LoanCallouts.vue
`LendCtaExp` component updated to show a correct message when loan is already funded
> Core 1127 lendctaexp funded update

- src/components/LoansByCategory/QuickFilters/FilterPills.vue
- rearrange feat removed from FilterPills component
> feat: stop gender pills moving when selected

- src/components/Subscriptions/SubscriptionsAutoDeposit.vue
https://kiva.atlassian.net/browse/CORE-806
- Updated the copy in the auto deposit settings (and added a second link to open the settings modal)
> feat: update auto deposit copy

- src/components/LoanCards/HoverLoanCard/InfoPanels/TrusteeInfoPanel.vue
- src/graphql/query/loanPartner.graphql
The `trusteeType` was removed from db and graphql api so is failing to resolve.
> fix: api error from querying trusteeType

- src/components/LoansByCategory/QuickFilters/LocationSelector.vue
- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
- new quick filters ui showed under a test
> Core 1195 filter pills test

- src/api/fixtures/LoanStatusEnum.js
- src/pages/Portfolio/AccountOverview.vue
- src/pages/Portfolio/AsyncPortfolioSection.vue
- src/pages/Portfolio/PortfolioOverviewPage.vue
- src/pages/Portfolio/RecentLoanItem.vue
- src/pages/Portfolio/RecentLoansList.vue
- src/plugins/delay-until-visible-mixin.js
> feat: recent loans section for Portfolio Overview page MARS-350

- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- src/components/LoanCards/LoanUse.vue
- `More` text added to `loanUse` component as requirement for new loan cards
> Core 1200 add more new card

- src/components/Contentful/CampaignLoanWrapper.vue
- src/components/CorporateCampaign/LoanSearch/LoanSearchFilters.vue
- src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
> feat: [CIT-102] changing header of cc landing page to match desgin specs

- src/components/WwwFrame/TheHeader.vue
- src/components/WwwFrame/WwwPageDesign.vue
- src/router/routes.js
Use `a` tag for homepage redirects since cps will handle it.
> feat: replace router-link for hp and comment out hp route

- server/vue-middleware.js
- src/pages/Portfolio/AccountOverview.vue
- src/pages/Portfolio/PortfolioOverviewPage.vue
- src/pages/Portfolio/RecentLoanItem.vue
- src/pages/Portfolio/RecentLoansList.vue
- src/pages/Portfolio/RecommendedLoanSlide.vue
- src/pages/Portfolio/RecommendedLoansList.vue
- src/util/flssUtils.js
> Portfolio overview recommended loans section MARS-351

- src/components/BorrowerProfile/LoanProgress.vue
- src/components/BorrowerProfile/LoanStory.vue
- src/plugins/numeral-filter.js
https://kiva.atlassian.net/browse/CORE-1223
- Special case showing "99%" when a loan is rounded up to "100%" but isn't completely funded
- Removed a prop from a component that no longer exists and was causing minor console error
> Core 1223 loan says 100 funded but is not fully funded

- src/router/routes.js
Remove contentful pages moved to CPS in [CPS #260](https://github.com/kiva/cms-page-server/pull/260)
> refactor: remove contentful pages

- .storybook/stories/PortfolioKivaCreditStats.stories.js
- src/pages/Portfolio/CreditSummaryLightbox.vue
- src/pages/Portfolio/KivaCreditStats.vue
- src/pages/Portfolio/KivaEffectFigure.vue
- src/pages/Portfolio/PortfolioOverviewPage.vue
Credit summary lightbox is still in-progress and will be completed in another ticket.
> feat: kiva credit stats for portfolio overview page MARS-352

- server/util/getGqlPossibleTypes.js
- Temp fix while we wait for `id` field to be released for `my` endpoint
> fix: temp fix for new id field on my endpoint

- src/util/loanSearch/filters/themes.js
https://kiva.atlassian.net/browse/CORE-1169
> feat: add earth day theme

- src/pages/Lend/LendByCategoryPage.vue
- We also needed to check the `savedSearch` object for the loans
> fix: loans were missing from bandit data

- src/components/LoansByCategory/HelpmeChoose/HelpmeChooseRecommendations.vue
- src/components/LoansByCategory/HelpmeChoose/HelpmeChooseWrapper.vue
- $5 notes test prop added to help me choose feature to show the dropdown correctly for the recommended loan
> feat: five dollars notes added to help me choose feat

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/pages/Lend/LoanSearchPage.vue
- new loan card test added to filter page
- customized grid added to filter page to show new loan cards as expected
- state updated if test is enable to match number of loans per page
> Core 1174 new loan card filter page

- src/components/LoanCards/Buttons/LoanBookmarkExp.vue
- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- new bookmark component `LoanBookmarkExp` added for new loan card based in bookmark component for BP summary card.
> feat: new bookmark button added to new loan card

- src/components/BorrowerProfile/LoanStory.vue
ACK-529
If a borrower profile has a video, lets prioritize that by putting it at the top of the loan story, and the borrower image below the loan story.
> feat: prioritize video on borrower profile

- src/components/Checkout/SocialShareV2.vue
- src/components/Kv/KvSocialShareButton.vue
- src/components/Thanks/ThanksPageShare.vue
- src/plugins/social-sharing-mixin.js
- src/util/urlUtils.js
- test/unit/specs/util/urlUtils.spec.js
There are currently 3 components which share to social media
- SocialShareV2 (ML thanks, thank-page-v2 layout on the thanks page)
- KvSocialShareButton (Borrower profile)
- ThanksPageShare (mars share layout on the thanks page)
This combines some of the shared functionality of these components into one place.
> refactor: refactor sharing functionality into shared mixin

- src/components/LoanCards/Buttons/LendCtaExp.vue
- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- some aria unique ids, link aria names and `aria-hidden="true"` statements were added to improve lighthouse scores in lh
> feat: additions to improve lighthouse scores in lending home

- src/components/WwwFrame/TheHeader.vue
- src/components/WwwFrame/WwwPageCorporate.vue
- src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
This reverts commit 977e4bf4f5d4103942b26caa42cab701cc980ea5.
> Revert "fix: show basket button not working"

- src/pages/LoanFinding/LoanFinding.vue
https://kiva.atlassian.net/browse/CORE-1236
- Added `metaInfo` with meta + title that match LBC
- Added canonical `link` to point to LBC - LH will be public for 50% of new user traffic next week
> feat: update meta and add canonical link to LH

- src/pages/Portfolio/ImpactDashboard/CreditSummaryLightbox.vue
- src/pages/Portfolio/ImpactDashboard/KivaCreditStats.vue
- src/util/getCacheKey.js
Depends on data from kiva/kiva#11549
> Account balance sheet MARS-361

- src/pages/Portfolio/ImpactDashboard/CreditSummaryLightbox.vue
- src/pages/Portfolio/ImpactDashboard/KivaCreditStats.vue
- src/util/getCacheKey.js
> Revert "Account balance sheet MARS-361"

- src/pages/Portfolio/ImpactDashboard/CreditSummaryLightbox.vue
- src/pages/Portfolio/ImpactDashboard/KivaCreditStats.vue
- src/util/getCacheKey.js
Restores code reverted in kiva/ui#4795 (will squash-merge)
> fix: restore credit summary lightbox code MARS-361

- src/components/LoanFinding/LendingCategorySection.vue
- src/graphql/query/userInfo.graphql
- src/pages/LoanFinding/LoanFinding.vue
- a/b setup added to lending home for relending experiments for users having a positive balance
> Core 1276 ab setup user with balance

- src/pages/LoanFinding/LoanFinding.vue
- copy updated for title and subtitle in recommened section when relending experiment is enable
> Core 1284 toggle recommended section titles

- src/pages/Portfolio/ImpactDashboard/AccountUpdates.vue
- src/pages/Portfolio/ImpactDashboard/RecentLoanItem.vue
- src/pages/Portfolio/ImpactDashboard/RecentLoansList.vue
- src/pages/Portfolio/ImpactDashboard/YourTeams.vue
This suppresses the same data as on the old portfolio page.
> fix: hotjar suppression classes for PII on impact dashboard MARS-389

- src/components/CorporateCampaign/CampaignThanks.vue
- src/components/WwwFrame/TheHeader.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
- src/pages/Thanks/ThanksPage.vue
- src/util/hotJarUtils.js
* refactor hotjar utility to more generic util
ACK-520
This event will fire a hotjar survey
> feat: add hotjar event to US borrower profile

- src/pages/LoanFinding/LoanFinding.vue
- matched loans section moved up to quick filters for relending test
- copy updated matched loans section for test
- data prefetched avoiding async behavior in this section
> Core 1290 new matched loans position relending test

- src/components/LoanCards/Buttons/MultipleAtcButton.vue
- src/components/LoanFinding/LendingCategorySection.vue
- redirect to checkout added when multiple button in lh is clicked
- disabled prop added to `MultipleAtcButton`
> feat: redirect and disabled option added to multiple button in lh

- src/pages/Portfolio/ImpactDashboard/YourTeams.vue
ACK-617
See ticket for example
> fix: team link for teams in new portfolio

- src/pages/Autolending/DefaultRateDropdown.vue
- src/pages/Autolending/PartnerDelRateDropdown.vue
- src/pages/Autolending/PartnerFilter.vue
- src/pages/Autolending/PartnerRadios.vue
- src/pages/Autolending/RiskRatingDropdown.vue
- copy for autolending pages updated from field partner to lending partner
> Core 1272 autoleding settings copy update

- src/components/LoanFinding/LendingCategorySection.vue
https://kiva.atlassian.net/browse/CORE-1355
- Missed updating the logic in the add all method
> feat: match logic in CTA component for add all relending

- src/pages/Lend/LoanSearchPage.vue
- test setup added to filter page to redirect to new category filter page in cps
> Core 1206 category filters test setup in filter page

- src/components/LoanFinding/LendingCategorySection.vue
Turns out the donation issue probably wasn't race condition related, so reverting a recent change
> fix: revert synchronous ATB

- src/components/WwwFrame/WwwPage.vue
- src/components/WwwFrame/WwwPageCorporate.vue
- src/components/WwwFrame/WwwPageMinimal.vue
- src/util/experiment/experimentUtils.js
- test/unit/specs/util/experiment/experimentUtils.spec.js
https://kiva.atlassian.net/browse/CORE-1374
- Create new simple method for loading the active experiments and assigning
- Placed the method call in the same place as previous global prefetched assignment
> feat: run all active experiment assignment on global preFetch

- src/components/LoanFinding/LendingCategorySection.vue
- Make the add all event unique to help with reporting on the relending experiment
> feat: make the add all to basket event unique

- src/components/WwwFrame/TheHeader.vue
updates mobile view to use the "Categories" dropdown instead of "Explore loans"
> feat: lend dropdown mobile update

- src/pages/Donate/DonateForm.vue
- src/plugins/retry-after-expired-basket-mixin.js
- src/util/basketUtils.js
This is an extension and reuse of the concept of recovering a failed add to basket for a loan.
> feat: add failed add donation to basket recovery process

- src/components/Thanks/ThanksPageDonationOnly.vue
- src/pages/Thanks/ThanksPage.vue
> Show share kiva with only donation in checkout mars 396

- src/components/Thanks/ThanksPageDonationOnly.vue
Small fixes in design and replicate thanks page logic for share link
> fix: styles and share link logic

- src/components/Lend/DonationCTA.vue
- src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBannerCircular.vue
- src/components/WwwFrame/TheFooter.vue
- src/pages/Portfolio/ImpactDashboard/LendingInsights.vue
- src/pages/Possibility/GivingTuesday.vue
- src/pages/Possibility/YearEnd.vue
- src/router/routes.js
Handle donate/supportus as a cps page
> feat: donate/supportus 

- src/pages/LoanFinding/LoanFinding.vue
- Something weird happened with last PR, here's the missing comment cleanup
> fix: actually comment itself no longer makes sense

- src/components/WwwFrame/TheHeader.vue
- test/unit/specs/components/WwwFrame/TheHeader.spec.js
Add Support Kiva Button on header. This works comes along with
> feat: support kiva button on header

- src/pages/AutoDeposit/AutoDepositLandingPage.vue
Fixes messaging for MG or AD subscribers landing on the autodeposit page
> fix: auto deposit landing page messaging

- src/components/BorrowerProfile/LendCta.vue
- src/util/loanUtils.js
- Noticed a couple minor errors in sentry that should be resolved
https://kiva.sentry.io/issues/4246651924/?project=1201288&query=is%3Aunresolved&referrer=issue-stream&stream_index=5
https://kiva.sentry.io/issues/4246552062/?project=1201288&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=13
> fix: resolve a couple sentry errors

- src/components/BorrowerProfile/CommentsAndWhySpecial.vue
> feat: add team name to comments on BP

- src/components/WwwFrame/TheHeader.vue
Same error as found on cps: 
When items on the basket as a visitor, search should be a button and small fixes (Log in is always link, show dropdown on tablet, support kiva order in about dropdown)
> Fix tablet design mars 410

- src/components/WwwFrame/TheHeader.vue
For logged in users:
Before
After
> Move support kiva btn mars 449

- src/pages/Lend/LoanChannelCategoryPage.vue
- src/pages/Lend/LoanSearchPage.vue
- experiment event `EXP-CORE-1205-May2023` fired for existing users only
> fix: experiment event fired for existing users only

- src/components/LoanFinding/LendingCategorySection.vue
- src/components/LoanFinding/PartnerSpotlightSection.vue
- src/components/LoanFinding/QuickFiltersSection.vue
- src/pages/LoanFinding/LoanFinding.vue
https://kiva.atlassian.net/browse/CORE-1327
- Removed lending home experiment card - new loan card (not shared component yet) rolled out
> feat: remove loan card exp from LH

- src/components/BorrowerProfile/MoreAboutLoan.vue
ACK-676
Screenshots, before on the right, after on the left:
> feat: support paragraphs in business description and purpose

- package-lock.json
- package.json
https://kiva.atlassian.net/browse/CORE-1376
> feat: update components library to get countdown timer on new loan cards

- src/components/LoanFinding/LoanFindingFeaturedLoan.vue
- src/pages/LoanFinding/LoanFinding.vue
- featured loan test for logged in users in lending home
> feat: featured loan test for logged in users in lending home

- cypress.config.js
- test/e2e/specs/RegisterSocial.cy.js
- Two changes were needed to get the e2e tests passing in Chrome
- Looks like test setup + config issues rather than app issues
> feat: resolve issues with register social e2e

- src/components/LoanCards/KivaClassicBasicLoanCard.vue
- src/components/LoanFinding/QuickFiltersSection.vue
- src/components/LoansByCategory/QuickFilters/LocationSelector.vue
- Resolved some new minor Sentry errors
https://kiva.sentry.io/issues/3927413744/?project=1201288&query=is%3Aunresolved&referrer=issue-stream&stream_index=17
https://kiva.sentry.io/issues/4323575755/?project=1201288&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=5
https://kiva.sentry.io/issues/4109780531/?project=1201288&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=8
> feat: resolve minor sentry issues

- src/pages/LoanFinding/LoanFinding.vue
- displayed loans event implemented for new featured loan test
> feat: displayed loans event implemented for new featured loan test

- src/graphql/query/userInfo.graphql
- src/pages/LoanFinding/LoanFinding.vue
- Implementing one query file in lh was not resulting as expected in page performance.
- code updated to clean up
Before one query file
After one query file
> feat: prefetch hook updated in lh page

- src/components/LoanFinding/FiveDollarsBanner.vue
- src/pages/LoanFinding/LoanFinding.vue
- $5 banner added to lending home page
> feat: 5 dollars banner added to lending home page

- package-lock.json
- package.json
- kv components version updated
> feat: kv components version updated

- src/components/CorporateCampaign/CampaignLoanGridDisplay.vue
- src/components/CorporateCampaign/CampaignLoanRow.vue
- src/components/LoanCards/KivaClassicBasicLoanCard.vue
> fix: skipping second addToBasket mutation

- src/pages/LoanFinding/LoanFinding.vue
- number of loans in lending home recommended row updated
> feat: number of loans in lending home recommended row updated

- src/components/Settings/SaveSearchItem.vue
- remove number of loans in saved search page
> feat: remove number of loans in saved search page

- src/components/Checkout/KivaCardRedemption.vue
Updating here this view:  https://www.kiva.org/gifts/kiva-cards/redeem
> feat: remove Kiva card postal delivery option redemption instructions

- src/pages/InstantActions/ConfirmInstantDonation.vue
Biggest impact will be from copy changes in contentful updating the title and body.
> feat: tweak instant donate page for better conversion MARS-492

- src/pages/Categories/CategoriesPage.vue
- code for categories redirect test removed
> feat: code clean up for categories redirect test

- build/webpack.base.conf.js
- package-lock.json
- package.json
Pre-compress static assets with gzip and brotli for static file store
> Asset compression MARS-429

- src/components/BorrowerProfile/BorrowerBusinessDetails.vue
> fix: bad isserver check

- src/components/Checkout/GuestUpsell.vue
> fix: missing component on guest upsell no comment ask

- package-lock.json
- package.json
- kv components package updated to last version
> feat: kv components package updated

- src/pages/LendingTeams/TeamLeaderboards.vue
- src/pages/LendingTeams/TeamListing.vue
Small styling tweaks and adding buttons, buttons just go to urls. 
Also added prefetch query to get current users teams so that we can select which buttons to show.
> feat: add recruit/join/quit buttons to new teams page

- src/components/Thanks/ShareStepper.vue
- src/components/Thanks/ThanksPageCommentAndShare.vue
- src/graphql/query/thanksPage.graphql
- src/pages/Thanks/ThanksPage.vue
- Message for FTDs added to thanks page
- Settings added to kiva admin to manage this feature
> Core 1513 thanks page ftds

- src/pages/ProcessJoinTeam.vue
If inviter param exists, create a recruitment, then use that for the join team mutation so the inviter gets credit for the recruitment
> fix: team recruitment attribution fix

- src/router/routes.js
We're planning to release this to the /teams url for next release
> feat: release teams-beta page as teams

- package-lock.json
- package.json
- kv components package updated to last version to include loan card update
> feat: kv componets updated

- src/components/LoanCards/KivaClassicBasicLoanCard.vue
- src/components/LoanCards/KvClassicLoanCardContainer.vue
- src/util/loanUtils.js
- unsubscribe method added to loan card queries
> feat: unsubscribe method added to loan card queries

- src/components/LoanCards/KivaClassicBasicLoanCard.vue
- subscription bug fixed in old loan card
> fix: subs bug fixed in old loan card

- config/dev-local.js
Also provides alternate environment urls for api and session endpoints
> chore: update local dev apollo setting

- src/components/LoansByCategory/QuickFilters/LocationSelector.vue
- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- css code for location selector reverted
> feat: css code for location selector updated

- config/dynamic.js
> fix: [CP-548] Fixing API audience URL

- src/components/LoanFinding/LendingCategorySection.vue
- src/components/LoanFinding/QuickFiltersSection.vue
- Omit view more card for loans length less than the page limit in new mobile carousel test for lending home page
> feat: omit view more card for loans length less than the page limit

- src/pages/LoanFinding/LoanFinding.vue
- A/B setup added for new almost funded loans row in lending home
> feat: ab setup added for new almost funded loans row in lending home

- src/pages/LoanFinding/LoanFinding.vue
- Almost funded row test added to lending home page
> feat: almost funded row test added to lending home page

- src/components/LoansByCategory/HelpmeChoose/HelpmeChooseWrapper.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
> feat: loan tags test code removed

- src/graphql/query/checkout/initializeCheckout.graphql
- src/graphql/query/thanksPage.graphql
- src/pages/Checkout/CheckoutPage.vue
- src/pages/Thanks/ThanksPage.vue
- boolean settings bug fixed for ftds in checkout and thanks pages
> fix: boolean settings bug fixed for ftds in checkout and thanks pages

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- Mobile filter CTA updated from "Filter and Sort" to just "Filter"
> feat: mobile filter cta copy updated in filter page

- src/pages/Checkout/CheckoutPage.vue
- Tip rate optimization old test code removed
> feat: tip rate optimization test code removed

- src/components/Thanks/CommentAsk.vue
- src/graphql/mutation/loanAddComment.graphql
- src/pages/Portfolio/ImpactDashboard/LoanCommentModal.vue
- src/pages/Portfolio/ImpactDashboard/RecentLoanItem.vue
- src/pages/Portfolio/ImpactDashboard/RecentLoansList.vue
- src/plugins/guest-comment-mixin.js
- Loan comment modal added to portfolio page
- Going to borrower profile after saving the comment
- Showing toast confirmation after saving the comment
> feat: loan comment modal added to portfolio page

- src/api/Auth0Link.js
- src/api/HttpLink.js
- src/api/apollo.js
> feat(FakeAuthentication): use headers for fake auth instead of url parameters CP-677

- package.json
- src/components/Checkout/BasketItem.vue
- src/pages/Checkout/CheckoutPage.vue
- src/util/teamChallengeUtils.js
- test/unit/specs/util/teamChallengeUtils.spec.js
https://kiva.atlassian.net/browse/ACK-895
- Created util for challenge cookie methods w/ tests
- Moved clearing cookie loans to checkout completion method
- Added script for test watch
> feat: clear challenge cookie after completed checkout

- src/pages/Portfolio/ImpactDashboard/TeamChallenge.vue
https://kiva.atlassian.net/browse/ACK-898
> feat: redirect portfolio CTA to new team challenge page

- src/components/Thanks/NotifyMe.vue
> fix: notify icon size updated

- src/components/BorrowerProfile/SupporterDetails.vue
https://kiva.sentry.io/issues/4522749279/?project=1201288&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=6
> fix: check for name before operating on it, default to empty string

- src/graphql/query/teamsGoals.graphql
I think this all we need once the back end change comes through ?
> fix: [ACK-959] filter goals that are not in progress for team query

- config/k8s-local.js
Update URLs for local development changes
Requires https://github.com/kiva/kiva/pull/12160 to merge.
> chore: updates for k8s-local config

- src/api/localResolvers/loanSearch.js
- src/api/localSchema.graphql
- src/graphql/mutation/updateLoanSearchState.graphql
- src/graphql/query/loanSearchState.graphql
- src/util/loanSearch/filterConfig.js
- src/util/loanSearch/filters/flexibleFundraisingEnabled.js
- test/unit/fixtures/mockLoanSearchData.js
- test/unit/specs/util/loanSearch/filters/flexibleFundraisingEnabled.spec.js
https://kiva.atlassian.net/browse/ACK-867
- Added new filter to `/lend/filter` page
> feat: add new flexibleFundraisingEnabled filter

- src/pages/Lend/LoanChannelCategoryControl.vue
https://kiva.atlassian.net/browse/CORE-1707
- Created simple placeholder component for IWD header
- Controlled by new experiment flag -> currently enabled on dev
`
uiexp.iwd_header_2024
{"name":"IWDHeader2024","distribution":{"a":0,"b":1},"population":1}
`
> feat: add placeholder for IWD 2024 category header

- .storybook/mixins/apollo-story-mixin.js
- .storybook/mock-data/thanks-page-data-mock.js
- .storybook/stories/DonationNudgeLightbox.stories.js
- .storybook/stories/EcoChallengeLightbox.stories.js
- .storybook/stories/KvSocialShareButton.stories.js
- .storybook/stories/ListLoanCard.stories.js
- .storybook/stories/ThanksPage.stories.js
- src/pages/Thanks/ThanksPage.vue
https://kiva.atlassian.net/browse/CORE-1729
- First step in IWD thanks page changes -> make it more easily testable locally
- Created working stories with variations for with and without conditions for IWD
- Fixed apollo mixin for `readQuery` and `readFragment`
- Data contains "real" data w/ fake IDs and names (real image kept)
> feat: added flag for IWD to thanks page, created working stories

- .storybook/mock-data/thanks-page-data-mock.js
- .storybook/stories/ThanksPage.stories.js
- src/components/Iwd/IwdThanksPageVariations.vue
- src/graphql/query/thanksPage.graphql
- src/pages/Thanks/ThanksPage.vue
https://kiva.atlassian.net/browse/CORE-1729
- Implemented remaining IWD thanks page variation
- Used existing share functionality and icons are made sense
- Hoping this works fine once deployed, since deployment before last didn't seem to hit the dev env -> I'll test and fix quickly
- Note there is an empty space where progress bar will be -> ticket exists but blocked
> feat: another thanks variation

- src/components/Iwd/IwdThanksPageVariations.vue
- IWD no-inviter thanks page update
> feat: iwd no inviter thanks page update

- src/components/Iwd/IwdProgressCampaign.vue
- Previous logic needed to be reversed
> fix: logic was incorrect for showing IWD progress

- src/components/Iwd/IwdThanksPageVariations.vue
-  iwd thanks page height fixed
> fix: iwd thanks page height fixed

- src/components/Iwd/IwdCategoryHeader.vue
- src/components/Iwd/IwdThanksPageVariations.vue
https://kiva.atlassian.net/browse/CORE-1772
- Fixed issue with category page progress bar not growing to fill space
- Tweaks to thanks page for IWD
> fix: change confirmation on thanks page

- src/components/WwwFrame/PromotionalBanner/GlobalPromotionalBannerContentful.vue
- visible url array added to global promotional banner component from contentful
> feat: visible url array added to global promotional banner component

- .storybook/stories/KvActivityRow.stories.js
- .storybook/stories/KvLoanActivities.stories.js
- package-lock.json
- package.json
- src/components/Kv/KvActivityRow.vue
- src/components/Kv/KvLoanActivities.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
- activity feed components added for borrower profile upcoming work
> feat: activity feed components added

- src/pages/Lend/LoanSearchPage.vue
- ab setup added to filters page for new challenge header
> feat: ab setup added to filters page for new challenge header

- src/components/Lend/LoanSearch/LoanSearchSavedSearch.vue
- src/graphql/mutation/createSavedSearch.graphql
- src/util/loanSearch/searchStateUtils.js
- test/unit/fixtures/mockLoanSearchData.js
- test/unit/specs/util/loanSearch/searchStateUtils.spec.js
https://kiva.atlassian.net/browse/CORE-1792
- New checkbox that matches the checkbox in the monolith
> fix: add email notification checkbox to saved search modal

- package-lock.json
- src/components/Lend/LoanSearch/ChallengeHeader.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/pages/Lend/LoanSearchPage.vue
- challenge header placeholder added to filters page
> feat: challenge header placeholder added

- src/components/Lend/LoanSearch/ChallengeHeader.vue
- src/graphql/query/myTeams.graphql
- src/graphql/query/teamInfoFromId.graphql
- src/pages/Lend/LoanSearchPage.vue
-  challenge header data fetch added to filter page to get goal data accordingly to team query or logged in team id
> feat: challenge header data fetch added

- src/components/Lend/LoanSearch/ChallengeHeader.vue
- src/components/Teams/TeamGoalsList.vue
- src/graphql/query/teamsGoals.graphql
- src/pages/Lend/LoanSearchPage.vue
- src/pages/Thanks/ThanksPage.vue
- src/util/teamsUtil.js
- team challenge info added to challenge header
> feat: team challenge info added to challenge header

- src/components/LoansByCategory/HelpmeChoose/HelpmeChooseWrapper.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
- grid width fixed on category page
> feat: grid width fixed on category page

- src/components/Lend/LoanSearch/ChallengeHeader.vue
- progress bar date bug fixed in challenge header
> fix: progress bar bug fixed in challenge header

- package-lock.json
- package.json
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/Lend/LoanSearch/TeamPicksSwitch.vue
- src/components/LoanCards/KvClassicLoanCardContainer.vue
- team picks handling for challenge header
> feat: team picks handling for challenge header

- src/pages/Checkout/CheckoutPage.vue
- Checkout upsell white space removed
> feat: remove checkout upsell white space

- src/graphql/query/loanActivities.graphql
https://kiva.atlassian.net/browse/MPL-51
> fix: add new filter to remove corporate lenders from BP activity feed

- src/components/WwwFrame/TheHeader.vue
> feat: header tweaks on mobile

- src/components/WwwFrame/TheHeader.vue
- correct profile image size on mobile
> fix: correct profile image size on mobile

- package-lock.json
- package.json
- src/components/Lend/LoanSearch/ChallengeHeader.vue
- src/graphql/query/teamsGoals.graphql
- Activity feed added to challenge header on filters page
> feat: activity feed added to challenge header on filters page

- src/components/BorrowerProfile/SupportedByLenders.vue
- src/components/Lend/LoanSearch/ChallengeHeader.vue
- challenge header participation avatars added
> feat: challenge header participation avatars added

- .storybook/stories/LoanSearchChallengeHeader.stories.js
- Loan search challenge header added to storybook
> feat: loan search challenge header added to storybook

- package-lock.json
- package.json
- src/components/Lend/LoanSearch/ChallengeCallout.vue
- src/components/Lend/LoanSearch/ChallengeHeader.vue
- src/pages/Lend/LoanSearchPage.vue
- test/unit/specs/components/Lend/LoanSearch/ChallengeCallout.spec.js
https://kiva.atlassian.net/browse/ACK-1105
> fix: small fixes to new challenge filter page header

- src/components/Thanks/ShareChallenge.vue
- src/components/Thanks/ThanksPageCommentAndShare.vue
- src/pages/Thanks/ThanksPage.vue
https://kiva.atlassian.net/browse/ACK-1110
- Cleaned up May challenge TY page to better match mocks
- Added in some existing TY page elements (minus old share module that would duplicate TY header module)
- Fixed server error current on dev when getting `teamId`
> feat: fe ty page shouldnt show challenge header unless the user atb from lend filter with challenge

- .storybook/stories/ChallengeCallout.stories.js
- src/components/Lend/LoanSearch/ChallengeCallout.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/LoanCards/KvClassicLoanCardContainer.vue
- src/graphql/query/goalParticipationForLoan.graphql
- src/graphql/query/myPublicLenderInfo.graphql
- src/pages/Lend/LoanSearchPage.vue
- test/unit/specs/components/Lend/LoanSearch/ChallengeCallout.spec.js
https://kiva.atlassian.net/browse/ACK-1070
- New tooltip/message shown when a user ATB from lend/filter with new challenge variation
> feat: show "added to cart" message for lend filter challenge

- .storybook/stories/TheHeader.stories.js
- src/components/WwwFrame/TheHeader.vue
- src/graphql/query/wwwHeader.graphql
https://kiva.atlassian.net/browse/CORE-1811
- Ported the recent PR from CPS
- Fixed unrelated bug with corporate header login button wrapping
- Fixed unrelated error with other story
**Small basket:**
**Large basket:**
> feat: add basket total to header for large baskets

- src/pages/Lend/LoanSearchPage.vue
- header showed for active user team challenge
> feat: header showed for active user team challenge

- src/components/Lend/LoanSearch/ChallengeHeader.vue
- src/components/Thanks/ChallengeHeader.vue
- src/pages/Thanks/ThanksPage.vue
Same tracking when progressbar shows in `lend/filter` but for sharing module in thanks page
> feat: track when challenge header appears on ty page

- src/pages/Lend/LoanSearchPage.vue
- Experiment tracking events updated
> feat: experiment tracking events updated

- src/components/Lend/LoanSearch/TeamPicksSwitch.vue
- team picks panel copy updated
- "On by default for team challenges" copy removed.
> feat: team picks panel copy updated

- src/components/Teams/TeamGoal.vue
- /teams challenge header updates
Note: upcoming work to update goal mixin
> feat: teams challenge header updates

- src/components/Lend/LoanSearch/ChallengeHeader.vue
- src/components/Teams/TeamGoal.vue
- src/components/Thanks/ChallengeHeader.vue
- src/components/Thanks/ShareChallenge.vue
- src/pages/Lend/LoanSearchPage.vue
- src/plugins/team-goal-mixin.js
- test/unit/specs/components/Thanks/ChallengeHeader.spec.js
- goal mixin updated
- goal mixin implemented to related challenge components
> feat: goal mixin updated

- src/components/Checkout/InContext/InContextCheckout.vue
- src/graphql/query/checkout/checkoutSettings.graphql
- src/graphql/query/checkout/initializeCheckout.graphql
- src/pages/Checkout/CheckoutPage.vue
- src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
We have better security measures than this already in-place, and this just causes friction. A similar change is being made in the api, and this will have to wait for that change to be deployed before this is merged.
> feat: remove active login check at checkout MP-87

- server/live-loan-router.js
- server/util/live-loan/live-loan-fetch.js
- test/unit/specs/server/live-loan-fetch.spec.js
- live loans powered by flss
Local test,
redirect:  https://kiva-ui.local/live-loan/flss/u/5314401/url/1
legacy user img: https://kiva-ui.local/live-loan/flss/u/5314401/img/1
classic user img: https://kiva-ui.local/live-loan/flss/u/5314401/img2/1
> feat: live loans powered by flss

- package-lock.json
- package.json
- src/util/loanUtils.js
- test/unit/specs/components/Checkout/BasketItem.spec.js
- test/unit/specs/util/loanUtils.spec.js
https://kiva.atlassian.net/browse/MP-88
- Ported new functionality from: https://github.com/kiva/kv-ui-elements/pull/390
- This affects loan finding pages, BP, and checkout
- Not going to merge until dev DB gets refreshed, since there are no loans currently to test this
- But the changes can get reviewed while we wait
> feat: add value options up to 10000

- server/util/getSessionCookies.js
- src/components/WwwFrame/Menus/TheMyKivaSecondaryMenu.vue
https://kiva.atlassian.net/browse/MP-67
- New cookie pulled from `start-ui-session`
- New menu item in portfolio that links to monolith application page
> feat: show link to borrower application

- src/components/LoanCards/KvClassicLoanCardContainer.vue
- tags and themes extra data fetched for loans
> feat: tags and themes data fetched for loans

- .storybook/stories/DepositIncentiveUpsell.stories.js
- src/components/Checkout/BasketItemsList.vue
- src/components/Checkout/DepositIncentiveUpsell.vue
- src/components/WwwFrame/PromotionalBanner/GlobalPromotionalBannerContentful.vue
- src/graphql/query/checkout/initializeCheckout.graphql
- src/pages/Checkout/CheckoutPage.vue
Loan upsell carousel for deposit incentive experiment. Only displays when user is in experiment group and still needs to lend more to reach the incentive goal.
> feat: loan upsell in checkout for deposit incentive experiment MP-95

- src/components/WwwFrame/PromotionalBanner/Banners/DepositIncentiveBanner.vue
- src/pages/Thanks/ThanksPage.vue
- Encountered that we aren't showing guest registration completion for the May challenge checkout thanks page
- Encountered missing number format for new header
> fix: guest upsell for challenge

- src/api/localResolvers/loanSearch.js
- src/api/localSchema.graphql
- src/graphql/mutation/updateLoanSearchState.graphql
- src/graphql/query/loanFacetsQuery.graphql
- src/graphql/query/loanSearchState.graphql
- src/util/loanSearch/dataUtils.js
- src/util/loanSearch/filters/activities.js
- src/util/loanSearch/queryParamUtils.js
- test/unit/fixtures/mockLoanSearchData.js
- test/unit/specs/util/loanSearch/dataUtils.spec.js
- test/unit/specs/util/loanSearch/queryParamUtils.spec.js
- URL and filter pills support added for activities on filter page
> feat: activity support on filter page

- .github/workflows/release-build.yaml
https://kiva.atlassian.net/browse/MP-226
- Adding action input to try running new step that uploads assets to S3
> feat: try new upload to s3 optional functionality

- .github/workflows/release-build.yaml
https://kiva.atlassian.net/browse/MP-226
> fix: remove extra slash from input

- .github/workflows/release-build.yaml
https://kiva.atlassian.net/browse/MP-226
> fix: disable new upload step

- .github/workflows/release-build.yaml
Depends on https://github.com/kiva/marketplace-web-ui-ci/pull/98 and https://github.com/kiva/github-actions/pull/38
> feat: build & upload static assets before docker image MP-212

- .github/workflows/semantic-release.yaml
Same as https://github.com/kiva/cms-page-server/pull/1182
> fix: upload static assets for staging and production releases MP-289

- server/auth-router.js
- src/util/KvAuth0.js
https://kiva.atlassian.net/browse/MP-245
> fix: add check for new access_denied error

- src/components/LoanCards/KvClassicLoanCardContainer.vue
- multiple clickable pills update
> feat: multiple clickable pills

- src/components/WwwFrame/DisclaimersContentful.vue
- footer disclaimer date updated to May 31, 2024
> feat: footer disclaimer date update

- src/pages/Settings/EmailSettings.vue
Ticket: https://kiva.atlassian.net/browse/MP-136
See: https://github.com/kiva/kiva/pull/12637
> feat: [MP-136] borrower funded email lend ui

- package-lock.json
- package.json
- src/components/Kv/KvLoanActivities.vue
- src/components/LoanCards/KvClassicLoanCardContainer.vue
- src/graphql/query/loanActivities.graphql
- lent amount removed in activity feed
> feat: lent amount removed in activity feed

- src/pages/Settings/EmailSettings.vue
- repayment email settings update
> feat: repayment email settings update

- src/pages/Checkout/CheckoutPage.vue
https://kiva.atlassian.net/browse/MP-372
> feat: added experiment setting for checkout sticky exp

- .storybook/stories/PieChartFigure.stories.js
- .storybook/stories/TreeMapFigure.stories.js
- src/components/Charts/PieChartFigure.vue
- src/components/Charts/TreeMapFigure.vue
- src/pages/Portfolio/ImpactDashboard/DistributionGraphs.vue
Pie chart was requested for new stack, but no designs provided. The design of the component in this PR has been briefly reviewed, so I'm creating this as a story for final review. There will be follow-up work to actually use this pie chart after it has been approved by prod/design.
> feat: pie chart design for distribution tables MP-434

- src/components/WwwFrame/PromotionalBanner/Banners/DepositIncentiveBanner.vue
Ticket: https://kiva.atlassian.net/browse/MP-362
Related: https://github.com/kiva/kiva/pull/12732
> feat: [MP-362] update lending credit link

- src/components/Thanks/ThanksPageDonationOnly.vue
https://kiva.atlassian.net/browse/MP-363
- The "double the donation" feature is already disabled via an existing feature flag in both dev and prod
- This changeset removes the feature entirely
> feat: remove double donation feature from donation-only thanks page

- src/api/ExperimentIdLink.js
- src/pages/Lend/LoanChannelCategoryControl.vue
- src/pages/Lend/LoanSearchPage.vue
- src/pages/LoanFinding/LoanFinding.vue
https://kiva.atlassian.net/browse/MP-480
> feat: replace BE FLSS experiment key

- src/pages/LoginAndRegister/RegisterSocial.vue
- use `partnerContentId` for exclusion from experiment state
- use `partnerContentId` to show partner logo if present
> fix: cit 1728 exclude corps radio exp

- src/components/Settings/AppAuthentication.vue
- Used braincrave inbox to test dev MFA
- Centered QR code in modal
> fix: cleanup QR code location

- src/components/WwwFrame/PromotionalBanner/GlobalPromotionalBannerContentful.vue
- src/pages/Checkout/CheckoutPage.vue
https://kiva.atlassian.net/browse/MP-540
> fix: update deposit incentive experiment

- src/graphql/query/lenderPublicProfile.graphql
- src/pages/LenderProfile/LenderProfile.vue
- src/router/routes.js
- new lender profile page added as point to start
There is other ticket to complete required meta data: https://kiva.atlassian.net/browse/MP-486
> feat: new lender profile page added

- src/components/LenderProfile/LenderSummary.vue
- src/graphql/query/lenderPublicProfile.graphql
- src/pages/LenderProfile/LenderProfile.vue
- Summary component added to lender profile
Requirements: https://kiva.atlassian.net/browse/MP-402
> feat: lender profile summary component added

- src/components/LenderProfile/LenderTeamsList.vue
- src/graphql/query/lenderTeams.graphql
- src/pages/LenderProfile/LenderProfile.vue
- teams section added to lender profile page
Desktop:
Tablet:
Mobile:
> feat: teams section added to lender profile page

- .storybook/stories/KvLoanCards.stories.js
- src/components/LenderProfile/LenderLoansList.vue
- src/components/LoanCards/NewHomePageLoanCard.vue
- src/util/loanUtils.js
- dedications added to lender loans list
Kiva dedication:
One recipient dedication:
Multiple recipients dedication:
> feat: dedications added to lender loans list

- src/components/LenderProfile/LenderLoansList.vue
- src/components/LenderProfile/LenderTeamsList.vue
- lender profile components fix
> fix: lender profile components fix

- .storybook/stories/AppealBannerCircular.stories.js
- src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBannerCircular.vue
- million format goal added to appeal banner component
> feat: million goal added to appeal banner component

- src/components/LenderProfile/LenderDedicationsList.vue
- src/graphql/query/lenderDedications.graphql
- src/pages/LenderProfile/LenderProfile.vue
- lender loans dedications list added to lender profile
> feat: lender dedications list added to lender profile

- src/components/LenderProfile/LenderInviteesList.vue
- src/components/LenderProfile/LenderTeamsList.vue
- src/graphql/query/lenderInvitees.graphql
- src/pages/LenderProfile/LenderProfile.vue
- Lender invitees added to lender profile
> feat: lender profile invitees

- src/components/LenderProfile/LenderBadges.vue
- src/components/LenderProfile/LenderDedicationsList.vue
- src/components/LenderProfile/LenderInviteesList.vue
- src/components/LenderProfile/LenderLoansList.vue
- src/components/LenderProfile/LenderStats.vue
- src/components/LenderProfile/LenderTeamsList.vue
- New Lender profile page tweaks
> feat: lender profile tweaks

- src/pages/LendingTeams/TeamListing.vue
- teams page sort option updated
> feat: teams page sort option updated

- package-lock.json
- package.json
- Updated the component library to make sure the lightbox still works in vue 2
> fix: update component library

- src/pages/NotFound.vue
- src/router/routes.js
- 404 page added
Reqs: https://kiva.atlassian.net/browse/MP-620
> feat: 404 page added

- src/graphql/query/lenderPublicProfile.graphql
- src/pages/LenderProfile/LenderProfile.vue
- meta data updated in lender profile
Reqs: https://kiva.atlassian.net/browse/MP-486
> feat: meta data updated in lender profile

- src/components/WwwFrame/DisclaimersContentful.vue
Setting this up for next week.
> feat: set new deposit incentive end date MP-692

- src/components/LenderProfile/AsyncLenderSection.vue
- src/components/LenderProfile/LenderBadges.vue
- src/components/LenderProfile/LenderDedicationsList.vue
- src/components/LenderProfile/LenderInviteesList.vue
- src/components/LenderProfile/LenderLoansList.vue
- src/components/LenderProfile/LenderMap.vue
- src/components/LenderProfile/LenderStats.vue
- src/components/LenderProfile/LenderTeamsList.vue
- src/pages/LenderProfile/LenderProfile.vue
- Loading states adding to lender profile sections
Reqs: https://kiva.atlassian.net/browse/MP-618
> feat: loading states adding to lender profile sections

- src/components/LenderProfile/LenderProfileWrapper.vue
- src/components/NotFound/NotFoundWrapper.vue
- src/pages/LenderProfile/LenderProfile.vue
- src/pages/NotFound.vue
- handle unknown lender on profile page
> feat: handle unknown lender on profile page

- src/components/LenderProfile/LenderBadges.vue
- src/components/LenderProfile/LenderDedicationsList.vue
- src/components/LenderProfile/LenderInviteesList.vue
- src/components/LenderProfile/LenderLoansList.vue
- src/components/LenderProfile/LenderMap.vue
- src/components/LenderProfile/LenderStats.vue
- src/components/LenderProfile/LenderSummary.vue
- src/components/LenderProfile/LenderTeamsList.vue
- lender profile headings updated
> feat: lender profile headings updated

- src/pages/Checkout/CheckoutPage.vue
https://kiva.atlassian.net/browse/MP-638
- Removed code associated with the failed checkout sticky experiment
> fix: remove checkout sticky code

- src/components/Payment/BraintreeDropInInterface.vue
https://kiva.atlassian.net/browse/MP-685
- Added helper text to the braintree dropin
**Desktop**
**Mobile**
> feat: braintree checkout multiple interaction helper text

- package-lock.json
- package.json
- src/components/LenderProfile/LenderDedicationsList.vue
- src/components/LenderProfile/LenderInviteesList.vue
- src/components/LenderProfile/LenderLoansList.vue
- src/components/LenderProfile/LenderMap.vue
- src/components/LenderProfile/LenderStats.vue
- src/components/LenderProfile/LenderSummary.vue
- src/components/LenderProfile/LenderTeamsList.vue
- src/components/LoanCards/NewHomePageLoanCard.vue
- src/components/Stats/StatsTable.vue
- tracking events added to lender profile
Reqs: https://kiva.atlassian.net/browse/MP-570
> feat: tracking events added to lender profile

- src/components/Thanks/WhatIsNextTemplate.vue
- src/pages/Thanks/ThanksPage.vue
https://kiva.atlassian.net/browse/MP-727
- Increased who sees TY variation (all not opted in and not from originally seeing direct loan)
- Removed code from losing variation (control)
- Changed tracking event per requirements
> feat: cleanup ty page experiment for opted out users

- src/pages/Thanks/ThanksPage.vue
https://kiva.atlassian.net/browse/MP-748
- Small issue with BG color found during QA
> fix: bg was wrong when user not opted in and no loans in checkout

- src/graphql/query/portfolioQuery.graphql
- src/pages/Portfolio/ImpactDashboard/ImpactDashboardPage.vue
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- src/router/routes.js
- my kiva page added as an alternative to the portfolio page
Reqs: https://kiva.atlassian.net/browse/MP-728
Local test: https://kiva-ui.local/portfolio?setuiab=my_kiva_page.b
> feat: my kiva experiment setup added

- src/components/Thanks/BadgesCustomization.vue
- An internal user encountered a server error on the TY page
- I found an error in Grafana mentioning accessing country on undefined
- This seems like a likely spot for the issue (I couldn't repro on dev)
> fix: resolve potential loan country undefined server error

- src/pages/Checkout/CheckoutPage.vue
- ensure show available upsell loan on checkout
> fix: ensure show available upsell loan

- src/components/Thanks/BadgesCustomization.vue
https://kiva.atlassian.net/browse/MP-780
- First attempt to track down memory leak from last release
> fix: disable unshift potential memory leak

- src/pages/LenderProfile/LenderProfile.vue
- Memory fix attempt 3, disabling components for new lender profile
> fix: try disabling new lender profile page

- src/pages/Thanks/ThanksPage.vue
- Attempt 4 to track down memory leak...
> fix: try disabling ty badge

- package-lock.json
- package.json
- src/components/Charts/PieChartFigure.vue
- src/components/Charts/TreeMapFigure.vue
- src/components/Stats/StatsTable.vue
- src/pages/Portfolio/ImpactDashboard/DistributionGraphs.vue
- src/pages/Thanks/ThanksPage.vue
- The last remaining change from the changeset that introduced the memory leak was these two charts
- I decided to revert both just in a hope to finally find the memory leak, I'll rollback and look individually if this works
- Reverted TY page disable from last fix attempt
- Noticed that charts weren't actually used in one of the components, so removed...
> fix: revert chart changes

- package-lock.json
- package.json
- Turns out the memory leak was in the component library
- Starting the slow process of walking up the version until we get the issue again
> fix: walk up component lib version

- package-lock.json
- package.json
> fix: try next component lib version for memory leak

- src/pages/Portfolio/LendingStats/BadgesList.vue
https://kiva.atlassian.net/browse/MP-806
> feat: add support for new equity badge in lending stats

- package-lock.json
- package.json
- Turns out a previous PR had an incomplete package install, so need to keep walking up a few more versions
> fix: another lib version check

- src/components/Thanks/ThanksPageDonationOnly.vue
- src/pages/Thanks/ThanksPage.vue
https://kiva.atlassian.net/browse/MP-814
- New TY variation for DAF
- No receipt info needed, just a query string flag to show the page
- CPS will navigate here on successful DAF transaction
- Fixed bug where the donation TY would show "undefined" briefly on page load for existing users
> feat: daf thanks page variation

- .storybook/stories/BorrowerStatusCard.stories.js
- src/components/MyKiva/BorrowerStatusCard.vue
- src/components/MyKiva/MyKivaContainer.vue
- src/components/MyKiva/MyKivaHero.vue
- src/components/MyKiva/MyKivaNavigation.vue
- src/components/MyKiva/MyKivaProfile.vue
- src/main.js
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- My Kiva components switched to composition api
- Provider added for $kvTrackEvent
- Storybook tweaks
> feat: mykiva components switched to composition api

- config/dynamic.js
- src/head/script.js
Noticed this was still trying to load and failing in dev. It's been off a while in staging in prod so this removes the code that would previously load the script.
> chore: remove unused script include

- package-lock.json
- package.json
https://kiva.atlassian.net/browse/MP-855
> fix: update component lib to get updated select

- src/pages/Portfolio/ImpactDashboard/ImpactDashboardPage.vue
- src/router/routes.js
- My Kiva experiment setup fixed
Current portfolio: https://kiva-ui.local/portfolio?setuiab=my_kiva_page.a
My Kiva variation: https://kiva-ui.local/portfolio?setuiab=my_kiva_page.b
> fix: my kiva experiment setup fixed

- src/graphql/query/lenderPublicProfile.graphql
- src/graphql/query/userAchievementsProgress.graphql
clearing up linting errors due to new ID field added to achievements service.
> fix: add request for new ID field on userAchievementProgress

- src/components/LenderProfile/LenderSummary.vue
- error message for failed sent messages
> feat: error message failed sent messages

- src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
- src/util/getDeepComponents.js
- Redirect to Error page with message if missing contentful content (fixes error state in the ticket)
- Fix completely broken dynamic contentful rendering in the client (this isn't working on the server due to failures in getDeepComponents)
Dynamic Rendering (https://www.development.kiva.org/cc/kiva-partner <- test after deploy):
Before (https://www.development.kiva.org/cc/kiva-partner):
> fix: mp 883 cc error and dynanic rendering

- src/pages/LenderProfile/LenderProfile.vue
There may be a way to normalize this across client and server but I've not found it just yet. This fixes it this issue for now.
> fix: ensure route values during client page load

- src/components/MyKiva/BadgeModal.vue
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- generic modal added for badge states
> feat: generic modal added for badge states

- .storybook/mock-data/badge-journey-data-mock.js
- src/components/MyKiva/BadgeContainer.vue
- src/composables/useBadgeModal.js
- test/unit/specs/composables/useBadgeModal.spec.js
- We are now using badges with a consistent square shape -> image shape, not badge itself
- Small adjustments were needed to keep the journey looking correct -> there were still small differences between the square icons
> fix: adjust to new square badges

- package-lock.json
- package.json
- server/vue-worker-pool.js
We're still seeing 500ms+ event loop lag, so trying some additional steps to reduce that. Using FixedQueue can provide better performance https://github.com/piscinajs/piscina?tab=readme-ov-file#built-in-queues
> feat: use FixedQueue for better performance in the vue worker pool

- src/components/MyKiva/BadgeInProgress.vue
- src/composables/useBadgeData.js
- src/composables/useBadgeModal.js
- src/graphql/query/userAchievementProgress.graphql
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- test/unit/specs/composables/useBadgeData.spec.js
- test/unit/specs/composables/useBadgeModal.spec.js
https://kiva.atlassian.net/browse/MP-969
- Integrated the "in-progress" badge modal state with loan data
- Moved a method to the data composable for consistency
> feat: connect in progress badge modal

- src/pages/Thanks/ThanksPage.vue
May challenge section only handled the top of the page, so should not have been separated as it's own thanks page view.
> fix: may challenge should only be a header not the full view MP-974

- src/components/MyKiva/BorrowerCarousel.vue
- src/components/MyKiva/BorrowerStatusCard.vue
https://kiva.atlassian.net/browse/MP-976
https://kiva.atlassian.net/browse/MP-978
> fix: resolved a couple minor UI issues

- src/components/MyKiva/BadgeCompleted.vue
- src/components/MyKiva/BadgeModal.vue
- src/components/MyKiva/EarnedBadgesSection.vue
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- modal usage added to earned badges section
Reqs: https://kiva.atlassian.net/browse/MP-951
> feat: my kiva earned badges section modal

- src/components/MyKiva/BadgeCompleted.vue
- src/components/MyKiva/MyKivaStats.vue
- src/composables/useBadgeData.js
- test/unit/fixtures/useBadgeDataMock.js
https://kiva.atlassian.net/browse/MP-983
- Added all of the fun facts + other strings to the tiered badges in Contentful
- Updated the code to use them correctly
> feat: add share facts and test earned completed modal

- src/components/WwwFrame/Menus/DeveloperSecondaryMenu.vue
- src/pages/Build/BuildPage.vue
- src/pages/Build/DocsPage.vue
- src/pages/Build/GettingStartedPage.vue
- src/pages/Build/TermsOfService.vue
The only outstanding questions I have around this are on the legal portion which [describes private data through the old v1 api endpoints](https://github.com/kiva/ui/blob/main/src/pages/Build/TermsOfService.vue#L78).
> chore: update build/docs url to our new graph uris

- .storybook/stories/ThanksBadges.stories.js
- src/components/Thanks/MyKiva/ThanksBadges.vue
https://kiva.atlassian.net/browse/MP-1015
- Created start for MyKiva TY experience, focusing on the parts that are consistent with previous badge TY page
- Created new component, since old experiment needs to remain active until we roll out new TY experience
> feat: add initial component for MyKiva thanks experience

- src/components/MyKiva/BadgeTile.vue
- src/components/MyKiva/EarnedBadgesSection.vue
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- Header badge tile added to my kiva page
- Reqs: https://kiva.atlassian.net/browse/MP-836
Loader:
Desktop:
Mobile:
> feat: header badge tile

- src/components/MyKiva/BadgeTile.vue
- src/components/MyKiva/MyKivaStats.vue
> fix: my kiva bugs

- src/components/MyKiva/BorrowerCarousel.vue
- src/graphql/query/myKiva.graphql
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
> fix: loans number fixed

- .storybook/stories/ThanksBadges.stories.js
- src/components/Thanks/MyKiva/ThanksBadges.vue
https://kiva.atlassian.net/browse/MP-1043
Single loan:
Two loans:
Two+ loans:
> feat: opted in version of TY page badge modal

- src/components/Thanks/MyKiva/ThanksBadges.vue
https://kiva.atlassian.net/browse/MP-1042
> feat: show guest account creation on continue on new TY badge page

- src/components/MyKiva/BadgeInProgress.vue
- start index added to badge in progress carousel
> fix: start index added to badge in progress carousel

- src/components/MyKiva/MyKivaProfile.vue
- src/graphql/query/myKiva.graphql
- show lastname in my kiva profile
> feat: show lastname in my kiva profile

- src/components/MyKiva/BadgeTile.vue
> fix: badge tile width fixed

- src/components/MyKiva/BadgeInProgress.vue
- src/components/MyKiva/BadgeModal.vue
https://kiva.atlassian.net/browse/MP-1033
> fix: adjustments to badge modal

- src/components/MyKiva/MyKivaNavigation.vue
- src/graphql/query/myKiva.graphql
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- Public lender profile link added to my kiva nav
> feat: lender profile link added to my kiva nav

- src/components/MyKiva/BorrowerStatusCard.vue
- src/components/MyKiva/MyKivaHero.vue
- src/components/MyKiva/MyKivaNavigation.vue
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- borrower status card what's next issue fixed on mobile
- some navigation issues fixed
> fix: borrower status card fix

- .storybook/mock-data/thanks-badges-mock-data.js
> fix: update mock old badge

- src/components/MyKiva/MyKivaHero.vue
> fix: gear icon width fixed

- src/components/MyKiva/JournalUpdatesCarousel.vue
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- counter fixed for journal updates
> fix: journal updates counter fixed

- src/components/MyKiva/MyKivaNavigation.vue
- donate link fixed on MyKiva nav
> fix: donate link fixed on mykiva nav

- src/components/MyKiva/BadgeInProgress.vue
- MyKiva mobile loan card width fixed
> fix: mykiva mobile loan card width fixed

- src/components/MyKiva/BadgeTile.vue
Thanks catching this @emuvente
> fix: badge tile bug fixed

- src/components/SystemFrame/SystemPage.vue
- src/components/WwwFrame/LendMenu/CountryList.vue
- src/components/WwwFrame/LendMenu/LendListMenu.vue
- src/components/WwwFrame/LendMenu/LendMegaMenu.vue
- src/components/WwwFrame/LendMenu/SearchList.vue
- src/components/WwwFrame/Menus/TheMyKivaSecondaryMenu.vue
- src/components/WwwFrame/Menus/ThePortfolioTertiaryMenu.vue
- src/components/WwwFrame/Menus/TheSettingsTertiaryMenu.vue
- src/components/WwwFrame/PromotionalBanner/Banners/GenericPromoBanner.vue
- src/components/WwwFrame/PromotionalBanner/Banners/PromoCreditBanner.vue
- src/components/WwwFrame/TheFooter.vue
- src/components/WwwFrame/TheHeader.vue
- src/pages/Settings/SettingsPage.vue
- Footer background changed to bg-primary
- Underlines removed from all navigation element links (header, nav menus, secondary/tertiary link lists)
- Removed underline from promo banner
- Full page height for system page frame
- Fixed settings page nav cards styling
> fix: style updates for ecosystem theme changes

- src/pages/Portfolio/ImpactDashboard/ImpactDashboardPage.vue
- I've been watching Sentry post-MyKiva release
- So far this is the only concerning one
- Only affect 4 users, so no need for hotfix
https://kiva.sentry.io/issues/6078655554/?project=1201288&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=8
> fix: missing optional chaining

- .storybook/mock-data/badge-journey-data-mock.js
- .storybook/stories/BadgeModal.stories.js
https://kiva.atlassian.net/browse/MP-984
- Added 10 new stories for the cases missing previously in storybook
> fix: add missing stories for MyKiva badge modal

- src/pages/Portfolio/MyKiva/MyKivaPage.vue
https://kiva.atlassian.net/browse/MP-1108
> feat: hide badge tile when all journeys are complete

- src/components/MyKiva/BadgeTile.vue
https://kiva.atlassian.net/browse/MP-1067
- Simple solution for the badge title caption
> feat: add more to badge title caption

- src/pages/BorrowerProfile/BorrowerProfile.vue
https://kiva.atlassian.net/browse/MP-750
- Experiment failed, reverting to control
- Original changeset: https://github.com/kiva/ui/pull/4726
> fix: revert code for experiment ACK-469

- .storybook/stories/ThanksBadges.stories.js
- src/components/Thanks/MyKiva/ThanksBadges.vue
- src/composables/useBadgeData.js
https://kiva.atlassian.net/browse/MP-1017
- Tested guest flow locally and fixed some issues
> fix: adjustments for guest user in MyKiva TY flow

- src/pages/Thanks/ThanksPage.vue
https://kiva.atlassian.net/browse/MP-1017
- MyKiva TY wasn't being shown when it should be
> fix: resolve issue where wrong MyKiva TY page shown for guest

- src/components/Thanks/MyKiva/ThanksBadges.vue
https://kiva.atlassian.net/browse/MP-1151
> fix: improve print view of MyKiva TY page

- src/pages/Thanks/ThanksPage.vue
https://kiva.atlassian.net/browse/MP-1151
> fix: resolve issue where equality badge wasn't being shown

- src/components/Thanks/MyKiva/ThanksBadges.vue
https://kiva.atlassian.net/browse/MP-1119
- Added some missing events
- Tweaked existing events that weren't correct
> fix: added missing MyKiva TY page analytics

- src/composables/useBadgeData.js
Noticed we were missing a tag while tracking down filtering issue
> fix: climate action needed one more tag filter

- src/components/MyKiva/MyKivaStats.vue
https://kiva.atlassian.net/browse/MP-1164
> fix: adjust MyKiva lending stats language

- src/components/MyKiva/BorrowerCarousel.vue
- src/composables/useBadgeData.js
https://kiva.atlassian.net/browse/MP-1219
- Title should use active loans in count (to match loans we display in carousel)
- Added optional chaining to address data edge case that currently only happens on dev
> feat: my kiva title should only count active loans

- src/components/Thanks/MyKiva/ThanksBadges.vue
- MyKiva TY page tracking events fixed on continue CTA
> fix: mykiva ty page tracking events fixed

- src/components/Thanks/MyKiva/ThanksBadges.vue
- tracking event added for opt in only to ty page
> feat: tracking event added for opt in only to ty page

- src/components/Thanks/MyKiva/ThanksBadges.vue
- src/pages/Thanks/ThanksPage.vue
- src/util/myKivaUtils.js
- test/unit/specs/util/myKivaUtils.spec.js
https://kiva.atlassian.net/browse/MP-1220
https://kiva.atlassian.net/browse/MP-1223
- Add tracking back to MyKiva portfolio page
- Log assignment for all users who see TY page + portfolio page
- Add some extra analytics to page load to be able to report of version of MyKiva TY page
- Remove door into MyKiva experiment from old TY badge experiment
> fix: update issues with mykiva tracking and assignment

- .github/workflows/run-ui-tests.yml
- src/components/Thanks/Badges/FirstScreen.vue
- src/components/Thanks/BadgesCustomization.vue
- src/pages/Thanks/ThanksPage.vue
- Opt-in and opt-out modules added to old badge TY page
Opt-in:
Opt-out:
> feat: optin and optout modules added to old badge ty page

- src/App.vue
Same as kiva/cms-page-server#1729
> perf: preload dovetail font

- src/components/Thanks/WhatIsNextTemplate.vue
- opt-in option added for guest users in non MyKiva TY page
> feat: optin option added to guest users in non mykiva ty page

- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- src/util/myKivaUtils.js
- test/unit/specs/util/myKivaUtils.spec.js
https://kiva.atlassian.net/browse/MP-1235
- Changed experiment key to reset assignments
- Changed experiment action to reset reporting
- Changed user preference setting to reset permanent viewing of MyKiva
> fix: update my kiva settings keys

- tailwind.config.js
fix up missing styles due to tailwind not including the compiled js kv-components
> fix: include new kv-components dist folder in tailwind content

- src/components/MyKiva/BadgeCompleted.vue
- src/components/MyKiva/EarnedBadgesSection.vue
- src/composables/useBadgeData.js
- test/unit/specs/composables/useBadgeData.spec.js
- modal added for non tiered badges
> feat: modal added for non tiered badges

- src/pages/Portfolio/MyKiva/MyKivaPage.vue
https://kiva.atlassian.net/browse/MP-1238
- We were combining journal updates when MyKiva borrower carousel selection changed
> fix: reset journal updates when selected loan changed

- src/components/Thanks/SingleVersion/LoanComment.vue
- src/components/Thanks/ThanksPageSingleVersion.vue
- src/composables/useTipMessage.js
- src/pages/Thanks/ThanksPage.vue
- Commenting module added to unified TY page
- Composable added to show tip message
Desktop:
Mobile:
> feat: commenting module added to unified ty page

- .storybook/stories/ThanksPageSingleVersion.stories.js
- .storybook/stories/ThanksPageUnifiedVersion.stories.js
- src/components/LenderProfile/BadgeCard.vue
- src/components/Thanks/MyKiva/OptInModule.vue
- src/components/Thanks/SingleVersion/KivaCards.vue
- src/components/Thanks/SingleVersion/LoanComment.vue
- src/components/Thanks/ThanksPageSingleVersion.vue
https://kiva.atlassian.net/browse/MP-1265
- Cleaned up some module style for consistency between modules
- Renamed the story file to match the component name
- Removed the TS props from the components, since this project doesn't use TS and it was showing errors in VSCode
- Resolved prop type console warning related to `onlyDonations` being number or boolean
- Created new Kiva Cards module
- Button emits, but event will be handle by future ticket
> feat: kiva card print card module

- src/components/Thanks/SingleVersion/AccountReceiptShare.vue
- src/components/Thanks/ThanksPageSingleVersion.vue
- src/pages/Thanks/ThanksPage.vue
https://kiva.atlassian.net/browse/MP-1311
- Ported over misc module from MyKiva, creating new dedicated component
- Added scroll to order confirmation from kiva cards section, since the confirmation has the buttons to download individual PDFs
- Added missing props to ty component
> feat: miscellaneous module ported from my kiva ty page

- .storybook/stories/ThanksPageSingleVersion.stories.js
- src/components/Thanks/SingleVersion/BadgeMilestone.vue
- src/components/Thanks/ThanksPageSingleVersion.vue
- src/pages/Thanks/ThanksPage.vue
https://kiva.atlassian.net/browse/MP-1318
https://kiva.atlassian.net/browse/MP-1319
https://kiva.atlassian.net/browse/MP-1313
- Ported badge module over from MyKiva TY page
- Added confetti to page load
- Created generic continue method that will be needed for several modules
> fix: badge module for new ty page

- src/graphql/query/thanksPage.graphql
- src/pages/Thanks/ThanksPage.vue
- ui setting added for single version ty page
> feat: ui setting added for single version ty page

- src/components/Checkout/CheckoutReceipt.vue
- src/components/Thanks/SingleVersion/AccountReceiptShare.vue
- src/components/Thanks/SingleVersion/LoanComment.vue
- elements hidden in single TY page when printing
> fix: elements hidden in single ty page when printing

- src/components/Thanks/ThanksPageSingleVersion.vue
https://kiva.atlassian.net/browse/MP-1269
https://kiva.atlassian.net/browse/MP-1334
- Added view analytics event to new TY page for module order
- Fixed issue where badge module was sometimes shown incorrectly (donation and kiva card use cases)
> feat: add view analytics for new ty page

- src/components/Thanks/SingleVersion/AccountReceiptShare.vue
https://kiva.atlassian.net/browse/MP-1332
> fix: resolved clunky closing animation on order confirmation

- src/pages/Portfolio/ImpactDashboard/DistributionGraphs.vue
Changing to correct variable name for portfolio dashboard stats
> fix: variable name for active loans

- .storybook/mock-data/receipt-data-mock.js
- .storybook/stories/ThanksPageSingleVersion.stories.js
- src/components/Thanks/SingleVersion/BadgeMilestone.vue
- src/components/Thanks/ThanksPageSingleVersion.vue
> feat: add borrowers avatars to badge module mp 1336

- src/components/Thanks/ThanksPageSingleVersion.vue
https://kiva.atlassian.net/browse/MP-1351
Also resolved a console error due to prop type being wrong.
> fix: equity badge should be shown to guest users

- .storybook/stories/ThanksPageSingleVersion.stories.js
- src/components/Thanks/SingleVersion/BadgeMilestone.vue
- fun fact and fun fact sourced added to single TY page badge module
> feat: fun fact added to single ty page badge module

- .github/workflows/run-ui-tests.yml
- src/components/Thanks/SingleVersion/BadgeMilestone.vue
- badge fun fact fixed to match mocks
> fix: badge fun fact fixed to match mocks

- src/components/Thanks/SingleVersion/BadgeMilestone.vue
- src/components/Thanks/ThanksPageSingleVersion.vue
https://kiva.atlassian.net/browse/MP-1334
> fix: badge module wasn't being shown when there was a kiva card and donationm

- .storybook/stories/JournalUpdateCard.stories.js
- .storybook/stories/JournalUpdatesCarousel.stories.js
- src/components/MyKiva/BorrowerCarousel.vue
- src/components/MyKiva/JournalUpdateCard.vue
- src/graphql/query/loanUpdates.graphql
- src/graphql/query/userUpdates.graphql
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
> feat: mykiva user updates fixed

- src/plugins/add-to-basket-exp-mixin.js
- New ATB experience UI setting added
> feat: new atb exp UI setting

- server/auth-router.js
- src/components/Checkout/CheckoutDropInPaymentWrapper.vue
- src/components/Forms/GuestAccountCreation.vue
- src/components/Thanks/CommentAsk.vue
- src/components/Thanks/MyKiva/ThanksBadges.vue
- src/components/Thanks/SingleVersion/AccountReceiptShare.vue
- src/components/Thanks/ThanksPageCommentAndShare.vue
- src/components/Thanks/ThanksPageSingleVersion.vue
- src/components/Thanks/WhatIsNextTemplate.vue
- src/pages/Checkout/CheckoutPage.vue
- src/pages/Checkout/PostPurchase.vue
- src/pages/LoginAndRegister/GuestAccountRedirect.vue
- src/pages/Thanks/ThanksPage.vue
- guest username passed to auth flow
> feat: guest username passed to auth flow

- src/components/BorrowerProfile/LendCta.vue
- src/plugins/add-to-basket-exp-mixin.js
> feat: atb modal added to BP

- src/pages/Thanks/ThanksPage.vue
- Passing correct number of loans for guest to get my kiva exp flag
> fix: my kiva ty page fixed

- server/auth-router.js
- login hint refactor to include username for account claiming process
> fix: login hint refactor to include username for account claiming

- src/graphql/query/whyKivaData.graphql
- src/pages/MonthlyGood/KivaAsExpert.vue
Also, adding `null` as a default value for stats to trigger fallback cases
> feat: use new field for amountFunded value

- src/pages/LoginAndRegister/GuestAccountRedirect.vue
> fix: missing field login hint

- src/pages/MonthlyGood/KivaAsExpert.vue
https://kiva.atlassian.net/browse/MP-1373
> fix: adjust monthly good page text

- src/components/BorrowerProfile/LendCta.vue
- src/components/WwwFrame/TheHeader.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
- src/pages/Lend/LoanSearchPage.vue
- src/pages/LoanFinding/LoanFinding.vue
> feat: atb modal position fix

- src/components/WwwFrame/LendMenu/LendListMenu.vue
- src/components/WwwFrame/LendMenu/LendMegaMenu.vue
- recommended loans removed from nav
> feat: recommended loans removed from nav

- src/components/BorrowerProfile/LendCta.vue
- src/components/WwwFrame/Header/KvAtbModalContainer.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
- src/pages/Lend/LoanSearchPage.vue
- src/pages/LoanFinding/LoanFinding.vue
- src/plugins/basket-modal-mixin.js
> feat: kv cart modal container added

- package-lock.json
- package.json
- src/components/BorrowerProfile/LendCta.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/LoanCards/KvClassicLoanCardContainer.vue
- src/components/WwwFrame/Header/KvAtbModalContainer.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
- src/pages/Lend/LoanSearchPage.vue
- src/pages/LoanFinding/LoanFinding.vue
- src/plugins/basket-modal-mixin.js
> feat: kv cart modal update

- src/components/Thanks/SingleVersion/OptInModule.vue
- spinner added to opt-in module buttons
> feat: spinner added to optin module buttons

- src/components/Thanks/MyKiva/OptInModule.vue
- src/components/Thanks/SingleVersion/OptInModule.vue
- src/composables/useOptIn.js
- src/graphql/query/thanksPage.graphql
- src/pages/Thanks/ThanksPage.vue
- correct email settings from opt-in modules
> fix: correct email settings from optin modules

- src/components/Checkout/BasketItem.vue
- src/plugins/loan-channel-query-map.js
https://kiva.atlassian.net/browse/MP-1414
- Updated basic-needs filter set
- Needed to resolve a linting error on import
> fix: update basic needs mapping flss filters

- src/plugins/loan-channel-query-map.js
https://kiva.atlassian.net/browse/MP-1414
- Needed for advanced filter link on category page
> fix: add query params for basic needs category page

- package-lock.json
- package.json
- src/components/WwwFrame/Header/KvAtbModalContainer.vue
- src/graphql/query/userAtbModal.graphql
- src/util/myKivaUtils.js
- MyKiva experiment flag added to ATB modal container
> feat: mykiva experiment flag added to atb modal container

- package-lock.json
- package.json
- src/components/BorrowerProfile/LendCta.vue
- src/components/LoanCards/KvClassicLoanCardContainer.vue
- src/components/WwwFrame/Header/KvAtbModalContainer.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
- src/pages/Lend/LoanSearchPage.vue
- src/pages/LoanFinding/LoanFinding.vue
- src/plugins/basket-modal-mixin.js
- First approach to MyKiva ATB modal
**Note: Upcoming work for 1 additional loan away edge case**
> feat: first approach to my kiva atb modal

- build/fetch-schema.js
- config/dynamic.js
- server/dev-server.js
- server/index.js
- server/util/config.js
- server/util/fetch.js
- server/util/fetchGraphQL.js
- server/vue-middleware.js
- src/api/HttpLink.js
- src/api/apollo.js
- src/main.js
- src/server-entry.js
- test/unit/specs/server/live-loan-fetch.spec.js
- This adds a config singleton that can be imported in any server file that needs the config
- This sets the User-Agent header for server requests based on the USER_AGENT environment variable
> feat: user agent for UI server requests

- package-lock.json
- package.json
- src/components/BorrowerProfile/LendCta.vue
- src/components/WwwFrame/Header/KvAtbModalContainer.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
- src/pages/Lend/LoanSearchPage.vue
- src/pages/LoanFinding/LoanFinding.vue
- src/plugins/basket-modal-mixin.js
- One loan away option at my kiva ATB modal
- Reqs: https://kiva.atlassian.net/browse/MP-1272
> feat: one loan away option at my kiva atb modal

- src/graphql/query/portfolioQuery.graphql
- src/pages/Portfolio/ImpactDashboard/ImpactDashboardPage.vue
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- ui setting added to show new My Kiva hero
> feat: ui setting added to show new my kiva hero

- src/components/Contentful/JourneyCardCarousel.vue
- gradient added to journey card carousel
Desktop:
Mobile:
> feat: gradient added to journey card carousel

- .storybook/stories/JourneyCardCarousel.stories.js
- src/components/Contentful/JourneyCardCarousel.vue
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- Contentful data added to new my kiva hero carousel
- Reqs: https://kiva.atlassian.net/browse/MP-1395
- Data: https://app.contentful.com/spaces/j0p9a6ql0rn7/environments/development/entries/5R8wb9yVrOfuOMigZwZR9Z?focusedField=slides
Loading:
> feat: contentful data added to new my kiva hero carousel

- src/graphql/query/portfolio/myDonations.graphql
- src/pages/Portfolio/Donations/DonationsPage.vue
- src/router/routes.js
https://kiva.atlassian.net/browse/MP-1308
- Ported the /portfolio/donations page to newstack
- All existing functionality ported
- Used simple table, export to abstract component pending design review
- Desktop and mobile views implemented
- Using beta route to enable functional QA on dev (changes already in flux)
> feat: implement portfolio donations page using new graphql query

- src/components/Contentful/JourneyCardCarousel.vue
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- My Kiva hero carousel order
- https://kiva.atlassian.net/browse/MP-1400
Loading:
Ordered:
> feat: my kiva hero carousel order

- src/components/Contentful/JourneyCardCarousel.vue
- feat: progress and badge added to journey
- https://kiva.atlassian.net/browse/MP-1399
- spacing added to clarify logic
> feat: progress and badge added to journey

- src/pages/Portfolio/Donations/DonationsPage.vue
https://kiva.atlassian.net/browse/MP-1308
- Link click areas were stretching in mobile
- Smoothed out loader pop-in for annual donations section
> fix: minor tweaks to donations mobile view

- src/components/Contentful/JourneyCardCarousel.vue
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- Toggling off badge tile when the hero is shown
- Changing “challenge” to “level X” in journey card
> feat: my kiva carousel small tweaks

- src/components/Contentful/JourneyCardCarousel.vue
- analytics added to my kiva carousel CTAs
> feat: analytics added to my kiva carousel ctas

- src/router/routes.js
https://kiva.atlassian.net/browse/MP-1445
- Migrated page passes QA, now to start release to prod
- Flux changes coming once this is live in prod
> feat: roll out new donations migration

- src/components/WwwFrame/Header/KvAtbModalContainer.vue
- first loan option showed under my kiva flag
> fix: first loan option showed under my kiva flag

- src/components/MyKiva/BadgesSection.vue
- journey modal open from my kiva carousel
> feat: journey modal open from my kiva carousel

- server/util/live-loan/live-loan-fetch.js
- src/util/loanCallouts.js
- test/unit/specs/util/loanCallouts.spec.js
- public tags filtered for live loans callouts
> feat: public tags filtered for live loans callouts

- package-lock.json
- package.json
- vite.config.js
https://kiva.atlassian.net/browse/MP-1472
- Looked at how we handled the `@kiva/kv-components` upgrade, and the same tweak worked for `@kiva/kv-shop`
> fix: resolve server error on checkout page from kv-shop

- package-lock.json
- package.json
https://kiva.atlassian.net/browse/MP-1471
> fix: update components to resolve error on avatar load

- src/components/WwwFrame/Header/KvAtbModalContainer.vue
- ATB modal fixed for first loan
> fix: atb modal fixed for first loan

- src/components/Contentful/JourneyCardCarousel.vue
https://kiva.atlassian.net/browse/MP-1476
> fix: slightly larger padding in hero CTA desktop version

- src/components/Checkout/BasketItemsList.vue
https://kiva.atlassian.net/browse/MP-1479
> fix: show milestone in checkout right after a non-tiered milestone achieved

- src/components/Contentful/JourneyCardCarousel.vue
- mykiva carousel subtitle update
> fix: mykiva carousel subtitle update

- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- remove url query when journey modal closed
https://kiva.atlassian.net/browse/MP-1502
> fix: remove url query when journey modal closed

- src/components/Thanks/MyKiva/ThanksBadges.vue
- src/components/Thanks/ThanksPageSingleVersion.vue
- src/composables/useBadgeData.js
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- src/pages/Thanks/ThanksPage.vue
- src/util/myKivaUtils.js
- test/unit/specs/util/myKivaUtils.spec.js
- all My Kiva scrolling actions removed
- https://kiva.atlassian.net/browse/MP-1494
> feat: all my kiva scrolling actions removed

- src/components/Contentful/JourneyCardCarousel.vue
- completed journey hidden in my kiva hero carousel
- https://kiva.atlassian.net/browse/MP-1503
> feat: completed journey hidden in my kiva hero carousel

- src/components/Thanks/MyKiva/ThanksBadges.vue
- src/components/Thanks/ThanksPageSingleVersion.vue
- src/pages/Thanks/ThanksPage.vue
- My kiva TY page redirects fixed to my kiva all users
- https://kiva.atlassian.net/browse/MP-1510
> feat: my kiva ty page redirects fixed to my kiva all users

- server/util/live-loan/live-loan-fetch.js
- src/api/localResolvers/loan.js
- src/components/BorrowerProfile/LendCta.vue
- src/components/BorrowerProfile/SummaryCard.vue
- src/components/LoanCards/NewHomePageLoanCard.vue
- src/components/LoanCards/RecommendedLoanCard.vue
- src/graphql/fragments/loanCardFields.graphql
- src/graphql/fragments/loanCardFieldsExtended.graphql
- src/graphql/query/basketLoansInfo.graphql
- src/graphql/query/checkout/initializeCheckout.graphql
- src/graphql/query/checkout/shopBasketUpdate.graphql
- src/graphql/query/checkout/upsellLoans.graphql
- src/graphql/query/loanCardBasketed.graphql
- src/graphql/query/portfolio/myLoans.graphql
- src/graphql/query/thanksPageReceipt.graphql
- src/graphql/query/userUpdates.graphql
- src/pages/BorrowerProfile/BorrowerProfile.vue
- src/pages/InstantActions/ProcessInstantLending.vue
- src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
- src/pages/Portfolio/ImpactDashboard/RecentLoanItem.vue
Addressing graphql lint errors about querying for new ID field on LoanFundraisingInfo.
> feat: add ID field for LoanFundraisingInfo queries

- src/components/Contentful/JourneyCardCarousel.vue
- src/components/MyKiva/BadgesSection.vue
- src/pages/MyKiva/MyKivaPage.vue
- avoid pushing route to open journey modal from hero carousel
- https://kiva.atlassian.net/browse/MP-1513
> feat: avoid pushing route to open journey modal from hero carousel

- src/plugins/my-kiva-homepage-mixin.js
https://kiva.atlassian.net/browse/MP-1427
- Bug uncovered during other testing
- Only redirect to MyKiva if the new feature is enabled
> fix: don't redirect when new feature disabled

- src/components/WwwFrame/TheHeader.vue
- sticky header for lg screens only
- https://kiva.atlassian.net/browse/MP-1514
> feat: sticky header for lg screens only

- README.md
- Added a missing step in our `README` that was identified when onboarding our latest engineer
- Also tweaked some formatting
> chore: update readme config

- .storybook/stories/JourneyCardCarousel.stories.js
- src/components/Contentful/JourneyCardCarousel.vue
- Contentful non-badges slides added to journeys carousel
- https://kiva.atlassian.net/browse/MP-1505
- Carousel data: https://app.contentful.com/spaces/j0p9a6ql0rn7/environments/development/entries/5R8wb9yVrOfuOMigZwZR9Z
Desktop:
Mobile:
> feat: non badges slides added to journeys carousel

- src/components/MyKiva/MyKivaSharingModal.vue
- auto copy sharing url removed
- https://kiva.atlassian.net/browse/MP-1541
> fix: auto copy sharing url removed

- src/components/Checkout/BasketItemsList.vue
- src/components/WwwFrame/Header/KvAtbModalContainer.vue
> fix: equity basket pill and first loan logic to show equity badge

- server/util/live-loan/live-loan-fetch.js
> feat(ui): add amountLeft filter to Live Loans

- src/pages/Portfolio/ImpactDashboard/ImpactDashboardPage.vue
- donations section moved on portfolio page
- https://kiva.atlassian.net/browse/MP-1536
> feat: donations section moved on portfolio page

- src/components/Checkout/BasketItem.vue
https://kiva.atlassian.net/browse/MP-1549
- Minor tweaks to make checkout pills consistent sizes
> fix: adjust mykiva checkout pills

- src/pages/Lend/LoanChannelCategoryPage.vue
- src/pages/Lend/LoanSearchPage.vue
- combo page flag added to filter and category pages
- https://kiva.atlassian.net/browse/MP-1480
> feat: combo page flag added to filter and category pages

- src/components/WwwFrame/Header/KvAtbModalContainer.vue
https://kiva.atlassian.net/browse/MP-1543
- Resolved regression with ATB pills for logged-in users
- Fixed spelling
> fix: resolve issue with logged in mykiva atb pills

- src/pages/Lend/LoanChannelCategoryPage.vue
- src/pages/Lend/LoanSearchPage.vue
> fix: combo page redirect fix

- src/components/WwwFrame/Header/KvAtbModalContainer.vue
https://kiva.atlassian.net/browse/MP-1543
- Another fix for ATB related to logged-out users
> fix: adjust logic for logged out user atb

- src/components/WwwFrame/Header/KvAtbModalContainer.vue
https://kiva.atlassian.net/browse/MP-1543
- That's what I get for moving fast...
> fix: another issue with atb resolved

- server/util/live-loan/live-loan-fetch.js
- test/unit/specs/server/live-loan-fetch.spec.js
Introduces a single filters set as opposed to an array of filter objects in order to properly OR the filters together within a single GraphQL query.
> fix: fixes the FLSS multiple filters bug

- src/components/WwwFrame/Header/KvAtbModalContainer.vue
https://kiva.atlassian.net/browse/MP-1543
- Figured out how to test locally... and to change things
> fix: hopefully last atb fix

- src/components/MyKiva/BorrowerCarousel.vue
- src/graphql/query/portfolioQuery.graphql
- src/pages/Portfolio/ImpactDashboard/ImpactDashboardPage.vue
- disclaimer added to portfolio page
- https://kiva.atlassian.net/browse/MP-1551
> feat: disclaimer added to portfolio page

- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- show sort dropdown for basic needs in category page
- https://kiva.atlassian.net/browse/MP-1566
> feat: show sort dropdown basic needs category

- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- src/plugins/loan-channel-query-map.js
- almost funded loan channel updates
We have renamed almost funded loan channel.
> feat: almost funded loan channel updates

- src/components/MyKiva/BorrowerCarousel.vue
- carousel controls added to MyKiva borrowers slides
- https://kiva.atlassian.net/browse/MP-1571
> feat: carousel controls added to mykiva borrowers slides

- src/pages/MyKiva/MyKivaPage.vue
- src/pages/MyKiva/MyKivaPageContent.vue
- src/util/myKivaUtils.js
- MyKiva page data prefetched
- https://kiva.atlassian.net/browse/MP-1603
> feat: mykiva data prefetched

- src/components/Contentful/JourneyCardCarousel.vue
- src/components/MyKiva/MyKivaStats.vue
- src/pages/MyKiva/MyKivaPage.vue
- src/pages/MyKiva/MyKivaPageContent.vue
- Data for my kiva hero carousel prefetch
- https://kiva.atlassian.net/browse/MP-1607
> feat: mykiva hero carousel loading refactor

- package-lock.json
- package.json
- src/components/WwwFrame/Header/KvAtbModalContainer.vue
- atb modal experience replached with shared component
- https://kiva.atlassian.net/browse/MP-1554
> feat: atb modal experience replaced with shared component

- src/components/Contentful/JourneyCardCarousel.vue
- src/pages/MyKiva/MyKivaPageContent.vue
- read queries moved to created in child components at mykiva page
- https://kiva.atlassian.net/browse/MP-1626
> fix: read queries moved to created at mykiva page

- src/components/MyKiva/BadgeModalContentJourney.vue
- src/pages/MyKiva/MyKivaPageContent.vue
Updates the copy on the `MyKivaPageContent` and `BadgeModalContentJourney` components based on the instructions for [MP-1605](https://kiva.atlassian.net/browse/MP-1605).
[MP-1605]: https://kiva.atlassian.net/browse/MP-1605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fix copy in MyKivaPageContent and BadgeModelContentJourney

- src/pages/MyKiva/MyKivaPageContent.vue
> feat: change achievements title to my achievements in my kiva

- src/router/routes.js
https://kiva.atlassian.net/browse/MP-1573
- Removed redirect no longer needed now that combo page supports all channels
> fix: update loan channels data

- package-lock.json
- package.json
- src/components/Contentful/JourneyCardCarousel.vue
- src/components/MyKiva/BadgeModalContentJourney.vue
- src/components/MyKiva/BadgesSection.vue
- src/components/MyKiva/BorrowerCarousel.vue
- src/components/MyKiva/BorrowerStatusCard.vue
- src/components/MyKiva/JournalUpdateCard.vue
- src/components/MyKiva/JournalUpdatesCarousel.vue
- src/components/MyKiva/MyKivaHero.vue
- src/components/MyKiva/MyKivaProfile.vue
- src/components/MyKiva/MyKivaStats.vue
- src/components/MyKiva/StatItem.vue
- src/components/Thanks/LoanNextSteps.vue
- src/pages/MyKiva/MyKivaPageContent.vue
https://kiva.atlassian.net/browse/MP-1643
https://kiva.atlassian.net/browse/MP-1650
https://kiva.atlassian.net/browse/MP-1638
- We mob programmed a bunch of tweaks to MyKiva at the onsite -> trying to iron out changes before Nathan being gone for a few weeks
- See tickets for the big list of tweaks and the screenshots below
> feat: misc changes and improvements to MyKiva UI from onsite

- src/components/LoanFinding/LendingCategorySection.vue
- src/pages/MyKiva/MyKivaPage.vue
- src/pages/MyKiva/MyKivaPageContent.vue
- Recommended loans carousel added to mykiva page
- https://kiva.atlassian.net/browse/MP-1635
> feat: recommended loans added to mykiva page

- src/components/MyKiva/BadgesSection.vue
- src/pages/MyKiva/MyKivaPageContent.vue
- loaders added to mykiva achievements section
- https://kiva.atlassian.net/browse/MP-1659
> feat: loaders added to mykiva achievements section

- src/components/Contentful/JourneyCardCarousel.vue
- src/composables/useBadgeData.js
- src/graphql/query/myKiva.graphql
- src/pages/MyKiva/MyKivaPageContent.vue
- test/unit/specs/composables/useBadgeData.spec.js
- last transaction considered for my kiva journeys sort
- https://kiva.atlassian.net/browse/MP-1683
> feat: journeys carousel update

- src/composables/useBadgeData.js
- src/plugins/loan-channel-query-map.js
https://kiva.atlassian.net/browse/MP-1577
> fix: update basic needs filters

- src/components/WwwFrame/SearchBar.vue
- test/unit/specs/components/WwwFrame/SearchBar.spec.js
https://kiva.atlassian.net/browse/MP-1719
> fix: add tracking to nav search bar

- src/components/BorrowerProfile/BorrowerSideSheetContent.vue
- src/components/BorrowerProfile/BorrowerSideSheetWrapper.vue
- src/components/MyKiva/BorrowerCarousel.vue
- src/components/MyKiva/LatestBlogCarousel.vue
- Found minor bug while testing for release
- Also resolve a console warning
> fix: side sheet content was wrong for MyKiva recommended carousel

- src/components/MyKiva/LendingStats.vue
- src/components/MyKiva/MyKivaProfile.vue
- src/pages/MyKiva/MyKivaPage.vue
- src/pages/MyKiva/MyKivaPageContent.vue
- Lending stats experiment added to MyKiva page
- Some refactor in the page
- https://kiva.atlassian.net/browse/MP-1745
> feat: lending stats experiment added to mykiva page

- src/components/Contentful/JourneyCardCarousel.vue
- src/pages/MyKiva/MyKivaPage.vue
- src/pages/Portfolio/ImpactDashboard/LoanCards.vue
- src/util/myKivaUtils.js
- Duplicated loans on mykiva fixed
- https://kiva.atlassian.net/browse/MP-1835
NOTE: Having a query limit of 100 transactions, we are showing 8 loans after filtering for reported case.
> fix: showing unique transactions in my kiva page

- src/components/MyKiva/JournalUpdateCard.vue
- src/graphql/query/myKiva.graphql
- update cards avatars fixed
- https://kiva.atlassian.net/browse/MP-1840
Bug:
Fix:
> fix: update cards avatars fixed

- src/graphql/query/myKiva.graphql
- src/pages/MyKiva/MyKivaPage.vue
- src/pages/MyKiva/MyKivaPageContent.vue
- src/pages/Portfolio/ImpactDashboard/LoanCards.vue
- My Kiva loans query reverted to show them correctly
- https://kiva.atlassian.net/browse/MP-1835
> fix: my kiva loans query reverted

- .storybook/stories/MyKivaCard.stories.js
- src/components/MyKiva/MyKivaCard.vue
- carousel added to MyKiva card
- Part of https://kiva.atlassian.net/browse/MP-1751
> feat: carousel added to mykiva card

- tailwind.config.js
> fix: remove tw fake line

- src/util/myKivaUtils.js
- test/unit/specs/util/myKivaUtils.spec.js
https://kiva.atlassian.net/browse/MP-1854
- Change mykiva redirect cookie for clean slate
> fix: update mykiva redirect cookie name

- src/components/Checkout/CheckoutDropInPaymentWrapper.vue
- src/components/Checkout/KivaCreditGuestPayment.vue
- src/components/Checkout/UserUpdatesPreference.vue
- src/pages/LoginAndRegister/RegisterSocial.vue
https://kiva.atlassian.net/browse/MP-1183
> fix: update tou checkbox label

- src/components/MyKiva/LendingStats.vue
> fix: mp-1748 / HOTFIX / Add Recommendations for Next Regions to Lend To

- package-lock.json
- package.json
Import the latest version of kv-tokens
> chore: update kv-tokens to 3.2.1

- src/components/MyKiva/JournalUpdateCard.vue
Just adding the missing dot here the filter issue will be addressed as a separate task
https://kiva.atlassian.net/browse/MP-1829
> fix: add missing dot to update card (MP-1829)

- src/pages/MyKiva/MyKivaPageContent.vue
- show next steps for mykiva borrowers carousel
- https://kiva.atlassian.net/browse/MP-1902
> fix: show next steps for mykiva borrowers carousel

- src/components/MyKiva/LendingStats.vue
> fix: mp-1921 update empty copy

- src/components/WwwFrame/Header/KvAtbModalContainer.vue
- src/graphql/query/basketItems.graphql
- ATB modal showed based on user balance and basket total
- https://kiva.atlassian.net/browse/MP-1933
> fix: atb modal showed based on user balance and basket total

- package-lock.json
- package.json
- src/pages/GivingFunds/GivingFundsManagementPage.vue
- Integrates the pulsing dot for active fundraiser
- Integrates the utility menu for each fund
- Update links to fund with new `action=donate/edit/start-fundraiser/share` query param to enable activating those functions once we reach the fund page
> fix: integrate new utility menu, pulsing do and update links

- src/components/BorrowerProfile/BorrowerSideSheetContent.vue
- src/components/BorrowerProfile/LoanProgress.vue
- progress bar added to bp side sheet alongside next steps
- https://kiva.atlassian.net/browse/MP-1869
> feat: progress bar added to bp side sheet alongside next steps

- src/pages/Portfolio/ImpactDashboard/ImpactDashboardPage.vue
- src/pages/Portfolio/ImpactDashboard/LendingInsights.vue
- Percentile by year experiment setup on portfolio page
- https://kiva.atlassian.net/browse/MP-1837
> feat: portfolio percentile by year experiment setup

- src/components/MyKiva/BailoutChips.vue
- src/components/MyKiva/PillsContainer.vue
- src/components/WwwFrame/LendMenu/TheLendMenu.vue
- src/graphql/query/countryList.graphql
- src/pages/MyKiva/MyKivaPageContent.vue
- Bailout section added on my kiva
- https://kiva.atlassian.net/browse/MP-1591
> feat: mykiva bailout section

- package-lock.json
- package.json
- kv tokens update
- https://kiva.atlassian.net/browse/MP-1899
> chore: kv tokens update

- src/pages/GivingFunds/GivingFundsManagementPage.vue
- Updates to zero fund state card copy and to include a button to create a fund
- Hide header button if zero state card is shown
> fix: copy and button updates for zero funds state

- src/components/MyKiva/BailoutChips.vue
- src/components/MyKiva/PillsContainer.vue
- More CTA added to MyKiva bailout category section
- https://kiva.atlassian.net/browse/MP-1971
> feat: more cta added to mykiva bailout category section

- server/live-loan-router.js
https://kiva.atlassian.net/browse/MP-1956
- Looking at the live-loan logs, it looks like the error is with sending the response after getting the image from the cache, and I'm seeing errors also from this week
- This PR isolates that response send to verify if this is indeed where the exception is occurring, with the URL that is being used for the loan image
> fix: isolate getting and serving image to narrow down exception

- src/pages/MyKiva/MyKivaPageContent.vue
https://kiva.atlassian.net/browse/MP-1934
> fix: resolve flex gap issues in mykiva recommended carousel

- package-lock.json
- package.json
- src/components/WwwFrame/LendMenu/LendListMenu.vue
- src/components/WwwFrame/LendMenu/LendMegaMenu.vue
- src/components/WwwFrame/LendMenu/TheLendMenu.vue
- src/components/WwwFrame/TheHeader.vue
https://kiva.atlassian.net/browse/MP-1826
> fix: resolve issue with countries exp nav redirect

- src/components/GivingFunds/ManagementCard.vue
- src/components/GivingFunds/ManagmentCard.vue
- src/composables/useGivingFund.js
- src/graphql/query/portfolio/myGivingFundParticipationDonations.graphql
- src/pages/GivingFunds/GivingFundsManagementPage.vue
Also included:
- created new fund participation query file for getting donation amounts
- started a new useGivingFund composable
- extracted the management card into it's own component
> fix: fetch and calculate my donations against a given fund

- src/components/Contentful/JourneyCardCarousel.vue
- src/components/MyKiva/GoalCard.vue
- src/components/MyKiva/LendingStats.vue
- src/pages/MyKiva/MyKivaPageContent.vue
https://kiva.atlassian.net/browse/MP-2012
Only missing piece is integrating the achievement card from other ticket (left the spot in a comment)
> feat: add complete goal card to lending stats
