kiva/ui

- package-lock.json
- package.json
apollo-link-http v1.5.3 has a bug which is crashing our server: https://github.com/apollographql/apollo-link/issues/542
> Limit apollo-link-http version to ^1.5.0 excluding 1.5.3

- src/components/LoanCards/ActionButton.vue
- src/components/LoanCards/BorrowerInfo.vue
- src/components/LoanCards/GridLoanCard.vue
- src/components/LoanCards/MatchingText.vue
Here are the loan card pieces cleaned up and implemented with flexbox, loan cards now work across all screen sizes. @jedlin-kiva I also cleaned up the rem vs rem-calc conflict you mentioned in the last code review.
> redoing loan cards with flexbox, cleaning up rem->rem-calc

- src/components/WwwFrame/PromotionalBanner/Banners/BonusBanner.vue
We're leaving the whole banner clickable, but I need a  new line of css to prevent the text from getting a blue underline on mouseover or touch.
> vue-75 don't underline select a borrower to text on hover

- src/components/LoanCards/Buttons/CheckoutNowButton.vue
Trying some more specific css here to fix this reported issue: 
"On the mobile devices, the checkout now button is always blue, should be black. Also on ie when the proceed to basket is clicked the checkmark image turns black, all the rest remains blue"
Having issues setting up something to test my vm on mobile so I want to get this into dev and test it out on my phone.
> vue-82 giving more specific css a shot.

- src/components/Checkout/LoanPrice.vue
Looks like the last fix didn't work for MS Edge browser. Here is a new media query with css rule targeted to that browser only.
> Another media query targeting the MS Edge browser specifically

- src/App.vue
- src/components/WwwFrame/TheFooter.vue
These 2 items are in the release branch (release-09262018) that will push out /protocol .
1. We forgot to update the dimensions with the new og:image so those are updates.
2. I've unfortunately, discovered a weird issue with our cache wherein the client renders multiple times if there is a mismatch with the html from the footer html that is cached. I've turned it off for now b/c it results in the paypal button being rendered 3 times stacked up. India is doing testing on this and I don't want to freak them out...
One fix is to clear memcached after any changes are made to cached content. Having an easy way to clear specific entried in memcached would be one solution. I'll continue trying to find a solution in our initialization and render of the paypal button too as it likely applies to …
> fix og:image dimensions and turn off footer cache

- src/components/Forms/RegisterForm.vue
@emuvente Your start and end time guards for experiments work well! And serve as great reminders as to what they are set as lol...
Realized today that the endTime for uiexp.register_fields was 2018-10-14 which was causing a page level 500 error due to the expVersion not being assigned.
Added this guard which will ensure I don't use it if it's absent...could have just checked for undefined but wanted to make sure the variant values were covered too.
> add gaurd for experiment version and assignment

- src/components/Checkout/KivaCardRedemption.vue
Small css tweek for the kiva card remove x to sit more nicely on the /checkout page.
> Small fix for the height placement of the Kiva cards remove x

- src/components/Checkout/KivaCardRedemption.vue
The need help text in the Kiva Card section was not centered vertically correctly. This fixes the text and puts vertically aligns it.
> Need help text wasn't centered correctly.

- src/components/Checkout/PayPalExpress.vue
- src/plugins/checkout-utils-mixin.js
Turns out Raven/Sentry doesn't parse objects sent to this call. Have to pass them as a string so we don't just get [object: object] :(
> Checkout error reporting

- src/components/Forms/RegisterForm.vue
Here is the front end build out for CASH-42, I built this to mimic current behavior and appearance of the analogous field on /register. If user doesn't have an inviter/referrer, this disabled input field is not shown. Example invite link: https://www.kiva.org/invitedby/joshuastarkey
The kiva/main side of the experiment setup changes are coming soon in another PR.
Everything around the showing, hiding and passing of data through to this field is complete from what I can tell. 
FYI: @ksekhri
> Cash 42 front end

- .travis.yml
This will make it so that pull requests are only built in node 8 (once). This also makes it so that only the master branch is built in both node 8 and the latest node version. It does this using the [Travis Build Matrix](https://docs.travis-ci.com/user/build-matrix/) to limit the branches that are built when pushed to to only master and any release branches, and only building in the latest node version when the branch is master.
> Travis build matrix

- src/pages/StyleGuide.vue
I noticed the buttons were sitting right on the bottom border of the .elem-desc and that was the only place it was occurring, so I added a little room for them. All the css for styleguide was present within the StyleGuide.vue file instead of the individual buttons, so I put it there, lmk if you want me to move this out and into StyleguideButtons.vue.
> button spacing

- src/components/LoansByCategory/RecentlyViewedLoans.vue
Moved check for recently loans in local storage up a level so we can report if those in control "could" have been shown their recently viewed loans.
> Gather any availabled loan ids from local storage for reporting

- src/components/LoanCards/Buttons/ActionButton.vue
- src/components/LoanCards/Buttons/LendIncrementButton.vue
- src/components/LoanCards/GridLoanCard.vue
- src/components/LoanCards/GridMicroLoanCard.vue
- src/components/LoansByCategory/CategoryRow.vue
- src/components/LoansByCategory/FeaturedLoans.vue
- src/components/LoansByCategory/RecentlyViewedLoans.vue
- src/graphql/query/lendByCategory/lendByCategory.graphql
- src/graphql/query/loanChannelPage.graphql
- src/pages/Lend/LendByCategoryPage.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
Converted the Action + Lend Increment button to rely on a passed in experiment version rather than having to call out to the apollo cache. /lend-vue ssr works again. Added a new variant to the experiment.
> Cash 557 lend increment 25

- src/pages/Lend/LendByCategoryPage.vue
* SASS was `scoped` previously, so background never was gray
> CASH-550: Fix styling

- src/components/Checkout/BraintreeCheckout.vue
- src/components/Checkout/PaymentWrapper.vue
Adam made the following requests: 
1) "Zip code" is supposed to be "Postal code"
2) Doesn't seem like zip code is verifying - I put in a jumble of 10 numbers and it didn't turn red.
3) Paypal option should be in the same width box as credit card so that the toggles stay in the same place between selections
This fixes #1 & #3 
#2 seems to be an issue with how braintree is doing their validation for the postal code field.
> zipcode -> postal code, payment holder same width for pp and bt

- src/components/Checkout/PaymentWrapper.vue
This change swaps the pay with paypal/ pay with card options in the payment toggle component.
> Switching pay with card/ pay with paypal order

- src/pages/Checkout/CheckoutPage.vue
I noticed that the all the loan card elements were centered in this new component, found the line that was the issues, deleted it.
> cash-232 loan card text no longer centered

- build/style-loaders.js
I had been running into this error for a while that was preventing the linter-eslint in Atom from actually linting anything, but I could never figure out what was causing it because linting would always work from the command line. Finally happened to narrow it down to dart-sass trying to access document.scripts if document is defined (something that dart2js inserts automatically apparently). Atom is based on chromium, so it happens to have a document defined, but it does not define document.scripts. Dart tries to iterate that as an array, and so tries to access document.scripts.length, which end up throwing a 'Cannot read length of undefined' error.
> Only load dart-sass if running in node

- src/pages/Lend/Filter/LendFilterMenu.vue
- src/pages/Lend/Filter/LendFilterPage.vue
This PR fixes an issue that would cause filters set using `ais-refinement-list` to be lost
The issue seems to occur due to:
1. We cannot derive classes based on props that are updated by parent components (hence `.sync` - using an uglier syncing-to-parent method and deriving class in child using `data` works too)
2. We cannot update classes in parent components of a filter
> 2019-04-14: Workaround Algolia issue

- src/pages/Lend/Filter/FilterSectionAttributes.vue
- src/pages/Lend/Filter/FilterSectionLocation.vue
- src/pages/Lend/Filter/FilterSectionSectors.vue
* Especially important for alphabetically sorted filters that we are pruning in `transformItems`
> Remove limits from filters

- src/assets/scss/global/page-layout.scss
- src/pages/Lend/AlgoliaPagination.vue
- src/plugins/smooth-scroll-mixin.js
This approach should work in more browsers than CSS based `smooth-scroll` and it lets us set the animation time (this timing is much more pleasant in my opinion). If we like it we can easily add an `xPosition` scrolling option in the future as well.
> CASH-802: Add JS smooth scrolling

- src/components/LoanCards/AlgoliaLoanCardAdapter.vue
- src/components/LoanCards/ListLoanCard.vue
- src/pages/Lend/Filter/LendFilterMenu.vue
- src/pages/Lend/Filter/LendFilterPage.vue
- src/pages/Lend/LendByCategoryPage.vue
- src/pages/Lend/LendHeader.vue
* Note: This doesn't affect how `/lend-by-category` looks in my testing, only affects `/lend/filter`
> CASH-804: Cleanup margins on lend/filter

- src/pages/Lend/Filter/LendFilterPage.vue
Width of `AisInstantSearch` container wasn't 100% when no results were present
> Fix styling when no results

- src/components/LoanCards/ListLoanCard.vue
* Currently US Direct loans have an empty "Field Partner" title under the image. This PR hides the entire Field Partner section if it's empty.
> Hide field partner in ListLoanCard for US Direct loans

- package.json
starts "dev mode" using the --inspect flag. has nothing to do with the 'dev' environment.
> new script command to start dev in inspect mode

- src/components/WwwFrame/TheHeader.vue
- src/components/WwwFrame/WwwPage.vue
- src/pages/Lend/AlgoliaSearchBox.vue
- src/pages/Lend/Filter/LendFilterPage.vue
- src/util/experimentPreFetch.js
This looks really good when running concurrently with the pinned filter experiment
```
uiexp.algolia_search
string
{"name": "AlgoliaSearch","enabled": true,"startTime": "2018-08-29T00:00","endTime": "2020-02-16T15:00","control": {"key": "variant-a","name": "Control (variant-a)"},"variants": {"variant-b": {"name": "Algolia Search Enabled"}},"distribution": {"variant-a": 0,"variant-b": 1}}
CASH-682: Algolia Search
```
> CASH-682: Add algolia search to lend/filter

- src/api/apollo.js
I think the stale basketId issues we've been seeing might be resolved by using this option to use a simpler cache during the server render, see https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L119
> Use simpler graphql cache for server renders

- src/api/StateLink.js
- src/api/localResolvers/activeLoan.js
- src/api/localSchema.graphql
- src/components/Kv/KvLightbox.vue
- src/components/LoanCards/BorrowerInfo/BorrowerInfoHeaderExpandable.vue
- src/components/LoanCards/Buttons/ActionButton.vue
- src/components/LoanCards/ExpandableLoanCard/ExpandableLoanCard.vue
- src/components/LoanCards/ExpandableLoanCard/ExpandableLoanCardCollapsed.vue
- src/components/LoanCards/ExpandableLoanCard/ExpandableLoanCardExpanded.vue
- src/components/LoanCards/ExpandableLoanCard/expandableLoanCardMixin.js
- src/components/LoanCards/FundraisingStatus.vue
- src/components/LoanCards/LoanCardController.vue
- src/components/LoanCards/LoanCardImage.vue
- src/components/LoansByCategory/CategoryRow.vue
- src/graphql/mutation/updateActiveLoan.graphql
- src/graphql/query/activeLoanClient.graphql
- src/graphql/query/lendByCategory/lendByCategory.graphql
- src/pages/Lend/Filter/FilterComponents/LendFilterMenu.vue
- src/pages/Lend/LendByCategoryPage.vue
- src/plugins/active-loan-mixin.js
- src/plugins/lock-scroll.js
- src/util/experimentPreFetch.js
This PR contains code for the basic desktop and mobile functionality of CASH-676. There are design/UX tweaks that will be incoming.
```
uiexp.expandable_loan_cards
string
{"name": "ExpandableLoanCards","enabled": true,"startTime": "2018-08-29T00:00","endTime": "2020-02-16T15:00","control": {"key": "variant-a","name": "Control (variant-a)"},"variants": {"variant-b": {"name": "Expandable Loan Cards"}},"distribution": {"variant-a": 0.5,"variant-b": 0.5}}
CASH-676: Expandable Loan Cards
```
> CASH-676: Expandable Loan Card

- src/components/LoanCards/ExpandableLoanCard/ExpandableLoanCardExpanded.vue
* Since tapping loans on small breakpoint takes over the screen we can allow tapping partially offscreen loans
> CASH-676: Allow tapping partially offscreen loans on phone but not tablet

- src/components/LoanCards/ExpandableLoanCard/ExpandableLoanCardExpanded.vue
- src/plugins/active-loan-mixin.js
* We were initially depending on a user to tap on another loan card to collapse the expanded loan card. This PR adds an invisible layer that's only visible when (1) A loan is expanded (2) Screen size is >480px and (3) CSS hover doesn't exist (tablet)
> CASH-922: Add layer to dismiss expanded card for tablet

- server/auth-router.js
- server/util/getSessionCookies.js
- src/components/WwwFrame/EndOfYearAppealBanner/AppealBanner.vue
Login sync was forcing users to go through the post-auth flow twice, causing the double team invite. Also, certain cookies being missing caused a new session to be generated, which would cause the invite handling to be skipped.
> Fix post-auth team redirect

- src/components/WwwFrame/TheHeader.vue
* When Algolia search is enabled, currently the header shows 2 borders to the right of Lend. Hiding the `top-nav-search-area` when the search icon is hidden fixes this.
> Cleanup header when Algolia search is enabled

- server/util/clearCachedVueModule.js
- server/vue-middleware.js
This removes the cached Vue module before the server-bundle is processed, ensuring that the next call to import Vue will return a fresh instance with no plugins installed yet (which will resolve the InvariantError caused by the apollo-plugin being installed multiple times)
> Ensure global Vue instance is clean when imported in the app

- src/graphql/query/categoryAdminControl.graphql
- src/graphql/query/loanChannelPage.graphql
@foochris The updates made to loan channel queries changed the way the popular: false mechanism works in an unexpected way. It seems that specifying 'false' now excludes the loan channels that are marked as popular. Removing the filter altogether got this working again.
Current state is popular categories are broken on dev, see -> /lend-by-category/education
> Update loan channel queries to not specify false filters.

- src/components/LoanCards/HoverLoanCard/HoverLoanCard.vue
- src/components/LoanCards/HoverLoanCard/HoverLoanCardLarge.vue
- src/components/LoanCards/HoverLoanCard/HoverLoanCardSmall.vue
- src/components/LoanCards/LoanCardController.vue
- src/components/LoansByCategory/CategoryRowHover.vue
- src/pages/Lend/LendByCategoryPage.vue
Additions:
* Add (and do tons of tweaks to) animations for cards to move out of the way
* Only pass loan card index to CategoryRowHover to ease math of card movement
* Simplify transitions to use more variables to allow further fine tweaking
Fixes:
* Disable pointer events during transition from small to large card
* Move mouseleave events to row level to make all animations much more smooth
* Fix visual bug causing a jumping flag on Chrome
Expandable loan panel support:
* Adjust bottom of CategoryRowHover for better loan panel placement
* Add computed detailedLoanCacheId to CategoryRowHover for loan panel use
Note: Another PR is required to handle loans at ends of the row
> CASH-960: Add row animations for cards to move out of the way

- src/components/LoanCards/ExpandableLoanCard/ExpandableLoanCard.vue
- src/components/LoanCards/ExpandableLoanCard/ExpandableLoanCardExpanded.vue
- src/components/LoanCards/HoverLoanCard/HoverLoanCard.vue
- src/components/LoanCards/HoverLoanCard/HoverLoanCardLarge.vue
- src/components/LoanCards/HoverLoanCard/HoverLoanCardSmall.vue
- src/components/LoansByCategory/CategoryRowHover.vue
- src/plugins/category-row-arrows-visible-mixin.js
Additions:
* Add code for rearranging cards when expanding first card in row and template for rearranging when expanding last card in a row
Fixes:
* Increases code reuse
* Cleanup comments and transitions
* Fixes horizontal scrollbar appearing intermittently in row
Known Issues/Limitations:
* Currently moving from the first card in the row to the second card causes one card to be skipped, this will be fixed in the subsequent PR
> CASH-960: Add support for end cards

- src/components/LoanCards/BorrowerInfo/BorrowerInfoBody.vue
- src/components/LoanCards/LoanCardImage.vue
* For the HoverLoanCards, clicking the image as well as the read more links expand the details panel.
* We need to ensure the link as well as the tracking is disabled in a way that maintains correct behavior for the rest of the loan cards.
> CASH-1074: Allow custom click behavior for loan card image and read more link

- src/assets/scss/components/loan-cards/hover-loan-card.scss
The prior animation resulted in a distracting, flashing image
Flashing is due to the change in ratio of image:totalHeight between the 2 card sizes. When the transition starts, the small card starts to disappear and the large card (with a smaller image:totalHeight ratio) appears, resulting in a flash of white where the large card image ends higher than the small card image:
```
Small Card          Large Card
|        |          |        |
|   i1   |          |   i2   |
|        |          |--------| // Flashing Occurs due to
|--------|          |        | // this difference
|        |          |        |
|   c1   |          |   c2   |
|        |t1        |        |t2
```
We can scale the large image (i2) up when the large card is scaled down to remove the flash. Reversing this scale on …
> CASH-1069: Update hover transitions to accomodate new card dimensions and layout

- src/components/LoanCards/HoverLoanCard/HoverLoanCard.vue
* Loan cards will only expand on screens where 3 or more cards are visible
* Clicking/tapping on loan cards on screens where fewer than 3 cards are visible will now directly expand the details panel
> CASH-1054: Implement mobile behavior of hover loan cards

- src/components/LoanCards/HoverLoanCard/InfoPanels/InfoPanel.vue
This prevents the borrower story from going outside the expanded card via setting an overflow on the container.
> fixing Borrower Story overflowing expanded section

- src/components/LoanCards/BorrowerInfo/BorrowerInfoHeader.vue
- src/components/LoanCards/BorrowerInfo/BorrowerInfoName.vue
- src/components/LoanCards/HoverLoanCard/DetailedLoanCard.vue
- src/components/LoanCards/HoverLoanCard/HoverLoanCardLarge.vue
- src/components/LoansByCategory/FeaturedHeroLoan.vue
* Componentize BorrowerInfoName and share between 4 components
* Style Name/Location/Sector
> CASH-1095: Expandable Panel Name/Location/Sector

- server/auth-router.js
- server/util/syncCookie.js
Without this you can end up in an infinite redirect loop
> WEBBUG-2709 clear login sync cookie on true failed login

- src/components/LoanCards/HoverLoanCard/DetailedLoanCard.vue
- src/components/LoanCards/HoverLoanCard/InfoPanels/LoanDetailsPanel.vue
- src/components/LoanCards/HoverLoanCard/InfoPanels/PartnerInfoPanel.vue
- src/components/LoanCards/HoverLoanCard/InfoPanels/TrusteeInfoPanel.vue
- src/components/LoanCards/LoanCardController.vue
- src/components/LoansByCategory/CategoryRowHover.vue
* We need many of the methods and computed values from LCC to complete the `DetailedLoanCard`
A known UI bug exists in this change: When the DetailedLoanCard is open and the user hovers over another loan, the card closes and reopens. This is a bug we will have to chase down.
> CASH-1096: Wrap DetailedLoanCard in LoanCardController

- src/components/LoanCards/HoverLoanCard/HoverLoanCard.vue
- src/components/LoansByCategory/CategoryRowHover.vue
From a user’s standpoint, cards now only expand when you enter the card body, not the card margin. This is implemented as follows:
* Hovering in margins will now only trigger card expansion when another card is already expanded
* To expand a card in a row where no other cards are expanded yet, you must actually enter the card body
> CASH-1067: Allow loan card rows to overlap page content

- src/components/LoanCards/HoverLoanCard/HoverLoanCard.vue
- src/components/LoanCards/HoverLoanCard/HoverLoanCardSmall.vue
- src/components/LoanCards/LoanCardController.vue
- src/components/LoansByCategory/CategoryRowHover.vue
Now when users click a HoverLoanCard to expand the DetailedLoanCard, they will no longer page through loans on mouseover until they first interact with either the DetailedLoanCard or explicitly click on a neighboring card.
Note: This new behavior was QA'd by Adam. Tested on tablet/mobile.
Fixes:
* Tapping on image in small hover card on mobile no longer triggers page redirection
> CASH-1101: Disable hover temporarily after detailed panel is triggered

- src/components/LoanCards/HoverLoanCard/HoverLoanCard.vue
- src/components/LoansByCategory/CategoryRowHover.vue
* Update size of “View All” card
* Add animation logic to “View All” card, allowing it to move to the right according to the state of the CategoryRowHover
> CASH-1104: Fix "view all" loan cards overlap

- src/components/LoansByCategory/CategoryRowHover.vue
* Sync margin animation of DetailedLoanCard to be same as HoverLoanCard expansion
* On mobile: scroll to DetailedLoanCard when switching loans or initially expanding DetailedLoanCard
* On desktop: scroll to CategoryLoanRowHover only when initially expanding DetailedLoanCard
> CASH-1142, CASH-1087: Sync margins when expanding DetailedLoanCard and add scroll when expanding

- src/components/LoanCards/HoverLoanCard/HoverLoanCard.vue
* Hovering over a loan card when the detailed panel was open would trigger a card switch on small screens, this fix ensures hover behavior for expanding HoverCards and expanding DetailedLoanCard is consistent
> Small fix for small screens

- src/components/LoanCards/HoverLoanCard/DetailedLoanCard.vue
This is beautiful:
* We start the diagonal `linear-gradient` at 50% so that the bottom and the left sides of the container don’t contain any color at all.
* The container width/height is 2x the distance from the bottom left corner of the “x” to the top right corner of the image so that 100% of the “x” will have some gradient background underneath it.
* We use a pointer-events: none on the container and a pointer-events: initial on the close button to ensure the background doesn’t interfere with clicking the image below.
> CASH-1144: Diagonal gradient background for close button

- src/graphql/mutation/braintreeDepositAndCheckout.graphql
I don't really know if this breaks anything else! I didn't see any other references to this mutation or to `braintreeDepositAndCheckout.graphql` outside the Braintree checkout component.
> CASH-1243 Update Braintree checkout mutation definition to include deviceData for Kount

- src/components/Checkout/PaymentWrapper.vue
- src/graphql/query/checkout/checkoutSettings.graphql
- src/graphql/query/checkout/initializeCheckout.graphql
- src/pages/Checkout/CheckoutPage.vue
Tested this out on my VM and it was still working with the new exp name. I also moved the new exp setting into the settingsManager on dev, qa & production. I'll deleted the old exp setting after verification of this work in dev.
> cash-1326 changing btVSpp exp name

- src/assets/icons/notice.svg
- src/components/Checkout/BraintreeCheckout.vue
- src/components/Checkout/PayPalExpress.vue
- src/components/Checkout/PaymentWrapper.vue
- src/components/Kv/KvIcon.vue
- src/graphql/mutation/deleteBraintreeCard.graphql
- src/graphql/query/myStoredCards.graphql
As the VaultManager delete method is not currently functional, this approach compares payment method information from our backend api with corresponding information from the VaultManager.fetchPaymentMethods function. We can match the card targed for deletion and then use our backend api to delete the card.
> Add initial delete saved payment method functionality

- config/dev.js
- config/index.js
- config/k8sdev.js
- config/qa.js
- config/stage.js
- src/App.vue
We've apparently been able to use HTTP/2 this whole time, we just had to change which url we were using https://docs.fastly.com/en/guides/setting-up-free-tls#support-for-http2-ipv6-and-tls-12
> Use Fastly HTTP/2 servers

- src/util/settingsUtils.js
Extra check to try and clear "ApolloMixin promotionalBanner TypeError: Cannot read property 'replace' of undefined" in Example.spec.js
> Return null if val and cleanedVal are empty.

- src/pages/Autolending/AutolendingPage.vue
* Basket bar overlaps save settings button for mobile. Hid basket bar so that save settings button can be clicked.
* CASH-1502
> Hide basket bar for autolending settings page

- package.json
- src/graphql/fragments/promoSetting.graphql
- src/plugins/index.js
- test/unit/specs/components/RouteListing.spec.js
- test/unit/specs/components/WwwFrame/TheHeader.spec.js
Cleaned up the unit tests, some minor misspellings. 
The e2e tests still produce this type of error: 
ApolloMixin promotionalBanner { Invariant Violation: Invariant Violation: 8 (see https://github.com/apollographql/invariant-packages)
Which I am giving up on because I didn't really get anywhere trying to figure out what it was...
> Cleaned up unit tests to remove warnings and errors

- build/webpack.client.base.conf.js
* Png assets referenced in the css of Vue single file components are not being referenced correctly when
read from cache. This excludes them from the cache. Issue can be seen with background image on KvDropdownRounded.vue
> PNG Dev Cache Fix

- src/api/localResolvers/autolending.js
This fixes an issue where you aren't redirected to login when navigating to /settings/autolending on the client-side
> Avoid cache when initializing auto-lending settings

- src/api/fixtures/AutolendProfile.js
- src/api/fixtures/LoanSearchFilters.js
- src/api/fixtures/MinMaxRange.js
- src/api/localResolvers/autolending.js
- src/pages/Autolending/AutolendingPage.vue
- src/pages/Autolending/DefaultRateDropdown.vue
- src/pages/Autolending/PartnerDelRateDropdown.vue
Fixes problems with range filters (CASH-1538, CASH-1539) and also addresses unticketed issue of page having trouble loading when autolend profile and/or loan search criteria are not defined.
> CASH-1538 CASH-1539 Fixes for autolending settings data layer

- build/webpack.client.base.conf.js
* Fixes issue in dev where when reading from cache, jpg images referenced in CSS (usually backgrounds) are missing
VUE-178
> Modified HardSource cache to exclude jpgs as well

- .storybook/stories/KvFormKitchenSink.stories.js
- .storybook/stories/KvRadio.stories.js
- src/assets/scss/_settings.scss
- src/components/Kv/KvRadio.vue
- src/pages/Autolending/GenderRadios.vue
- src/pages/Autolending/GroupRadios.vue
- src/pages/Autolending/LightboxFilter.vue
- src/pages/Autolending/LoanIncrementRadios.vue
- Use name property instead of name-set and label-set. 
- Add focus and disabled styles. 
- Wrap component in label el instead of using ids.
- Allow font-size to scale label without reaching inside the component styles. i.e., `<kv-radio style="font-size: 100px;">`Will scale both the circle and the label up
- Start the kitchen sink file.
VUE-192
> KvRadio tuneup

- .storybook/stories/KvCheckbox.stories.js
- .storybook/stories/KvRadio.stories.js
- src/components/Checkout/BraintreeCheckout.vue
- src/components/Checkout/DonateRepaymentsToggle.vue
- src/components/Kv/KvCheckbox.vue
- src/components/Kv/KvRadio.vue
- src/pages/Lend/admin/FeaturedAdminControls.vue
VUE-201 
DonateRepaymentsToggle.vue showed a use case for having the checkbox on the right and the label also wrapped to multiple lines. Added a new prop to kv-checkbox and tweaked styles to accommodate multi-line labels.
No rush to get this merged.
> Replace <input type="checkbox"> with <kv-checkbox>

- src/components/Styleguide/StyleguideIcons.vue
Removing these icons from styleguide because we're just using them inline for a promotion.
> cleaning up now inline svgs

- src/App.vue
- src/components/WwwFrame/IntercomMessenger.vue
- src/main.js
- src/pages/Error.vue
- src/pages/LoginAndRegister/RegisterSocial.vue
- src/plugins/algolia-init-mixin.js
As I'm working on the social share buttons, I've found a need to access the application config to be able to get our facebook application id. Accessing it through a prop didn't seem worth the effort, as I would have to pass that down through WwwPage and ThanksPage. I was considering using provide/inject to make the config available, but that seems like overkill for a static object that we could access through an instance property instead: https://vuejs.org/v2/cookbook/adding-instance-properties.html
For this pr I converted everything over to using that so that there wouldn't be differing examples of how to access the app config.
> Provide config through a single $appConfig instance property

- package-lock.json
- package.json
* Updated Husky, Cross-Env, File-Loader, and Url-Loader - all of which required node > 8 but no other breaking changes
> Updated Dependencies - For Node 12

- src/pages/Autolending/LendTimingDropdown.vue
Had a last minute minor request from Brandon to limit the width of this text on the /settings/autolend page.
> cash-1688 containing length of autolend expl. text

- package.json
- src/components/Kv/KvTipMessage.vue
- src/pages/Autolending/AutolendingOptOutPage.vue
- src/pages/Autolending/LendTimingDropdown.vue
- src/pages/Autolending/MainToggle.vue
- src/pages/Autolending/SaveButton.vue
- test/e2e/fixtures/wwwPageMock.js
- test/e2e/specs/AutolendingOptOutPage.spec.js
- test/e2e/specs/AutolendingPage.spec.js
- test/e2e/support/commands.js
This changes the serialization method for the mocks so that simple primitive values and variable values can be used, which makes mocking simple responses much easier. This also includes an example test involving a mutation, where the mock returns a different value based on the request arguments.
> Improve cypress mocking

- src/graphql/query/lendByCategory/lendByCategory.graphql
- src/pages/Lend/LendByCategoryPage.vue
- src/util/experimentPreFetch.js
Jira ticket:
https://kiva.atlassian.net/browse/DSCI-376
provides setup frame for recommendation_channel experiment, validates a recommendation channel can be segmented to different audiences.  No changes for frontend required just checking if values or consoles logs picked up by different audiences.
added uiexp.recommendation_channel setting value to admin.kiva.org in `settings manager`
added initializeRecommendedLoansRowExp() to initialize a category row
added recommendation_channel to lendByCategory.graphql 
Also sets up for:
https://kiva.atlassian.net/browse/CASH-1807
> DSCI-376: Test audience split for recommended loans row experiment

- src/pages/Thanks/ThanksPage.vue
GraphQL Federation expects strict typing, and checkoutId is defined as an Int, so we need to ensure it is provided as an integer value instead of a String.
> ENG-2895: checkoutId strict typing

- src/pages/Thanks/ThanksPage.vue
This prevents 500 errors when the page is loaded when the user is not logged in (i.e. a couple days after they checkout and they open the browser again)
> CASH-1844 Require login for thanks page

- config/dev.js
AWS-DEV: try multi-node Memcache setup
AWS-DEV: use Memcache node FQDN/ not Route53 CNAME
Related backend PR: https://github.com/kiva/kiva/pull/8408
> AWS-DEV: try multi-node Memcache setup

- config/dev.js
We stil need aliases. The memcahce node instances are gated, so cannot access
them
> DEV AWS: multi node setup

- test/e2e/specs/AutolendingPage.spec.js
Quick fix for e2e tests failing. This will have to be adjusted in the future as we change some of the conditional wording.
> Fixed e2e autolending wording test

- src/components/LoansByCategory/FeaturedHeroLoanWrapper.vue
We'd seen some errors where the sector id went through as a string.
> Ensure we pass an int to the sector variable when present

- src/graphql/query/lendByCategory/lendByCategory.graphql
- src/pages/Lend/LendByCategoryPage.vue
initial commit for setting up category rows hillclimb experiment
https://kiva.atlassian.net/browse/DSCI-403
sets up web traffic segmentation on LendByCategory page
associated Admin Settings Manager variables
uiexp.category_row_hillclimb
{"name": "categoryRowHillclimb", "enabled": false, "startTime": "2020-03-01T00:00", "endTime": "2020-04-18T16:00", "control": {"key": "control", "name": "Control"}, "variants": {"variant-a": {"name": "Category Row MAB Sort enabled"} }, "distribution": {"control": 0.5,"variant-a": 0.5} }
> DSCI-403 initialize experiment distribution for category row 

- deploy/dev/values.yaml
As per fairwinds recommendation, the only cert manager annotation necessary is `cert-manager.io/cluster-issuer: letsencrypt-prod`
> Cert manager fixes

- src/pages/MonthlyGood/EmailPreview.vue
Fixes max-width, since img is no longer the first child of kv-responsive-img (picture is now).
> Fix image width on Monthly Good page

- .storybook/stories/KvResponsiveImage.stories.js
By using placeholder images which show the width and height of the image currently displayed
> Make kv-responsive-image storybook examples clearer

- src/components/WwwFrame/TheFooter.vue
changing router-link to anchor so this works correctly and directs outside of the kiva.org domain
> webbug-2811 router-link to anchor

- src/api/localResolvers/autolending.js
Possibly fixes the issue with the autolend settings page not redirecting non logged in users.
The GQL Federation error response does not include `errors[0].code`, but instead includes `errors[0].extensions.code`.
On the VM we have both, hence why it was working locally. This local resolver is a unique case and we arent doing this anywhere else. 
Discovered testing the refactor of components in CASH-1205, I dont think its actually a cause of that change, but just the move to federation. 
thanks @emuvente for the help
> Fixes redirect on dev environment for autolend settings page

- test/unit/specs/components/WwwFrame/TheHeader.spec.js
Travis and 'npm run test' are throwing a console error on the unit test for the header component due to the changes made to make the search box keyboard accessible. 
See https://travis-ci.org/github/kiva/ui/builds/668990621#L455 for the console error. 
This fixes that
> Fixed TheHeader unit test

- src/App.vue
- src/components/WwwFrame/TheAppInstallBanner.vue
- src/manifest.webmanifest
Also continue loading webmanifest on all pages, but move app banner logic into TheAppInstallBanner.vue.
GROW58, GROW-59
> Only show app banners on certain routes

- config/k8sdev.js
This change matches up with a change I made to the fastly configuration where I removed the invalid `ui-dev.dk1.kiva.org` domain (see [valid domain name guide](https://docs.fastly.com/en/guides/adding-cname-records#choosing-the-right-fastly-hostname-for-your-cname-record)) and replaced it with the `ui-dev-dk1-kiva-org.global.ssl.fastly.net` domain. Adding this domain also automatically makes the `https://ui-dev-dk1-kiva-org.freetls.fastly.net` domain, which has HTTP/2 support and TLS 1.2 (see [tls support guide](https://docs.fastly.com/en/guides/setting-up-free-tls#support-for-http2-ipv6-and-tls-12))
> Fix fastly url for k8s dev configuration

- src/pages/Homepage/HeroSlideshow.vue
Prevent a padded green box if there's nothing in contentful for the headline or subhead slot.
If no CTA text is provided, make the whole image a link.
This will allow marketing to upload images with CTAs embedded in the image (for COV campaign)
> Homepage slideshow tweaks

- src/components/Kv/KvCheckoutSteps.vue
- src/pages/Checkout/CheckoutPage.vue
- src/pages/MonthlyGood/MonthlyGoodSetupPage.vue
- src/pages/MonthlyGood/MonthlyGoodSetupPageControl.vue
- src/pages/MonthlyGood/MonthlyGoodSetupPageVariant.vue
- src/plugins/loan-group-categories.js
Sorry for the giant PR, it might be easier to view the files whole instead of as diffs. 
Overview:
- Renames MonthlyGoodSetupPage.vue to MonthlyGoodSetupPage**Control**.vue 
- Builds the new design from GROW-82 to MonthlyGoodSetupPage**Variant**.vue
- MonthlyGoodSetupPage.vue now checks the uiexperiment and determines which component (control or variant) to show.
- Some tweaks to KvCheckoutSteps to make it work well in this scenario and the checkout.
- To test:
- add a setting named `uiexp.mg_setup` to your vm admin settings manager with this data:
`{ "name": "MonthlyGoodSetup", "enabled": true, "startTime": "2020-05-01T00:00", "endTime": "2021-05-01T00:00", "control": { "key": "control", "name": "Control" }, "distribution": { "control": 0.5, "shown": 0.5 } }`
- To see the new design go …
> GROW-82 New MG setup design experiment

- build/webpack.client.base.conf.js
- server/vue-middleware.js
This addresses the issue that was causing the header and footer styles to not be included in the initial server render. The issue was caused by some components (like `TheHeader`) being duplicated into multiple chunks instead of occupying a single chunk. Once duplicated, the vue server renderer skips on including the js or css for that component in the html (https://github.com/vuejs/vue/blob/dev/src/server/webpack-plugin/client.js#L39).
See https://webpack.js.org/plugins/split-chunks-plugin/ for more details about the `maxAsyncRequests` option.
> Increase max async requests for chunk splitting

- src/api/SnowplowSessionLink.js
- src/api/apollo.js
Depends on https://github.com/kiva/kiva/pull/8810 for direct calls to monolith graphql (generally only the VM at this point)
> Pass snowplow session id as header in api requests.

- src/pages/MonthlyGood/LandingFormExperiment.vue
When choosing monthly good from a /lend-by-category/* page, if you're in the new landing form  experiment the dropdown is not pre-selected correctly. This is a fix for that and some other minor touchups.
> GROW-108 monthly good select element fix

- test/e2e/fixtures/wwwPageMock.js
- test/e2e/specs/AutolendingPage.spec.js
Removes these warnings during e2e testing:
`Warning: No error handler for error code 'INTERNAL_SERVER_ERROR': No mock defined for type "Money"`
`Warning: No error handler for error code 'INTERNAL_SERVER_ERROR': No mock defined for type "Url"`
> Fixed warning about missing mocks for lunar server

- package-lock.json
- package.json
- src/components/Kv/KvLightbox.vue
Adds accessibility improvements following the recommendations for a dialog
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role
Remaining items from the ARIA dialog recommendations
> VUE-219 KvLightbox a11y improvements

- .storybook/stories/KvLightbox.stories.js
- src/components/Checkout/DonationItem.vue
- src/components/Checkout/KivaCardRedemption.vue
- src/components/Checkout/LoanReservation.vue
- src/components/Kv/KvLightbox.vue
- src/components/Lightboxes/AddToBasketInterstitial.vue
- src/components/Lightboxes/ContentfulLightbox.vue
- src/pages/Autolending/AutolendingSettingsPage.vue
- src/pages/Autolending/AutolendingStatus.vue
- src/pages/Autolending/AutolendingWhen.vue
- src/pages/Autolending/AutolendingWho.vue
- src/pages/Autolending/SaveButton.vue
- src/pages/Checkout/CheckoutPage.vue
- src/pages/ComponentDemo/ComponentDemo.vue
- src/pages/LandingPages/MGCovid19/MGCovidFAQ.vue
- src/pages/MonthlyGood/MonthlyGoodSetupPageVariant.vue
- Use prop to set title for consistency. 
- Add aria-labelledby and fix focus-lock for a11y. 
- Remove fixed width from lightboxes to allow narrower content without overrides. 
- Add a css custom property for overriding the title color.
- Remove unused "showCloseButton" property
- Scope lightbox styles
> VUE-318 lightbox improvements

- src/pages/Autolending/AutolendingWho.vue
- src/pages/Autolending/LoanIncrementDropdown.vue
https://kiva.atlassian.net/browse/AUTO-177
https://kiva.atlassian.net/browse/AUTO-154
This switches the loan increment selector to a dropdown; having 5+ radio buttons looked cluttered.
Tested with https://github.com/kiva/kiva/pull/8878: I changed the limit on my dev VM to 25, then 100, then any, refreshing each time and verifying the previous selection appeared correctly.
> Increase options for autolending loan limits

- src/components/WwwFrame/PromotionalBanner/GlobalPromotionalBannerContentful.vue
- src/pages/Autolending/LendTimingMessaging.vue
* Removes some code associated with the autolending opt in before may 21.
* e2e tests had been previously removed already in hot fix.
AUTO-178
> AUTO-178 Autolending Opt In Cleanup

- src/components/WwwFrame/PromotionalBanner/PromoBannerSmall.vue
- src/components/WwwFrame/PromotionalBanner/PromotionalBanner.vue
* Moved CSS for promo banner small border so that border is not visible if banner is not visible. (It creates a problem for homepage takeovers with white headers)
VUE-336
> VUE-336 Promo Banner Border Bug

- src/components/WwwFrame/TheHeader.vue
- src/pages/Checkout/CheckoutPage.vue
When preFetchAll is used outside of apollo mixin (by component methods) we need to send the rejection to the router.
> Fixed issue with auth pop up login not redirecting on preFetch rejection

- src/pages/Autolending/AutolendingWhen.vue
Resolves https://kiva.atlassian.net/browse/AUTO-207
I couldn't tell why this component makes a direct mutation to update the `donationPercentage` (rather than go through the local resolver), but IIUC this change will pre-empt that code path, as the controls that modify `this.donation` are not rendered.
> Hide auto-lending donation controls and zero out donation if there is an auto-deposit donation

- src/pages/Autolending/AutolendingPage.vue
- src/pages/LandingPages/MGCovid19/MGCovidHero.vue
- src/pages/MonthlyGood/AlreadySubscribedNotice.vue
- src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
- src/pages/MonthlyGood/MonthlyGoodSetupPage.vue
- src/pages/PageTwo.vue
- src/pages/Subscriptions/SubscriptionsAutoDeposit.vue
- src/pages/Subscriptions/SubscriptionsMonthlyGood.vue
- src/pages/Subscriptions/SubscriptionsPage.vue
- test/e2e/specs/AutolendingPage.spec.js
* Changed /settings/subscriptions page title to be "settings"
* Changed /settings/autolending page title to be "settings"
* Removed specific 'from Paypal' copy from MG subscription status texts to allow for MG bt drop in subscriptions
* Changed links to /settings/credit to be /settings/subscriptions on MG already subscribed elements
* Removed GROW-82 MG Variant selection code page
> Monthly Good & Subscriptions & BT Drop In Misc Changes

- src/util/experimentPreFetch.js
* Added ability to chain multiple setuiab query params, for example:
https://dev-vm-01.kiva.org/lend-by-category/women?setuiab=add_to_basket_redirect.shown&setuiab=add_to_basket_v2.control
> Multiple setuiab query params

- src/util/authenticationGuard.js
* Changed doneUrl param in auth guard to use route.fullPath, which will keep the query params when redirecting. This was causing some issues, see SUBS-334
> SUBS-334 Auth Guard and Query Params

- src/graphql/query/lendMenuPrivateData.graphql
Fixes minor error due to validation in GraphQL API
`query: "query ($userId: Int) {↵  lend {↵    loans(limit: 0, filters: {lenderFavorite: $userId}) {↵      totalCount↵      __typename↵    }↵    __typename↵  }↵  my {↵    savedSearches(limit: 10) {↵      values {↵        id↵        name↵        url↵        __typename↵      }↵      __typename↵    }↵    __typename↵  }↵}"
`
`0: "GraphQLError: Limit must be positive."`
> Limit for loan query must be positive rather than 0.

- src/pages/MonthlyGood/MonthlyGoodSetupPageControl.vue
* Fixes typo in prop causing oneTime boolean not to be passed correctly to mutation
SUBS-9
> SUBS-9 Braintree MonthlyGood Setup One Time Fix

- src/pages/Homepage/Homepage.vue
Prevents loading in JS and SVGs that aren't being used depending on the experiment. Good results:
> Dynamically import homepage component

- .storybook/stories/KvCarousel.stories.js
- .storybook/stories/KvLoadingSpinner.stories.js
- src/components/Kv/KvCarousel.vue
- src/components/Kv/KvCarouselSlide.vue
Most of the work done to make KvCarousel able to handle what's needed for the homepage redesign as well as other carousels Kiva has done in the past (homepage hero images, KivanSlider on holiday promo).
Still have some styling todos around colors and the arrow btns but don't want to hold up Eddie. I also don't love the way the transitions are handled right with scoped slots, may work on that more tomorrow. Lotta position absolutes, wish I could use grid.
Right now none of the other implementations of KvCarousel are live so this shouldn't break anything.
@eddieferrer There's a storybook story "loanCardExample", with an idea around how to show the loans. The text above the slider isn't part of this component, but you should be able to build that using the change event on the carousel.
> GROW-159 KvCarousel

- src/components/Homepage/CategoryGrid.vue
* Fixed - [Vue warn]: Property or method "loanChannels" is not defined on the instance but referenced during render.
> CategoryGrid Vue Warn Fix

- src/pages/Homepage/LendByCategoryHomepage.vue
Found a small overlap issue on specific screen size. Added a z-index to the loans-not-donation__flourish and fixed it up. 
**Before fix:** 
**After fix:**
> lend by category homepage loan not donation flourish z-index update

- src/components/Homepage/LendByCategory/FeaturedLoansCarousel.vue
- src/components/LoanCards/LendHomepageLoanCard.vue
- src/pages/Homepage/LendByCategoryHomepage.vue
* Implemented features loans on the lend by category homepage
> GROW-130 Featured Loans

- src/pages/Homepage/LendByCategoryHomepage.vue
PR addressing these concerns: 
- this is causing an error. Should be:
:to="'/lend-by-category'" 
- The design calls for this text to be vertically centered in the section.
- I've added the [foundation class](https://get.foundation/sites/docs/flex-grid.html#vertical-alignment-of-child-columns-individually-) .align-self-middle, which once the carousel has a height, it should correctly vertically center the text as the design shows.
> get started redirect link fix and message centering using foundation align-self-middle class

- src/components/Homepage/LendByCategory/LoanCategoriesSection.vue
- src/components/LoanCards/LendHomepageLoanCard.vue
- src/pages/LandingPages/MGCovid19/MGCovidHero.vue
* Fixed CSS of category loan carousel so that loans with 2 line info align with loans with 3 line borrower info
* Prefetch categories and category infor for category loan carousel
* Unrelated fix that was throwing a vue error
GROW-131
> GROW-131 Prefetch Categories And Small CSS fix

- server/auth-router.js
I would like to get this out as a hotfix as well, so this should be fine to merge to master along with any homepage changes.
> AUTH-291 Restore automatic redirect to login for OIDC-conformant errors

- src/graphql/query/checkout/initializeCheckout.graphql
- src/pages/Checkout/CheckoutPage.vue
Will remove setting from env's after this gets pushed to production. We should NOT merge this in for the hotfix, while low risk, theres no need to get it.
> SUBS-313 Removes braintree checkout experiment code

- .storybook/mixins/apollo-story-mixin.js
- .storybook/mock-data/loan-channels-data-mock.js
- .storybook/mock-data/loan-data-mock.js
- .storybook/mock-data/receipt-data-mock.js
- .storybook/stories/CheckoutReceipt.stories.js
- .storybook/stories/LendByCategoryHomepage.stories.js
- .storybook/stories/LendHomepageLoanCard.stories.js
- .storybook/stories/SocialShare.stories.js
- .storybook/utils.js
Some functional improvements to mocking data. 
My thinking is that we can mock objects/arrays of data in the mock-data folder. Instead of mocking entire API responses.  We can then reuse these across different stories for different needs. 
For example, we can use these objects to mock apollo response. Like `.storybook/stories/LendByCategoryHomepage.stories.js`
Or we can use them to mock props, like in: `.storybook/stories/CheckoutReceipt.stories.js`
We can also then write any logic to process the data in the stories themselves or in utility functions such as the `arrayOfLoans` functions or the apollo mocks in `.storybook/stories/LendByCategoryHomepage.stories.js`
> Additional Storybook enhancements

- src/components/Forms/MonthlyGoodUpdateForm.vue
- src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue
- src/pages/Autolending/AutolendingWho.vue
- src/pages/Subscriptions/SubscriptionsMonthlyGood.vue
* Adds ability to modify MG payment method.
**Behavior**
For users who are not opted in to experiment:
Current behavior, minor styling updates on form
Users opted in:
- If user has a BT vaulted card, they will see current payment method and link to update payment method which will take them to the drop in screen to update. On clicking confirm a new MG subscription will be created with new payment method. 
- If user has legacy paypal agreement. They will not see current payment method details, but will see update payment method link. On clicking this link, and going through the drop in interface, they will cancel their paypal auto deposit and create a new one with braintree. 
~~If a user's card expires and they're MG becomes inactive, they will see the same interface, as if they were …
> SUBS-373 MG Update Payment Method

- src/pages/Checkout/CheckoutPage.vue
- src/util/experimentPreFetch.js
https://kiva.atlassian.net/browse/GROW-203
I've already added the `uiexp.checkout_login_cta` setting to Dev, QA, Stage, and Prod. In Dev and QA it is enabled and set to 100% `b`. In Stage it is enabled and set to 100% `a` to avoid messing with any automation tests. In Prod it is not enabled and is set to 50% `a` and 50% `b`, meaning that it will have to be enabled once the code is deployed and the experiment is ready to launch.
The changes to the login method require https://github.com/kiva/auth0/pull/185
@ryan-ludwig could you please take care of making any requested changes to these PRs and getting them merged?
> GROW-203 Experiment to change checkout steps and login button text

- src/pages/Subscriptions/SubscriptionsMonthlyGood.vue
Removed setting based toggle for mg_update
This was flipped on this release to 100%. Assuming there are no issues, we can remove this for next release. I will remove the setting from admin at that point.
> SUBS-489 Removed setting braintree_dropin_mg_update

- package-lock.json
- src/pages/BorrowerProfile/fundedBorrowerProfile.vue
On the funded loan page KvFlag's default 100% width was overriding the 1rem width set on the fundedBorrowerProfile.vue page.
The order the CSS is bundled can cause this. I feel like we don't usually see it in prod bundles though :/
I also noticed the country names in assistive text were coming in as undefined so fixed that in the flag-icon-css repo and bumped the package-lock here.
> VUE-405 giant flag fix

- src/components/Kv/KvProgressCircle.vue
Roll back to CSS transforms since Chrome borked on the last Firefox fix. Hide for firefox.
> GROW-246 more swashie touchups

- src/router/index.js
Given our use of Auth0 and this scrollBehavior, we end up getting errors like:
```
SyntaxError: Document.querySelector: '#access_token=...'
SyntaxError: Document.querySelector: '#_=_' is not a valid selector
SyntaxError: Document.querySelector: '#/login' is not a valid selector
SyntaxError: Failed to execute 'querySelector' on 'Document': '#/' is not a valid selector.
```
This should fix those errors.
> Stop passing route hashes as selectors unconditionally

- src/components/Checkout/BasketVerification.vue
- src/components/Kv/KvLightbox.vue
- src/components/LoanCards/HoverLoanCard/HoverLoanCardSmall.vue
- src/graphql/mutation/checkout/startBasketVerification.graphql
- src/graphql/query/checkout/basketVerificationState.graphql
- src/graphql/query/checkout/initializeCheckout.graphql
- src/graphql/query/checkout/shopBasketUpdate.graphql
- src/pages/Checkout/CheckoutPage.vue
https://kiva.atlassian.net/browse/GROW-223
* Used the design and copy linked from the ticket.
* One thing I added is some text on the checkout page when the basket is verified. I'm not attached to this, but I found it helpful to differentiate the states.
* Another thing I implemented, which is not specified in the design, is hiding the checkout buttons (but not the login button) when verification is required, especially since the verification lightbox is dismissable. [GROW-243](https://kiva.atlassian.net/browse/GROW-243) tracks making verification block checkout on the backend.
> GROW-223: basket verification in new UI

- src/components/Kv/KvFlag.vue
Width is set on the .wrapper one div deep, so we don't need it on the top level where it can cause problems.
> KvFlag expansion / specificity fix

- src/assets/iconLoader.js
Works OK on my VM, and seemed like it works in my local storybook export. But... I feel like I've tried this before without success 🤔. May revert after github actions runs its thing post merge.
> Attempt to fix svg sprite loading in github pages

- src/components/GetStarted/EditPreferences.vue
- src/pages/GetStarted/GetStartedResults.vue
Fixes `vue.runtime.esm.js:1888 Error: Cannot find module './refugees-and-id-ps_2x.png'` wherein the LoanChannel name was being used that doesn't match the image names.
> Fix string passed to Edit Causes instance of KvCauseSelector.

- server/index.js
This is to fix these console errors on /15:
```
Access to fetch at 'https://www-dev-kiva-org.freetls.fastly.net/static/wasm/gkweb_bg.caff18f.wasm' from origin 'https://www.dev.kiva.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
> GROW-249 fix CORS headers for binary and wasm files

- src/components/15Years/15YearsHeader.vue
Small change so that we don't have to use custom code for number formatting, and a fix for this warning:
```
WARNING: calc(100vw - 72px) was passed to rem-calc(), which is not a number.
```
> Use numeral for number formatting and rearrange combined calc/rem-calc

- package-lock.json
This brings in this update: https://github.com/kiva/flag-icon-css/pull/2
> Update flag-icon-css for IE

- src/components/15Years/15YearsPartners.vue
* Switch to css animations for the stats coming in, with a delay to allow the text to free up some space before they come in. Prevents the layout shift of the page.
> Fixed jank of partner text expansion

- src/pages/Borrow/BorrowHowLong.vue
Removed s from check out this useful guide link at /borrow/pre-applic…ation/how-long.
Tested locally and this appears to work as expected.
> Fixed link on borrower pre-application/how-long page

- src/components/Checkout/MonthlyGoodCTA.vue
- src/pages/MonthlyGood/MonthlyGoodSetupPage.vue
- src/pages/MonthlyGood/MonthlyGoodSetupPageControl.vue
- src/pages/MonthlyGood/MonthlyGoodSetupPageVariant.vue
- src/router/routes.js
* Implemented start date minus 1 for MG setup form for users coming from thanks page CTA
This was part of the spec for SUBS-320. The idea being that the user will start MG about next month.
> SUBS-320 Thanks Page MG CTA Start Date

- src/pages/Thanks/ThanksPage.vue
* This hr looks weird if there isn't anything displayed above it. This is an edge case but possible if on thanks page with no loans, and not opted for the CTA experiment
> SUBS-320 Thanks Page HR Fix

- src/pages/Autolending/AutolendingPage.vue
- src/pages/Settings/SecuritySettings.vue
- src/pages/Settings/TwoStepVerificationPage.vue
- src/pages/Subscriptions/SubscriptionsPage.vue
Sets page titles, use h1s.
This changes the appearance of the headings on these pages. If we want to keep the old appearance, we can do something like `<h1 class="h2">` but we should keep the `<h1>` for semantics and screenreaders. 
My personal opinion is to use a raw h1 here, and really on nearly all pages for consistency. If design wants to change the typography of what a page header look like, we change it in our global styles and all pages with a raw h1 will get the update, rather than more and more one-off designs that we'll have to go through when design updates to a new look.
Raw h1 on the left, h2 on the right:
> Settings area semantic tweaks

- test/e2e/specs/AutolendingPage.spec.js
AutolendingPage spec fails periodically on Travis. This might be able to fix it, as cypress will retry the assertion before click.
Reference:
https://docs.cypress.io/guides/core-concepts/retry-ability.html#Commands-vs-assertions
`If the assertion that follows the cy.get() command fails, then the cy.get() command will requery the application’s DOM again. Then Cypress will try the assertion against the elements yielded from cy.get(). If the assertion still fails, cy.get() will try requerying the DOM again, and so on until the cy.get() command timeout is reached.`
> Attempt to fix flaky Travis test

- src/pages/Borrow/BorrowHowLong.vue
Updates to the new borrower application link which has moved out of Salesforce's portal and into FormAssembly forms which are embedded on kiva.org
In the main Kiva code we have this as a settings manager setting, not sure if that is possible here so just using the actual relative URL
This would ideally go out with next Kiva production release (which is when the code changes are going out in the PHP code for the new borrower application)
> Update borrower application link to new link

- config/audit.js
- config/dev-vm.js
- config/dev.js
- config/index.js
- config/qa.js
- config/stage.js
- config/test.js
- src/client-entry.js
- src/util/KvAuth0.js
This adds the means for the client-side portion of the app to fetch an access token to use with the auth0 MFA api.
To use in a component, first include `inject: ['kvAuth0']` in the component definition. You can then call `this.kvAuth0.getMfaManagementToken()` which returns a promise that will resolve with the token or reject with an error. That method will fetch a new token if one doesn't exist already, or it will resolve the promise with the current token.
After the token is fetched, you can also access it synchronously via `this.kvAuth0.mfaManagementToken`
> GROW-314 Add method to fetch MFA management access token

- src/pages/Borrow/BorrowIntro.vue
Kiva US is moving to embedded FormAssembly forms for its application instead of portals in Salesforce
This updates the link to point at the place on kiva where we have the embedded forms
> Update to new borrower application link

- src/components/Kv/KvAlert.vue
* Storybook with PostCSS says ' start value has mixed support, consider using flex-start instead'
> Minor CSS Fix For KvAlert

- src/util/expander.js
Seeing the banner sometimes get stuck in a closed position. After this change haven't seen it totally bork yet. Would like to do more browser testing once it's in dev.
> Instead of settimeout, force a reflow to avoid timing bugs

- src/components/Checkout/BasketItem.vue
- src/components/Checkout/LoanPrice.vue
- src/components/Forms/MultiAmountSelector.vue
- src/components/LoanCards/Buttons/LendIncrementButton.vue
- src/graphql/fragments/detailedLoanCard.graphql
- src/graphql/fragments/loanCardFields.graphql
- src/graphql/query/algoliaLoanStatus.graphql
- src/graphql/query/checkout/emptyBasketData.graphql
- src/graphql/query/checkout/initializeCheckout.graphql
- src/graphql/query/checkout/shopBasketUpdate.graphql
- src/graphql/query/loanCardBasketed.graphql
- src/util/loanUtils.js
Uses the GraphQL field defined in https://github.com/kiva/kiva/pull/9463 but defaults to $25 without it. Also adds a couple of `25_hard_coded` tags.
Screenshot below. See [SUBS-582](https://kiva.atlassian.net/browse/SUBS-582) for before picture.
> SUBS-582: Use a configurable note size rather than a hardcoded share price

- src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBannerCircular.vue
I was looking into how to get line breaks created in contentful rich text (using `Shift + Enter`) to be rendered as `<br />`, and found [a comment](https://github.com/contentful/rich-text/issues/69#issuecomment-479790401) pointing me in the direction of this whitespace value `pre-wrap` that works like this: "Sequences of white space are preserved. Lines are broken at newline characters, at `<br>`, and as necessary to fill line boxes."
So I added a line break into the rich text for the appeal banner and tried `pre-wrap` and it worked:
> Render newlines as line breaks in the appeal banner body

- package-lock.json
- package.json
- src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBannerCircular.vue
Since we were transitioning on height on the appeal banner, we ended up with a lot of jank. This package does some interesting stuff behind the scenes to use transforms for everything instead. Ends up smooth.
Don't love throwing this in at the last second without much testing though. Adds 10k too.
https://bundlephobia.com/result?p=vue-smooth-reflow@0.1.12
Thoughts?
> GROW-313 smoother transitions

- src/pages/StartVerification.vue
- src/router/routes.js
This page is used to initiate email verification when MFA is not available. Various other pages (like /withdraw and /settings/security) will redirect here if the user has not authenticated with MFA.
> GROW-279 Create page to allow users to initiate email verification

- src/graphql/mutation/removeMfa.graphql
- src/pages/Settings/TwoStepVerificationPage.vue
This endpoint changed so that it no longer requires an mfa token (for details see https://github.com/kiva/kiva/pull/9509)
> GROW-373 Update deleteAllAuthenticatorEnrollments usage

- .storybook/stories/KvLightbox.stories.js
- src/components/Checkout/DonationNudge/DonationNudgeLightboxImage.vue
- src/components/Kv/KvLightbox.vue
- test/e2e/specs/AutolendingPage.spec.js
Refactors KvLightbox to fill the screen on mobile, while keeping the title and controls always visible.
As part of GROW-303, we've changed course a little - instead of doing special pages for mobile, we're making the lightbox work better on phones. 
I'll do some more testing on my vm tomorrow morning since KvLightbox is used in many places, but initial tests look good.
Component keeps the same props/events/slots as before.
> GROW-303 full-screen mobile lightbox

- src/components/Homepage/LendByCategory/FeaturedLoansCarousel.vue
- src/components/Homepage/LendByCategory/LoanCategory.vue
- src/components/LoanCards/Buttons/ActionButton.vue
- src/components/LoanCards/Buttons/CheckoutNowButton.vue
- src/components/LoanCards/LendHomepageLoanCard.vue
- src/components/LoanCards/LoanCardController.vue
- src/pages/Homepage/LendByCategoryHomepage.vue
Introduces the option to showViewLoanCta (link to loan detail) for the LendHomepageLoanCard which will now also be used on landing pages.
Also, introduces the option to not automatically redirect when clicking the Checkout button and to respond to the bubbled `add-to-cart` event instead.
I've verified the alternate/default states for both of these in the homepage context. These changes are required and included in some landing page work that is forthcoming.
> Optional cta checkout redirect

- src/pages/Settings/TwoStepVerificationPage.vue
I haven't actually tested this on my vm, but I came across this as the possible problem after I noticed in the network inspector that the removeOneMfaMethod query didn't have the `id` variable. I don't see `authId` used anywhere else, so I think this didn't get updated when `formatMfaMethods()` changed.
> GROW-382 use mfaMethod.id instead of mfaMethod.authId

- src/pages/Settings/SecuritySettings.vue
- src/pages/Settings/TwoStepVerificationPage.vue
Removed the padding from the settings-cards on small screens for /settings/security & setting/security/mfa. 
This change makes these two pages look visually consistent with the /settings/autolend page when on a small screen.
Cards now have no padding while on small screen sizes:
> removing settings card's padding on small screens

- src/components/Kv/KvLightbox.vue
Cleanup more unused full-widths.
Fixes a bug where the watcher doesn't always fire on the first initial load, so focus lock, scroll lock, etc. doesn't get set.
> Lightbox fixes

- src/components/Kv/KvVerificationCodeInput.vue
- src/components/Settings/AppAuthentication.vue
On small screen, the Auth App Code, and the 6 digit input didn't fit on our smallest support screen size 320px
Just for reference, this is the same lightbox on large screens (looking good)
I made adjustments to:
AppAuthentication.vue - Updated the font size of the returned code
-- The one thing I'm worried about with my fix, is this font-size being too small, setting it to 12px
KvVerificationCodeInput.vue - added a few style adjustments that I was hoping to get your eyes on @ryan-ludwig, I just made a couple style adjustments for small screens and reimplement most of your original styles at the medium breakpoint.
**My Fix** 
_small screen_
_large screen_ 
I think this looks good across screen sizes, but my one concern is that the App Auth code that you manually input into your auth app is …
> grow-387 adjustments to KvVerficationCodeInput for small screens.

- src/components/Settings/PhoneAuthentication.vue
I ran into the same screen size issue with the PhoneAuthentication.vue file, so I made really similar changes in that file to get it looking better on small screen sizes: 
Looks the same still on larger screen sizes:
> grow-387 change for small screen size in the phoneauth.vue lightbox.

- src/pages/StartVerification.vue
- src/util/authenticationGuard.js
It possible for these methods to be called on the client before an auth token has been fetched, meaning that it would appear that the user was not MFA authenticated even when they actually were. This fixes that by ensuring their graphql queries don't use the cache, forcing a checkSession call to be made (via src/api/Auth0link.js).
Also, the email verification page wasn't checking if a user was MFA authenticated and therefore didn't need to verify their email.
> GROW-416 Fix being redirected to the email verification page on the client side when MFA authenticated

- .storybook/stories/KvLightbox.stories.js
- src/components/Checkout/BasketItem.vue
- src/components/Checkout/BasketItemsList.vue
- src/components/Checkout/BasketVerification.vue
- src/components/Checkout/CheckoutHolidayPromo.vue
- src/components/Checkout/DonationItem.vue
- src/components/Checkout/InContext/InContextCheckout.vue
- src/components/Checkout/KivaCardItem.vue
- src/components/Checkout/KivaCardRedemption.vue
- src/components/Checkout/LoanPrice.vue
- src/components/Checkout/LoanReservation.vue
- src/components/Checkout/OrderTotals.vue
- src/components/Kv/KvLightbox.vue
- src/pages/Checkout/CheckoutPage.vue
- src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
Broadly, reworks checkout CSS to use standard Foundation grid with less overrides (mainly by adding .columns class and removing padding/margin css). Aimed to prevent overrides on overrides for the in-context checkout and make working in checkout more predictable. Visually the existing checkout should not have changed (within a few pixels).
* Replace some span > divs
* Fix scoping, removed forced-width class.
* Fix issue where lightbox contents with a foundation grid were indented too much, add a story for that.
* Min-width for the in-context checkout
> ML2-167 improve checkout styles

- src/components/Settings/AppAuthentication.vue
- src/components/Settings/PhoneAuthentication.vue
- src/pages/Settings/TwoStepVerificationPage.vue
If a user cancels their App Authentication setup (by closing the lightbox or closing the page) we can end up in a situation where a recovery code was generated but it was not shown to the user. We can identify those situations by the user having a recovery code method that is not active (there is only ever 1 recovery code method, and it only becomes active once the user confirms their first MFA enrollment). We can fix this situation by reseting the user's MFA so that they get a new recovery code on their next setup.
> GROW-401 Reset MFA if there is an inactive recovery code on page load

- src/pages/Homepage/MonthlyGoodHomepage.vue
We had a request in grow-443 to updated two button on the monthly good homepage. 
Desktop:
Mobile:
> grow-443 changing CTA buttons back to older style per grow-443

- config/audit.js
- config/dev-vm.js
- config/dev.js
- config/index.js
- config/qa.js
- config/stage.js
- config/test.js
- src/components/Payment/BraintreeDropInInterface.vue
- src/pages/Settings/PaymentSettings.vue
* Adds ability to add a card in payment settings
~Basically Done. Waiting for Production btTokenKey - See ITS-6279~
~- We have to use a token key to bypass the vault and only show an add card form in UI~
~- Token key is fine to expose publicly: https://developers.braintreepayments.com/guides/authorization/tokenization-key/javascript/v3#obtaining-a-tokenization-key~
> SUBS-614 Add A Card Interface

- src/pages/Thanks/ThanksPage.vue
These headline/subhead styling changes are permanent changes that design wants implemented.
They were created for the upcoming SUBS-554 experiment, but I confirmed that these changes should be permanent and not experimented on
Screenshot:
> Thanks Page header styling changes

- src/components/CorporateCampaign/CampaignLogoGroup.vue
- src/components/CorporateCampaign/CampaignPartner.vue
- src/components/CorporateCampaign/CampaignPartnerThanks.vue
The images uploaded for Visa's campaign were pretty giant for what they were.
Contentful lets you add query params to dynamically set the height/width/format/quality. Saves a lot of bytes.
Original
Using picture
> ML2-222 Don't send the raw contentful image

- src/pages/Settings/TwoStepVerificationPage.vue
This additional request came in on top of grow-465. 
Simply removing the green "(Most secure)" text from the /settings/security/mfa page
> grow-471 removing the (most secure) language

- src/components/Checkout/CheckoutItemImg.vue
Prevents keyboard focus. Couldn't find any CSS references to this so I think it's fairly safe.
> ML2-204 Render a span instead anchor if disabling links.

- src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
- src/pages/Thanks/ThanksPage.vue
* Removes 'ui-homepage-monthly-good' setting which was used to activate contentful content on the MG landing page and thanks page.
This setting was essentially a hack - I used it to turn contentful on for these pages on a certain date. These sections (mg landing/ thanks page mg cta) should always be driven by contentful moving forward, so the setting is no longer necessary. Once this code is out, this setting will need to be removed on contentful from these page layouts as well. 
Note - The 'ui-homepage-monthly-good' setting is still active and used on the homepage to toggle the "monthly good" homepage.
> VUE-478 Remove Old Setting

- src/components/CorporateCampaign/CampaignLoanRow.vue
- src/components/Homepage/LendByCategory/LoanCategory.vue
- src/components/LoanCards/LendHomepageLoanCard.vue
- src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
- Give images an aspect ratio so the content doesn't jump. Prevent stretched out cards when one is tall.
- Bring back interaction tracking to homepage carousel
- Don't show extra `<hr>` if we have no partner content
> Carousel tweaks

- src/pages/Checkout/CheckoutPage.vue
Guest checkout button shown on /checkout page if user's browser doesn't contain a 'kvu' cookie? 
ticket: https://kiva.atlassian.net/browse/GROW-440.
Desktop: 
Mobile:
> grow-440 guest checkout button in place

- src/components/Homepage/HomepageLoanCategories.vue
- src/components/Homepage/LendByCategory/LoanCategoriesSection.vue
- src/pages/Homepage/iwd/IWD2021Homepage.vue
Some complex pre-fetching would be needed to have the category ids defined in Contentful instead of Settings Manager, so I skipped doing that for now to focus on the other parts of the page.
> GROW-434 Contentful Homepage loan categories component

- src/pages/Donate/DonateFromMacro.vue
- src/pages/Donate/DonateFromMacroHero.vue
- src/util/contentfulUtils.js
* Get images from contentful (VUE-326)
* Add contentful util helper which converts contentful responsive image into kv-responsive-image array
* Remove _get from page
* Remove usage of 'content' from contentful use, contents instead.
This is both the work for VUE-326 and VUE-463 (partial). And necessary so we can remove the content group 'content' field
TODO: 
There are corresponding changes in contentful, I've already made them in the dev environment, related to the support-kiva page nested content. 
Once this gets to prod, we can delete the 'support-kiva' page from prod, and copy the updated one from dev.
> VUE-326 Refactor donate from macro site page

- src/components/Homepage/HomepageBottomCTA.vue
- src/components/Homepage/HomepageCorporateSponsors.vue
- src/components/Homepage/HomepageTestimonials.vue
- src/pages/Homepage/iwd/IWD2021Homepage.vue
General spacing adjustments across the page.
- Dropped the margin between sections from 4rem to 2 rem (consistent with current homepage)
- Made minor spacing adjustments for consistency in some headings of sections.
- Made adjustments to bottomCTA section based on current homepage: 
**Desktop:**
**Mobile**
**Spacing adjusted below loan cards above How it works section:**
**Space adjusted below the testimonials section:**
> grow-490 spacing adjustments post review meeting

- src/components/Homepage/HomepageHowItWorks.vue
- src/components/Homepage/HomepageTestimonials.vue
Column fixes for the How it works and Testimonials sections of the IWD 2021 homepage.
_Desktop_
_Mobile_
_Desktop_
_Mobile_
> Iwd column fixes

- .storybook/mixins/apollo-story-mixin.js
- .storybook/stories/MGCovid19Response.stories.js
- config/dev-vm.js
- config/local.js
- config/local.vm.js
- src/api/apollo.js
- src/main.js
- src/pages/Autolending/AutolendingSettingsPage.vue
- src/pages/Homepage/DefaultHomepage.vue
- src/pages/Possibility/12DaysOfLending.vue
* Removes secondary apollo client
This was the second apolloClient that I created to be able to run contentful queries from the federation service and queries to the vm. This is no longer needed with our new docker setup.
> VUE-479 Removes Federation Apollo Client

- src/components/CorporateCampaign/CampaignLoanRow.vue
- src/components/Homepage/LendByCategory/LoanCategory.vue
Fix specificity issue depending on what order the CSS bundles are served. Possible it only happen on VMs, but still annoying.
Fixes this:
> Occasional carousel item width bug

- src/components/Homepage/HomepageStatistics.vue
Adding the ? to the statsHeadline incase it's undefined. 
`statsHeadline() {
return this.statsText?.headline ?? '';
},`
This small change got left behind on my VM yesterday, I noticed it on my VM this morning.
> adding ? incase headline is not defined

- src/pages/Lend/LendByCategoryPage.vue
The snowplow tracking event for this experiment was slightly incorrect (see GROW-517 ticket for full details).
The actual experiment was working properly, as we can see in the ML service data, but the snowplow tracking events were all coming through with the control label "a". This is because the tracking code was expecting "variant-a" to be the name of the version for the variant group, but the experiment setting in settings manager was using "b" for the variant group (and "a" for the control group).
> GROW-517 fix tracking event label/action/value for ML bandit experiment

- src/components/Homepage/LendByCategory/LoanCategory.vue
Storybook loves warning about this. 
`start value has mixed support consider using flex-start instead`
> Fix CSS storybook warning

- src/components/Checkout/CheckoutDropInPaymentWrapper.vue
- src/pages/Checkout/CheckoutPage.vue
This will show the braintree drop-in and guest checkout fields when a non-logged in user selects "Checkout as guest". This does not remember that the user selected that option, so if they refresh the page before completing the checkout they will need to select "Checkout as guest" again. We can change that behavior in another ticket if needed.
> GROW-519 show braintree drop-in for guest checkout

- src/pages/Checkout/CheckoutPage.vue
The loginContinueButtonText() function was previous remove and text was set to a string of 'Continue', this is a cleanup from those changes.
> fixing tracking event, changing from function that was removed to string

- src/pages/Settings/EmailSettings.vue
- src/pages/Settings/PaymentSettings.vue
- src/pages/Settings/SettingsPage.vue
- src/router/routes.js
* Initial new stack email settings page
Working great, all functionality duplicated from legacy page. 
**STILL TODO:**
* Add trustee email settings section
* Add borrower email settings section
* Add service worker for lending notifications on browser
* Set up this new route in kiva/main and puppet repos
* Delete legacy code in kiva/main and styleguide repos
> VUE-315 Email Settings

- server/auth-router.js
Using `/ui-login?forgot=true` will redirect to the forgot password page, even for logged in users.
> GROW-563 Add option to redirect to forgotPassword page

- src/components/AutoDeposit/AutoDepositDropInPaymentWrapper.vue
- src/components/Checkout/CheckoutDropInPaymentWrapper.vue
- src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue
- src/plugins/braintree-dropin-error-mixin.js
* Extracted BT DropIn Wrapper error processing to a plugin
* The UI has to use extensions.code instead of errors.code to display friendly errors
The API returns a response that looks like:
```
{
"errors": [
{
"message": "Some error",
"locations": [
{
"line": 3,
"column": 5
}
],
"path": [
"shop",
"doNoncePaymentDepositAndCheckout"
],
"code": "braintree.transactionRequestRejected",
"extensions": {
"code": "braintree.transactionRequestRejected"
}
}
],
"data": {
"shop": {
"doNoncePaymentDepositAndCheckout": null
}
}
}
```
This can be replicated in the GQL playground, but on the UI side, `errors[0].code` is always undefined. I'm not sure where that is happening. Maybe `src/util/apolloPreFetch.js` But these queries aren't in preFetch so I'm not sure. 
`errors[0].extensions.code` contains the …
> SUBS-499 Friendly BT Errors

- src/components/Homepage/HomepageStatistics.vue
- src/pages/Homepage/LendByCategoryHomepage.vue
Grow-478: https://kiva.atlassian.net/browse/GROW-478
We've refreshed the look the homepage statistics section. 
**Mobile:** 
**Tablet:** 
**Desktop:**
> Grow 478 updates

- src/pages/ContentfulPage.vue
This is a page component that dynamically pre-fetches and displays a page based on a Contentful Page Layout, using the contentGroup types to decide which components to display.
This handles the page title, the page frame, and has some default content in case there is an error when getting the Page Layout from Contentful.
The possible components are pre-determined, but in the future it could setup to use any component in a given directory.
To use, simply create a route that defines `contentfulPage` in the meta data, e.g.:
```
{
path: '/',
name: 'homepage',
component: () => import('@/pages/ContentfulPage'),
meta: {
contentfulPage: 'home',
},
},
```
> VUE-531 Generic Contentful page component

- src/graphql/mutation/completeGuestAccountClaim.graphql
This mutation isn't being used anywhere and isn't in the graphql api anymore.
> Remove unused and deprecated mutation

- src/router/routes.js
Added dynamic route for `/lp/support-causes-monthly` 
Added content on contentful, for now just a copy of the `Home` page content. 
I made the page key `lp/support-causes-monthly` which I know doesnt match the format of the keys for the cc landing pages, but thought this would be more descriptive
> SUBS-663 Added Route for dynamic landing page

- src/pages/ContentfulPage.vue
- src/util/contentfulUtils.js
- test/unit/fixtures/CorporateCampaignContentfulPageRaw.json
- test/unit/specs/util/contentfulUtils.spec.js
The `headerTheme` and `footerTheme` fields on the `PageLayout` content type in Contentful are setup as a dropdown with limited options, similar to the `type` field on `ContentGroup`. The options for each one match up with the names of the exported header and footer themes from `src/util/siteThemes.js`.
> VUE-551 Use header & footer themes for the page frame in ContentfulPage

- src/components/Kv/KvTipMessage.vue
> VUE-559 Stop blue links from vibrating against the red error state background

- src/api/localResolvers/my.js
- src/api/localSchema.graphql
- src/components/WwwFrame/WwwPage.vue
- src/components/WwwFrame/WwwPageCorporate.vue
- src/components/WwwFrame/WwwPageMinimal.vue
- src/graphql/query/checkout/initializeCheckout.graphql
- src/graphql/query/shared/hasEverLoggedIn.graphql
- src/pages/Checkout/CheckoutPage.vue
- test/unit/specs/api/localResolvers/my.spec.js
This adds a new local resolver field to handle the kvu cookie being server-only. It works by using the kvu cookie to set a "hasEverLoggedIn" field in the apollo cache on the server, and then forces the browser to use the cached value for that field.
That new field is used to fix the issue in GROW-586 that was sending experiment events for users that were ineligible for guest checkout.
This also includes the requested change in GROW-585, "Checkout as guest" -> "Continue as guest".
> GROW-586 GROW-585

- src/components/Settings/PhoneAuthentication.vue
- src/pages/Settings/FirstMFASetup.vue
[GROW-481](https://kiva.atlassian.net/browse/GROW-481)
Requirements of ticket: 
R1 - Left align the title during the phone/SMS flows (it’s currently offset to the right approx 17px)
*** Unable to reproduce this issue.**
R2 - Make the window width the same size for the “We just sent you a text message” prompt
*** I shortened this text by removing "just" text now reads -> "We sent you a text message"**
R3 - On the last phone setup page, replace “Phone number” title with “Complete setup”, remove the current “Complete setup.”
*** added an additional step check in the lightboxTitle() function and removed the now duplicated title from FirstMFASetup.vue
> grow-481 shortened copy, title swaps on last step of MFA flow

- src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBannerCircular.vue
[Vue-574](https://kiva.atlassian.net/browse/VUE-574)
Replaced the < img > with < kv-contentful-img > within AppealBannerCircular.vue.
Tested locally and looking good.
> VUE-574 running promo banner through kvContentfulImg component

- src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBannerCircular.vue
Error: 
Closed appeal banner, button in hover state: 
Fixed:
> grow-601 closed button hover state fixed

- src/graphql/query/flssQuery.graphql
- src/pages/FlssPrototypes/FlssLoanRow.vue
Ticket:
https://kiva.atlassian.net/browse/PSD-196
What does this do:
replaces flss filters hard coded in graphql query to filters hard coded in the vue pages
linting
how to test:
A loan row should render on this page:
localhost:8888/flss
> PSD-196 pass flss filters to graphql via vue pages

- src/components/MonthlyGood/MonthlyGoodSelectorWrapper.vue
* Stack the MG sticky selector on top of the OneTrust cookie banner when it exists
> SUBS-723 Fix Stocky MG Selector & Cookie Banner

- .storybook/stories/MonthlyGoodSelector.stories.js
- src/components/MonthlyGood/MonthlyGoodSelectorDesktop.vue
- src/components/MonthlyGood/MonthlyGoodSelectorMobile.vue
- src/components/MonthlyGood/MonthlyGoodSelectorWrapper.vue
* Allows MG Selector to read contentful setting and preselect a cause in both mobile and desktop
* Renamed MG Selector desktop component
Works off UI Setting on contentful, which contains a data object and looks like:
```
{
"preSelectedCategory": "refugees"
}
```
Example: 
https://app.contentful.com/spaces/j0p9a6ql0rn7/environments/development/entries/34Cn8yRZCnqRjwv580UZyu?previousEntries=6Q14Zf7ttG0iBKLdQ4KAjD,3z8Yn1Inpy8iCZPY72pAS5
> SUBS-738 MG Selector Pre Selected Cause

- package-lock.json
These are the package-lock.json updates that I removed from [this PR.](https://github.com/kiva/ui/pull/2953)
These updates were a result of running npm install in the /kiva/ui repo.
> build: package-lock updates that we removed from borrower profile frame build

- package-lock.json
- package.json
- src/components/BorrowerProfile/BorrowerAvatar.vue
- src/components/BorrowerProfile/BorrowerName.vue
- src/components/BorrowerProfile/LoanUse.vue
- src/components/BorrowerProfile/SummaryCard.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
This brings in the latest Tailwind config via the @kiva/kv-components package, which alters our Tailwind classes to put a 'tw' prefix on all of them.
The purpose is to prevent class name collisions between Tailwind classes and Foundation or any other class names used on the site.
https://tailwindcss.com/docs/configuration#prefix
After this is merged, writing Tailwind classes on UI will require a 'tw' prefix. e.g., `class="flex align-center mb-2"` would become `class="tw-flex tw-align-center tw-mb-2"`
> VUE-610 Bring tailwind prefix into UI

- src/components/MonthlyGood/MonthlyGoodSelectorWrapper.vue
This restores prior styles to prevent the header from showing above the mobile full-screen lightbox and obscuring the headline. No issues on desktop.
> Fix z-index for sticky state of MG selector

- src/components/Contentful/DynamicHero.vue
Currently the adaptive images on the homepage block are being served at the dimensions they're uploaded at in contentful. This PR scales them down to their container size at the different breakpoints.
> Homepage contentful block - image scaling

- src/components/BorrowerProfile/LoanProgress.vue
I added aria-label="Percent the loan has funded" to the <kv-progress-bar> include within LoanProgress.vue which stops this error/warning from being thrown.
> grow-709 adding aria-lable to <kv-progress-bar> within LoanProgress.vue

- src/components/BorrowerProfile/LendCta.vue
- src/util/basketUtils.js
The userProperties.amountInBasket field only works when the query is made with a logged in user. To deal with that, this changes the "in basket" check to look for the loan id in the basket items array.
While I was testing that, I noticed that the "non actionable loan" button was being displayed but with "Lend now" as the button text, and that when adding the loan to the basket there were 2 buttons, one saying 'lend now' and the other saying 'adding to basket...'. Those were making it difficult to test my changes, so I refactored the state checks for the buttons to address those issues.
> GROW-691 Fix lend cta not updating after adding to basket

- src/graphql/query/flssLoansQuery.graphql
Jira Ticket:
https://kiva.atlassian.net/browse/PSD-265
What does this do:
creates graphql loan query to flss service with filtering ability. the query should return all information necessary to populate a loan card. 
how to test:
The full expanded version of the query with a country default of ["US"] should return loans from the flss endpoint:
`https://marketplace-api.k1.kiva.org/graphql`
```graphql
fragment loanCardFields on LoanBasic {
id
status
name
borrowerCount
geocode {
city
state
country {
isoCode
name
region
}
}
use
activity {
id
name
}
sector {
id
name
}
whySpecial
lenderRepaymentTerm
loanAmount
minNoteSize
loanFundraisingInfo {
fundedAmount
reservedAmount
isExpiringSoon
}
plannedExpirationDate
matchingText
userProperties {
favorited
lentTo
}
lenders(limit: 0) {
totalCount
}
... …
```
> general flss loans query

- src/components/BorrowerProfile/LendCta.vue
While QAing grow-688 I found a couple issues. 
1) The lend again button was showing up when the loan had been basketed. 
- Changing the v-if condition on the "lend again" button fixed this issue
2) Tracking was not working correctly for the lend again button, upon click I was getting the tracking info of the Lend button. I added keys to both buttons, which tells vue that the buttons are in fact different and passes through all the data for each button. They are so similar, it seems that vue was only updating some of the fields (not tracking fields) which was causing the issue.
> Grow 688 fix

- src/components/BorrowerProfile/LendCta.vue
I'm really not sure why the transition-group+delay wasn't working. It seems like it should.
Anyhow, after futzing around enough this seems to smooth things out.
> LendCta: Smooth out the animation

- src/graphql/query/flssLoansQuery.graphql
- src/pages/Lend/FilterAlpha/LendFilterAlpha.vue
Jira ticket:
https://kiva.atlassian.net/browse/PSD-280
What does it do:
adds flss query to filter-alpha page to provide access to live loans and data for component presentation. 
How to test:
download the branch and run the dev server
when the `filter-alpha` page renders open the developer tools console and look for `console.log` outputs for loans from the US and the totalCount number of available loans.
> PSD-280: add data call with Graphql flss query to filter-alpha page

- .github/workflows/lighthouse-dev.yml
- .github/workflows/lighthouse-prod.yml
- .github/workflows/run-ui-tests.yml
- .github/workflows/storybook-to-gh-pages.yml
Following these guides ([github](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action), [cypress](https://docs.cypress.io/guides/continuous-integration/introduction#Caching), [stack overflow](https://stackoverflow.com/questions/55230628/is-there-a-way-to-speedup-npm-ci-using-cache)), this will make it so that the npm cache and the cypress binary cache are preserved between builds, allowing subsequent PRs to install much faster.
It's possible to preserve multiple caches, based on a key name. This uses key names based on the hash of package-lock, so anytime package-lock changes a new cache is created. The restore-keys tell github which caches to use as a fallback in case there isn't an exact match for the key (as would be the …
> VUE-634 add caching for github action build dependencies

- src/plugins/app-install-mixin.js
I determined this to be the source of the multi-line console logging, do to the error happening at the same time as other invariant violation errors, and this being the only place that was using `console.error` with errors caught from `apollo.readQuery`.
> VUE-635 use logReadQueryError for app-install-mixin

- src/components/BorrowerProfile/MoreAboutLoan.vue
[Grow-746](https://kiva.atlassian.net/browse/GROW-746)
I wasn't able to do anything about the embedded html issue, as the business description is already run through v-html before it's rendered. 
I did find this minor case error that I fixed up. 
Business Description -> Business description
> grow-746 changing a title to sentence case

- .babelrc
- .github/dependabot.yml
- package-lock.json
- package.json
This seems to drastically improve tree-shaking. I'm not sure if there are improvements across the board or if it's mainly the mdi.js package getting cleaned up. 
Arrived at this direction after reading this article https://webpack.js.org/guides/tree-shaking/#conclusion
With commonjs transform: 891kb
Without commonjs transform: 231kb 
Oddly was having issues with the SVG loader after it was no longer being run through the commonjs transform. Rolling back a version appears to solve that. https://github.com/visualfanatic/vue-svg-loader/issues/121
Since this is kindof a big change I think it'd be good to get some testing in on dev before shipping to prod.
> VUE-643 remove commonjs transform

- src/client-entry.js
- src/plugins/kv-analytics-plugin.js
The condition in the for loop checked `queue.items.length` every time the loop ran, however that length was constantly getting smaller as items are removed. So when you start with 3 items in the queue, you eventually end up with `i == 2` and `queue.items.length == 1`, so the loop is skipped and the last event in the queue does not get sent. Using a while loop that only checks if the queue is empty will ensure that all items in the queue get processed.
> Use while loop to empty tracking event queue

- src/components/MonthlyGood/MonthlyGoodSelectorWrapper.vue
Fix for sticky selector in `/lp/support-refugees`
I tried adding the `kv-tailwind` class to the page wrapper in: `src/pages/ContentfulPage.vue` but that broke a lot of the other components, so this is an easier fix just for the landing page. 
SUBS-788
> fix: fix monthly good selector styling tailwind class wrapper

- src/assets/inline-svgs/logos/yelp-logo.svg
Yelp logo had a color issue too once rendered. Locally it looked good, only once it got up on dev was it an issue. I added the fill to the actual <svg tag>, that seemed to fix things up.
> adding fill color to fight place of svg

- tailwind.config.js
The configuration for PurgeCSS was not up to date with the version of PurgeCSS that we are using. 
This led to a situation where adding a tailwind class in UI that was *not*  being used in kv-ui-elements would not display because it was purged. 
VUE-647
> fix: Fix UI tailwind purging classes

- package-lock.json
- src/pages/Lend/FilterAlpha/LendFilterAlpha.vue
I have imported the data for the loan count and displayed it onto the website.
https://kiva.atlassian.net/browse/PSD-279?atlOrigin=eyJpIjoiMzVhNmFiMWQzNzRlNGQ1NGJjNzRjZjgwMzYzZjBkNGQiLCJwIjoiaiJ9
The way that you could test this is by loading up the site and noticing that the loan count has appeared. From there you can minimize your screen so that you can see the responsiveness of the loan count. It will then move from being under the search box to next to the filter tap at the top left.
> Created loan count display

- server/util/getSessionCookies.js
The request cookies are decoded by default when [they are first read](https://github.com/kiva/ui/blob/master/server/vue-middleware.js#L60):
```
const cookies = cookie.parse(req.headers.cookie || '');
```
Doing that is useful because those cookies are directly used by the app. However, when sending those cookies to the monolith when starting a new session, we haven't been encoding them again, leading to request failures when there are non-ASCII characters in the cookie values.
This PR encodes the cookies before including them in the monolith request.
> VUE-649 re-encode cookies included in request to start session

- src/components/Contentful/HeroWithCarousel.vue
- src/components/MonthlyGood/MonthlyGoodSelectorWrapper.vue
- src/pages/ContentfulPage.vue
Adds new Content Group of type 'landingPageHero'
Creates frame and headline and subheadline for that content group
Adds tailwind wrapper class to some components from contentful page
Design reference:  https://www.figma.com/file/weQAkMDYoBA5ZnuHf4TPOA/Cause-Based-Landing-Page-Templates?node-id=136%3A331
SUBS-777
> feat: New header frame for cause based landing pages

- src/pages/Lend/FilterAlpha/LendFilterAlpha.vue
I've created a section for the icons titled "explore" and "filter". By having these icons available the user is able to switch pages. Also, the header and text has been added to the top of the title page. The title page is also responsive to fit the mobile screen which makes a few features hidden compared to the desktop screen. 
https://kiva.atlassian.net/browse/PSD-281?atlOrigin=eyJpIjoiMjU3OGVjZDM4ZGQ1NDA4NmE5MDI4ZTNhYWM5YmUwZmMiLCJwIjoiaiJ9
The way that you can test this is by loading up the page and looking at the top for the title portion. The user should see both the icons and as well as the header and text. Then the user can minimize the window so that the mobile screen is shown and the icon titles and as well as the text will be removed.
> Filled in Title Page

- server/util/getGqlFragmentTypes.js
- server/util/initCache.js
- server/util/memJsUtils.js
- server/util/vueSsrCache.js
The third argument for `memjs.set()` is [supposed to be an options object](https://github.com/memcachier/memjs#settings-values), with a single option `expires`. Many of the current usages are passing in a number, with the assumption that the number is being used for `expires`. That's not the case. What actually happens is `memjs.set()` will ignore invalid options arguments and use 0 for `expires` (meaning never expire!). Luckily this hasn't caused a problem yet because we use the release hash in our vue component cache keys and the graphql fragment types have never changed!
> Fix memjs options argument usage

- src/pages/AutoDeposit/AutoDepositLandingPage.vue
* Refactor _get on page
* Refactor content group naming and access content groups with processPageContent
This was the only page that had ContentGroups that were camelCased. This PR just standardizes some of the naming and accessing of the content groups on the page, as well as use processPageContent and remove lodash/_get
> refactor: auto deposit landing page

- src/plugins/loan-group-categories.js
* Changes the 'eco friendly' label to 'climate' in the UI without touching the MG value or loan channel
GD-112
I think this is what we want. The url for the category will still be `/monthlygood?category=eco_friendly` but the drop downs and interactive selector will all display `climate` this is because the query param maps directly to the value we send to the API
> feat: change eco friendly label in UI

- src/components/Contentful/HeroWithCarousel.vue
Makes the carousel not be affected by page padding on mobile.
Before: 
After:
> fix: Fix for carousel on cause based landing pages

- build/webpack.base.conf.js
- server/dev-server.js
While doing research and testing on: https://github.com/kiva/ui/pull/3223 I came across these 2 minor webpack improvements. 
Improving ExtractCSS which should not use hashes for dev - https://webpack.js.org/plugins/mini-css-extract-plugin/#advanced-configuration-example
Refactoring deprecated compiler hook - reference: https://webpack.js.org/api/compiler-hooks/
> fix: minor webpack dev issues

- src/components/Contentful/DynamicRichText.vue
- src/pages/ContentfulPage.vue
- src/util/contentful/richTextRenderer.js
* Adds a field on contentful Button types. 'webClickEventName'
* For the Rich Text Renderer, if this field is present, render the button with an onclick which passes this value up to dynamic rich text component
* In dynamic rich text component, emit a global event of the same name
* TLDR: This allows a button inside of a rich text field in contentful to open up the monthly good interactive selector.
GD-116
> feat: Adds custom event fields to buttons in RTF's

- server/live-loan-router.js
Cache headers for dynamic images: https://stackoverflow.com/questions/21802820/dynamic-images-for-email-such-as-countdown-clocks-in-light-of-gmail-image-cachi/40569195
> VUE-695 Set cache headers for live loan images to prevent caching

- src/components/MonthlyGood/MonthlyGoodSelectorMobile.vue
GD-120
This should help, but the real issue is a bug in styleguide, see VUE-700
> fix: Fix Mobile MG lightbox CTA button being cut off

- src/components/Contentful/RichTextItemsCentered.vue
The column break was not working properly on dev. 
:class="`tw-col-span-12 lg:tw-col-span-${12/richContentfulContent.length}`"
This was because I was breaking the tailwinds class into pieces, which wasn't allowing the function to run before rendering, preventing tailwinds from working correctly, even though the right classes were rendered on the front end. 
The fix passes through full tailwind class names based on the calculation... which works. 
https://tailwindcss.com/docs/just-in-time-mode#arbitrary-value-support
* I spoke to Nathan and he did want to go with the 2 column view for medium view ports. 
**Small:**
**Medium:** 
**Large:**
> core-5 fixing up cols on medium and large screens

- src/components/MonthlyGood/MonthlyGoodSelectorMobile.vue
- src/components/MonthlyGood/MonthlyGoodSelectorWrapper.vue
GD-121
Some light refactoring, mostly prettier syntax in the template and removing isMobile check since class based showing/hiding the selector is working. 
Changes from GD-121 ticket (only for the mobile selector, desktop selector to remain  unchanged):
* Make button text not scale down from mobile
* Make selector animate in 
* Add icon on button
* Add border top and bottom 
* Make button not full width
* Change background color
> feat: Cause based landing page improvements

- src/components/Contentful/CenteredRichText.vue
- src/components/Contentful/DynamicHeroClassic.vue
- src/components/Contentful/RichTextItemsCentered.vue
- src/plugins/contentful-ui-setting-styles-mixin.js
This sets the max-width on the children of the grid instead of the grid.
Instead of `tw-mx-auto` on the grid element, it uses `tw-justify-items-...` to horizontally align the grid children and allow overrides from Contentul.
> feat: Allow horizontal alignment of grid items

- .storybook/preview.js
- src/components/LoanCards/KivaClassicBasicLoanCard.vue
- src/components/LoanCards/LoanMatchingText.vue
[Core-100](https://kiva.atlassian.net/browse/CORE-100)
Adding CTA button to KivaClassicBasicLoanCard. 
New loan card with all the pieces assembled.
**THE ISSUE DESCRIBED BELOW IS NO LONGER OCCURRING, FIXED STATE SHOWN BELOW IN COMMENTS**
_**One note, I'm not sure why `<kv-button>` is rendering with the secondary style in my local storybook. According to the [docs](https://608b4cf87f686c00213841b1-vwqtxldhix.chromatic.com/?path=/docs/kvbutton--variant-secondary), primary is the default button variant, but even when I define the variant="primary" it still renders as the secondary style.
`<kv-button
v-if="!isLoading"
class="tw-mb-2"
:to="`/lend/${loan.loanId}`"
>
Read more
<kv-material-icon
class="tw-align-middle"
:icon="mdiChevronRight"
/>
</kv-button>`
This is my import line, including the …
> core-100 Adding CTA button to KivaClassicBasicLoanCard

- src/components/LoanCards/KivaClassicBasicLoanCard.vue
- src/components/LoanCards/LoanProgressGroup.vue
Core-102 All shares reserved state of KivaClassicBasicLoanCard
When all shares are reserved we disable the button click, update the funding text to "Funding complete" and set the fundraising meter to 100%. 
Once we have the click interaction in place for the borrower image, that will also be disabled if allSharesReserved is true. 
Here it is:
> Core-102 adding the allSharesReserved state to KivaClassicBasicLoanCard

- src/plugins/kv-analytics-plugin.js
I encountered this bug this weekend on my home pc. Homepage would load but then lock up (frozen animations, no interactions working). Some digging with the javascript debugger revealed that this loop would never end if snowplow was not loaded. What happened is that each time a snowplow event would be removed, the track event function would be called, and because snowplow wasn't loaded the event would be added back to the queue, which caused the while loop to never stop because the queue was never empty. This fix makes it so that the track event functions aren't called until the loop has already finished, so even if events are added back to the queue the loop doesn't continue.
I'd like to try to get this into today's release.
> VUE-712 Prevent infinite loop in event tracking queue

- src/components/Contentful/LoansByCategoryCarousel.vue
- src/components/LoanCards/KivaClassicBasicLoanCard.vue
- src/components/LoanCards/LoanProgressGroup.vue
- src/components/LoanCollections/KivaClassicLoanCarousel.vue
- src/components/LoanCollections/KivaClassicLoanCategorySelector.vue
- src/components/LoanCollections/KivaClassicMultiCategoryCarousel.vue
- src/pages/ContentfulPage.vue
A variable set of loan channel ids and shortName fields are set in contentful. These are then used to generate the selector if there are more than 1 present in the array. The first loan channel is automatically loaded into a loan carousel.
Sample with existing Homepage Categories
> Implement Contentful driven loan chanel selector and carousel.

- src/components/MonthlyGood/MonthlyGoodSelectorWrapper.vue
The global event used on the cause based landing pages is firing an event that is being captured by both the desktop and mobile monthly good selector. 
On the mobile selector, even though the wrapper is hidden on desktop, the lightbox still triggers, causing it to open , which is causing some print overflow classes to be applied to the body which is locking the page scroll 
GD-128
> fix: bottom CTA global event on desktop

- src/components/Contentful/ButtonWrapper.vue
- src/components/Contentful/DynamicHeroClassic.vue
- src/components/Contentful/DynamicRichText.vue
- src/plugins/kv-analytics-plugin.js
- src/util/contentful/richTextRenderer.js
- tailwind.purge.safelist.txt
* Refactor button handling in DynamicHeroClassic
* Add new component
* Enable buttons to be rendered from contentful, inside of both RTF's and as items in content with support for global event handlers (like openMonthlyGoodSelector)
Sample page that uses buttons inside RTF's - /design
Sample using buttons as content items /lp/homepage-classic
VUE-713
> feat: contentful button wrapper component

- src/components/LoanCards/KivaClassicBasicLoanCard.vue
Tracking event needed to be updated after CTA text was changed.
> updating tracking event after CTA text uwas changed

- .dockerignore
- .github/workflows/run-ui-tests.yml
- package.json
- test/e2e/plugins/index.js
- test/e2e/specs/AutolendingMessagingPage.spec.js
- test/e2e/specs/AutolendingPage.spec.js
- test/e2e/specs/Example.spec.js
- test/e2e/specs/HeaderNavigation.spec.js
- test/e2e/support/index.js
- test/mergeCoverage.js
This changes the cypress testing to run against a real instead of mocked environment, and also removes the cypress test from the pull request checks. Cypress testing will now be run in Jenkins. 
The coverage drop is expected, because the Cypress tests aren't running in github anymore.
The commented code will be cleaned up in VUE-704 and VUE-707.
> VUE-702 Convert Cypress to run in real env without a mocked server

- src/components/Contentful/StoryCard.vue
I had to try several different ways of setting the eslint comment, but this finally worked for me locally
> fix: Use html comment to disable max-length lint check for data uri

- src/components/Contentful/MediaItemsCentered.vue
- src/pages/ContentfulPage.vue
[Core-48](https://kiva.atlassian.net/browse/CORE-48)
Partner logos section
**Mobile:** 
**Tablet:** 
**Desktop:**
>  Core-48 Centered partner logos fed from contentful.

- .dockerignore
This allows unit tests to be run when building docker images.
> ci: let __mocks__ folder be included in docker images for unit testing

- src/App.vue
The previous 100% height fix could have problems once you scrolled the page down and then turned on dark mode toggle. This appears to fix that and keeps the minimum page height of 100%.
> typography: ensure #app fills the full screen height

- .husky/commit-msg
- commitlint.config.js
- package-lock.json
- package.json
Enforces conventional commit messages for those with husky hooks installed (run `npx husky install` in the ui repo to do that if you haven't already). If the commit message does not follow the conventional commits format, the commit will not happen and an error like this will be displayed:
```bash
> git ci -m 'not a valid commit message'
⧗   input: not a valid commit message
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
husky - commit-msg hook exited with code 1 (error)
```
> build: enable commitlint for project commits VUE-757

- src/pages/Homepage/DefaultHomepage.vue
- src/pages/Homepage/LendByCategoryHomepage.vue
- src/util/contentfulUtils.js
* removed processContent and determineResponsive image size functions
VUE-814
> refactor: remove deprecated contentfulUtils

- .github/workflows/release-workflow.yml
- .github/workflows/run-ui-tests.yml
- .github/workflows/storybook-to-gh-pages.yml
- .releaserc.json
- Jenkinsfile
- README.md
- deploy/charts/templates/deployment.yaml
- src/components/Styleguide/StyleguideIntro.vue
This will only be merged after the `master` branch has been renamed `main`. GitHub will automatically switch the base for this and other pull requests after the renaming. See https://github.com/github/renaming#renaming-existing-branches for more details about how Github handles renamed branches.
> support for switching default branch name to `main`

- .github/workflows/release-workflow.yml
Need to use a token that is allowed to push to protected branches to avoid errors during the release action. This technically allows the branch protection rules to be bypassed by anyone with write access to the repo. However, we don't hand out write access to many people, and actually bypassing branch protections takes determined effort (a new workflow is required to be made, configured with this new token, and it needs to run git push commands). Pull requests from outside contributors won't be able to run actions, so there is no concern there.
> build: update token for release

- src/components/BorrowerProfile/LoanDescription.vue
- src/components/BorrowerProfile/PreviousLoanDescription.vue
[Core-251](https://kiva.atlassian.net/browse/CORE-251)
On the borrower profile, I've added a link to a borrower's previous loan if there's a previousLoanId related to a loan. Tracking task Core-274 included in these changes.
> feat: core-251 adding previous loan link to borrower profile

- src/components/BorrowerProfile/DetailsTabs.vue
- src/components/BorrowerProfile/MoreAboutLoan.vue
Following up on an email from Google's search console today, 
```
Content wider than screen
We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.
```
This doesn't fix the root problem, something's odd with the content coming in and adding a bunch of `&nbsp;`
but it does prevent the layout from breaking in those cases.
https://www.kiva.org/lend-beta/2272570
> fix: prevent content from breaking mobile layout

- src/components/BorrowerProfile/DetailsTabs.vue
- src/components/BorrowerProfile/TrusteeDetails.vue
[Core-185](https://kiva.atlassian.net/browse/CORE-185)
We had the trusteeName in a spot where we actually wanted borrowerName. I've added name to the graphql query and passed the data into TrusteeDetails.vue to be rendered.
Corrected text now reads "Why are you endorsing Alan?"
> fix: core-185 replacing borrowerName with TrusteeName

- src/components/BorrowerProfile/TrusteeDetails.vue
[Core-316](https://kiva.atlassian.net/browse/CORE-316)
Small formatting fix for a couple stats in the No Trustee tab of the borrower profile, Just added comma formatting. 
1000 -> 1,000
> fix: core-316 simple formatting on numBorrowers & numDefaultedLoans

- src/server-entry.js
Fixes `Error: Redirected when going from "/" to "/register/social" via a navigation guard` by catching and ignoring it, as recommended in solution 2.1 of https://stackoverflow.com/a/65326844
> fix: catch redirection errors from router.push

- .storybook/stories/15years.stories.js
- .storybook/stories/BorrowerProfile.stories.js
- .storybook/stories/CorporateCampaign.stories.js
- .storybook/stories/GetStarted.stories.js
- .storybook/stories/MGCovid19Response.stories.js
- .storybook/stories/SecuritySettings.stories.js
- .storybook/stories/TwelveDaysCalendar.stories.js
Really not sure why this is happening but there's tons of console errors that look like
Renaming from Pages to Page makes them all disappear 🤷
> docs: workaround storybook console errors when stories are named Pages

- config/dev-vm.js
- config/dev.js
- config/index.js
- config/stage.js
- server/auth-router.js
- server/live-loan-router.js
- server/util/fakeAuthentication.js
- server/util/live-loan/live-loan-fetch.js
- server/util/log.js
- src/api/Auth0Link.js
- src/api/HttpLink.js
- src/api/apollo.js
- src/client-entry.js
- src/server-entry.js
- src/util/KvAuth0.js
- test/unit/specs/util/KvAuth0.spec.js
Allows for faking authentication in development and testing. If this fake authentication is attempted in environments that do not allow it (like prod) there will be odd behavior, like the login sync not happening and baskets being lost, but no protected information will be exposed by the api.
> feat(auth): set dev graphql query params when fake authentication cookie is present

- src/util/contentful/richTextRenderer.js
VUE-916
Our custom richTextRenderer was causing a 500 error, when processing a rich text field with no content
> fix: richTextRenderer should handle undefined content more gracefully

- package-lock.json
- package.json
- src/components/BorrowerProfile/FieldPartnerDetails.vue
- src/components/BorrowerProfile/JumpLinks.vue
- src/components/BorrowerProfile/LendCta.vue
- src/components/BorrowerProfile/LendersAndTeams.vue
- src/components/BorrowerProfile/PreviousLoanDescription.vue
- src/components/BorrowerProfile/RepaymentSchedule.vue
- src/components/Kv/KvExpandableQuestion.vue
- src/components/LoanCards/KivaClassicBasicLoanCard.vue
- src/components/LoanCards/WhySpecial.vue
- src/components/WwwFrame/LendMenu/LendListMenu.vue
- src/components/WwwFrame/LendMenu/LendMegaMenu.vue
- src/components/WwwFrame/TheHeader.vue
- src/components/WwwFrame/WwwPageDesign.vue
- src/pages/Borrow/BorrowIntro.vue
Adds a width and height classes to all `<kv-material-icon>`s.  If a width and height class aren't specified Safari lets the SVG icon take all available space, where Chrome and Firefox use the SVG's intrinsic size. 
Brings in latest kv-components which has these same fixes.
Fixes stuff like this happening on Safari (mobile and desktop I believe)
> kv-material-icon Safari fixes

- package-lock.json
- package.json
1.3.1 (2022-01-11)
Bug Fixes
allow buttons to inherit font weights (593b28f)
> chore: pull in latest kv-tokens

- src/components/BorrowerProfile/RepaymentSchedule.vue
[Core-148](https://kiva.atlassian.net/browse/CORE-148) These changes get the mobile view of the repayment schedule in place.
[Figma spec](https://www.figma.com/file/EI9I5sR9mATRxIV8hBWKwm/Repayment-Schedule---Borrower-Profile-v2-Nov.2021%5BNT%5D?node-id=1%3A8)
A few different versions of this to take a look at. 
**Loan payment incoming:**
**Loan payment made**
**Loan payment deliquent**
> feat: core-148 mobile view of repayment schedule

- src/pages/Homepage/Homepage.vue
GD-205
~~Is this the best approach for this?~~
~~Unfortunately, this loads the homepage, then the created hook will redirect to the landing page. I could not find a way to avoid this. Trying to handle the experiment in preFetch doesn't work because the experiment depends on the user being on mobile, which the server does not know about in preFetch.~~
When the homepage loads, if new user and is mobile, assign the experiment, fire the event and redirect to '/lp/causes/' if experiment version is shown
On repeated visits, we can read the session cookie and redirect in the preFetch to avoid having to load the homepage. This should work as expected since only  eligible users should have the experiment assignment.
If a user is assigned to the experiment and they sign up (becoming a known user) …
> feat: causes homepage redirect experiment

- src/components/Contentful/StoryCard.vue
- src/util/contentfulUtils.js
GD-208
Supports 'right', 'center', 'left'. Content type changes in contentful dev, will add to production when this gets merged in. 
Examples:
> feat: allows StoryCards to be aligned with contentful field

- src/components/BorrowerProfile/RepaymentSchedule.vue
- src/components/BorrowerProfile/SummaryCard.vue
During QA of the loan bookmark functionality I discovered an overlap issue I was causing by absolutely positioning an element. 
**Issue:**
I removed the absolute positioning and handled the spacing with a 'tw-ml-auto'. 
**Fixed**
> feat: core-151 fixing bookmark placement for large screens

- src/components/BorrowerProfile/LoanBookmark.vue
- src/components/BorrowerProfile/SummaryCard.vue
In my code review yesterday, I was testing on a loan who's location and activity were so long it pushed my bookmark into the right place like this.
Once things got up to dev, I realized that I forgot to set the 'tw-w-full' class on the parent component allowing it to take up the full width of the container and then giving space for my 'tw-ml-auto' on the bookmark component.to work.
**Error state:**
**After 'tw-w-full' class is added:** FIXED
> fix: core-151 setting width to full, so margin can have space

- src/components/Contentful/DynamicHeroClassic.vue
GD-199
Takes a uiSetting object like:
```
"video": {
"autoplay": true,
"muted": true
}
```
Default for component if setting is missing is our previous options of autoplay true and mute true. if Options are not default display the video controls (So user can mute video and/or click play)
TODO: 
Add to Setting details to: `admin-component-reference`
Add these changes to component in `cms-page-server`
Important note: _In some browsers (e.g. Chrome 70.0) autoplay doesn't work if no muted attribute is present._
> feat: add video options for dynamicHeroClassic

- src/components/BorrowerProfile/DetailsTabs.vue
During QA of the repayment schedule Lauren happened to look at a "Funded" loan in development while being logged out, in that situation she was getting this result, as the check to show the repayment schedule was only looking at the loans "anonymizationLevel".
[Loan](https://www.dev.kiva.org/lend-beta/2293062) 
So I was showing the repayment schedule but no data was coming through for it.  
I compared the older borrower profile, logged in and logged out states and noticed that for funded loans we were only showing the repayment schedule while being logged in. 
The check I've now put in place: 
```
displayRepaymentSchedule() {
// check anonymization of loan, if it's not set to
// full anonymization, continue
if (this.loan.anonymizationLevel !== 'full') {
// if loan is fundraising, always …
```
> Core 148 fix

- src/api/ExperimentIdLink.js
This `ml_loan_to_loan` key was initially used for testing and is not currently being used for analysis.
> chore: remove ml_loan_to_loan exp link entry

- src/components/WwwFrame/WwwPageCorporate.vue
Fixes this on the managed lending page:
> fix: prevent carousel slides from floating above the CC header

- src/components/WwwFrame/LendMenu/LendListMenu.vue
- src/components/WwwFrame/LendMenu/LendMegaMenu.vue
[Core-218](https://kiva.atlassian.net/browse/CORE-218)
There will be more changes coming related to this ticket in the other repos, this covers the changes for /kiva/ui.
Text change from "Starred loans" -> "Saved loans"
> fix: core-218 updating Starred loans -> Saved loans in lend menu

- src/components/BorrowerProfile/LoanStory.vue
This has been bugging me for a while and affects all viewports.
Prod Broken:
Fixed:
> fix: bump spacing between borrower image and name in LoanStory component

- src/components/Contentful/StoryCard.vue
- src/util/contentfulUtils.js
ACK-206
Allows for a layout similar to the one in ACK-206 ticket. Cards with link can be put into card rows. they will be the height of the background image. Analytics is also supported. 
We'll be reusing the StoryCard 'link' field for mobile needs as well (will support a deep link for mobile)
See sample cards at bottom of:  `/lp/eddie-test-page`
> feat: clickable imageCard theme story cards

- src/components/MonthlyGood/AlreadySubscribedNotice.vue
- src/components/Settings/SubscriptionsSettingsCards.vue
- src/graphql/query/thanksPage.graphql
- src/pages/AutoDeposit/AutoDepositLandingPage.vue
- src/pages/LandingPages/MGCovid19/MGCovid19.vue
- src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
- src/pages/MonthlyGood/MonthlyGoodSetupPage.vue
- src/pages/Thanks/ThanksPage.vue
ACK-219
ACK-220
I tested all instances of this. 
We're now doing this in quite a few places. A future improvement would be better to centralize all this business logic somewhere. Maybe straight from the API? my.userAccount.isEligibleForMonthlyGood or maybe a local resolver of some sort?
> feat: restrict Causes users from seeing MG and AD signups

- src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
- src/pages/MonthlyGood/PersonalizedMonthlyGoodLandingPage.vue
- src/router/routes.js
[Core-399](https://kiva.atlassian.net/browse/CORE-399) EXPERIMENT TICKET
- Added a new uiexp to settingsManager in Admin. 
- Created new page with <www-page> component.
[Core-398](https://kiva.atlassian.net/browse/CORE-398) TRACKING TICKET
- Added the EXP to the MonthlyGoodLandingPage.vue file
- If EXP is active and user is in group B -> direct users to new PersonalizedMonthlyGoodLandingPage.vue where the Tracking is fired in the mounted hook currently (I can move this to a read query if wanted)
- If EXP is active and user is in group A -> leave user on /monthlygood and fire tracking for group A.
> feat: core-399 Monthlygood appeal personalized experiment setup

- src/components/WwwFrame/WwwPage.vue
- src/components/WwwFrame/WwwPageCorporate.vue
- src/components/WwwFrame/WwwPageMinimal.vue
- src/pages/15Years/15Years.vue
- src/pages/Autolending/AutolendingPage.vue
- src/pages/Build/BuildPage.vue
- src/pages/Build/CodeOfConductPage.vue
- src/pages/Build/DataPage.vue
- src/pages/Build/DocsPage.vue
- src/pages/Build/GettingStartedPage.vue
- src/pages/Build/Research.vue
- src/pages/Build/TermsOfService.vue
- src/pages/ContentfulPage.vue
- src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
- src/pages/LendingStats/LendingStatsPage.vue
- src/pages/Settings/EmailSettings.vue
- src/pages/Settings/PaymentSettings.vue
- src/pages/Settings/SecuritySettings.vue
- src/pages/Settings/SettingsPage.vue
- src/pages/Settings/SubscriptionsSettings.vue
- src/pages/Settings/TwoStepVerificationPage.vue
- src/util/contentfulUtils.js
- test/unit/specs/util/contentfulUtils.spec.js
The latest header and footer do not theme via a theme object like before, since they use the new themable tailwind colors. This PR just removes those objects which aren't doing anything on prod right now. For example http://www.kiva.org/build does not have a green header.
If we'd like to make theming the header/footer an option again, a way to do it would be to wrap whatever needs to be themed with a `kv-theme-provider` component and then pass either a predefined theme from kv-tokens/kivaColors to it, or a custom one.
roughly
```
import {
defaultTheme, darkTheme, darkGreenTheme, mintTheme,
} from '@kiva/kv-tokens/configs/kivaColors.cjs';
data() {
darkGreenTheme
}
<kv-theme-provider :theme="darkGreenTheme"><the-header /></kv-theme-provider>
```
> refactor: remove unused theme props

- src/components/LoanCards/Buttons/ActionButton.vue
- src/components/LoanCards/Buttons/CheckoutNowButton.vue
- src/components/LoanCards/Buttons/Lend25Button.vue
- src/components/LoanCards/Buttons/LendAgainButton.vue
- src/components/LoanCards/Buttons/LendButton.vue
- src/components/LoanCards/Buttons/LendIncrementButton.vue
- src/components/LoanCards/GridLoanCard.vue
- src/components/LoanCards/HoverLoanCard/DetailedLoanCard.vue
- src/components/LoanCards/HoverLoanCard/HoverLoanCardLarge.vue
- src/components/LoanCards/LendHomepageLoanCard.vue
- src/components/LoanCards/ListLoanCard.vue
- src/components/LoanCards/PromoGridLoanCard.vue
ACK-229
Applies Kiva Classic styling to the "Lend" buttons. 
Pages affected:
/lend-by-category/women (And all other categories)
/lend-by-category
/lend/filter
/cc/groupon (and other corporate campaign pages)
There may be other pages? It's pretty hard to track down these buttons in a maze of loan card controllers and dynamic components...
I double checked with design about the new design of the "Checkout Now" button. and also the removal of the "Adding to basket" text displayed while loading.
A picture is worth 1000 words so here are the screenshots:
> feat: kiva classic lend now and lend 25 buttons

- src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
- src/pages/MonthlyGood/PersonalizedMonthlyGoodLandingPage.vue
[Core-439](https://kiva.atlassian.net/browse/CORE-439)
Made the cta box on the monthly good pages darker to pass accessibility tests.
> feat: core-439 fixing opacity in monthly good cta boxes

- src/pages/ContentfulPage.vue
- src/pages/Homepage/Homepage.vue
ACK-249
Since we no longer need to check this on the client, we can do the experiment assignment in prefetch and route accordingly. Also added a check for the experiment on Contentful page. This will allow the tracking event to fire for users who are in the shown group when they get rerouted to lp/causes. 
ACK team wants this hotfixed asap to try to increase the rate at which users are funnelled into the experiment to gather statistical significance
> feat: modifies cause hp experiment to include non mobile users as well.

- src/pages/MonthlyGood/PersonalizedMonthlyGoodLandingPage.vue
Lauren noticed that there was a typo in one of the headings on /monthlygood/personalized. That revealed that the connection to the contentful piece wasn't quite connected properly. This change fixes that connection as well as fixes a typo in the fall back text.
> fix: core-400 altering contentful to read subHeadline instead of Headline

- src/server-entry.js
Because the domain was not defined, fake authentication was never allowed.
> fix(FakeAuthentication): set auth domain from server entry

- src/pages/MonthlyGood/PersonalizedMonthlyGoodLandingPage.vue
The personalized mg page we're testing was a duplicate of the existing landing page. These `deep` styles help the hero image scale across larger viewports.
> fix: replicate deep styles for mg hero contentful image

- src/App.vue
- src/pages/Homepage/Homepage.vue
- src/plugins/unbounce-event-mixin.js
- src/router/routes.js
ACK-223
I wasn't  sure about the best place to put the unbounce trigger to make sure it loads every time for the selected routes. So added it to App.vue created lifecycle hook.I had some trouble getting it to work in client-entry on initial page ssr load. 
See ticket for list of routes this should be added to.
> feat: add unbounce capture to additional routes

- src/graphql/query/loanChannelPage.graphql
- src/pages/Lend/LoanChannelCategoryControl.vue
- src/pages/Lend/LoanChannelCategoryExperiment.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
ACK-227
Refactor `src/pages/Lend/LoanChannelCategoryPage.vue` to be a basic wrapper component containing the page frame, add to basket interstitial and the new component which is the page layout. We'll eventually get our experiment value here and toggle layouts. 
Page layout hard coded to `control` for now. No substantial changes to control layout, except for removing the add to basket interstitial experiment code and moving that up to the page wrapper
> refactor: allow lbc/category template to have multiple page layouts

- src/App.vue
This was causing the re-rendering issue in the browser. When checking if the page was server rendered, Vue checks if the element being mounted has the data attribute that the vue server renderer applies. If that attribute isn't present, the entire page is re-rendered. That attribute is applied automatically to the root element of the root component (App.vue), and in client-entry.js we mount the element with the id "app". So when kv-theme-provider was added as a wrapper around #app, #app was no longer the root element of App.vue, meaning it didn't get the ssr data attribute, and therefore Vue re-rendered the entire app. kv-theme-provider was later replaced with a div, though it could have been removed, leaving just the #app div. This PR removes the wrapping div and the extra flexbox styles …
> fix: for proper mounting after ssr App.vue root element must have id `app`

- src/components/WwwFrame/LendMenu/LendListMenu.vue
- src/components/WwwFrame/LendMenu/LendMegaMenu.vue
Found several links in the LendMenu's that weren't triggering their click events. This seems to work. Also, I realize the `.native` modifier is a Vue2 construct and won't transfer to Vue3.
> fix: ensure link tracking is active on router-links

- src/pages/Lend/LoanChannelCategoryPage.vue
ACK-271
This will be hotfixed out. Hoping to release all of main. 
Removes `kiva-u-s` from this  experiment. I kept the image asset and category specs for `kiva-u-s`  incase it needs to be added back in in the future.
> feat: remove kiva us from lbc page experimental layout

- src/components/BorrowerProfile/JumpLinks.vue
- src/components/BorrowerProfile/LoanUse.vue
- src/components/BorrowerProfile/SummaryCard.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
ACK-273
The goal of this work is to make the profile page previews look like:
> feat: enhance borrower profile meta previews

- src/components/Checkout/KivaCardRedemption.vue
**Ticket:**
[https://kiva.atlassian.net/jira/software/projects/CORE/boards/248?selectedIssue=CORE-376](https://kiva.atlassian.net/jira/software/projects/CORE/boards/248?selectedIssue=CORE-376)
**Steps to test:**
1. Login
2. Go to http://localhost:8888/checkout
3. Resize the screen to 320px
4. Open the "Have a Kiva card ?" option
5. Each one of the 3 elements should be in it's own row like is shown in the figma design [https://www.figma.com/file/KHkcWqBeHNuPIxLifrkUkg/Checkout-2021---Kiva-Classic-%5BJoice.Aug.2021%5D?node-id=665%3A2028](https://www.figma.com/file/KHkcWqBeHNuPIxLifrkUkg/Checkout-2021---Kiva-Classic-%5BJoice.Aug.2021%5D?node-id=665%3A2028)
> fix: mobile styles for kiva card updated

- src/graphql/query/lendMenuData.graphql
The `experiment` resolver `id` argument is not meant to include the `Experiment` typename. This caused the version to always resolve to `null` because the experiment setting could not be found.
> fix: type name should not be part of id argument MARS-89

- src/components/LoanCards/KivaClassicBasicLoanCard.vue
- src/components/LoanCards/KivaClassicBasicLoanCardBundleExp.vue
- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- src/util/loanUtils.js
This delays loading the home page loan card data until the loan cards have entered the viewport, reducing the initial time-to-interactive, especially for mobile browsers.
> perf: lazy-loading for homepage loan cards MARS-74

- server/sitemap/generators/contentful-pages.js
Request came in Friday afternoon to not include these routes in the sitemap initially.
> fix: remove /lp/* routes from the sitemap

- src/pages/Lend/LoanChannelCategoryControl.vue
This fix prevents `Loan Channel Category` meta title from being overwritten by  `Loan Channel Category Control `child component.
> fix: category control component overwriting meta title

- src/components/LoanCards/Buttons/ActionButton.vue
- src/components/LoanCards/Buttons/LendAmountButton.vue
- src/components/LoanCards/Buttons/LendButton.vue
- src/components/LoanCards/GridLoanCard.vue
- src/components/LoanCards/HoverLoanCard/DetailedLoanCard.vue
- src/components/LoanCards/HoverLoanCard/HoverLoanCardLarge.vue
- src/components/LoanCards/LoanCardController.vue
- src/components/LoansByCategory/FeaturedHeroLoan.vue
this PR updates Lend by Category loan cards to use the `LendAmountButton` when there is <$25 less to be funded on a single loan. this PR also:
* updates tracking for `LendAmountButton`
* removes `amountLeft` computed prop since it now is coming from the parent component(s)
* updates `amountLeft` computed prop on `LoanCardController` such that a negative value is never returned, fixing progress meters that display a negative amount
> feat: update LBC to accommodate less than 25 lend button + add tracking

- src/components/Kv/KvLoadingPlaceholder.vue
Small css change to improve place holder animation on KvLoadingPlaceholder component
https://user-images.githubusercontent.com/102815442/165628944-f79a27c9-bdce-4785-a6d5-6c40566af40b.mp4
> feat: use transform/translate instead left for place holder animation

- .storybook/stories/ListLoanCard.stories.js
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/LoanCards/ListLoanCard.vue
- src/components/LoanCards/LoanCardController.vue
https://kiva.atlassian.net/browse/VUE-1008
- Added new prop to enable rounded corners on loan card
- Added true to new filter alpha
- Added stories for loan card variations
Without rounded (default)
With rounded
> feat: added property to enable rounded corners on the list loan card

- src/api/localResolvers/loanSearch.js
- src/api/localSchema.graphql
- src/graphql/query/loanSearchState.graphql
- test/unit/specs/api/localResolvers/loanSearch.spec.js
This may prove to be a temporary construct, but for now it provides a place to hold, way to transport and subscribe to changes of a generic search state object. It will need to be kept in sync with any/all filters we may use across the standard `lend > loans` and `flss` queries.
> Vue 1006 basic loan search state

- src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBannerCircular.vue
> fix: remove extra margins on collapsed banner state

- src/components/WwwFrame/LendMenu/TheLendMenu.vue
- src/graphql/query/lendMenuData.graphql
- src/graphql/query/wwwHeader.graphql
Removing code from Lend Menu experiment that ordered categories' list depending on a setted weight in Admin, leaving categories sorted by name (winning version).
> refactor: remove code from lend menu experiment

- src/router/routes.js
This feature:
- adds a new route for new `/gender-equality` Contentful page
- redirects `/lp/own-the-chang-gender-equality` to `/gender-equality` route.
[MARS-110](https://kiva.atlassian.net/browse/MARS-110?atlOrigin=eyJpIjoiZTE2YjQyZTQ4N2JmNDA0NzgwYWFhOGFlMTFjNDBiODkiLCJwIjoiaiJ9)
> feat: create gender-equality route and redirect own-the-chang-gender-equality to this new route

- src/pages/ContentfulPage.vue
Fix calling `trackExperimentVersion` in mounted hook instead of calling it in `prefetch` function that caused an internal error.
> fix: call trackExperimentVersion in mounted hook

- src/util/loanSearchUtils.js
- test/unit/specs/util/loanSearchUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1070
- Theme filter options are still sourced from lend API, but they are now filtered using case insensitive matching against the FLSS loan results
- There were casing differences between lend and FLSS APIs
- Also added case insensitive matching to ISO codes just in case
> fix: filters now transformed case insensitive

- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/util/loanSearchUtils.js
- test/unit/specs/util/loanSearchUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1050
https://kiva.atlassian.net/browse/VUE-1034
- `?gender=female` will now pre-set the gender filter
- This changeset also resolves the ticket of keeping filter state consistent between desktop + mobile filter components
- Work needed to get other filters to behave similarly
> feat: pre-set the gender filter using the query string param

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/router/index.js
- src/router/routes.js
- src/util/loanSearchUtils.js
- test/unit/specs/util/loanSearchUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1045
- Gender filter now updates the query string params
- Updated router to allow an optional param to prevent auto-scroll to top when route changes
- Using the browser back/forward buttons also now apply the gender filter
> feat: update query string when filters change

- .storybook/stories/LoanSearchGenderFilter.stories.js
- .storybook/stories/LoanSearchSortBy.stories.js
- src/api/localResolvers/loanSearch.js
- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/components/Lend/LoanSearch/LoanSearchGenderFilter.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/Lend/LoanSearch/LoanSearchSortBy.vue
- src/graphql/query/loanFacetsQuery.graphql
- src/util/loanSearchUtils.js
- test/unit/specs/components/Lend/LoanSearch/LoanSearchGenderFilter.spec.js
- test/unit/specs/components/Lend/LoanSearch/LoanSearchSortBy.spec.js
- test/unit/specs/util/loanSearchUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1052
https://kiva.atlassian.net/browse/VUE-1047
- The sortBy filter can now be initialized via the query param
- Changing the sortBy filter now gets applied to the query params
- Added filter validation against available facets before the search state is stored
- Filter validation ensures that bad values in the query params don't result in empty searches
- Bad values result in default filter values being used instead for the problem query param(s)
- Consolidated all interactions with the search state to `LoanSearchInterface` for easier maintenance
- Added `TODO` placeholders for clarity for where future query params can be added
- While not absolutely necessary due to the simple filter options, pulled gender options from the API
- Added `queryType` to …
> Vue 1052 initialize the page with a sort by option when the query param is present on page load

- package-lock.json
- package.json
This adds the change to KvCarousel that hides the control arrows when there is only one slide.
> chore(deps): upgrade @kiva/kv-components to v3.0.5

- src/components/LoanCards/KivaClassicBasicLoanCard.vue
This typo causes the 'view loan' button to not render and to not be interactive.
> fix: typo in tag name

- .storybook/stories/KvCheckboxList.stories.js
- .storybook/stories/LoanSearchSectorFilter.stories.js
- .storybook/stories/LoanSearchThemeFilter.stories.js
- src/components/Kv/KvCheckboxList.vue
- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/Lend/LoanSearch/LoanSearchSectorFilter.vue
- src/components/Lend/LoanSearch/LoanSearchThemeFilter.vue
- src/graphql/query/flssLoanFacetsQuery.graphql
- src/util/flssUtils.js
- src/util/loanSearchUtils.js
- test/unit/specs/components/Kv/KvCheckboxList.spec.js
- test/unit/specs/components/Lend/LoanSearch/LoanSearchSectorFilter.spec.js
- test/unit/specs/components/Lend/LoanSearch/LoanSearchThemeFilter.spec.js
- test/unit/specs/util/flssUtils.spec.js
- test/unit/specs/util/loanSearchUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1051
https://kiva.atlassian.net/browse/VUE-1046
- Sector filter can now be initialized via the query param
- Handles both FLSS/legacy "1,2" and Algolia "Arts~Agriculture" formats
- Algolia format will be replaced with the new FLSS format after page load
- Changing the sector filter now populates the query param
- `KvCheckboxList` selection can now be changed via a prop
- Fixed issue where `updateSearchState` could be comparing the wrong objects
Update: https://kiva.atlassian.net/browse/VUE-1044
- Theme filter can now be initialized via the query param
- Handles both FLSS/legacy "1,2" and Algolia "Rural Exclusion~Conflict Zones" formats
- Algolia format will be replaced with the new FLSS format after page load
- Changing the theme filter now populates …
> VUE-1051, VUE-1046, VUE-1044

- src/components/CorporateCampaign/CampaignLoanRow.vue
On `www.kiva.org/cc/sage` on first page load the loan carousel would not scroll right. Taking an action to reinit the embla carousel would fix the issue, such as: 
- resizing the page
- modifying filters
- switching to grid display then back to row
I narrowed down the issue to `this.embla.slidesInView(true)` returning an incorrect value in KvCarousel when the page loads. (It returns 16, aka, all the loans as in view on page load). 
At first I thought it was a timing issue and tried various $nextTick and modifying some code to make sure the carousel isnt loading until after the loans. None of this worked. 
I now believe this could just be an issue with embla and browser rendering. It really struggles to calculate the size of the carousels with the combination of `display:flex` and `width: …
> fix: fixes campaign page loan carousel not scrolling on page load

- src/plugins/braintree-dropin-error-mixin.js
https://kiva.atlassian.net/browse/FIN-693
Seemed simple enough not to trouble you with it! But I would appreciate anything that's off here. Via linting I needed to use the `'` style quote here.
> feat: changed Braintree dropin error content to include support email

- .storybook/stories/KvSectionModalLoader.stories.js
- src/components/Kv/KvSectionModalLoader.vue
- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- test/unit/specs/components/Kv/KvSectionModalLoader.spec.js
https://kiva.atlassian.net/browse/VUE-1032
https://kiva.atlassian.net/browse/VUE-1072
- Created new `KvSectionModalLoader` component that displays a green `KvLoadingSpinner` centered horizontally slightly below the top of the relative parent, with a white slightly transparent background
- Replaced last CSS section with Tailwind JIT classname
- Fixed constrained filter width in mobile view
- Updated `LoanSearchInterface` to use `Promise.all` for graphql queries that aren't interdependent
Initial load:
Filter change:
Mobile filters now full width:
> Vue 1032 add loading state overlay for loan section of the page

- src/pages/BorrowerProfile/FundedBorrowerProfile.vue
Change from `Support these loans for ${sectorName}”` to `“Support these ${sectorName} loans"` for better understanding
> style: change heading for sector loans row

- src/util/contentfulUtils.js
- test/unit/fixtures/CorporateCampaignContentfulPageRaw.json
- test/unit/specs/util/contentfulUtils.spec.js
This change adds `pageDescription` and `canonicalUrl` fields to `contentfulObject`.
> feat: add page description to contentful utils

- src/components/Kv/KvCheckboxList.vue
- src/components/Lend/LoanSearch/LoanSearchGenderFilter.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/Lend/LoanSearch/LoanSearchLocationFilter.vue
- src/components/Lend/LoanSearch/LoanSearchSectorFilter.vue
- src/components/Lend/LoanSearch/LoanSearchSortBy.vue
- src/components/Lend/LoanSearch/LoanSearchThemeFilter.vue
- test/unit/specs/components/Kv/KvCheckboxList.spec.js
https://kiva.atlassian.net/browse/VUE-1074
https://kiva.atlassian.net/browse/VUE-1075
https://kiva.atlassian.net/browse/VUE-1076
https://kiva.atlassian.net/browse/VUE-1077
https://kiva.atlassian.net/browse/VUE-1078
https://kiva.atlassian.net/browse/VUE-1079
- Added loan results/hits analytics
- Added gender filter analytics
- Added sort by analytics
- Added location filter analytics
- Added sector filter analytics
- Added theme filter analytics
- `KvCheckboxList` now emits more change event data to allow analytics to be more detailed
> Vue 1074 setup and fire the loans shown event on every loan query execution

- .storybook/stories/KvPager.stories.js
- src/api/localResolvers/loanSearch.js
- src/api/localSchema.graphql
- src/components/Kv/KvPager.vue
- src/components/Lend/LoanSearch/LoanSearchGenderFilter.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/graphql/mutation/updateLoanSearchState.graphql
- src/graphql/query/flssLoansQuery.graphql
- src/graphql/query/loanSearchState.graphql
- src/util/flssUtils.js
- src/util/loanSearchUtils.js
- src/util/numberUtils.js
- test/unit/specs/api/localResolvers/loanSearch.spec.js
- test/unit/specs/components/Kv/KvPager.spec.js
- test/unit/specs/util/flssUtils.spec.js
- test/unit/specs/util/loanSearchUtils.spec.js
- test/unit/specs/util/numberUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1033
https://kiva.atlassian.net/browse/VUE-1059
- Implemented new `KvPager` component
- The existing `KvPagination` used the Vue router directly, both accessing the query params and pushing routes, so I created a new component without that dependency
- The new pager component is entirely tailwind and has the new arrow icons, but it retains the existing behavior (I fixed one edge case as well from the existing component)
- Added `pageOffset` and `pageLimit` to `loanSearchState`
- There are some conversions between offset and page number in the areas that need page numbers (FLSS + pager), but the state holds the more generic offset and limit values
- Created `numberUtils`, since I kept needing a simple method to check if a value is a number
> Vue 1033 implement loan pager component

- src/client-entry.js
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/util/loanSearchUtils.js
- test/unit/specs/util/loanSearchUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1086
- Added optional route param support (`noAnalytics`) to allowing skipping page view analytics
- Added hit counts to `loans-shown` event
> Vue 1086 adjust pageview loans shown events for filters

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/util/loanSearchUtils.js
- test/unit/specs/util/loanSearchUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1054
https://kiva.atlassian.net/browse/VUE-1049
- Query params now supports page
- Query param for page not added if page is "1"
- Simple validation added: checks for number above 0 (logged ticket for handling number above available pages)
> feat: page query param support

- src/graphql/query/checkout/upsellLoans.graphql
- src/pages/Checkout/CheckoutPage.vue
this PR updates the upsells module experiment to ensure we do not show reserved loans to users. if user A reserves the upsell module loan, other users will see a different loan instead. 
per: https://kivahq.slack.com/archives/C02TDSFQ551/p1655394514010749
> fix: do not show reserved loans for upsells on checkout

- src/components/Kv/KvPager.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/plugins/kv-analytics-plugin.js
- src/util/loanSearchUtils.js
https://kiva.atlassian.net/browse/VUE-1089
https://kiva.atlassian.net/browse/VUE-1090
https://kiva.atlassian.net/browse/VUE-1092
- Added click analytics to `KvPager`
- Added `$kvSetCustomUrl` to analytics plugin and called before `loans-shown` event -> testing yesterday in dev showed that the URL was not updated like expected after filter changes
- Removed `amountLeft` sort option since FLSS doesn't fully support that option yet
> Vue 1089 add click interaction on kv pager

- .storybook/stories/KvResultsPerPage.stories.js
- src/components/Kv/KvResultsPerPage.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/util/loanSearchUtils.js
- test/unit/specs/components/Kv/KvResultsPerPage.spec.js
- test/unit/specs/util/loanSearchUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1053
https://kiva.atlassian.net/browse/VUE-1093
https://kiva.atlassian.net/browse/VUE-1094
- Created new `KvResultsPerPage` component modeled after the existing Algolia component
- Couldn't use the old component because it was a wrapped Algolia component
- Resets to the first page when results per page changed, like existing component
- Added behavior of scrolling back to the top of the page when results per page changed
- We can remove the scroll behavior, but I thought the UX made sense, since the pager also scrolls
- Fixed potential edge case in pager
- Added 0 loan state
> feat: results per page component

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
https://kiva.atlassian.net/browse/VUE-1095
- Added missing analytics to zero loans reset
- Added `h3` to match newer styling
> feat: zero loans reset analytics

- src/util/loanUtils.js
update `isLoanFundraising` to return `false` for loans that are overreserved
> fix: accommodate overreserved loans

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
https://kiva.atlassian.net/browse/VUE-1092
https://kiva.atlassian.net/browse/VUE-1096
- Fixed issue where analytics URL wasn't updated when visible results matched previous search
- Fixed issue where changing a filter to reduce results would result in empty page if user was on page beyond new results
- Updated behavior to reset to first page when a new filter gets changed, like lend page
> feat: reset page offset when filtering, fixed analytics URL

- Developer_Tools.md
The GraphQL vscode extension has been taken over by VSCode and is not maintained by prisma anymore, updated links
> fix: update developer tools readme

- src/pages/Checkout/CheckoutPage.vue
fixes an issue on upsell loans where if a user tries to add a reserved loan, it will pull a new non-reserved loan for them as the upsell loan in their cart
> fix: error handling for upsell loans

- build/webpack.client.base.conf.js
This pr changes `webpack.client.base.conf.js` configuration file to ensure that modules are only loaded when they are actually used by the page.
> feat: increase number of allowed webpack chunks

- src/components/LoansByCategory/ViewToggle.vue
This pr fixes an error getting cache for `ViewToggle` component probably caused by the formatting of the url.
> fix: error getting cache for viewtoggle component

- src/components/CorporateCampaign/CampaignLogoGroup.vue
This makes all the corporate landing pages look better. The bottom logo was always getting distorted. 
Fix for MRKT-597, see slack
> fix: corporate campaign logo in footer distortion

- src/components/Checkout/SocialShareV2.vue
This pr changes `shareLink` function inside `SocialShareV2` component to add `inviterName`.
> fix: add inviter name to shareLink func

- package-lock.json
- package.json
- server/util/live-loan/live-loan-draw.js
`node-canvas` has a [known memory leak](https://github.com/Automattic/node-canvas/issues/1974) that occurs when `registerFont` is called multiple times. This PR changes our usage of `registerFont` to only happen on startup to avoid that memory leak. Additionally, this PR sets up a pool of canvases to be used and re-used for drawing loan cards to avoid the memory and cpu cost of creating a new canvas for every request.
> live loan drawing memory usage optimizations

- .storybook/preview.js
- .storybook/stories/LoanSearchFilterChips.stories.js
- src/components/Lend/LoanSearch/LoanSearchFilterChips.vue
- test/unit/jest.conf.js
- test/unit/setupJestMocks.js
- test/unit/specs/components/Lend/LoanSearch/LoanSearchFilterChips.spec.js
https://kiva.atlassian.net/browse/VUE-1100
- Added `LoanSearchFilterChips` unit tests and stories
- Added global `$kvTrackEvent` mocking for both tests and stories
- With this mocking, we can now spy on `$kvTrackEvent` (like in this PR) or usages will simply not break tests/stories
> feat: loan filter chips tests and stories

- package-lock.json
- package.json
- server/util/fetch.js
- src/api/HttpLink.js
Because we were providing a custom agent we weren't getting any of the optimized configurations (specifically keepAlive). We only needed the custom agent for allowing invalid VM certificates via `rejectUnauthorized`, and that can be controlled using [the `strictSSL` option](https://github.com/npm/make-fetch-happen#--optsca-optscert-optskey-optsstrictssl) instead.
> fix: use optimized default make-fetch-happen agent instead of custom agent

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/util/loanSearchUtils.js
- test/unit/specs/util/loanSearchUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1136
- Added extra query for all facets on mount
- It does lead to an extra render of the filters and an extra async call on mount, but otherwise we won't get the full list of available filters from FLSS for display
- Added a missing test case for `runFacetsQueries`
> fix: initial load has all facets regardless of query params

- package-lock.json
Ran `npx browserslist@latest --update-db`:
```
Latest version:     1.0.30001365
Installed version:  1.0.30001304
Removing old caniuse-lite from lock file
Installing new caniuse-lite version
$ npm install caniuse-lite
Cleaning package.json dependencies from caniuse-lite
$ npm uninstall caniuse-lite
caniuse-lite has been successfully updated
Target browser changes:
- and_chr 97
+ and_chr 103
- and_ff 95
+ and_ff 101
- android 97
+ android 103
- chrome 97
- chrome 96
+ chrome 103
+ chrome 102
+ chrome 101
- edge 97
- edge 96
+ edge 103
+ edge 102
- firefox 96
- firefox 95
+ firefox 102
+ firefox 101
- ios_saf 15.2-15.3
- ios_saf 15.0-15.1
+ ios_saf 15.5
+ ios_saf 15.4
- opera 82
- opera 81
+ opera 86
+ opera 85
- safari 15.2-15.3
- safari 15.1
- safari 14.1
+ safari 15.5
+ safari 15.4
- …
```
> chore(deps-dev): update browsers list db

- lighthouserc-prod.js
This uses the live-loan redirect url add the fundraising borrower profile to the lighthouse monitoring
> feat: track lend-by-category and borrower profile page performance

- src/App.vue
Found this warning in lighthouse reports:
Followed this guide to add this preconnect https://crenshaw.dev/preconnect-resource-hint-crossorigin-attribute/
> fix: additional preconnect for anonymous crossorigin requests

- lighthouserc-prod.js
Latest lighthouse build failed with a 403 forbidden error that seemed to occur because the loan was funded. Hoping that this resolves that issue for now by looking at newest loans only. A future improvement I am planning is to get the loan id with a separate js function and then go directly to `/lend-beta/<loan id>` or `/lend/<loan id>` instead of going through the live loan redirect.
> fix: lighthouse run fails when loan is funded, use newest sort instead

- src/pages/Categories/CategoriesBeta.vue
ACK-341
Added tracking for experiment
@galen94 Just FYI -- this is how this will work, user attempts to go to `/categories` which is handled by our legacy php server, that server then assigns that user to an a/b testing variant. And will either render the legacy /categories page or set a cookie and redirect them to `/categories-beta` in either case we fire an analytics event. A cookie is needed here because our vue code doesnt have any concept of the legacy experiment framework. So we can use cookies to share data between the legacy php and the ui vue server.
> feat: add cookie for redirect to categories-beta page

- src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
Ran into this small bug: 
Before: 
After:
No changes for smaller screens
> fix: mg landing header on wide displays styling fix

- src/components/BorrowerProfile/LendersList.vue
Small design fix. There was an extra margin in the bottom of the lenders list in the mobile view that was hiding a portion of the borrower's story image.
> fix: remove bottom margin in mobile view

- src/components/BorrowerProfile/LendersList.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
As there isn't a fast way of filtering lenders collection in loan type to avoid fetching anonymous lenders.
The idea behind this pr is to fetch more lenders (10) in order to have more options and always show the required amount of lenders (3 lenders in desktop and 2 in mobile).
Problem: Fetching 3 lenders and filtering one because was an anonymous lender. This image should show 3 people.
> fix: fetch more lenders to avoid small filtered list

- src/components/BorrowerProfile/LendCta.vue
- src/components/BorrowerProfile/LoanBookmark.vue
- src/components/BorrowerProfile/SummaryCard.vue
- src/components/Kv/KvDropdown.vue
I introduced this bug, on the non PFP pages, the about menu and user menu show up under the lend cta. This is because unlike the lend menu they use the kv-dropdown component which has a different z-index. 😭 
I'll hotfix this out
The rest are more minor spacing changes. 
The borrower profile is starting to feel a little bit hacky with all the state dependent styling and the 3 different states and all their permutations (share button on/off, logged in/out, social exp on/off). Maybe some refactoring and more thinking of these styles with style guide in mind.  Personally I prefer the approach with the share button of using slots from the borrower profile to slot the button in the summary card/lend cta. It at least keeps the component in one place vs having an instance nested in the lend cta …
> fix: kvdropdown menu showing up under borrower profile lend cta

- src/util/loanSearch/filterUtils.js
- test/unit/specs/util/loanSearch/filterUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1180
- Instead of explicitly excluding, sort options are now explicitly included
- This will prevent this bug from happening the next time a sort option is released
> fix: only show expected FLSS sort options

- src/pages/BorrowerProfile/BorrowerProfile.vue
It turns out that in the case of using the /invitedby/{lender_id}/for/{loan_id} url it sets the inviter id in the `name` parameter instead of `utm_content`. We should change that so it uses utm_content instead, but until we can get that released in the monolith this will deal with the issue.
> fix: also check name url param for inviter public id MARS-206

- src/pages/Thanks/ThanksPage.vue
Fixes production issue that causes thanks page to 502 for non-lending checkouts (donations, kiva card purchases)
> fix: require loan purchase to display focused share ask on thanks page MARS-218

- src/plugins/loan-channel-query-map.js
- src/util/loanSearch/queryParamUtils.js
Did a pass in dev with a logged in and logged out user to find loan channels/categories that didn't have a translated url to lend/filter or legacy lend. This fixes a few of those and adds another exclude query param.
> fix: update query param defs for categories without them

- src/components/Homepage/HomepageVerticalCTA.vue
- src/pages/LandingPages/MGCovid19/CovidLandingForm.vue
- src/pages/Lend/LendByCategoryPage.vue
- src/util/experimentPreFetch.js
Removed the experiments: 
"homepage_verticalcta_active"
"homepage_verticalcta"
"mg_recurring_only"
"expandable_loan_cards"
from UI
also deleted from settings manager.  
Updated in excel doc. 
All of these were disabled and/or out of date range. Tried to do minimal cleanup, I'm not sure some of these components are even used anymore...
> refactor: remove inactive experiments

- .github/workflows/lighthouse-prod.yml
- .gitignore
- format-lh-for-s3.js
- lighthouserc-prod.js
- package-lock.json
- package.json
- src/client-entry.js
- src/util/webVitals.js
A couple things in this PR:
- Switching the nightly production Lighthouse test to use the PageSpeed Insights API, to improve consistency of the results and automatically keep the Lighthouse version used for the test up-to-date.
- Adding a step to the Lighthouse test that uploads trimmed-down versions of the reports to S3 where they can be consumed by our data warehouse.
- Tracking [web vitals](https://github.com/GoogleChrome/web-vitals) (CLS, FCP, FID, LCP, TTFB) for real-user page loads via Snowplow.
> Web vitals & PageSpeed Insights tracking MARS-169

- src/pages/Lend/LoanChannelCategoryClimateExperiment.vue
ACK-393
If a category has no loans, then hide it from the exp carousel layout
> fix: hide empty categories on the eco experiment layout

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/Lend/LoanSearch/LoanSearchSavedSearch.vue
- src/pages/Lend/LoanSearchPage.vue
- sets the `queryString` param as empty since custom keywords are not yet available on new lend filter page (to revisit after exp), confirmed w/ BE
- additional tracking
- hide saved search notif when creating saved search success message is visible
> fix: update query str and tracking on new saved search

- server/index.template.html
The goal of this is to improve the Optimizely loading time to hopefully minimize or avoid the FOUC caused for pages with Optimizely experiments. By moving the renderedExternals to the very first line in the `<head>`, that should get the browser to load and execute OneTrust (and then hopefully Optimizely) before loading anything else like fonts, styles, or the body of the page. This has the potential to break things and to harm the overall loading performance scores, so I'll be keeping a close eye on it and I'll revert this if necessary.
> fix: load head scripts before anything else

- .github/workflows/lighthouse-prod.yml
Force github checkout action to look deeper into the commit history.
ref. https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/troubleshooting.md#running-lhci-in-github-actions-i-constantly-get-ancestor-hash-not-determinable
> fix: update lighthouse checkout step to gain visibility to ancestor hash

- .github/workflows/lighthouse-prod.yml
minor clean. Our run this evening should be fine with the fetch depth addition. Let's see if it solves the ancestor warning...
> fix: remove commented out code in this config

- src/components/Contentful/HomePage/NewHomeLoansByCategoryGrid.vue
- src/components/Homepage/HomeExp/KivaMultiCategoryGrid.vue
- src/components/LoanCollections/HomeExp/LoanCategorySelectorHomeExp.vue
Ran into a couple issues trying this out in a Contentful page.
> fix: add missing injections and props for new loans-by-category grid

- src/components/Contentful/CardRow.vue
- src/components/Contentful/CenteredRichText.vue
- src/components/Contentful/DynamicHeroClassic.vue
- src/components/Contentful/FrequentlyAskedQuestions.vue
- src/components/Contentful/HeroWithCarousel.vue
- src/components/Contentful/HomePage/NewHomeLoansByCategoryGrid.vue
- src/components/Contentful/LoansByCategoryCarousel.vue
- src/components/Contentful/MediaItemsCentered.vue
- src/components/Contentful/RichTextItemsCentered.vue
- src/components/Contentful/SectionWithBackgroundClassic.vue
- src/components/Contentful/StoryCardCarousel.vue
- src/plugins/contentful-ui-setting-styles-mixin.js
This allows the theme of any component that uses SectionWithBackgroundClassic to be controlled with a "themeName" string in a UiSetting data block. Part of MARS-245.
> feat: theme controls for SectionWithBackgroundClassic

- src/components/Kv/KvExpandableQuestion.vue
> fix: remove jump of content when toggling FAQs

- test/unit/jest.conf.js
We found that the vueuse components had cjs/mjs extensions so jest couldn't find them... maybe we need to add this elsewhere too???
> fix: add other file extensions so @vueuse modules can be found

- src/graphql/query/achievementMilestones.graphql
- src/pages/Checkout/CheckoutPage.vue
- src/pages/Checkout/PostPurchase.vue
- src/pages/Thanks/ThanksPageEcoChallenge.vue
- src/plugins/checkout-utils-mixin.js
- src/router/routes.js
- src/util/ecoChallengeUtils.js
- test/unit/specs/util/ecoChallengeUtils.spec.js
* Adds routing to eco thanks page and reading achievement information from service
On checkout, if user is part of the eco_challenge experiment, fetch the achievements milestones (which is passed loan ids in basket) if these loans would progress the users challenge progress, add a query param, the goes through post purchase route and directs them to the thank you page. 
Added some computed properties to the thank you page to parse achievement response. This thank you page is based on the mars exp, so it only shows 1 loan in the hero area. Ideally we would want this loan to be one of the loans in the checkout that contributed to the challenge progress, this proved to be a little difficult, so for the test, I am generalizing the message displayed next to the loan, and then just searching …
> feat: eco challenge thanks page

- package-lock.json
Brings in carousel fix and Contentful image captions.
> chore(deps): bump @kiva/kv-components from 3.5.1 to 3.6.0

- src/pages/Lend/LoanChannelCategoryClimateExperiment.vue
- src/pages/Thanks/ThanksPageEcoChallenge.vue
* Adds the eco carousels to the bottom of the thanks page for the eco challenge categories that are missing. 
* Hide some more of the thanks page if receipt is not available
> feat: add carousels of missing categories in eco challenge thanks page

- src/components/Checkout/UpsellModule.vue
- src/graphql/query/checkout/upsellLoansExpiringSoon.graphql
- src/pages/Checkout/CheckoutPage.vue
an experiment we are running where if there are no loans available with <=$50 left to lend, we will show loans that are expiring soonest first instead. we will determine a random amount for the user to lend (5/10/15/20/25) on the client side.
> feat: dynamic upsell when no loans under $50

- src/components/LoanCollections/KivaClassicSingleCategoryCarousel.vue
- src/plugins/loan-channel-query-map.js
- src/util/flssUtils.js
- src/util/loanChannelUtils.js
- src/util/loanSearch/queryParamUtils.js
- test/unit/specs/util/loanChannelUtils.spec.js
Use FLSS for the lend-by-category/"category" pages and the eco friendly game page with sub categories for the categories that are in the eco game. The "filter" link will still default to the legacy page, since the new one does not have support for keywords.
Since the subcategory carousels on the eco page are not set to prefetch, and we only have `getCachedChannel` `preFetchChannel` and `watch` in `loanChannelUtils.js ` I added one more function which is just a regular fetch. Not super elegant since it's basically the same as getCachedChannel....
> feat: use flss for lbc page for eco game categories

- src/pages/Donate/DonateForm.vue
- src/pages/Donate/DonateFromMacroHero.vue
- src/pages/Donate/DonateSupportUs.vue
- src/router/routes.js
* Creates duplicate of donate/supportus at donate/supportkiva
* Clean up donation form analytics success event
ACK-416
This new page will be used to test new content for the donation page, traffic will be routed/experiment will be driven with optimizely. 
Also renamed the contentful key of `donate/supportus` it is currently web-donate-support-us which doesnt really match the convention of the keys in contentful being the url, I will take care of syncing this change in contentful with the release of this to prod.
> feat: add donate/supportkiva duplicate page

- src/pages/Homepage/Homepage.vue
CPS routes have been updated, so we need to update the redirect route. Just want to verify this in Dev before I prep the hotfix updates.
I'm organizing additional PRs to update lighthoust-prod.js config and routes in puppet as well.
> fix: update cps temporary homepage route

- src/head/script.js
- src/pages/LandingPages/Unbounce/IFrameEmbed.vue
- src/server-entry.js
Optimizely isn't loading at all for new users. Tracked down the issue to the `hasOptOut` definition in server-entry, which was returning `true` when the kvgpdr cookie didn't exist. I don't think script.js and IFrameEmbed have this issue because they aren't using optional chaining, but I changed the comparisons in those files as well just to be safe.
```js
const a = {};
a?.b?.c?.indexOf('string') !== -1; // true
a?.b?.c?.indexOf('string') > -1; // false
```
I also found that because the renderedExternals string is cached, all users were getting the same script tags, regardless of having the opt-out cookie or not. I addressed that by making separate strings for opted in and opted out users.
> fix: hasOptOut should be false when kvgdpr cookie does not exist

- src/pages/Checkout/CheckoutPage.vue
`showMatchedLoanKivaCredit` is a computed property on line 619, and we should not assign it a value
> fix: computed property warning on checkout page

- src/pages/Checkout/CheckoutPage.vue
Reverted old fix. 
After a successful checkout, before the achievements query fires, the achievements service, had already processed this checkout (On dev, and presumably on prod). In the vm this lag is greater and so the achievements query would return post checkout status on dev, and pre-checkout status in the vm. 
We don't really have a way to guarantee this timing, so I refactored to check for pre-checkout achievement status on mounted and then use that to determine if we should redirect to the eco challenge thanks page.
> fix: redirect to eco thanks page on eco checkout

- lighthouserc-dev.js
To be clear this is not a long term fix, it will just let us get through a full test run to get the latest ui code in QA. We need to get this page back in shape...
Some of the recent changes merged in this sprint and maybe the lighthouse updates from the week prior.
> fix: remove cc/kiva-universal from dev lighthouse

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/LoanCollections/KivaClassicSingleCategoryCarousel.vue
- src/graphql/query/flssLoanChannel.graphql
- src/graphql/query/flssLoanFacetsQuery.graphql
- src/graphql/query/flssLoansQuery.graphql
- src/graphql/query/lendByCategory/categoryServiceLoanChannels.graphql
- src/graphql/query/lendByCategory/mfiRecommendationsLoans.graphql
- src/graphql/query/lendByCategory/personalizedLoans.graphql
- src/pages/BorrowerProfile/FundedBorrowerProfile.vue
- src/pages/Lend/LendByCategoryPage.vue
- src/pages/Lend/LoanChannelCategoryClimateExperiment.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
- src/pages/Thanks/ThanksPageEcoChallenge.vue
- src/util/flssUtils.js
- src/util/loanChannelUtils.js
- src/util/loanSearch/dataUtils.js
- test/unit/specs/util/flssUtils.spec.js
- test/unit/specs/util/loanSearch/dataUtils.spec.js
Passes the `origin` variable into all `fundraisingLoans` queries.
> fix: pass query origin context on all flss queries

- src/pages/Lend/LoanChannelCategoryClimateExperiment.vue
I used to do a query with multiple channel ids for the main category 'eco-friendly'. This worked because eco-friendly uses a tagId which was not supported with FLSS
With the added support for tagId now I need to do separate queries here to get all the categories. The problem stems from 
the function `transformFLSSData` returning `data?.lend?.loanChannelsById?.[0]` which only returns the first item in that array, so it does not support multiple categories.
> refactor: climate lbc page to work with flss query

- src/components/LoanCards/KivaClassicBasicLoanCard.vue
- src/graphql/fragments/loanCardFields.graphql
Added fields to commonly used fragment (used in both flss and legacy lend by category queries) then kiva classic loan card can just load these fields if they are present. 
This makes it so the eco-challenge page loads all the cards almost instantly since we have already queried for them when getting the categories on `src/pages/Lend/LoanChannelCategoryClimateExperiment.vue`
> feat: use loanCardFields fragment for kiva classic basic loan card

- src/components/Payment/BraintreeDropInInterface.vue
This addresses a 500 error caused by importing a module on the server that tries to use `window`:
```
uncaughtException: window is not defined
ReferenceError: window is not defined
at Object.<anonymous> (/ui/node_modules/braintree-web/lib/vendor/polyfill.js:3:51)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at Module.require (/ui/node_modules/require-in-the-middle/index.js:43:24)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/ui/node_modules/braintree-web/lib/create-authorization-data.j …
```
> fix: only import braintree dropin on initialization in the client

- src/router/routes.js
- Moved filter routes above `/lend/:category`
> fix: filter route now usable again

- package-lock.json
- src/api/localResolvers/loanSearch.js
- src/api/localSchema.graphql
- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/components/Lend/LoanSearch/LoanSearchFilterChips.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/Lend/LoanSearch/LoanSearchRadioGroupFilter.vue
- src/components/Lend/LoanSearch/LoanSearchSavedSearch.vue
- src/graphql/mutation/updateLoanSearchState.graphql
- src/graphql/query/loanSearchState.graphql
- src/plugins/loan-channel-query-map.js
- src/util/flssUtils.js
- src/util/loanSearch/filterUtils.js
- src/util/loanSearch/minMaxRange.js
- src/util/loanSearch/queryParamUtils.js
- src/util/loanSearch/searchStateUtils.js
- src/util/numberUtils.js
- test/unit/fixtures/mockLoanSearchData.js
- test/unit/specs/components/Lend/LoanSearch/LoanSearchFilterChips.spec.js
- test/unit/specs/components/Lend/LoanSearch/LoanSearchRadioGroupFilter.spec.js
- test/unit/specs/util/flssUtils.spec.js
- test/unit/specs/util/loanSearch/filterUtils.spec.js
- test/unit/specs/util/loanSearch/minMaxRange.spec.js
- test/unit/specs/util/loanSearch/queryParamUtils.spec.js
- test/unit/specs/util/loanSearch/searchStateUtils.spec.js
- test/unit/specs/util/numberUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1324
https://kiva.atlassian.net/browse/VUE-1341
- Added `isIndividual` and 'lenderRepaymentTerm` filters to the new filter page
- Uses legacy query params: `isGroup` and `lenderTerm`
- Created pattern (similar to old pattern) for min max range filters
- Created pattern for boolean filters
- Updated and verified channel mappings with new filters
> Vue 1324 add individual group filter

- src/api/localResolvers/loanSearch.js
- src/api/localSchema.graphql
- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/components/Lend/LoanSearch/LoanSearchFilterChips.vue
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/Lend/LoanSearch/LoanSearchSavedSearch.vue
- src/graphql/mutation/updateLoanSearchState.graphql
- src/graphql/query/loanSearchState.graphql
- src/plugins/loan-channel-query-map.js
- src/util/flssUtils.js
- src/util/loanSearch/queryParamUtils.js
- src/util/loanSearch/searchStateUtils.js
- test/unit/fixtures/mockLoanSearchData.js
- test/unit/specs/components/Lend/LoanSearch/LoanSearchFilterChips.spec.js
- test/unit/specs/util/flssUtils.spec.js
- test/unit/specs/util/loanSearch/queryParamUtils.spec.js
- test/unit/specs/util/loanSearch/searchStateUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1307
- Implemented keyword search filter/input
- Brought over placeholder from legacy, "Search borrower story"
- I know we're moving away from lodash, but using `debounce` from lodash is quite convenient... And we want debounce on a text input that changes filters...
- Used the same query param as legacy, `queryString`
> Vue 1307 add keyword search field

- src/components/Contentful/FrequentlyAskedQuestions.vue
Fixes issue where background colors is added as a question, see Kyle's conversation in Slack. Seems to **not** be an issue in: https://github.com/kiva/cms-page-server/blob/main/components/contentful/FrequentlyAskedQuestions.vue
> fix: don't add background as a question in faqs

- src/components/Contentful/HomePage/NewHomeLoansByCategoryGrid.vue
- src/components/Homepage/HomeExp/KivaMultiCategoryGrid.vue
- src/components/LoanCards/KivaClassicBasicLoanCard.vue
- src/components/LoanCards/NewHomePageLoanCard.vue
- src/components/LoanCollections/HomeExp/KivaLoanCardCategory.vue
- src/pages/ContentfulPage.vue
- src/util/loanUtils.js
Loads the first loan in the first category during prefetch so that it is server-rendered. Remaining loan ids in the category are loaded on mounted. Other categories are only loaded when selected. Placeholder loan cards in a loading state are created by using loan id 0, which returns `null` from the api.
This required modifying the ContentfulPage prefetch so that it passed the ContentGroup content to each group as it was prefetched. 
https://user-images.githubusercontent.com/4149025/197258380-c0e7a62d-745d-460f-91fb-49f7f16b9d26.mov
> NewHomeLoansByCategoryGrid prefetch MARS-274

- src/graphql/query/myLendingStats.graphql
- src/graphql/query/userAchievementsProgress.graphql
- src/pages/LendingStats/BadgesSection.vue
- src/pages/LendingStats/LendingStatsPage.vue
I just added this new query to the created hook, I suppose the page could be refactored to add this in prefetch, but it will need a sequence of requests since the achievements api request depends on the userId. 
Users without badges should not be shown anything, for now.
> feat: display achievement service badge on lending stats page

- .storybook/stories/KvSelectBox.stories.js
- src/components/Kv/KvSelectBox.vue
- test/unit/specs/components/Kv/KvSelectBox.spec.js
- Partner ID needed a new component for rendering a list of selectable items w/ headers
- Here's the first pass, and I'm sure it'll be adjusted as it's used in the filters
- Utilized popper to save time, and we were already using it in this repo
- Works fine so far in desktop + mobile
- Creating separate PR in the spirit of small regular PRs
Empty/no-results:
Results w/ no filtering:
Results w/ filtering:
> feat: new select box component for lend filter partner ID

- src/components/Kv/KvRangeMinMaxSlider.vue
- Handles now work like expected in FF (both can be interacted with)
- Slider green now within handles in FF (it wasn't before)
- Slider colors now use new Kiva branding (and global CSS vars - missed that in my last PR)
> fix: issues with new range min max slider (FF and colors)

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/graphql/query/flssLoanFacetsQuery.graphql
- src/util/flssUtils.js
- src/util/loanSearch/dataUtils.js
- src/util/loanSearch/filterUtils.js
- test/unit/specs/util/flssUtils.spec.js
- test/unit/specs/util/loanSearch/dataUtils.spec.js
- test/unit/specs/util/loanSearch/filterUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1335
- Tag IDs now have loan counts from FLSS
- Loan counts added to tag filter like other filters
> feat: loan count added to tag filter

- lighthouserc-prod.js
We're going to try and get some isolated readings on the 2 versions of the homepage running on ui and the new version of the homepage running on cps.
> chore: add exp versions of hp and cps version of new homepage layout

- .storybook/stories/KvRangeMinMaxSlider.stories.js
- src/components/Kv/KvRangeMinMaxSlider.vue
- src/components/Kv/KvSectionModalLoader.vue
- src/components/Kv/KvSelectBox.vue
- src/util/loanSearch/filterUtils.js
- test/unit/specs/components/Kv/KvRangeMinMaxSlider.spec.js
- test/unit/specs/util/loanSearch/filterUtils.spec.js
The following changes were needed for the new filters w/ range sliders. General behavior matches legacy.
- Handles now have tooltips that show values that track with the handles as they move
- A unit can be displayed in the tooltip
- A range slider can be a percentage, which assumes the number needs to be multiplied by 100 when displayed
- The number of decimals shown is based on the step provided
- Adjusted the z index on a couple other components to ensure everything layers correctly
Tooltips:
Unit:
Percentage w/ unit:
> Add range slider functionality

- package-lock.json
- src/api/localResolvers/loanSearch.js
- src/api/localSchema.graphql
- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/graphql/mutation/updateLoanSearchState.graphql
- src/graphql/query/loanSearchState.graphql
- src/plugins/loan-channel-query-map.js
- src/util/loanSearch/filterConfig.js
- src/util/loanSearch/filters/activities.js
- src/util/loanSearch/filters/distributionModels.js
- src/util/loanSearch/filters/genders.js
- src/util/loanSearch/filters/isIndividual.js
- src/util/loanSearch/filters/keywordSearch.js
- src/util/loanSearch/filters/lenderRepaymentTerms.js
- src/util/loanSearch/filters/pageOffset.js
- src/util/loanSearch/filters/partnerAvgProfitability.js
- src/util/loanSearch/filters/partnerDefaultRate.js
- src/util/loanSearch/filters/partnerRiskRating.js
- src/util/loanSearch/filters/partners.js
- src/util/loanSearch/filters/regions.js
- src/util/loanSearch/filters/sectors.js
- src/util/loanSearch/filters/sortOptions.js
- src/util/loanSearch/filters/tags.js
- src/util/loanSearch/filters/themes.js
- src/util/loanSearch/queryParamUtils.js
- test/unit/specs/util/loanSearch/filters/activities.spec.js
- test/unit/specs/util/loanSearch/filters/partnerAvgProfitability.spec.js
- test/unit/specs/util/loanSearch/filters/partnerDefaultRate.spec.js
- test/unit/specs/util/loanSearch/filters/partnerRiskRating.spec.js
- test/unit/specs/util/loanSearch/queryParamUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1326
https://kiva.atlassian.net/browse/VUE-1372
https://kiva.atlassian.net/browse/VUE-1327
- Added parter risk rating, partner default rate, and partner profitability range slider filters
- Range slider added as option to `LoanSearchFilter` for rendering range slider filters
- Added `activities` filter (not displayed) so that the loan channels with `activity` work - there was also a mapping missing
> feat: new partner filters

- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/components/Lend/LoanSearch/LoanSearchRadioGroupFilter.vue
- test/unit/specs/components/Lend/LoanSearch/LoanSearchRadioGroupFilter.spec.js
Found some bugs while testing the new filter work. Logged a couple to the backlog, fix a couple others in this PR without logging them.
- Some whitespace added around filters for consistency
- Radio group that used value maps + object values (loan length) weren't passing readable values to analytics
- This also changes the value sent by is individual, from boolean to a string key - this filter isn't live yet, so changing the analytics value should be OK
> Filter update cleanup

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/util/loanSearch/filters/lenderRepaymentTerms.js
During functional testing found these issues:
- Experiment sort options weren't visible
- One of the keys for loan length had "key" incorrectly in it
> Missing sort options

- src/util/loanSearch/filters/distributionModels.js
- src/util/loanSearch/queryParseUtils.js
- test/unit/specs/util/loanSearch/filters/distributionModels.spec.js
- test/unit/specs/util/loanSearch/queryParseUtils.spec.js
https://kiva.atlassian.net/browse/VUE-1396
- The distribution model used and expected for the query is now the legacy format, `field_partner` and `direct`
> feat: changed distribution model query to use and expect legacy values

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/Lend/LoanSearch/LoanSearchSavedSearch.vue
https://kiva.atlassian.net/browse/VUE-1390
- While waiting for deploys, I went ahead and adjusted the alignment of the new saved search link
Desktop:
Mobile:
> fix: saved search link alignment

- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/util/loanSearch/filterConfig.js
https://kiva.atlassian.net/browse/VUE-1417
- `isMatchable` isn't being used anywhere else (not in the query map), so we can just remove it for now from the config
> fix: hide isMatchable filter

- src/components/WwwFrame/TheHeader.vue
Due to `has_lent_before` and `has_deposited_before` values are not being sent to Optimizely in Borrower Profile page (where the experiment is running). We want to test if this is caused by the condition wrapping the call.
> test: always set user attributes in Header

- src/components/WwwFrame/TheHeader.vue
Boolean was parsing a string (Got from cookies) so it was setting user attributes to `true` for `hasLentBefore` and `hasDepositBefore`. 
This only happened in `TheHeader` component
> fix: validation of boolean as string

- src/pages/LoanFinding/LoanFinding.vue
query added to lending-home page to get user info for personalized welcome message that will be added in other ticket
> feat: query to get user info added to lending home page

- src/components/Checkout/DonationItem.vue
ACK-485
When a user adds only a donation to cart, through the supportus page, the donation item has no donation tagline text. This happens for all variants of the donation item. This check was added as part of CASH-173, many moons ago. 
This removes the `hasLoans` check on these taglines
> fix: show donation item tagline when there are no loans

- src/components/LoanFinding/QuickFiltersSection.vue
- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
css rules overridden in quick filter component for sort-by dropdown to follow new design
> feat: sort by dropdown updgraded in quick filters component

- src/components/LoanFinding/QuickFiltersSection.vue
- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
default value added to sort-by dropdown options avoiding an empty state
pointer added to the dropdown for ux
> feat: customized sortby dropdown updated

- src/components/BorrowerProfile/LoanStory.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
Earlier today some changes were merged that introduced a few invariant violation errors that occur when Apollo tries to read something from cache that doesn't exist. Those errors were blocking/confusing my borrower profile optimization work, so I spun out these fixes, since we are also currently seeing these errors on dev.
@christian14b Two items to look into:
1. I didn't want to add the experiment query to the `preFetch`, but I noticed that the experiment flag was used quite a bit in the template. If we can move this to clientside, please do in a follow-up PR.
2. I didn't spend time verifying that delaying this data fetching indeed works okay from a UX perspective (like if text pop-in is bad), since I'm not familiar with this new experiment. Please test this when you have a chance, …
> fix: errors resolved for apollo cache on BP

- src/components/Settings/SubscriptionsSettingsCards.vue
- src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
Reverts kiva/ui#4432
Bug reported by Melissa -- I did not realize that MG subscriptions are now modern subscriptions and this change disabled the subscriptions settings box for everyone
> Revert "fix: add additional checks for modern subscriptions"

- package-lock.json
- package.json
This should update several of the smaller dependencies that dependabot is highlighting.
I've gone through the UI pages in the VM with this version running and things look to be functioning properly.
Most of the updates to express since our current version are dependency updates with a few minor fixes as they are now working on V5. https://github.com/expressjs/express/releases
> chore: update expressjs to latest version 4.18.2

- src/components/Checkout/DonationItem.vue
- src/components/Checkout/OrderTotals.vue
- src/pages/Checkout/CheckoutPage.vue
Variant looks like this, when there are loans in the basket, else show the control (variant a)
> feat: add 5th donation item variant as line item in order totals

- src/components/WwwFrame/LendMenu/CountryList.vue
- src/components/WwwFrame/SearchBar.vue
https://kiva.atlassian.net/browse/VUE-1437
https://kiva.atlassian.net/browse/VUE-1443
- Search navigates either to new or old filter page based on query params
- Lend menu country list navigates to new filter page
- Used full navigation to ensure that `/lend/filter` state updates like expected - simpler solution than special handling if the navigation happens from the filter page
> Header /lend links

- src/components/BorrowerProfile/LendCta.vue
- src/components/BorrowerProfile/LoanDescription.vue
- src/components/BorrowerProfile/LoanStory.vue
- src/components/BorrowerProfile/MoreAboutLoan.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
- src/util/experimentUtils.js
- test/unit/specs/util/experimentUtils.spec.js
Fixes and updates after product review:
- Expand experiment target matching ability with depositor and lender checks instead of checking that in vue components
- Change how the stats slot is cycled through to make it easier to add and remove items or change the conditions for when items display
- Use `expectedPayments` for repayment date when available
- Estimate first repayment date for loans without an expected payment date yet (non-disbursed loans)
- Drop 'First' language when there is only 1 payment (`repaymentInterval === 'at_end'`)
- Track what repayment date is displayed to the user
- Use line-clamp for truncating loan story and 'more about this loan' sections instead of character count
- Track when users click the 'read more' buttons
- A couple typo fixes
> updates and fixes for MARS-317

- src/components/WwwFrame/LendMenu/MonthlyGoodExpMenuWrapper.vue
- src/components/WwwFrame/LendMenu/TheLendMenu.vue
- src/components/WwwFrame/TheHeader.vue
- src/util/loanSearch/searchStateUtils.js
https://kiva.atlassian.net/browse/VUE-1407
- I investigated updating the Apollo cache again, but ran into the same general issue: the bookmark query needs the user ID, and some bookmark mutations are ran by loan card controller, which doesn't have the user ID and is used in a bunch of places
- This solution is a safer version of my previous PR - it still only runs `onLoad` when the lend menu was previously closed, but it uses the updated version of `isLendMenuVisible`
- Previously the `onLoad` was being ran every time a user hovers over the lend menu button in the header, regardless of whether it was open - the existing watch queries ran each time (pulling from cache) - getting the new data needs to skip the cache, so that existing behavior was sending off a network query with each hover …
> Vue 1407 saved search doesnt refresh in lend menu

- src/components/Checkout/DonationItem.vue
- src/components/Checkout/OrderTotals.vue
* Move the donation line item variant up in the order totals line items
* Refactor/css cleanup, use tailwind classes
* Alignment, spacing and font size changes
* Changes parenthesis to minus signs
Before: 
After:
> feat: spacing and alignment pass on order totals line items

- src/components/Thanks/ShareStepper.vue
- src/pages/Thanks/ThanksPage.vue
Adds a test id on the 2 different thanks messages that may be shown. This will allow us to stop checking against copy that continues to change.
https://github.com/kiva/kiva-tests/pull/25
> fix: add thanks-message testid to simplify automated thanks page test

- src/components/BorrowerProfile/ShareButton.vue
- src/components/Checkout/SocialShareV2.vue
- src/components/Kv/KvSocialShareButton.vue
- src/components/Thanks/ThanksPageShare.vue
* Also removed `this` from inside templates
* Standardized `handleFacebookResponse` method. I believe one of these was firing an error event when it should not have
ACK-495
> feat: add loan ids to various social share events

- lighthouserc-dev.js
- lighthouserc-prod.js
- src/router/routes.js
Handling any external links we can't control
> fix: redirect visits from /lp/how-kiva-works to /about/how

- src/pages/BorrowerProfile/BorrowerProfile.vue
loanId added as computed property to borrower profile page to fix the bug: 
`when you reach a fully funded borrower profile and click on any recommended borrower profiles (through their loan card) the information is incorrect.`
here to reproduce it https://www.kiva.org/lend/2456251
> Core 932 borrower profile bug

- src/pages/Homepage/Homepage.vue
Twitter stops showing the title in the preview when it gets longer than 81 characters. Their docs say that it shouldn't be longer than 70 characters, but they apparently have some wiggle room.
> fix: shorten year review share title for twitter requirements

- src/components/Kv/KvExpandableQuestion.vue
- src/components/Kv/KvFrequentlyAskedQuestions.vue
There was not space between paragraphs in expandable questions. This bug was introduced while working on show one answer at a time.
> fix: paragraph spacing in expandable questions

- src/components/Checkout/OrderTotals.vue
ACK-500
This experiment was initialized in 2 components `OrderTotals` and `DonationItem` But order totals was missing the setting query. It was working and then it stopped working. 
I believe the issue is that we cannot determine the order of the prefetch of child components. This seems to be determined at build time. After the release on 12/19, it seems that OrderTotals would prefetch before DonationItem, both being children components inside the Checkout Page. 
When OrderTotals would prefetch, it would run the experiment assignment query before knowing the results of the experiment setting query and this would disable the experiment assignment all together.
> fix: assigment of ACK-440 exp was not working correctly

- src/components/LoanCards/KivaClassicBasicLoanCard.vue
- src/components/LoanCards/LoanProgressGroup.vue
- src/components/LoanFinding/LendingCategorySection.vue
- src/components/LoanFinding/QuickFiltersSection.vue
- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- src/pages/LoanFinding/LoanFinding.vue
- src/plugins/loan-channel-query-map.js
This PR addresses a few things that came out of QA'ing the Quick Filters section of the MVP Lending Page:
* Update the progress bar to use the fundraising bar (so UI works with the grey background)
* Update some tracking (added tracking for selecting a category and refactor existing tracking for loan cards ATB)
* Ensure that "special loans" that use `partnerId` for their filter object work correctly by factoring `partnerId`s into the filter object, and added an LGBTQ channel map entry so that it works with the FLSS query
* Fix other "special loan" edge cases (women/Kiva US/ending soon)
* Some UI fixes requested by design
> fix: qa fixes for quick filters on mvp lending page

- test/e2e/specs/MetaInfo.cy.js
Noticed this was failing since the recent updates
> fix: update cypress meta tests to use new lbc and category title format

- src/util/contentful/richTextRenderer.js
When using `UI Setting` on FAQ content group, pages that uses FAQ inside a dynamic hero returns a [500 error](https://www.dev.kiva.org/hp/crowdfund-for-good). 
This pr filters only the content for faq.
> fix: filter faq content

- src/components/BorrowerProfile/JournalUpdates.vue
- src/components/BorrowerProfile/UpdateDetails.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
ACK-470
Adds updates to borrower profile: 
Loading state: 
Loaded: 
Updates load 3 at a time, this section is using the same pattern of loading as the other sections of the borrower profile to ensure that we don't slow down the main query in the borrower profile. 
Additional functionality coming in future PR's. (social sharing, linking)
Related backend change: https://github.com/kiva/kiva/pull/11265 to reverse the order of the API return.
> feat: journal updates on borrower profile

- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
- src/util/loanChannelUtils.js
https://kiva.atlassian.net/browse/CORE-957
https://kiva.atlassian.net/browse/CORE-897
- Quick filters now enabled for all categories (3 used to be disabled)
- Category pages again use cached loan data (since the filters don't currently change on mount)
- Because prefetched data is being used again, the page no longer initially loads with "no loans found"
> Core 957 qf channel improve page initialization

- .storybook/stories/GridLoanCard.stories.js
- src/components/LoanCards/GridLoanCard.vue
- src/components/LoanCards/KivaClassicBasicLoanCard.vue
- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- src/components/LoanCards/LoanMatchingText.vue
- src/components/LoanCards/LoanTags/LoanTag.vue
- src/components/LoanCollections/KivaClassicLoanCarouselExp.vue
- src/components/LoanFinding/LendingCategorySection.vue
- src/components/LoanFinding/PartnerSpotlightSection.vue
- src/components/LoanFinding/QuickFiltersSection.vue
- src/components/LoansByCategory/MFIRecommendations/MfiLoanCard.vue
- src/components/LoansByCategory/MFIRecommendations/MfiLoansWrapper.vue
https://kiva.atlassian.net/browse/CORE-939
- The lending-home page uses 3 (the grid component is on the category page) different loan card components
- All 4 cards now have an option prop (default `false`) for adding loan tag pills to the top of the card
- Consolidated the loan tag logic (other than `amountLeft`) into the tag component itself
- Once we finalize the loan card in the next body of work, we can clean up the loan card tag usage
- Updated matching text to reddish color (see screenshots)
3 cards on lending-home (1 has two screenshots, since it's used twice):
> Core 939 add loan labels to mvp

- src/plugins/kv-analytics-plugin.js
Custom events should use the `revenue` or `value` tags for metrics  https://docs.developers.optimizely.com/web/docs/event#parameters.
Based on fix from kiva/ui#4410
> fix: use revenue tag for custom optimizely events MARS-330

- src/components/BorrowerProfile/UpdateDetails.vue
Adding wrapping and spacing to journal info and button on mobile:
> fix: styling of share update button and updaate info on mobile

- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
Quick filters padding issue fixed for category page
Tested in:
/lend-by-category/livestock
/lend-by-category/women
/lend-by-category/kiva-u-s
/lend-by-category/ending-soon
/lending-home
for mobile, tablet and desktop
Default value added to sorting options in category page avoiding empty state in the dropdown
> fix: padding fix for quick filters feat in category page

- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- src/components/LoanCards/LoanProgressGroup.vue
- test/unit/specs/components/LoanCards/LoanProgressGroup.spec.js
https://kiva.atlassian.net/browse/CORE-1031
- Progress bar text is now orange when amount left is under $100
- Exclamation mark added, if time left doesn't already add it
- Unit tests added to confirm behavior
> feat: update progress text when amount left is low

- src/graphql/query/userInfo.graphql
- src/pages/LoanFinding/LoanFinding.vue
- Turns out that we are missing "b" group tracking for the `loan_finding_page` experiment
- The existing tracking occurs in the LBC page, in `mounted`, so it never gets hit when the redirect happens
> fix: tracking was missing on new page

- src/pages/Lend/LoanChannelCategoryControl.vue
- src/util/loanChannelUtils.js
- test/unit/specs/util/loanChannelUtils.spec.js
https://kiva.atlassian.net/browse/CORE-1059
https://kiva.atlassian.net/browse/CORE-990
- Help me choose now hidden for categories with a pre-defined sort, since help me choose are just sort options
- Help me choose results are now updated when QF change (though sort is not applied from QF)
- Added back in way to filter FLSS channel, since that was removed in a recent refactor
- Renamed "HelpMe" for variable naming consistency
> Core 1015 quick filters update when using help me choose

- src/components/LoansByCategory/QuickFilters/LocationSelector.vue
https://kiva.atlassian.net/browse/CORE-1060
- Pass by reference issue, location array reference never changed, so the apollo query didn't realize it wasn't the same
- The QF in general need to be refactored, but this was the smallest possible tweak for a hotfix :)
> fix: pass by reference issue for quick filters

- src/util/loanSearch/filters/sortOptions.js
- test/unit/specs/util/loanSearch/filters/sortOptions.spec.js
https://kiva.atlassian.net/browse/CORE-1002
- "Recommended" sort option is now at the bottom of the list in /lend/filter
> fix: put recommended at the bottom of the sort options

- src/pages/Lend/LoanChannelCategoryControl.vue
- src/util/flssUtils.js
- src/util/loanChannelUtils.js
- test/unit/specs/util/flssUtils.spec.js
- test/unit/specs/util/loanChannelUtils.spec.js
https://kiva.atlassian.net/browse/CORE-1060
- The last fix was incomplete
- Instead of tracking down why recreating an apollo watch query wasn't working, I instead fixed what apollo was watching, since re-creating a watch shouldn't be necessary
> fix: location QF wasn't working after first selection

- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- src/components/WwwFrame/LendMenu/TheLendMenu.vue
https://kiva.atlassian.net/browse/CORE-1035
- Set up experiment assignment and tracking for new lend menu button experiment
- Fixed issue where errors were being sent to the console for the new loan card tags while loan data was loading
> Core 1035 a b test lend dropdown split

- server/vue-middleware.js
- src/router/routes.js
- src/server-entry.js
1. Redirects in routes.js now use status 301 (permanent) instead of 302 (temporary) so that google stops indexing the old routes
2. Added redirects for old category pages
> Old category redirects MARS-335

- src/components/LoanCards/PromoGridLoanCardExp.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
New `PromoGridLoanCardExp` component added to show new style for new loan card experiment
Based in existing component `PromoGridLoanCard`
Desktop:
Mobile:
> Core 1001 new monthlygood card style

- server/vue-middleware.js
Set's strict cache-control headers on authenticated, user specific pages.
> fix: add strict cache-control headers to private pages

- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- src/components/LoanCards/LoanTags/LoanCallouts.vue
- src/components/LoanFinding/QuickFiltersSection.vue
- src/components/LoansByCategory/HelpmeChoose/HelpmeChooseWrapper.vue
- src/graphql/fragments/loanCardFields.graphql
- src/pages/Lend/LoanChannelCategoryControl.vue
- src/util/loanUtils.js
implements loan callouts on new loan cards with the following priority tag order (only show a max of 2):
p1: category (limited only to eco-friendly, refugees + IDP, + single parents)
p2: activity 
p3: sector (if it's not the same as activity)
p4: random public tag
p5: random theme
we also ignore p1 on category pages to avoid redundancy.
> feat: loan callouts on loan cards

- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- src/components/LoanCards/LoanUse.vue
- test/unit/specs/components/LoanCards/LoanUse.spec.js
https://kiva.atlassian.net/browse/CORE-1069
- Changed loan use statement string building for direct loans, since they have a more free-form loan data entry
> feat: updated loan use for direct loans

- package-lock.json
- package.json
- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- src/pages/LoanFinding/LoanFinding.vue
- src/util/loanSearch/filterConfig.js
https://kiva.atlassian.net/browse/CORE-1047
https://kiva.atlassian.net/browse/CORE-1052
- Changed lending-home matched loans section to use FLSS
- The toast shown to new users of lending-home now stays open for 10s (didn't disappear previously)
> Core 1047 update matched loans to flss

- server/auth-router.js
- src/components/Checkout/InContext/InContextCheckout.vue
- src/pages/Checkout/CheckoutPage.vue
Lenders often return to the site without any cookies (new sessions, new devices, etc.) which includes the `kvu` cookie. That cookie is used to determine whether to send users to login or to sign-up by default, and without it the users are sent to sign-up. This is very confusing behavior when clicking a login button, and it has led to several lenders unintentionally creating new accounts. The PR forces all the existing login buttons to always go to login (which is the expected ux). The previous default behavior is now accessed with the `autoPage=true` url parameter to support the checkout "continue" buttons.
> fix: ensure login links always go to login MARS-327

- src/components/Checkout/BasketItemsList.vue
- src/util/optimizelyUserMetrics.js
ACK-540
I thought the `BasketItemList` would be a cleaner place to put this as opposed to the `CheckoutPage`. This fires a user attribute to signal that a user has a US loan in basket. I added this attribute on optimizely already, the idea is that we would like to exclude users with this attribute from the thanks page experiment.
> feat: add user attribute for when a user has a us loan in basket

- src/components/WwwFrame/TheHeader.vue
- I thought I had tested mobile click, but apparently I just tested smaller browsers for this situation
- Touching the categories button in mobile should toggle the menu
> fix: touch should toggle categories menu

- src/pages/Thanks/ThanksPage.vue
- src/util/hotJarUserAttributes.js
- An error came through DD today for accessing props on null/undefined
- Location of error wasn't obvious, but I noticed a few missing usages optional chaining when compared to other similar usages of the affected objects
https://app.datadoghq.com/logs?query=service%3Akiva-ui%20env%3Aprod%20status%3Aerror&cols=host%2Cservice&event=AQAAAYZXipjnwxMHsgAAAABBWVpYaXBvLUFBQW40ZGUtTndNbUNnQUc&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1676504337021&to_ts=1676507937021&live=true
https://app.datadoghq.com/logs?query=service%3Akiva-ui%20env%3Aprod%20status%3Aerror&cols=host%2Cservice&event=AQAAAYZXipT_wxMHrwAAAABBWVpYaXBvLUFBQW40ZGUtTndNbUNnQUQ&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1676504337021&to_ts=1676507937021&live=true
> fix: missing optional chaining

- src/components/LoanFinding/LendingCategorySection.vue
height for new card in `LendingCategorySection` component fixed to adjust to the carousel height
> fix: height fixed for new loan cards in lendingcategorysection component

- package-lock.json
- package.json
Hoping this will address the memory leak we've been seeing, based on https://github.com/apollographql/apollo-client/issues/9712#issuecomment-1197225283
> fix: downgrade @apollo/client to v3.3.21 to address memory leak

- src/api/fixtures/AutolendProfile.js
- src/api/localResolvers/autolending.js
- src/api/localResolvers/loanSearch.js
- src/api/localResolvers/tipMessage.js
- test/unit/specs/api/localResolvers/loanSearch.spec.js
- The `updateQuery` method is simply `readQuery` followed by `writeQuery`
- Realized that the `writeQuery` doesn't actually return the updated state, and the return wasn't being used, so removed from `loanSearch`
https://github.com/apollographql/apollo-client/pull/8382/files
> fix: updated Apollo updateQuery usage for downgrade

- src/components/LoanCards/Buttons/LendCtaExp.vue
- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- src/plugins/loan-channel-query-map.js
https://kiva.atlassian.net/browse/CORE-1122
https://kiva.atlassian.net/browse/CORE-1123
- Added matched-loans to the channel map file - enables QF on matched-loans category (before they were visible but not working)
- Added click + add to basket analytics for the new loan card - the analytics aren't new standard but match existing loan card analytics
- The one change from existing analytics is that I added `loanId` to all of the analytics (the existing loan card only has `loanId` when the lend button is clicked) and the existing grid loan cards incorrectly log add to basket whenever the lend amount dropdown is clicked
- Added Sentry logging to add to basket error, matching old `LendButton`
> Core 1122 no add to basket event on new loan card

- src/api/localResolvers/autolending.js
- src/pages/Autolending/AutolendingStatus.vue
- src/pages/Autolending/AutolendingWhen.vue
- src/pages/Autolending/AutolendingWho.vue
- src/pages/Autolending/SaveButton.vue
https://kiva.atlassian.net/browse/CORE-1148
- Resolved issues in autolending local resolver with the `readQuery` and `writeQuery` combo that was needed to replace the `updateQuery` after Apollo downgrade
- Used lodash `mergeWith` in order to create a deep copy + overwrite arrays (specifically country list in `LoanSearchFilters`
- I would randomly get a weird "init" error when testing my autolending changes, and I eventually tracked it down to the 3rd party `FocusLock` component in the `KvLightbox` - I replaced the usages with the lightbox from our component library
> fix: resolve errors with read/write query for autolending

- src/pages/LoanFinding/LoanFinding.vue
query to get matched loans in lh page replaced by flss isMatchable option
> feat: flss ismatchable rolled out in lh matched loans

- .storybook/stories/KivaClassicBasicLoanCardExp.stories.js
- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
https://kiva.atlassian.net/browse/CORE-1114
- Updated new loan cards to only underline loan use statement when the image, loan callouts, or use statement hovered - before the underline occurred when any part of the card was hovered
- Cleaned up the props - we had several unused props
- Cleaned up the stories - we had stories that no longer did what was expected
> feat: hover on card update, cleaned up stories

- src/components/LoanCards/Buttons/LendCtaExp.vue
- padding decreased for lend again button in LendCtaExp component
> feat: padding decreased for lend again button in lendctaexp component

- src/pages/Lend/LendByCategoryPage.vue
- There was an experiment key mismatch that caused tracking analytics to not be logged
> fix: mismatched experiment key

- src/pages/Categories/CategoriesPage.vue
- src/pages/LoanFinding/LoanFinding.vue
- Turns out the other 2 potential spots a user lands also needed the tweaked exp key
> fix: remaining tracking

- src/pages/LoanFinding/LoanFinding.vue
- trigger for spotlight observer moved above matched loans avoiding a delay showing spotlight section when scrolling
> Core 1145 lg lazy loading spotlight

- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
This PR adds a loading state to the gender filter pills using placeholders when all of our filters are on one line. This ensures that the location selector and select sort dropdowns don't shift over dramatically once the data loads which can be confusing and jarring for the ux.
> feat: loading state for quick filter genders

- src/components/BorrowerProfile/DetailsTabs.vue
- src/components/BorrowerProfile/FieldPartnerDetails.vue
- Field Partner text replaced by Lending Partner at bottom of borrower profile page
> feat: field partner replaced by lending partner at bottom of bp

- src/graphql/query/lendByCategory/lendByCategory.graphql
- src/pages/Lend/LendByCategoryPage.vue
- src/pages/LoanFinding/LoanFinding.vue
- src/router/routes.js
https://kiva.atlassian.net/browse/CORE-1121
https://kiva.atlassian.net/browse/CORE-1008
https://kiva.atlassian.net/browse/CORE-1006
- Checks for `hasEverLoggedIn` instead of just logged in - the `kvu` cookie is create during log in process
- Removed experiment setting + assignment cookies that aren't needed in `preFetch`, since those get prefetched in parent wwwpage component
- Header text changed for logged out users
> Core 1008 UI header change for logged out lending home page

- src/components/LoanCards/Buttons/LendButton.vue
- src/components/LoanCards/Buttons/LendCtaExp.vue
https://kiva.atlassian.net/browse/CORE-1147
- The ATB events for category pages and lend/filter did not include the loan amount
- We want to track the amount to help decide if $5 notes is a success
- Moved tracking off HTML, since the analytics mixin doesn't work with dynamic data (it's set on render and isn't reactive)
> fix: added loan amount to ATB events on category and lend/filter pages

- src/pages/BorrowerProfile/BorrowerProfile.vue
ACK-552
Will add the `data-testid` to the main div in the borrower profile. Allowing us to use this property for exclusion of loans in optimizely tests.
looks like:
`<div class="www-page" id="borrower-profile" data-testid="partner-loan">`
> feat: add test id based on loan type to bp

- src/router/routes.js
Commenting out `/lp` route handling. This ensures links from Ui handled landing pages or the footer aren't loaded from UI.
https://github.com/kiva/puppet/pull/345
> fix: comment out lp route handling for cms-page-server verification

- src/components/LoanCards/HoverLoanCard/InfoPanels/TrusteeInfoPanel.vue
- src/graphql/query/loanPartner.graphql
Removing organizationType due to redundancy from template (Bellow image) and being not used in Borrower profile.
> fix: remove organizationType due to redundancy and being not used

- test/e2e/specs/HeaderNavigation.cy.js
https://kiva.atlassian.net/browse/CORE-1142
- The one failure was due to there being a slight delay in focus listener in CPS when compared with ui for the search bar -> the test now just looks to a ui page for the time being, and disables a header exp
> fix: ensure e2e test uses ui header

- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- We want to have the funded loan cards still clickable
- For some reason we have a couple unused components that weren't noticed by previous commit checks
> Funded should click

- src/plugins/kv-analytics-plugin.js
`donationTotal` and `loanTotal` are both strings, so the if statements were always returning true. That means the events were always firing for every transaction, even when `donationTotal` and/or `loanTotal` are $0. We only want the events to fire when the amounts are greater than $0.
> fix: only send optimizely events if tracked value is greater than 0

- src/components/CorporateCampaign/LoanSearch/LoanSearchFilters.vue
Current issue: Header displays promoName in dev but not in prod- more time is needed to figure out and fully fix this issue however for now, this PR is a solution that works and allows us to eventually figure out this bug. 
Banner falls back to prior header when campaign is not active: 
Banner displays promoName when campaign is active:
> fix: header rendering (added a fallback option when promoName is false)

- src/components/Checkout/GuestUpsell.vue
- src/components/Thanks/ThanksPageShare.vue
- src/pages/Thanks/ThanksPage.vue
For guests who are checking out with only US loans, show them the focused share ask. Instead of the portfolio link show a "Create account" link that just goes to the normal guest upsell state. 
ACK-553
Screenshots:
Then clicking on "Create your account" goes to:
> feat: show the focused share ask for guest checkout for us loans

- src/api/localResolvers/experiment.js
- src/util/experiment/experimentUtils.js
- test/unit/specs/api/localResolvers/experiment.spec.js
- test/unit/specs/util/experiment/experimentUtils.spec.js
https://kiva.atlassian.net/browse/CORE-1238
- Whether the assignment was query forced is now saved to the cookie value
- This is a temporary need while we have experiments active from before this refactor, since moving forward we won't need to store assignments in the cookie unless query forced, but this also isn't a bad addition to the cookie value
- The forced assignment lives regardless of distribution and population changes and will only be disregarded if the experiment is removed from the active_experiments
> feat: query forced saved in cookie assignment

- src/components/BorrowerProfile/LendCta.vue
Forgot to add the exp assignment query for this experiment. Since this component doesnt prefetch, this is all done in the initialize function
ACK-538
> fix: add exp assignment for matching_highlight

- src/api/apollo.js
- src/api/localResolvers/experiment.js
- src/main.js
- src/util/experiment/experimentUtils.js
- test/unit/specs/api/localResolvers/experiment.spec.js
- test/unit/specs/util/experiment/experimentUtils.spec.js
https://kiva.atlassian.net/browse/CORE-1242
- Resolved `route` from Vue router now passed to apollo init, makes grabbing query params much easier
- Multiple `setuiab` query params can now be added to the URL
> Core 1242 experiment assignment setuiab should be allowed multiple times in url

- src/api/localResolvers/experiment.js
- test/unit/specs/api/localResolvers/experiment.spec.js
This seems like a nice quality of life add. Maybe it'll motivate developers to get rid of stale experiments?
> feat: add id to experiment log message

- src/api/localResolvers/experiment.js
- test/unit/specs/api/localResolvers/experiment.spec.js
- Through functional testing found that I accidentally wasn't splitting the active experiments list
- Added unit test to cover this case
> fix: active experiment list should be split

- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- src/components/LoanCards/LoanTags/LoanTagV2.vue
`KivaClassicBasicLoanCardExp` component updated based in this requirements:
Let’s add the hover state back and remove the “more” cta for the next version of the test. 
Test group
category page, filter page, homepage include new loan card without the “more” (original design)
Control:
original /old loan cards in each of those loan card
Lending Home
by the time this ticket is done, we’ll have data on LH, so we can roll out the test and the loan card there can a/b more vs. no more 
Prop added to control lending home test in the future
> feat: prop added to new loan card to hide more cta in use component

- src/api/localResolvers/experiment.js
- src/components/LoanCards/Buttons/LendCtaExp.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
- src/pages/Checkout/CheckoutPage.vue
- src/pages/Lend/LendByCategoryPage.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
- src/pages/Lend/LoanSearchPage.vue
- src/pages/LoanFinding/LoanFinding.vue
- src/plugins/five-dollars-test-mixin.js
- src/util/experiment/experimentUtils.js
- test/unit/specs/api/localResolvers/experiment.spec.js
- test/unit/specs/util/experiment/experimentUtils.spec.js
https://kiva.atlassian.net/browse/CORE-1253
- I forgot that the active experiments come back in a JSON string (extra double quotes) - parsing and splitting moved to util method - it meant that the first and last experiment in `active_experiments` was ignored due to extra double quote
- Selected option in `LendCtaExp` couldn't be a computed, since it was bound to a dropdown - an error was being shown locally, and it wasn't adding the right amount to the basket (defaulted to $25) - ported the `watch` code from `LendCta` component, since it should be the same logic needed
- While tracking down the active experiments issue, I went ahead and refactored the $5 notes mixin, since I initially thought it might have to do with timing of assignment (it didn't...), but I kept the refactor in - it …
> fix: resolve $5 notes issues

- src/components/BorrowerProfile/LendCta.vue
- src/components/BorrowerProfile/LoanFollow.vue
- src/components/BorrowerProfile/MoreAboutLoan.vue
- src/components/BorrowerProfile/SummaryCard.vue
We want to replace the save button with a follow button for us loans that just scrolls down the page. See ACK-569 for more details. 
Screenshots:
ACK-569
> feat: add follow button to scroll to links on us loans

- .storybook/stories/KivaClassicBasicLoanCardExp.stories.js
- .storybook/stories/PortfolioKivaCreditStats.stories.js
- src/components/LoanCards/LoanTags/LoanCallouts.vue
https://kiva.atlassian.net/browse/CORE-1180
- Turns out that removing the 50% limitation fixes this issue in most cases
- Fixed issue preventing storybook from loading due to folder structure change for portfolio
> Core 1180 solution for loan card tags that are truncated

- .storybook/stories/KivaClassicBasicLoanCardExp.stories.js
- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- src/components/LoanFinding/LendingCategorySection.vue
https://kiva.atlassian.net/browse/CORE-1168
- Large card variation that brings CTA higher
- See left card below, vs old version on the right
- Currently only used in LH recommended carousel
> feat: large loan card variation

- .storybook/stories/KivaClassicBasicLoanCardExp.stories.js
- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
https://kiva.atlassian.net/browse/CORE-1129
- CTA now only shown once progress data is loaded client-side
> fix: don't show CTA until progress loaded

- src/api/localResolvers/experiment.js
- src/util/experiment/experimentUtils.js
- test/unit/specs/util/experiment/experimentUtils.spec.js
- Use experiment key instead of name for assignment to match BE
> fix: use experiment key instead of name

- src/components/BorrowerProfile/LendCta.vue
ACK-584
Matching experiment revision. When the matching experiment is on, keep the sparkle bubble around after user adds to basket. 
This involved just moving the sparkle to a different DOM node that wouldn't change based on basket state and changing the absolute positioning to accomodate that.
> feat: add matching bubble when loan is in basket

- src/pages/Lend/LendByCategoryPage.vue
- Turns out that our LH redirect wasn't including query params
> Redirect exp with params

- src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
This was previously in an else statement here but was accidentally removed. We can look later at how to make it more clear that this handles global scroll position changes.
> fix: ensure scroll handler is called

- src/api/ExperimentIdLink.js
- src/api/apollo.js
- src/pages/Lend/LendByCategoryPage.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
- src/pages/Lend/LoanSearchPage.vue
- src/pages/LoanFinding/LoanFinding.vue
https://kiva.atlassian.net/browse/CORE-1296
- Turns out that the recent experimentation refactor broke passing experiment header to gql for new users without an existing `uiab` cookie
- We didn't previously provide the header outside of LBC, and the data team requested it on: /lend/filter, /lending-home, /lend-by-category, and /lend-by-category/*
- The header value and experiment name for tracking were both updated following the data team's request, since this will be an ongoing experimentation setup for the ML backend
> Core 1296 enable flss experimentation on lending home

- src/pages/Lend/LoanChannelCategoryControl.vue
- Data format changed from return now that two requests are made in the initial prefetch
- Issue noticed when category pages on dev showed "no loans" on initial render
> feat: ensure correct channel data is collected

- src/components/Checkout/CheckoutDropInPaymentWrapper.vue
We currently don't have an initial click event for a braintree checkout. We have several subsequent events for different actions but not this one... It is a sibling [to this](https://github.com/kiva/ui/blob/main/src/components/Checkout/KivaCreditPayment.vue#L29) Kiva Credit button click.
> fix: add missing initial click event for braintree type checkout button

- src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
The basketLoans variable needs to be populated first before we can run all of these basket validation checks that open up the appropriate form.
> fix: email verification form not appearing for every user

- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- While testing relending exp, I would occasionally get a couple loan cards with blank data in the second row
- Looks like the initial load of the second row provides loan IDs of `0` due to lazy loading
- There seems to have been a race condition between the initial request and the one triggered by watching the loan ID
> feat: there was an edge case where a loan could be cleared

- src/components/LoanCards/Buttons/LendCtaExp.vue
- src/components/LoanCards/Buttons/MultipleAtcButton.vue
- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- src/components/LoanFinding/LendingCategorySection.vue
https://kiva.atlassian.net/browse/CORE-1363
- Adding "all" loans in relending experiment synchronously
- Button shows "adding to basket" while waiting for async calls
- Add all no longer navigates to checkout
- Add a simple hover state to the "add all" button
- Fixed bug where lend amount button wouldn't appear if the loan had less than $25, wasn't in the relending experiment, and $5 notes was running
> Core 1363 race condition when adding all to basket

- src/components/BorrowerProfile/LoanProgress.vue
ACK-635
We think the text "1 day in private fundraising" is confusing, changed it to "1 day left in private fundraising"
Before:
After:
> fix: add text to time left in pfp

- src/components/Checkout/SocialShareV2.vue
- src/components/Thanks/CommentAsk.vue
- src/components/Thanks/ThanksPageCommentAndShare.vue
- src/plugins/social-sharing-mixin.js
* Also standardize share button interactions -- make them buttons and enable small share pop up window on click and working toast messages
ACK-637
The result looks basically the same, the main content area is slightly wider because of the grid differences:
> refactor: remove foundation classes from thanks share

- src/components/BorrowerProfile/SummaryCard.vue
While adding inline block to the a tag makes the clickable area more precise, it introduces unwanted spacing.
> fix: summary card spacing

- src/components/Thanks/CommentAsk.vue
We found that everybody was just leaving our prefilled comments and all the comments looked the same which made them look spammy. 
This leaves the comment empty so users can enter their unique comment. With a placeholder in place. Also adds validation incase the API returns a success but failed to add comment. Also disables the button until the comment contains text.
> feat: make suggested loan comment a placeholder

- src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
ACK-492
Now that the subscription service supports non logged in users, we can add this code back to show the already signed up box if a user has a modern sub
> fix: mg page should show the already signed up box for modern subs

- src/util/basketUtils.js
https://kiva.atlassian.net/browse/CORE-1397
- There were internal reports of issues with ATB - the theory was that the invalid basket handling would fail
- I noticed that we get a relatively large number of unhandled exceptions in Sentry related to the error handling in ATB logic, including in the last 24 hours (linked below)
- We explicitly changed the catch to handle arrays 2 years ago, so I made sure we now handle both situations, arrays and non-arrays
https://kiva.sentry.io/issues/2576987672/?project=1201288&query=is%3Aunresolved+basketutils&referrer=issue-stream&statsPeriod=14d&stream_index=0
> fix: the ATB error can be singular

- src/components/LoanFinding/QuickFiltersSection.vue
- src/pages/LoanFinding/LoanFinding.vue
https://kiva.atlassian.net/browse/CORE-1434
- Snowplow events added using the new schema and following the behavior requested from data team
- Fixed issue where we kept loading spotlight data whenever the observer was hit in the browser
> feat: add loan display events to lending home

- server/index.js
I noticed a trace for a live loan image that indicated waiting 7 seconds to do the fs.stat() call in express.static. I've seen this call in all our requests for a while now (usually only taking a few milliseconds), but I just realized that we could isolate that filesystem call to only static requests. This should improve server response time, especially in high-traffic situations.
> feat: only check filesystem for static files when the /static route is requested

- src/pages/Portfolio/LendingStats/LendingStatsPage.vue
Updates verbiage on lending stats page from field partner to lending partner in accordance with guidance from the Inclusion Committee. 
I wasn't able to validate this locally, so your support in that if you've already got your machine set up to do so would be greatly appreciated!  This updates the bottom section and paragraph of `/portfolio/lending-stats`
> chore: update verbiage on lending stats page to lending partner

- src/components/BorrowerProfile/CommentsAndWhySpecial.vue
- src/components/Thanks/CommentAsk.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
* allows logged in users to report a comment for 1 of 3 reasons
ACK-628
Menu should show for logged in users. Use toast to give feedback. If a user reports a comment a second time, the message returned from the API is displayed "You have already submitted feedback"
Screenshots:
> feat: comment reporting

- src/components/Kv/KvDropdown.vue
- src/components/WwwFrame/TheHeader.vue
Fixes recent errors like `Cannot read properties of null (reading 'addEventListener')`
> fix(KvDropdown): skip dropdown init and log error when controller missing

- package-lock.json
- src/components/LoanCards/KivaClassicBasicLoanCardExp.vue
- removing smallest image size option to avoid image bug in tiny screens and zoomed out desktop version
Fixed example
> fix: avoid zooming bug removing smallest image size

- src/components/Checkout/CheckoutDropInPaymentWrapper.vue
https://kiva.atlassian.net/browse/CORE-1444
- An internal user ran into an infinite checkout spinner when a bad CC was used
- No one else could repro -> I guess it was an unusual situation where the user got a replacement card
- I identified which spinner on the page and found in code a user path where an error could have encountered and spinner not hidden
- Other usages of `requestPaymentMethod` hide the loading indicator in the `catch` like in this changeset
- Hopefully this resolves the issue moving forward
> feat: ensure loader is hidden on validation error

- src/components/BorrowerProfile/CommentsAndWhySpecial.vue
There was a bug with displaying the team name if a user is in many teams and the default limit of 20 is not enough. Added artificial limit of 100 
Also added word wrapping as some users are putting in very long urls in the comment
> fix: minor issues with comments on bp

- src/components/Checkout/GuestUpsell.vue
- src/components/Forms/GuestAccountCreation.vue
- src/components/Thanks/CommentAsk.vue
- src/components/Thanks/ThanksPageCommentAndShare.vue
- src/pages/BorrowerProfile/BorrowerProfile.vue
- src/pages/LoginAndRegister/GuestAccountRedirect.vue
- src/pages/Thanks/ThanksPage.vue
- src/plugins/guest-comment-mixin.js
Ask for comments from guests as well, since they are a large portion of Kiva US Checkout.
The flow for guests is: 
1. On thank you page ask for comment
2. Save comment to cookie, inform user that they have to finish creating an account to post their comment. 
3. Display account claim form (first Name, last name)
4. Follow account claim steps: auth0 password creation, redirect to `/register/guest-redirect`
5. If comment in progress cookies are found by `/register/guest-redirect` redirect to login with destination URL borrower profile with query params.
6. User lands on borrower profile. Mix-in checks for comment cookies, and submits comment and deletes cookies if successful.   
Refactors: 
- Refactored guest account creation form so we can use it in multiple places (normal upsell an this …
> feat: requests comments from guests on thank you page

- config/dev-vm.js
- config/dev.js
- config/index.js
- config/qa.js
- config/stage.js
- config/test.js
- src/components/Forms/ReCaptchaEnterprise.vue
- src/pages/LoginAndRegister/RegisterSocial.vue
- test/e2e/specs/RegisterSocial.cy.js
Add support for requiring a captcha at login/registration. Because captcha values can be large, I changed the form to submit a POST request with form encoded data instead of redirecting with GET query parameters. Support for the data coming in a POST request was added in kiva/auth0#338.
> feat: show captcha on /register/social page when required MARS-446

- src/plugins/guest-comment-mixin.js
Should eliminate that error. Cookie value should always be a string or undefined.
> fix: toString error in guest comment compare

- src/components/Kv/KvBaseInput.vue
Going with 'on' to match what the Auth0 rule is expecting.
> fix: provide default value for checkbox to override empty KvCheckbox default

- src/components/Contentful/CampaignLoanWrapper.vue
- src/components/CorporateCampaign/CampaignProgressBar.vue
- src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
For Matching Type Accounts there is no promo credit therefore the UI should not render promo credit meter. Curious if the button length should be reduced?
(How it looks without a filled basket) 
(With loan in basket)
(Mobile screen)
> feat: adding v-else for matchingCampaign type [CIT-160]

- src/components/LoanFinding/LendingCategorySection.vue
- src/components/LoanFinding/PartnerSpotlightSection.vue
- carousel updated for mobile version in lending home page
New mobile version
Desktop version stills as current
> feat: carousel updated for mobile version in lending home page

- src/components/Settings/SaveSearchItem.vue
- var removed as is no longer being used
> fix: unused var removed in saved search component

- src/components/LoanFinding/QuickFiltersSection.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
- src/util/loanSearch/filters/sortOptions.js
Users requested the ability to sort loans by most recent. This adds it to the ui interfaces. There is a companion PR to add it to the loan filters utilities in kv-ui-elements
> feat: add most recent loan sort

- src/api/fixtures/FlashMessageTypeEnum.js
- src/components/WwwFrame/TheTipMessage.vue
- test/unit/specs/components/WwwFrame/TheTipMessage.spec.js
Checks for FlashMessages from the api while still using the TipMessage from the local resolver. Displays whichever has a higher level first (error being the highest, then warning, then tip), favoring the tipMessage in a tie. Displays the next available message after the current message is closed.
> feat: display flash messages for visitor in the tip message MARS-448

- src/api/ExperimentIdLink.js
- src/pages/Lend/LoanChannelCategoryControl.vue
- src/pages/Lend/LoanSearchPage.vue
- src/pages/LoanFinding/LoanFinding.vue
> feat: flss experiment key updated

- deploy/dev/values.yaml
Let me know if this is not the right place to change. We're wanting to start proxying requests that are made to `*.dk1.kiva.org` to our EKS dev cluster, but ran into an issue with Apollo Router not supporting operation batching.
> feat: [CP-477] disabling batching so we can shift traffic to the EKS cluster

- build/webpack.base.conf.js
Gzip version of some files was not being generated, which caused a 403/404 when trying to request them.
I discovered this in the description of [the `minRatio` option](https://webpack.js.org/plugins/compression-webpack-plugin/#minratio):
> Use a value of `Infinity` to process all assets even if they are larger than the original size or their original size is `0` bytes (**useful when you are pre-zipping all assets for AWS**).
> fix: ensure all assets get compressed before upload MARS-288

- src/main.js
This should clear up the false alarms for UI checkout errors
> fix: filter out unhanded google ads code request errors from sentry

- build/webpack.base.conf.js
- build/webpack.client.base.conf.js
Moving the compression to after the svg plugin in client base so that it runs on the icons file as well, and runs a little faster b/c it's not compressing the files for the server build. I also found that the font files were *larger* after compression, so I'm excluding those.
> fix: ensure icons are compressed and skip font compression MARS-288

- src/pages/ProcessJoinTeam.vue
- src/router/routes.js
We can't generate an recruitmentId if the user is not logged in, so this page needs to also support the inviter query param. 
This allows us to go from un authenticated page > auth0 > team process page (with inviter param) 
Then we can use the inviter param to get the inviter id and pass that to the join team mutation as the recruitment id.
> feat: support inviter param and recruitment on team process page

- src/pages/LendingTeams/TeamListing.vue
- src/pages/LendingTeams/TeamSearchBar.vue
Support all team search params to and from the url query for the `/teams-beta` page. Fixes paging and allows the url to hold all the values for a specific teams search
This page is now feature complete
> feat: support all teams search params to/from url

- src/graphql/query/leaderboardsQuery.graphql
- src/pages/LendingTeams/TeamLeaderboard.vue
- src/pages/LendingTeams/TeamLeaderboards.vue
- src/pages/LendingTeams/TeamListing.vue
- src/util/teamsUtil.js
Some additional features for the /teams page
* Leaderboards now change to filter on the category 
* Added info line indicating this. 
* Added placeholder loader while leaderboards load. 
* Added no teams to show when leaderboard query is empty
* Fixed some issues with query params not being removed when the "all" value is selected
* Added utility variable of team category values and friendly labels
> feat: teams page additional features

- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- src/graphql/query/loanEnumsQuery.graphql
- src/graphql/query/loanFacetsQuery.graphql
- src/util/loanSearch/dataUtils.js
- test/unit/specs/util/loanSearch/dataUtils.spec.js
- Introspection queries passed to a new query file for filtering options.
- Genders bug fixed in quick filters when resetting selected filters. We are currently showing no option selected in gender dropdown after resetting the filters.
- Updates tested in `/lend/filter`, `/lend-by-category` and `/lend-by-category/*` pages
> feat: introspection queries passed to a new query file

- .github/workflows/create-release.yaml
Read the docs more closely and realized it said we should pass the token when checking out the repo 🤦🏻‍♀️ 
https://github.com/stefanzweifel/git-auto-commit-action/tree/v4#commits-made-by-this-action-do-not-trigger-new-workflow-runs
> fix: [CP-603] Pass kiva-robot token when checking out repo

- src/assets/images/checkout/ftds_sparkle.svg
- src/components/Checkout/FtdsDisclaimer.vue
- src/components/Checkout/FtdsMessage.vue
- src/graphql/query/checkout/initializeCheckout.graphql
- src/graphql/query/thanksPage.graphql
- src/pages/Checkout/CheckoutPage.vue
- FTDs message added to checkout page for first time lenders
- Admin settings updated for checkout and thank you pages
> feat: ftd message added to checkout page for first time lenders

- src/pages/LendingTeams/TeamLeaderboard.vue
- src/pages/LendingTeams/TeamListing.vue
- Change the amounts format  to show the full number in the leaderboards, seeing the exact number is more valuable.
- Add some helper text to the first two tabs in the leaderboard member counts like this: “Only members who have lent at least once are counted”
- Hide the text "We loan because:" if the field is empty
> feat: teams page tweaks

- server/index.js
Adds surrogate keys for Ui assets along with the `all-assets` key. We don't currently cache pages out of ui but if there are other surrogate keys you think we should add, let me know!
> fix: add surrogate keys for ui assets

- src/pages/LendingTeams/TeamLeaderboards.vue
- src/pages/LendingTeams/TeamListing.vue
Changes the query param for teams categories from `teamCategory=something` to `category=something` on the `/teams` page. 
This is needed because there are some links in the legacy teams pages that are linking to `/teams?category=something` so instead of fixing all the legacy link, lets just make this query param the same.
> fix: change query param on new teams page

- config/dev-local.js
- src/graphql/query/checkout/checkoutSettings.graphql
- src/graphql/query/checkout/initializeCheckout.graphql
- src/pages/Checkout/CheckoutPage.vue
- Move the new ftd settings to a different query
- Add Sentry log for missing totals data. One key component of critical basket data.
- - Looks like our current apollo prefetch handler is not returning the `errors` out of the collected set of queries so a check at that level will need additional work.
> fix: reduce checkout query complexity

- .github/workflows/create-release.yaml
- .github/workflows/semantic-release.yaml
Use semantic-release actions for creating releases.
> feat: semantic-release actions

- config/index.js
- deploy/charts/values.yaml
Preparation for changes to api infra
> fix: turn off apollo batching for ui in all evns including prod

- config/dynamic.js
Activates the API_HOSTNAME env var in our dynamic config when passed.
> fix: allow passing in full api url

- config/dynamic.js
missed the server setup in the previous update :(
> fix: ensure server api url uses passed env var too

- src/components/Lend/LoanSearch/LoanSearchFilter.vue
- Matched loans filter added to filter page
Thanks Casey for previous work!
> feat: matched loans filter added to filter page

- src/components/WwwFrame/TheHeader.vue
- test/e2e/specs/HeaderNavigation.cy.js
- lend menu buttons old test code removed
> feat: lend menu buttons test code removed

- src/components/WwwFrame/PromotionalBanner/GlobalPromotionalBannerContentful.vue
We hit a case over this past weekend where we had unresolved entries in the list of promo content causing high level failures on the page requests.
> fix: guard against missing fields and draft ui-global-promo banners

- server/index.js
Missed initializing `promBundle` in `server/index.js`.
> fix: missing const for prometheus middleware

- package-lock.json
- package.json
- src/main.js
Verified the library update is working in Dev, webvitals emanate from Tracing and there are now some in the dashboard.
Minor tweaks
- increase sampling span to 25% which will cascade to prod in the next release, I'll also add these to flux and plan to turn dev up to 100%
- remove localhost and regex match on host
- remove unnecessary package!
> fix: remove unnecessary package, reduce origins to only our domain

- src/components/Checkout/BasketItem.vue
We want the ability for a guest or logged in user to attribute a loan to a team from the challenge page. They may not be part of that team, and they may or may not be logged in at the time they add the loan to their basket
1. User goes to team challenge page, adds a loan to basket, cookie is created (Not in this PR, this will be on cps)
2. User eventually arrives at checkout. 
3. Read cookie 
4. Set the teamId on the loan reservation by calling the `updateLoanReservationTeam` mutation. 
5. If the user is not part of the team, append the team name and id to the drop down, user can manually change the attribution at this point. 
6. Checkout --> user will attribute loan to team and contribute to the challenge even if they are not part of the team. 
I have verified that you can in fact …
> feat: ability to attribute a loan to a team from cookie value

- config/dev-local.js
- config/dynamic.js
- config/index.js
These couple with the recent updates to sentry to allow passing in an env var for the trace rate.
> fix: add sentry trace rate config defaults

- src/components/Teams/TeamGoal.vue
- src/graphql/query/teamsGoals.graphql
- src/util/imageUtils.js
- test/unit/specs/util/imageUtils.spec.js
https://kiva.atlassian.net/browse/ACK-875
- Added lender image to MVP team activity section
- Note that the lenders in our MVP data mostly have legacy avatars
- Border color switches between white and gray depending on if the avatar is legacy (with white background)
- Added ellipsis overflow for participation count text, since there was wrapping before
- added missing aria label on progress component
> feat: add user avatar to teams page challenge cta

- .storybook/stories/NotifyMe.stories.js
- src/components/Thanks/NotifyMe.vue
- src/graphql/query/thanksPage.graphql
- src/pages/Thanks/ThanksPage.vue
https://kiva.atlassian.net/browse/ACK-913
> feat: add link back to team challenge page

- src/components/Teams/TeamGoalsList.vue
https://kiva.atlassian.net/browse/ACK-945
- Prefetched the team goals on `/teams`
- The goals themselves are still lazy loaded
- This causes the goals to appear immediately w/ skeleton loaders (then the data to lazy load)
> feat: prefetch the goals on the teams page

- server/vue-middleware.js
- server/vue-worker-pool.js
I think it would be useful to have these metrics reported from the start, to monitor for issues. Are these metric names good or could they be better?
> feat: export worker pool metrics to monitor vue rendering

- .github/workflows/semantic-release.yaml
https://docs.github.com/en/actions/using-jobs/using-concurrency
> build: ensure only one release is running at any time

- package-lock.json
- package.json
- server/dev-server.js
- server/index.js
- server/sitemap/middleware.js
- server/sitemap/worker.js
- server/util/getGqlPossibleTypes.js
- server/util/initCache.js
- server/vue-middleware.js
- server/vue-worker-pool.js
- server/vue-worker.js
- src/util/KvAuth0.js
This is a quick first pass at using worker threads for ui server requests.
I didn't find a way to share the vue bundle renderer between threads (functions can't be passed, as far as I can tell from the errors), so I just initialized one for each request. Not sure how that will affect performance, but I think threading will likely more than make up for it.
I setup a worker for live loans as well, but ran into issues with font registration. It sounds like node-canvas doesn't play nice with threads (according to https://github.com/Automattic/node-canvas/issues/1694) because of having to communicate between native C code and the nodejs process. I think it would be better to spin off live loans into their own service anyway, or maybe set it up as a lambda function.
> feat: use worker threads for vue app and sitemap rendering

- config/dynamic.js
- config/index.js
- server/vue-middleware.js
- server/vue-worker-pool.js
Also sets default `minWorkers` to 1 so that there will always be at least 1 worker ready to render requests.
> feat: configure min/max vue worker count with env vars

- .storybook/stories/CommentsContainer.stories.js
- package-lock.json
- package.json
- src/components/Contentful/CommentsContainer.vue
- src/components/Contentful/DynamicRichText.vue
- test/unit/specs/components/Contentful/CommentsContainer.spec.js
https://kiva.atlassian.net/browse/ACK-919
- Added basic Contentful wrapper for `CommentsContainer`
- Unlike the recent CPS PR, I didn't add this new component to the `ui` rich text component -> `ui` has a slightly different collection of rich text components, and I think it makes sense to identify the use case before adding this new Contentful component to the wrong parent(s)
> feat: contentful comments component base in cps

- server/dev-server.js
- server/vue-worker-pool.js
Avoids errors like `Error: A metric with the name vue_total_workers has already been registered.` which cause server crashes when the dev-server request handler is updated.
> fix: handle pool reinitialization by dev server

- .storybook/mock-data/thanks-page-data-mock.js
- .storybook/stories/ThanksPage.stories.js
- src/components/Iwd/IwdThanksPageVariations.vue
- src/graphql/query/lenderPublicProfile.graphql
- src/graphql/query/thanksPage.graphql
- src/pages/Thanks/ThanksPage.vue
https://kiva.atlassian.net/browse/CORE-1729
- Implemented the first IWD thanks page variation
- This is when a user checks out after being invited by a user
- The query string in this situation will have `valet_inviter` as either `kiva` or the lender public ID
- There is a slight variation on whether the inviter is Kiva, but below is the situation where there's a lender public ID
- Implemented decorator to change a story iframe URL before it gets rendered
> feat: first IWD thanks page variation

- .storybook/mock-data/thanks-page-data-mock.js
- .storybook/stories/KvProgressCampaign.stories.js
- src/components/Iwd/ActivityFeed.vue
- src/components/Iwd/IwdCategoryHeader.vue
- src/components/Iwd/IwdProgressCampaign.vue
- src/components/Iwd/IwdThanksPageVariations.vue
- src/components/Kv/KvProgressCampaign.vue
- src/graphql/query/IwdActions.graphql
- src/graphql/query/campaignStats.graphql
- src/pages/Lend/LoanChannelCategoryControl.vue
- test/unit/specs/components/Kv/KvProgressCampaign.spec.js
https://kiva.atlassian.net/browse/CORE-1724
- Updated the campaign progress bar to match the updated mocks + data
- Moved the IWD header into its own file
- Created a wrapper component for the shared progress bar usage
- Added the bar to the category page for IWD
- Small fix for padding on thanks page from previous PR
**UPDATE**
- Added the progress bar to the thanks page variations for IWD
- Created minimal version of the progress bar
> feat: add campaign progress bar to category page

- src/components/Iwd/IwdProgressCampaign.vue
- iwd progress bar hidden when goals reached
> feat: iwd progress bar hidden when goals reached

- src/components/WwwFrame/TheFooter.vue
- 'Happening now' broken link removed from footer
> feat: footer broken link removed

- src/client-entry.js
Somewhere along the way we lost the setting of the `uid` on snowplow events when it's available. We had to do this with CPS recently too which is working well and was the basis for this code.
> fix: patch in userid before pageview if available

- src/util/loanSearch/filters/flexibleFundraisingEnabled.js
- test/unit/specs/util/loanSearch/filters/flexibleFundraisingEnabled.spec.js
https://kiva.atlassian.net/browse/CORE-1717
- We were trying to save a new FLSS filter that isn't supported by saved-search/monolith
> feat: don't save new filter to saved search

- src/components/Iwd/ActivityFeed.vue
- src/graphql/query/IwdActions.graphql
https://kiva.atlassian.net/browse/CORE-1785
https://kiva.atlassian.net/browse/CORE-1786
- Aggregate/sum amounts for lenders who lend to more than one loan quickly
- Exclude some known corporate accounts that were clogging the feed
- Increased the amount of activity feed data to allow enough displayed items after aggregation and filter
- The default limit of `campaignActions` is 20, so just removing `limit` is safe enough
- Monolith work will likely filter the corporate accounts in the future
- This will be part of a hotfix
At the moment on dev, anonymous has lent a bunch, so they only show up once:
> feat: aggregate and filter the activity feed

- src/pages/Lend/LoanChannelCategoryControl.vue
- src/util/flssUtils.js
https://kiva.atlassian.net/browse/CORE-1783
- We were getting an apollo cache miss due to using `undefined` as the fallback sort enum value
> fix: ensure prefetched channel data is correctly pulled from apollo cache

- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/Lend/LoanSearch/TeamPicksSwitch.vue
- team picks switch added for team challenges on filters page
Note: There is some work left to match the switch logic with loans display as the BE stuff is done
> feat: team picks switch added for team challenges on filters page

- src/util/loanSearch/queryParamUtils.js
- team query params added to filtering query params
As we don't have filters for `team` and the logic for this query is in the page side, we just need to preserve the team query param like utm cases.
> feat: team query params added to filtering query params

- src/components/Kv/KvProgressCampaign.vue
- src/components/Lend/LoanSearch/ChallengeHeader.vue
- src/components/Thanks/ShareChallenge.vue
https://kiva.atlassian.net/browse/ACK-1115
- We weren't looking to the correct props for the new amount lent challenge type
- Small fix to progress bar in challenge header
- Fixed issue with prop type
> feat: fe progress bar not correctly showing progress

- package-lock.json
- package.json
- src/util/webVitals.js
- FID web vitals tracking replaced with INP
- web vitals package updated to last version
> feat: fid web vital tracking replaced with inp

- src/pages/Checkout/CheckoutPage.vue
String comparison leads to unexpected results:
```javascript
'25.00' > '75.00' // false
'25.00' > '100.00' // true
```
> fix: use number instead of string comparison for incentive upsell MP-95

- package-lock.json
- package.json
- src/components/Lend/LoanSearch/LoanSearchInterface.vue
- src/components/LoanCards/KvClassicLoanCardContainer.vue
- src/pages/Lend/LoanSearchPage.vue
- src/plugins/clickable-tags-mixin.js
https://kiva.atlassian.net/browse/MP-170
- Loan card callouts on the `/lend/filter` page are now clickable
- Takes the user to `lend/filter/` with the filter from the callout applied
- Works for tags, themes, and sectors
- Activities are not clickable currently since they are not an active filter on `lend/filter`
> feat: loan card clickable callouts

- src/api/ExperimentIdLink.js
Seeing a CORS failure on all api calls in prod when uiab cookie is present, because the x-uiab header is not is the allowed list of headers. commenting out this code until we can sort that out.
> fix: stop adding uiab header to api calls pending header approval

- server/util/getSessionCookies.js
https://kiva.atlassian.net/browse/MP-237
- Cookie now being set on monolith applicant form page: https://github.com/kiva/kiva/pull/12547
> fix: borrower applicant cookie setting location

- .github/workflows/release-build.yaml
Note: This will also upload the client manifest and server bundle to s3, but that on't harm anything except the upload time for now. Once we confirm that the action is working, we can come back and exclude those files.
> feat: restart upload process with new action changes MP-226

- .github/workflows/release-build.yaml
- .github/workflows/semantic-release.yaml
The `use-existing-assets` branch of marketplace-web-ui-ci has [been merged into `main`](https://github.com/kiva/marketplace-web-ui-ci/pull/100), so we can switch back to using `main`.
> build: use main branch of marketplace-web-ui-ci

- src/components/WwwFrame/PromotionalBanner/Banners/PromoCreditBanner.vue
When a user arrives to the BP with a query param like: `fromContext=/impact-dashboard/hitachi` Generate banner with link back to `/impact-dashboard/hitachi`
This banner state should trump all other states. 
Waiting on copy confirmation in ticket, so there could be a copy  update here
> feat: add banner link back to impact dash if user came from impact dash

- src/components/Thanks/AnimatedSparkles.vue
- src/components/Thanks/WhatIsNextTemplate.vue
I noticed this positioning was not centered due to the svg sizing
> fix: reposition animated sparkles around borrower image MP-376

- README.md
- src/pages/Thanks/ThanksPage.vue
Folks are consistently getting to, or trying to load thanks without a transaction id which spews a mass query failure error for the reciept. This prevents us from executing an unnessesary query and restores the Login link instead of showing an empty page frame.
Also adds notes on dev setup with caddy...
> fix: prevent failed reciept query thanks

- src/components/BorrowerProfile/LendCta.vue
- Activity feed hidden for sticky CTA in borrower profile page
> feat: bp activity feed hidden for sticky cta

- src/components/BorrowerProfile/LendCta.vue
- bottom position fixed for sticky lend cta when having an extra label
bug:
> fix: bottom position fixed

- src/components/BorrowerProfile/LendCta.vue
- 'XX Matched Loan' component updated to full width for tablets on borrower profile
> feat: bp matching component size fixed for tablets

- src/components/Thanks/AnimatedSparkles.vue
- animated sparkles component updated
Ex: https://www.loom.com/share/ae246e31377c4e53b7eac021ab0be398?sid=5e5c3359-5389-4183-80ea-3b7c3a613ade
> feat: animated sparkles component updated

- src/components/LoansByCategory/QuickFilters/QuickFilters.vue
- src/plugins/loan-channel-query-map.js
https://kiva.atlassian.net/browse/MP-513
- Two new home page channels have the `amountLeft` sort
- Updated the category page to handle the new sort -> preselect special casing, hiding sort quick filter, and updating channel map
- The category page is linked to from the home page loans by category component, so this special casing is needed
> feat: new categories shouldn't show sort by quick filter

- src/components/Checkout/DonationItem.vue
- src/components/Payment/BraintreeDropInInterface.vue
- src/pages/Checkout/CheckoutPage.vue
- ensures we update the config for paypalCredit like we do for paypal, google and applepay
- makes the amount watcher use the immediate flag
- extend the overlay visibility so the braintree widget is covered until it gets the updated values
> fix: mp 517 paypal credit update config

- src/components/Checkout/UserUpdatesPreference.vue
- src/pages/LoginAndRegister/RegisterSocial.vue
The terms agreement was missing for version c (radio buttons), causing redirect errors, and the marketing email consent didn't have the right name in versions b & c, so if anyone opted into marketing emails it wasn't saved on their account.
> fix: missing newAcctTerms and newsConsent form values for opt-in-comms exp MP-535

- src/components/WwwFrame/PromotionalBanner/Banners/DepositIncentiveBanner.vue
- src/graphql/query/configSetting.graphql
https://kiva.atlassian.net/browse/MP-539
- The deposit incentive campaign ID is now pulled from the Settings Manager
- The settings key is `config.deposit_incentive_active_campaign_id`
- There's currently an error in the dev API for pulling campaign info, so I can't test end-to-end, but I verified that the campaign ID is returned, parsed, then the query to get the data for the banner is returned
- Also cleaned up a variable name in the same file
> feat: get deposit incentive banner campaign ID from settings manager

- src/graphql/query/autolending/autoLendingSelected.graphql
- src/graphql/query/autolending/partnerList.graphql
- src/pages/Autolending/PartnerFilter.vue
- src/pages/Autolending/PartnerRadios.vue
- src/util/autoLendingUtils.js
- test/unit/specs/util/autoLendingUtils.spec.js
https://kiva.atlassian.net/browse/MP-276
- The partners shown were limited to the 100 returned by default from the monolith -> this must have been a bug since that limitation was added to the monolith endpoints
- Now all non-direct partners are shown in the autolending settings modal
> fix: auto lending advance settings incorrectly displays partners

- src/pages/LendingTeams/TeamListing.vue
- Make recent activity sort option the default sort on /teams
Reqs: https://kiva.atlassian.net/browse/MP-531
> feat: teams page sort updated

- src/components/LenderProfile/LenderSummary.vue
- src/graphql/mutation/sendLenderMessage.graphql
- src/graphql/query/userInfo.graphql
- message lightbox added to lender profile
Not signed:
Signed and no loans:
Signed with loans:
> feat: message lightbox added to lender profile

- src/components/LoansByCategory/HelpmeChoose/HelpmeChooseRecommendations.vue
- src/components/LoansByCategory/HelpmeChoose/HelpmeChooseWrapper.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
We used to have the `grid-loan-card` class on all ui loan cards but those were lost when moving to our new components. This adds a generic default class for use in [kiva-tests](https://github.com/kiva/kiva-tests/pull/38).
> fix: add classes for finding and accessing loan cards from kiva-tests

- package-lock.json
- package.json
- src/components/LoansByCategory/HelpmeChoose/HelpmeChooseRecommendations.vue
- src/components/LoansByCategory/HelpmeChoose/HelpmeChooseWrapper.vue
- src/pages/Lend/LoanChannelCategoryControl.vue
I found more places (lend/filter) that also had no way to easily grab a list of loans followed by drilling into the selected card. Let's go with a global data-testid instead...
> fix: use global loan card classes

- src/components/Settings/TwoStepVerification.vue
- src/pages/ProcessBrowserAuth.vue
- src/util/KvAuth0.js
Auth0 will require MFA authentication via redirect after Aug 30 for MFA API tokens, so silent auth calls like checkSession need to be replaced. Since it's a redirect for an implicit grant, we need to parse the token from the hash on an approved callback url (like /process-browser-auth). /process-browser-auth wasn't being used anymore (previously only used for popup window auth) so I repurposed that to redirect to a destination after confirming state.
Depends on https://github.com/kiva/kiva/pull/12870
> fix: mfa api token auth requires using authorize call, not checkSession MP-479

- src/plugins/braintree-dropin-error-mixin.js
With the release yesterday we started to see the format of some of the unhandled errors. This update handles the formatted error response from async checkout more directly.
Example error surfaced in sentry: `UNKNOWN_ERROR_CODE:[{"error":"SALE_REJECTED","message":"Sale was rejected, Status: CHARGE_TRANSIENT_PAYMENT_METHOD_FAILED"}]`
> fix: extract async checkout error object with primary format

- src/pages/ProcessBrowserAuth.vue
I found that the state param is actually sent over in the hash. I initially got only a blank page though, so I also added a push to the error page to handle those cases more gracefully.
> fix: state is in hash and show error page for error conditions MP-479

- src/components/Charts/PieChartFigure.vue
> feat: pie chart mobile view fixed

- package-lock.json
- package.json
- src/components/LenderProfile/LenderMap.vue
- src/components/LenderProfile/LenderProfileWrapper.vue
- src/components/LenderProfile/LenderStats.vue
- src/graphql/query/lenderPublicProfile.graphql
- src/graphql/query/lenderStats.graphql
- Lender stats data import updated
> feat: lender stats data import updated

- src/components/BorrowerProfile/FundedBorrowerProfile.vue
https://kiva.atlassian.net/browse/MP-473
- Added the same loan display snowplow event as `/lend-by-category` with the same type of data
- Fixed index issue on interaction snowplow events for the recommended loan
- Changes applied to funded borrower profile
> feat: additional tracking events and event details on funded borrower page

- src/pages/Thanks/ThanksPage.vue
https://kiva.atlassian.net/browse/MP-748
- Take non-loan (for example, gift card) purchases to old TY page
> fix: show old ty page for non-loan purchases

- src/components/LenderProfile/LenderProfileWrapper.vue
- Removing `unshift` didn't solve the memory leak, now let's try disabling the new lender map component
> fix: try disabling lender map for memory leak

- src/components/WwwFrame/TheFooter.vue
- footer content updated: "Students and educators" link removed
> feat: footer updated

- package-lock.json
- package.json
- Let's try rolling back the package lib
- This is the oldest we can move to without rolling back other files related to charts
> fix: try rolling back components library for memory leak

- server/util/live-loan/live-loan-fetch.js
- test/unit/specs/server/live-loan-fetch.spec.js
Use FLSS for all filter searches that it supports, with a fallback to the legacy loan search if using a sort option that only works there.
> feat: use FLSS for live loan image filter searches when supported MP-732

- .github/workflows/semantic-release.yaml
I think we'll need this option to kick off a semantic release using an alternal `marketplace-web-ui-ci` branch
> chore: allow input of optional ci build branch

- .github/workflows/semantic-release.yaml
Because there are additional steps (like notify slack) in the semantic-release action after the actual semantic release process runs, the image build step can end up being skipped when those additional steps fail, even though a tag was created and a github release was created. This is because a "default status check of success() is applied unless you include one of" the [status check functions](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#status-check-functions). This adds a `!cancelled()` check to the build image step so that it will happen as long as a release was published, even if the previous step failed overall.
> build: ensure image build happens if github release was published

- src/components/MyKiva/MyKivaNavigation.vue
- horizontal overflow hidden in my kiva nav
> fix: horizontal overflow hidden in my kiva nav

- src/api/apollo.js
Because responses from the server are handled in reverse order (requests start at the top of the link chain and responses are sent back up from the terminating link), network errors are being logged as errors even when the retry is happening successfully. This PR change the link order so that the network error retry link is the first one to process the server response, followed by the network error logging link. This should make it so that we only log network errors when the retries fail.
> fix: attempt retry after network error before logging the error MP-857

- .storybook/mock-data/loan-data-mock.js
- .storybook/preview.js
- .storybook/stories/BorrowerProfile.stories.js
- .storybook/stories/KivaClassicSingleCategoryCarousel.stories.js
- .storybook/stories/KivaMultiCategoryGrid.stories.js
- src/components/LoanCollections/KivaClassicLoanCarousel.vue
- src/components/LoanCollections/KivaClassicSingleCategoryCarousel.vue
- Mostly issues with mocked data
- One problem with a loan carousel was uncovered and resolved (related to the slots not being set and causing an empty slide to be added to the carousel before the loans + the view more would go incorrectly in front of the loans)
- `KivaClassicSingleCategoryCarousel.vue` doesn't appear to be used, but it was also getting data incorrectly
> fix: migration stories

- .github/workflows/lighthouse-prod.yml
I kinda expect this will error out in the `format-lh-for-s3.js` file next...
> chore: update lighthouse filename in github action

- src/components/15Years/15YearsButton.vue
- src/components/Kv/KvButton.vue
The render function API changed from Vue 2 to Vue 3 and VNodes now have a flat prop structure. See https://v3-migration.vuejs.org/breaking-changes/render-function-api.html#vnode-props-format for details.
> fix: props and attrs not set correctly on buttons MP-858

- src/client-entry.js
- src/util/authenticationGuard.js
Without this, the auth guard redirect was not being observed during client side navigation. This ensures the redirect occurs based on the route contained in the error.
> fix: mp 877 client auth guard

- package-lock.json
- package.json
- src/components/LenderProfile/LenderStats.vue
- bugs in lender profile stats section fixed
> fix: lender profile stats bugs fixed

- src/components/Kv/KvRadio.vue
- src/pages/Autolending/AutolendingStatus.vue
- src/pages/LoanFinding/LoanFinding.vue
- src/util/loanSearch/dataUtils.js
- vite.config.js
A few things:
- Changes vite config to load all assets and other vite urls behind the `/static` path instead of various direct references such as `/src/`, `@vite` and others... This will help fix Ui in Tilt where we don't have all the new possible vite hmr locations setup
- Updates the KvRadio component to set the initial `inputValue`, this was a similar fix to some we made in our global components. Removes the previous hack watcher which didn't work once deployed to dev.
- Filters out `null` entries in loan queries used in LBC
> fix: autolending dev mode lbc null

- src/pages/MonthlyGood/MonthlyGoodSetupPage.vue
missed one `.value()` on previous fix
> fix: validation in monthly good setup form

- src/pages/UiSiteMap/RouteListing.vue
This separates the redirect routes into their own list, showing both the original path and the destination.
This also extracts and replaces path parameters with values from inputs, allowing clicking on the link with whatever test value you want. However, this doesn't yet work with parameters that have pattern limitations (like `/lend/:id(\d+)`).
> feat: improve ui-site-map MP-880

- src/components/Contentful/DynamicRichText.vue
- vite.config.js
Fixes rendering of dynamic components in the built production mode on /monthlygood
> fix: dynamic rich text rendering

- src/components/MonthlyGood/AutomaticallySupportNotice.vue
- src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
It seems we need to wrap 'v-html' and components which use 'v-html' with 'isClient' to avoid hydration errors and missing content in the built app
> fix: hydration and missing content on mg page

- src/pages/Lend/LoanChannelCategoryRecommendedByLenders.vue
Was able to replicate on server load locally and verify the fix.
> fix: use default page number of 0 if no page number is passed in

- src/components/Checkout/CheckoutReceipt.vue
- src/pages/Thanks/ThanksPage.vue
- Remove `this` from template
- Use `kivaCards` length in setup of `printableKivaCards` to ensure an empty array is passed and we don't hit the filter case without any content.
> fix: guard printableKivaCards with kivaCards

- src/plugins/kv-analytics-plugin.js
'bind' has been deprecated in Vue3, analytics events were not firing
> fix: analytics directive

- src/components/Thanks/ThanksLayoutV2.vue
- src/components/Thanks/ThanksPageCommentAndShare.vue
- src/components/Thanks/ThanksPageDonationOnly.vue
- src/pages/Thanks/ThanksPage.vue
The thanks page is complex enough that it's hard to know what version of the page a user actually saw without digging into the details of the URL parameters and what was in their basket. This refactors the logic for selecting which thanks view is visible into a computed value, and adds tracking for the visible view.
> feat: thanks view tracking MP-921

- src/components/MyKiva/BorrowerCarousel.vue
- src/components/MyKiva/BorrowerStatusCard.vue
- src/components/MyKiva/MyKivaHero.vue
- src/components/MyKiva/MyKivaNavigation.vue
- src/components/MyKiva/MyKivaProfile.vue
- src/components/Thanks/LoanNextSteps.vue
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
https://kiva.atlassian.net/browse/MP-937
I tested the MyKiva work that we have so far and ran into a number of small issues that I resolved:
- hero element sizing and positioning
- name left aligned mobile
- carousel overflow issue -> page scrolls
- carousel slides size incorrectly on page resize
- removed small green border around borrower avatars
- newline before borrower card “view details”
- settings modal height issue (not full parent)
- scrollbar appears when settings menu opened/closed
- settings menu navigation links could be hovered but not clicked on the top/bottom edges
- settings menu height changes during slide animation
> fix: random issues resolved with my kiva work

- src/components/Checkout/CheckoutDropInPaymentWrapper.vue
- src/components/Checkout/KivaCreditGuestPayment.vue
- src/components/Checkout/UserUpdatesPreference.vue
- src/components/Forms/GuestAccountCreation.vue
- src/components/Kv/KvLoadingOverlay.vue
- src/components/Settings/PhoneAuthentication.vue
- src/pages/LoginAndRegister/RegisterSocial.vue
I found various issues when completing some checkouts in dev, one using a guest account and another using a new signup.
* form input error messages were showing when they shouldn't. I found all the cases where checks for `$error` had been switched to `$invalid` and switched them back.
* the first name input was always displaying on /register/social, even when it was not required. looks like that was due to a line for debugging that was left in.
* it's possible to click "complete registration" multiple times, but only the first request will succeed. Clicking the button cancels the in-flight request and starts a new one, which will end in being sent to the error page. I added a loading overlay so that none of the form can be interacted with after the button is clicked.
* I found a case of …
> feat: various fixes for form inputs and /register/social MP-938

- src/client-entry.js
Excludes another/duplicate form of the Failed to fetch error from 3rd party scripts.
> chore: filter out addition Failed to fetch calls from 3rd party scripts

- src/components/MyKiva/BadgesSection.vue
- src/composables/useBadgeData.js
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
https://kiva.atlassian.net/browse/MP-966
- Partial implementation to allow for other engineers to utilize this work
- Created composable for combining badge tiered achievements and contentful data
- Work to come: comments, unit tests, using on MyKiva correctly, etc.
- This doesn't break the page more than it already is currently 😄
> feat: composable for tiered badge data

- src/components/MyKiva/BadgeModalContentJourney.vue
- src/components/MyKiva/BadgesSection.vue
- src/composables/useBadgeData.js
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- test/unit/fixtures/useBadgeDataMock.js
- test/unit/specs/composables/useBadgeData.spec.js
https://kiva.atlassian.net/browse/MP-966
- Next step is getting the badges section of MyKiva to show the correct badge title, level, and icon based on the current in-progress tier
- Added unit testing for new composable (mostly adding lots of mock data to make a realistic test)
- Fixed small spacing issue on MyKiva badge section badges
- Moved tier date cleanup to composable
- Moved Vue lifecycle methods out of composable so it could be reused as a util
- Other minor cleanup, like commenting
> feat: continue expanding use of tiered badge data

- src/client-entry.js
Most recent error signature from the pinterest GET failures
> fix: add additional error signature filter for pinterest tag

- src/components/MyKiva/BadgeModalContentJourney.vue
- src/components/MyKiva/BadgesSection.vue
- src/composables/useBadgeData.js
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- test/unit/fixtures/useBadgeDataMock.js
- test/unit/specs/composables/useBadgeData.spec.js
https://kiva.atlassian.net/browse/MP-945
- Created tested util/composable method
- Renamed another util to be more accurately named
- Updated badge section to just show "visible tiers"
- Updated badge journey to just show "visible tiers"
- Badges section now shows "active" level number to match the badge icon shown
> feat: badges show just 3 levels at a time

- .storybook/mock-data/badge-journey-data-mock.js
- src/components/MyKiva/BadgeCompleted.vue
- src/components/MyKiva/BadgeInProgress.vue
- src/components/MyKiva/BadgeModalContentJourney.vue
- src/components/MyKiva/EarnedBadgesSection.vue
- src/composables/useBadgeData.js
- test/unit/fixtures/useBadgeDataMock.js
- test/unit/specs/composables/useBadgeData.spec.js
https://kiva.atlassian.net/browse/MP-980
- Created new field on challenges in Contentful, `levelName` short string, and removed unused `level` field -> simplifies differentiating challenge and level names
- Updated field for all 7 levels of the current 5 badges on dev in Contentful
- Updated `useBadgeData` to utilize this new field (allows us to have `levelNames` as strings)
- Updated UI to use the new field as required
> feat: change contentful level to a string and update code accordingly

- src/pages/Portfolio/MyKiva/MyKivaPage.vue
https://kiva.atlassian.net/browse/MP-985
- Just wrapped the bottom components in `<template v-if="badgeAchievementData">`
> fix: hide MyKiva content further down page as achievement data loads

- config/dynamic.js
- config/index.js
- server/vue-middleware.js
- server/vue-worker-pool.js
Piscina creates nodejs performance histograms that it updates continually as requests come in for the [run time](https://github.com/piscinajs/piscina?tab=readme-ov-file#property-runtime-readonly) and the [wait time](https://github.com/piscinajs/piscina?tab=readme-ov-file#property-waittime-readonly). These stats can only be read in terms of the lifetime of the pool, not any smaller or larger time segments, which makes them not very useful outside of development testing. In our real environments, we can use our existing metrics in grafana to get the same information.
There is a chance that constantly updating these histograms is what is contributing to the increasing event loop lap over the lifetime of the UI pods that keeps happening, so I'm creating this PR to test that. The recordTiming …
> feat: optional run & wait time recordings in vue worker pool

- src/components/MyKiva/BorrowerStatusCard.vue
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- src/util/myKivaUtils.js
- test/unit/specs/util/myKivaUtils.spec.js
https://kiva.atlassian.net/browse/MP-995
- Dynamically adding footnote asterisk to borrower status cards
- Dynamically adding footnote to bottom of MyKiva page (only one footnote currently)
> feat: footnote support for borrower status cards in MyKiva

- src/components/WwwFrame/TheFooter.vue
We have a new page path for the Gifts landing page.
> fix: update gifts url in the footer to new path

- src/components/MyKiva/BorrowerCarousel.vue
- src/components/MyKiva/EarnedBadgesSection.vue
- src/components/MyKiva/MyKivaNavigation.vue
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
https://kiva.atlassian.net/browse/MP-996
https://kiva.atlassian.net/browse/MP-997
https://kiva.atlassian.net/browse/MP-998
Settings menu fixed (now just over MyKiva page content):
Borrower carousel height fixed (now all same height):
Old tiered badges no longer clickable (no screenshot needed).
> feat: settings menu modal gets pushed down when banner enabled

- src/components/MyKiva/BadgeModal.vue
https://kiva.atlassian.net/browse/MP-1006
- Added a loader component for the async components that occasionally take a 1-2 seconds to load
> feat: added loader for badge modal async components

- src/components/MyKiva/BadgeModalContentJourney.vue
- in-progress badge container fixed
> fix: in progress badge container fixed

- src/components/MyKiva/BadgeInProgress.vue
- in progress carousel loan card updated to show loan amount dropdown
> fix: loan card updated in inprogress carousel

- src/components/MyKiva/BadgesSection.vue
- src/components/MyKiva/MyKivaHero.vue
https://kiva.atlassian.net/browse/MP-1027
https://kiva.atlassian.net/browse/MP-1040
https://kiva.atlassian.net/browse/MP-1038
Show in-progress badge state in journeys:
Adjust welcome and gear in hero:
> fix: several MyKiva UI fixes

- src/components/Thanks/MyKiva/ThanksBadges.vue
- src/composables/useBadgeData.js
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
https://kiva.atlassian.net/browse/MP-1041
- We want to scroll to two different MyKiva sections when continuing from the TY page
- Data is loaded async, so we needed a way to wait for that data
- This implements the logged-in use case, there's another ticket for the guest use case
> feat: scroll to on page load on sections with async data

- src/graphql/query/myKiva.graphql
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- src/util/myKivaUtils.js
- test/unit/specs/util/myKivaUtils.spec.js
- my kiva first login for guest claim flow
> feat: my kiva first login for guest claim flow

- src/components/MyKiva/BadgeTile.vue
> feat: level added to badge tile

- src/components/MyKiva/BadgesSection.vue
- complete status added to journey
> feat: complete status added to journey

- src/components/MyKiva/BorrowerCarousel.vue
- Tracking event trigger fixed for MyKiva loans number
- As `hasActiveLoans` is a computed prop, was always false on mounted hook
> fix: tracking event trigger fixed for loans number

- src/components/Thanks/MyKiva/OptInModule.vue
- src/components/Thanks/MyKiva/ThanksBadges.vue
- src/composables/useBadgeData.js
- src/graphql/query/postCheckoutAchievements.graphql
- src/main.js
- src/pages/Thanks/ThanksPage.vue
- test/unit/specs/composables/useBadgeData.spec.js
https://kiva.atlassian.net/browse/MP-1017
- Fixed issue where badge module needed to be shown for guests (with equality badge)
- Fixed issue where badge rays animation was displayed while the badge data was being loaded
- Fixed issue where `getLastCompletedBadgeLevelData` didn't sort completed date desc
- Fixed issue where `getLastCompletedBadgeLevelData` didn't handle when two tiers were achieved at the same time
- Fixed issue where `getLastCompletedBadgeLevelData` returned the wrong achievement data
- Fixed issue where MyKiva TY would be shown when no loan was checked out (Kiva Card)
- Fixed issue where MyKiva TY was being shown when loans advanced a tier but didn't achieve the tier
- Fixed issue where loan/borrower images on MyKiva TY were pixelated
> fix: more issues resolved for the MyKiva TY flow

- server/util/errorLogger.js
Making inferences from the logs is difficult at the moment because the request/response metadata is not structured (just dumped to `message`). This makes the logs much more searchable/sortable by changing the log format from this:
```
{"meta":{},"level":"info","message":"HTTP 200 GET /UI_REVISION 663ms"}
```
To this:
```
{"meta":{"req":{"url":"/UI_REVISION","headers":{"host":"localhost:8888"}},"res":{"statusCode":200},"responseTime":221},"level":"info","message":"HTTP 200 GET /UI_REVISION 221ms"}
```
> chore: add request/response metadata to logs

- lighthouserc-prod.cjs
This will turn off pushing data to our external server and retain the static uploads which are used internally.
[More info here](https://kiva.atlassian.net/browse/CIT-2372)
> chore: turn off lighthouse push to external server

- src/components/MyKiva/BadgeModalContentJourney.vue
- src/components/MyKiva/EarnedBadgesSection.vue
- src/composables/useBadgeData.js
- src/pages/Portfolio/LendingStats/BadgesList.vue
- test/unit/specs/composables/useBadgeData.spec.js
**Sections updated:**
- Completed badge modal title
- In-progress badge modal title
- Badge journey tier names
- MyKiva “my achievements”
- Portfolio lending stats
- Public lender profile
**For example:**
> feat: make badge level names consistent

- .storybook/preview.js
- .storybook/stories/ThanksBadges.stories.js
- src/components/Thanks/MyKiva/ThanksBadges.vue
- src/composables/useBadgeData.js
- test/unit/specs/composables/useBadgeData.spec.js
https://kiva.atlassian.net/browse/MP-1161
- Update TY page to use update badge level format
- Fixed some issues with MyKiva stories
> feat: change MyKiva TY page level name format

- src/components/Thanks/MyKiva/OptInModule.vue
https://kiva.atlassian.net/browse/MP-1178
> fix: looks like transition group might need else instead of multiple ifs

- src/pages/Thanks/ThanksPage.vue
- src/util/myKivaUtils.js
- test/unit/specs/util/myKivaUtils.spec.js
https://kiva.atlassian.net/browse/MP-1150
- We want to now show the MyKiva TY to all types of lenders
- We were getting uneven experiment assignment -> my current theory is that the slightly different users being assigned between TY and portfolio pages were affecting the assignment numbers, so we now only track assignment on the TY page
> feat: alter my kiva experiment assignment

- src/components/BorrowerProfile/CommentsAndWhySpecial.vue
- Comments section is showing after "why this loan is special" first when it should be last fixed
> feat: bp why special position fixed

- lighthouserc-prod.cjs
`/borrow` is in our top 10 most visited pages, so we're going to try improving the performance but first we need to start tracking the lighthouse scores.
> perf: analyze /borrow page with lighthouse

- src/pages/Portfolio/LendingStats/BadgesList.vue
- src/pages/Portfolio/LendingStats/BadgesSection.vue
- src/pages/Portfolio/LendingStats/LendingStatsPage.vue
- lending stats badges section updated
Desktop:
Tablet:
Mobile:
> feat: lending stats badges section updated

- src/pages/Portfolio/LendingStats/BadgesSection.vue
- lending stats badge section gray bg removed
> fix: lending stats badge section gray bg removed

- src/components/Thanks/SingleVersion/LoanComment.vue
- src/components/Thanks/ThanksPageSingleVersion.vue
https://kiva.atlassian.net/browse/MP-1329
Ported functionality from old TY page
> feat: add guest loan comment functionality to new ty page

- src/components/MyKiva/BadgeCompleted.vue
- Quotation marks around the fun fact removed
- Font size for the fun fact fixed to be h3
> feat: completed badge modal updates

- .storybook/stories/ThanksPageSingleVersion.stories.js
- src/components/Thanks/SingleVersion/BadgeMilestone.vue
- src/components/Thanks/ThanksPageSingleVersion.vue
https://kiva.atlassian.net/browse/MP-1334
- The simple equity version of the badge module should display when only donations or only kiva cards when there are no loans
> fix: adjust when badge module shown for kiva cards and donations

- src/components/MyKiva/EarnedBadgesSection.vue
- src/pages/Portfolio/MyKiva/MyKivaPage.vue
- stacked badges added to MyKiva page
https://kiva.atlassian.net/browse/MP-1367
> feat: mykiva stacked badges

- src/components/BorrowerProfile/LendCta.vue
- src/components/WwwFrame/TheHeader.vue
- src/pages/Lend/LoanChannelCategoryPage.vue
- src/pages/Lend/LoanSearchPage.vue
- src/pages/LoanFinding/LoanFinding.vue
Issue: With sticky header on mobile we were not able to show navigation correctly
Solution: Have static header on mobile as before across the site but showing ATB modal at top of the viewport
> fix: static header for mobile

- server/auth-router.js
This should make it so that we always attempt an sso connection via the login screen when using the ssoRedirect parameter.
> fix: force login screen to load for sso redirects

- src/api/HttpLink.js
This provides a way to send all operations through stellate with a `*` config value, allowing us to test using stellate for all operations in an isolated environment without changing production.
> feat: send all operations through stellate when wildcard is used

- build/fetch-schema.js
- server/dev-server.js
- server/index.js
- server/util/config.js
- test/unit/jest.conf.cjs
- test/unit/specs/server/live-loan-fetch.spec.js
ui server is currently failing in dev with `TypeError: Cannot read properties of undefined (reading 'userAgent')` in server/util/fetch.js. That means `config.server` is undefined, which shouldn't be happening if the config was initialized properly. I'm switching this to use a module-level await to load the config when the module is loaded, which I've confirmed fixes the error. However, the unit tests fail because they are still compiled to commonjs and don't have support for module-level await. I've temporarily ignored the failing test suite so we can unblock dev until the tests can be run as esm (vitest here we come)
> fix: config init not updating existing references

- src/pages/Portfolio/Donations/DonationsPage.vue
https://kiva.atlassian.net/browse/MP-1308
- Turns out we need to use options API to ensure child components with options API prefetch like expected -> there was pop-in with user status in header (which shouldn't happen in `ui`)
- Fixed another minor pop-in issue with loader found while testing
> fix: use options api to ensure perfetch works on new donations page

- src/pages/Portfolio/Donations/DonationsPage.vue
https://kiva.atlassian.net/browse/MP-1308
- Realized during QA that we needed to hide sections when there were no donations
- Smoothed out pop-in for spinner for mobile
> fix: hide sections when no donations and smooth out some loader pop-ins

- config/dynamic.js
- package-lock.json
- package.json
- src/client-entry.js
This allows for two things that noticeably improve performance:
- The apollo cache is maintained when the page is refreshed
- The apollo cache is **shared between ui and cps!** (see kiva/cms-page-server#1927)
I tried this out in the tilt VM and navigating between pages I had already visited was *much* faster. I didn't spot any problems with stale data or anything else, though I haven't tried checking out. We've already used the 'network-only' fetch policy for many of the queries that need to be up-to-date, so I don't expect that this would cause problems in any important user journeys.
I've set this up with a feature flag so that we can test it out in development and staging for a while before moving to production. The main difference is that data will stay cached much longer than it has …
> feat: persist apollo cache in session storage

- src/components/MyKiva/BadgesSection.vue
- avoid scrolling to journeys sections from my kiva hero carousel
> fix: avoid scrolling to journeys sections from my kiva hero carousel

- src/components/NotFound/NotFoundWrapper.vue
- src/components/Thanks/SingleVersion/JourneyGeneralPrompt.vue
- src/components/Thanks/ThanksPageSingleVersion.vue
- src/components/WwwFrame/Header/KvAtbModalContainer.vue
- src/composables/useMyKivaHome.js
- src/pages/Checkout/CheckoutPage.vue
- src/pages/Portfolio/ImpactDashboard/ImpactDashboardPage.vue
- src/pages/Thanks/ThanksPage.vue
- src/plugins/my-kiva-homepage-mixin.js
- src/util/myKivaUtils.js
- test/unit/specs/util/myKivaUtils.spec.js
https://kiva.atlassian.net/browse/MP-1516
- Use session cookie to ensure guests see the same MyKiva experiment assignment after account creation
- Usually we don't care too much about the edge case of before/after account creation assignment changing, but consistent experience is critical for MyKiva data analysis
- Fixed issue where we were showing the MyKiva pills in the checkout page if the ATB feature was disabled
> feat: ensure MyKiva assignment consistent through guest account creation

- src/components/WwwFrame/TheHeader.vue
- sticky header for large screen only reverted
> fix: sticky header for large screen only reverted

- package-lock.json
- package.json
- vite.config.js
- Newer version of `vite` now requires `allowedHosts` for security reasons
- NPM auto installs this version with our current package configs
> fix: local dev change requirement for newer vite version

- src/util/myKivaUtils.js
- test/unit/specs/util/myKivaUtils.spec.js
https://kiva.atlassian.net/browse/MP-1530
- Sets a cookie when a user sees MyKiva that can then be used at the CDN layer
- Goes along with: https://github.com/kiva/terraform/pull/438
> feat: create simple cookie for redirecting at cdn layer

- src/components/MyKiva/MyKivaSharingModal.vue
- src/graphql/query/myKiva.graphql
- src/plugins/social-sharing-mixin.js
https://kiva.atlassian.net/browse/MP-1550
- Bluesky requires the URL shared to be in the text, otherwise it isn't shown in the post
- We were missing the public ID in one share use case, so `undefined` was in the URL
- There was a console error for one share component that needed `apollo`
> fix: change how bluesky shares links

- config/dev-custom-host.js
- config/k8s-local.js
- server/dev-server.js
- vite.config.js
This moves the vite config options that were specific to `dev-custom-host` into that config file and merges them into the vite config when the server is created, which fixes the issue with hmr not working when using the `local` config.
This also fixes the issue with the tilt vm where vite won't run without monolith.kiva.local being added to allowed hosts. There is still a separate issue with hmr in the tilt vm related to ssl.
> fix: set vite options per config file

- index.html
There is an extra closing head tag before the preload links. Browsers seem to be correcting for this, which is why this hasn't caused any noticeable problems for months. I only found this when starting to make changes to the template and some of the head tags were not loading.
> fix: remove extra head closing tag

- src/assets/scss/_settings.scss
- src/assets/scss/app.scss
- src/components/Checkout/SocialShareV2.vue
- src/components/CorporateCampaign/CampaignLoanRow.vue
- src/components/Kv/KvButton.vue
- src/components/Kv/KvCarousel.vue
- src/components/Kv/KvDropdown.vue
- src/components/Thanks/ThanksPageCommentAndShare.vue
- src/components/Thanks/ThanksPageDonationOnly.vue
- src/pages/Possibility/GivingTuesday.vue
Mixins imported directly from foundation were not using the values defined in _settings.scss. This fixes that by providing all the foundation mixins from settings and only using settings in other files instead of using foundation.
> fix: ensure foundation mixins use settings variables

- vite.config.js
The server-entry built by vite has `import { create } from "timesync";`, and it doesn't bundle `timesync`, so node is trying to resolve it and running into the `require('promise')` issue. We have an internal package for using the node native Promise type, and we have the alias configured in vite, but vite has externalized `timesync` so the alias is never used. This PR makes vite not externalize `timesync` so that the `require('promise')` in `timesync` is replaced by our alias.
The dependencies for `@storybook/vue3-vite` include `promise`, so that's why we don't see this error locally, where we have all the dev dependencies installed.
> fix: ensure timesync is bundled for the server build

- src/components/WwwFrame/TheHeader.vue
There is an extra-wide gap in the header between the logo and the lend menu button for large screens when a user is logged in with a balance greater than $0. This gap is caused by a grid area that isn't being used but is configured to appear.
Before
After
> fix: remove header gap caused by non-existent grid area

- src/components/LoanFinding/LendingCategorySection.vue
- src/components/LoanFinding/PartnerSpotlightSection.vue
- src/components/LoanFinding/QuickFiltersSection.vue
- src/pages/LoanFinding/LoanFinding.vue
- src/plugins/is-bp-modal-enabled-mixin.js
Reinstates the usage of the `isBpModalEnabled` prop as the determinant for whether or not the `KvSideSheet` and `showLoanDetails` functionality are active in the LBC page.
> fix: mp-1730 / Add isBpModalEnabled prop to LoanFinding and associated components

- src/components/BorrowerProfile/BorrowerSideSheetContent.vue
- src/composables/useBorrowerProfileData.js
- src/graphql/query/borrowerProfileSideSheet.graphql
Adds the `isGuest` prop to the `LoanFinding` component and the `my { id }` graphql request to the `borrowerProfileSidesheet.graphql` file in order to toggle the huge amounts lending feature for non-guest users of the site.
> feat: mp-1744 / add huge lending amounts to LBC page

- src/components/Thanks/MyKiva/ThanksBadges.vue
- src/components/Thanks/ThanksPageSingleVersion.vue
- src/components/WwwFrame/Header/KvAtbModalContainer.vue
- src/composables/useMyKivaHome.js
- src/graphql/query/checkout/initializeCheckout.graphql
- src/graphql/query/portfolioQuery.graphql
- src/graphql/query/shared/myKivaForAllUsers.graphql
- src/graphql/query/thanksPage.graphql
- src/graphql/query/userAtbModal.graphql
- src/pages/Checkout/CheckoutPage.vue
- src/pages/Portfolio/ImpactDashboard/ImpactDashboardPage.vue
- src/pages/Thanks/ThanksPage.vue
- src/plugins/my-kiva-homepage-mixin.js
- src/util/myKivaUtils.js
- src/util/userPreferenceUtils.js
- test/unit/specs/util/myKivaUtils.spec.js
- test/unit/specs/util/userPreferenceUtils.spec.js
https://kiva.atlassian.net/browse/MP-1854
- Simplified logic for MyKiva experiment assignment
- Removed user preferences usage -> MyKiva experiment no longer needs check for number of loans
- Moved user preferences utils to dedicated file -> these aren't being used but seem useful to keep around
- Fixed issue where all users were taken to MyKiva from TY page regardless of experiment assignment
> feat: resolve issue with TY page redirect and simplify MyKiva experiment logic

- src/components/BorrowerProfile/CommentsAndWhySpecial.vue
Hotfix for MP-1753. Fixes the `disableCache` prop not properly triggering a re-load of the data at the child component level in the `CommentsAndWhySpecial` component, leading to the GraphQL query using `cache-first` as opposed to `network-only` as its fetching policy and thus returning the outdated set of comments.
> fix: mp-1753 – Create Watch for disableCache prop in BorrowerCarousel

- src/components/MyKiva/LatestBlogCarousel.vue
Tracking now includes the blog post’s category and title in the event label:  
`Blog-{category}:{title}` (e.g., `Blog-Impact:How Kiva Works`).  
This makes analytics more descriptive for each blog card interaction.
> feat: tracking data blog cards - data - fix

- src/components/MyKiva/JournalUpdateCard.vue
- src/pages/MyKiva/MyKivaPageContent.vue
Updated MyKiva update cards to align with design guidelines:
– Removed subject lines from transaction updates
– Adjusted repayment cards to keep "Success!" on the same line as repayment info
– For journal updates, replaced “Subject line” with “Re:” formatting
– Matched update card height to recent borrower cards
– Updated truncation rules to unify text length across all update cards
> feat: mp-1829-MyKiva Update card adjustments

- src/components/MyKiva/BorrowerStatusCard.vue
https://kiva.atlassian.net/browse/MP-1937
https://kiva.atlassian.net/browse/MP-1954
- Fixes to borrower carousel in portfolio and mykiva
- We were incorrectly showing emoji for "failed" loan statuses
- We were incorrectly called "ended" loans "defaulted"
> fix: resolve issue with incorrect loan status in borrower carousel

- src/components/GivingFunds/ManagementCard.vue
- src/pages/GivingFunds/GivingFundsManagementPage.vue
- Adds fundraising meter and copy to mgmt card when fund is active
- Improve fund active checks to include both NONE + IN_PROGRESS statues as well as a date check
- Hide the "Start a fundraiser" button if one is already active
- Fix utility menu styles
New:
Previously:
> fix: show fundraising meter for active funds, improve visibilty checks

- server/vue-middleware.js
- server/vue-render.js
- src/api/apollo.js
- src/api/localResolvers/experiment.js
- src/esiTags/head.js
- src/main.js
- src/server-app-render.js
- src/util/experiment/experimentUtils.js
- src/util/experiment/fastlyExperimentUtils.js
- test/unit/specs/api/localResolvers/experiment.spec.js
- test/unit/specs/server/vueMiddleware.spec.js
- test/unit/specs/util/experiment/experimentUtils.spec.js
Sync experiment handler with CPS logic, following the order:
1. fastly header variant/value 
2. query param from `setuiab` cookie
3. cookieStore
> fix: [MP-2046] issues with experiment header for nav with cache

- server/util/live-loan/live-loan-draw.js
Fixes broken image loading through node-canvas loadImage which doesn't support webp.
> fix: use jpeg image instead of webp to match node-canvas support
