kiva/ui

build/webpack.base.conf.js, build/webpack.client.base.conf.js, build/webpack.client.dev.conf.js, build/webpack.client.prod.conf.js
Move configs around a bit to make it easy to run alongside the Kiva vm.
=> Dev server vm

src/App.vue, src/assets/scss/_settings.scss
There will be more changes pending updated font work in styleguide.
=> Add in some base styles for font sizes

src/pages/LendingStats/LendingStatsPage.vue, src/pages/UueSiteMap/RouteListing.vue, src/pages/UueSiteMap/UueSiteMapPage.vue, src/router/routes.js, test/unit/specs/components/RouteListing.spec.js
Planning to pull these menus out into components (and add the mobile versions...) in those tickets. Just wanted to get a frame up and running.
=> Eng 2026 lending stats page

src/components/WwwFrame/LendMenu/CountryList.vue, src/components/WwwFrame/LendMenu/LendListMenu.vue, src/components/WwwFrame/LendMenu/LendMegaMenu.vue, src/components/WwwFrame/Menus/TheMyKivaSecondaryMenu.vue, src/components/WwwFrame/Menus/ThePortfolioTertiaryMenu.vue, src/components/WwwFrame/TheFooter.vue, src/components/WwwFrame/TheHeader.vue, src/plugins/kv-analytics-plugin.js
This is how I've started out...thoughts?
=> Basic click events based on current values and tracking libs.

src/pages/LendingStats/LendingStatsPage.vue
First commit in the UI server! 🎉
=> ENG-2054 small text update

server/vue-middleware.js, src/plugins/kv-analytics-plugin.js, test/unit/specs/components/WwwFrame/TheHeader.spec.js
A few little clean up items which should fix up the test warnings
=> Prevent analytics calls missing lib

src/components/WwwFrame/PromotionalBanner/Banners/GiftBanner.vue
=> vue-24 fixing kiva-dark-green box on large screens.

src/components/WwwFrame/PromotionalBanner/Banners/BonusBanner.vue
Minor fix for the call to numeral to get the bonus amount to 2 decimal points. 
Old format: $0
New format: $0.00
=> vue-26 adding .00 to dollar amount displayed in bonus banner.

src/components/WwwFrame/PromotionalBanner/Banners/GiftBanner.vue
Tiny commit, we want this bottom border.
=> vue-29 border bottom to gifts banner on xl down

src/components/WwwFrame/PromotionalBanner/Banners/WomensDayBanner.vue
Small update to fix the text color for the IWD banner, good catch Matt.
=> defining text color for IWD promo banner.

src/components/WwwFrame/PromotionalBanner/Banners/GiftBanner.vue
This took a bit more finessing than initially thought, but it's all fixed up now and looking good across the various screen sizes.
=> vue-28 fixing the spacing in the gifts banner.

src/components/LoanCards/BorrowerInfo.vue
Here are the changes you mentioned via email. Thanks for catching that.
=> requested changes for id type and default.

src/components/LoanCards/BorrowerInfo.vue
Adding tracking to borrower name and "read more" text on loan cards.
=> adding tracking to borrower-info pieces of loancard.

src/components/Kv/KvPagination.vue, src/graphql/query/loanCardData.graphql, src/pages/Lend/LendPage.vue, src/pages/Lend/LoadingOverlay.vue, src/plugins/apollo-mixin.js, src/util/apolloPreFetch.js
Not ready for merging quite yet. I'm just looking to get thoughts & opinions. Also, the loading spinner isn't working yet. There were other ways I could have gone about handling updating the query variables, so if there are any downsides to this I can explore other means.
=> VUE-34 pagination

package-lock.json, package.json, src/components/Forms/LoginForm.vue, src/components/Forms/RegisterForm.vue, src/plugins/formValidate.js
This replicates the current validation of the login & registration forms in production.
=> Feck 139k validation

src/graphql/query/initializeCheckout.graphql, src/pages/Checkout/CheckoutBetaPage.vue
And use that to show and hide login/reg and paypal.
=> Add User Data to Initialize Checkout Query

src/components/Forms/RegisterForm.vue
Made some updates to the vue password meter.
=> Updating the style of the password meter

src/components/Checkout/LoanPrice.vue
This should finish up 185 for now using the requirements as currently written.
=> Feck 185 6 more shares

src/components/LoansByCategory/FeaturedLoans.vue
This will allow the featured loans section to be rendered on the server so that we don't get the flash of unstyled content.
=> LC-56 provide prefetch variables for ssr

src/components/Checkout/BasketItemsList.vue, src/pages/Checkout/CheckoutBetaPage.vue
Minor margin fix as discussed.
=> feck-187 fixing margins bor basket items list.

src/components/Checkout/KivaCardRedemption.vue
Keeping it fresh with more style.
=> Feck 187 moar stylez

src/components/Checkout/LoanPrice.vue
I forgot to add scoped to this file's css, this is a small change making that update.
=> adding scoped to this file's css

src/components/WwwFrame/AppealBanner.vue
A typo made this branch name weird.
=> changing px to rem-calc()

src/components/Checkout/DonationItem.vue
Another tweak came in from adam
=> spacing donation input and update elements on smaller screens.

src/App.vue
These are the base tags we'd need for twitter. This set matches those tags on the homepage currently.
=> LW-1741 Add base twitter tags

src/components/WwwFrame/TheFooter.vue, src/graphql/query/protocolUiPage.graphql, src/pages/Protocol.vue
1. add the flag and GQL query. This has been tested on my VM with true and false and it behaves correctly. 
2. update the URL to be the correct one for the info link
3. update footer in ui server (flagged)
=> LW-1730 Add flag

src/components/Forms/LoginForm.vue, src/components/Forms/RegisterForm.vue, src/pages/Checkout/CheckoutBetaPage.vue, src/router/routes.js
!!! This has a sibling in Kiva (both should be merged and pushed to dev simultaneously)
=> Change /checkout-beta to /checkout to better future proof data analysis

src/components/Checkout/KivaCardRedemption.vue, src/pages/Checkout/CheckoutBetaPage.vue
I've added an event and updated the url in the promo area, you'll likely remove this once we get to that ticket.
=> Add events for kicking lenders to legacy flow

src/pages/Checkout/CheckoutBetaPage.vue
Small text update. I think it makes the text too long, but that's for adam to decided. Attaching screenshots of before and after to ticket. Text updated for the login and register cases.
=> register to checkout -> register to complete your loan

package-lock.json, package.json, src/api/HttpLink.js
=> Support batch graphql queries

src/components/Checkout/KivaCardRedemption.vue
This should fix that error up.
=> fixing this media query

src/components/Checkout/OrderTotals.vue
This branch fixes up the additional requests from adam for cash-9
=> Cash 9 further adjustments

src/components/Checkout/LoanPrice.vue
Minor css tweak to get all interactive elements on the page get a cursor: pointer on mouse over. Users first!
=> updating pointer events for all interactive elements we missed

src/pages/Checkout/CheckoutBetaPage.vue
Small fix found when QAing previously logged in user flow.
=> fix loading overlay position for previously logged in users

src/components/Checkout/BasketItem.vue, src/components/Checkout/TeamAttribution.vue
I would prefer to verify this is working before merging but here are the changes.
=> cash-14 dev error fixes

src/components/Checkout/TeamAttribution.vue
=> removing these console.logs

src/components/Checkout/LoanPrice.vue, src/components/Checkout/TeamAttribution.vue
There were style issues for other browsers (mainly IE) These changes fix those spacing issues.
=> Cash 14 bug fixes

src/components/Forms/RegisterForm.vue, src/graphql/query/register/registerData.graphql, src/graphql/query/register/registerExpData.graphql
Here is the object and my specific item I need pulled out correctly.  FYI: invitee data entry and the container i was putting the inviter name into didn't match up. Correction made, now invitee name is coming through correctly. Now I just need to do the front end for that ticket. But this should get that object in place for @ksekhri to use for the team stuff.
=> Getting invitee parameter data out of graphql

src/components/Checkout/DonationItem.vue
Small fix for the thanks text.
=> fix for uiexp.donation_boost setup

src/pages/Lend/LendByCategoryPage.vue
This is for the UI Server half of this ticket
=> CASH-367: Add snowplow tracking to /lend-by-category tip messages

src/components/Checkout/DonationItem.vue
Adding @horationunez and @mcstover for their reference
=> CASH-373: Fix IE11 Win 7 Bug by using v-show instead of v-if

src/components/LoansYouMightLike/lymlContainer.vue, src/graphql/query/loansYouMightLike/loansYouMightLikeData.graphql
* MinimalLoanCard is commented out temporarily so you can test the GQL query
=> CASH-101: GraphQL Query to get loans

src/components/LoansYouMightLike/lymlContainer.vue, src/pages/Checkout/CheckoutBetaPage.vue
Slide functionality part of the way there. loan cards do not stay in a row when screen size is small, they stack instead.
=> Cash 101 slide functionality

src/pages/Build/DocsPage.vue
added intro to graphql, links to explorer tool, and sample curl code.
=> ENG-2334 add graphql spotlight and sample curl command

src/components/WwwFrame/Menus/DeveloperSecondaryMenu.vue, src/pages/Build/GettingStartedPage.vue, src/router/routes.js
@ksekhri not sure when something is a page or a component? "Getting starting" is its own page on build.kiva.org so i just followed suit and made its own page based on DocPage.vue.
=>  ENG-2335-first draft of getting started page in Vue

src/pages/Build/BuildPage.vue
change string variable to html text
=> ENG-2333 - first commit for build docs 

src/components/WwwFrame/Menus/DeveloperSecondaryMenu.vue, src/pages/Build/TermsOfService.vue, src/router/routes.js
create new terms of service page
add route
add to terms of service to secondary menu
=> Eng 2338 terms of service

src/pages/Build/CodeOfConductPage.vue
cleaning up the file to remove import settings. The branch was merged and deleted before I could push the change.
=> remove import settings

src/pages/Build/CodeOfConductPage.vue, src/pages/Build/GettingStartedPage.vue
connect getting started page to Terms of Service and Code of Conduct pages
=> ENG-2350 add vue router-link tags

src/pages/Build/BuildPage.vue, src/pages/Build/CodeOfConductPage.vue
adding more terms of service links
porting overview text to Build landing page
=> ENG-2350 - add more links

src/components/Styleguide/StyleguideButtons.vue, src/pages/StyleGuide.vue
Moved this css into the related component and removed it from page level file. Just wanted to do this while it was on my mind. Less tech debt felt better, even if it was really minor.
=> moving styleguide button css into styleguideButtons.vue

src/components/WwwFrame/TheFooter.vue
update developer api link to point to kiva.org/build
=> change footer url link

src/components/Checkout/BasketItemsList.vue, src/components/Checkout/KivaCardRedemption.vue, src/components/Checkout/OrderTotals.vue, src/pages/Checkout/CheckoutPage.vue
=> Cash 461 cleanup

src/head/script.js
Here's one approach to using the new opted_out param in the kvgdpr cookie.
=> prevent load of 3rd party scripts if lender has opted_out

src/components/LoansByCategory/ViewToggle.vue
Hover state for filters toggle.
=> cash-566 hover states for view-toggle

src/components/Checkout/DonationItem.vue, src/components/Checkout/DonationNudge/DonationNudgeLightbox.vue, src/components/Checkout/DonationNudge/DonationNudgeLightboxBorrowerImage.vue
In preparation for a more complicated mobile header coming next
=> CASH-379: Refactor and decrease code repetition

src/pages/UiSiteMap/RouteListing.vue
@mcstover Thought the routes should be listed alphabetically
=> sort routes for ui site map (route listing)

package-lock.json, src/components/WwwFrame/Menus/DeveloperSecondaryMenu.vue, src/pages/Build/Research.vue, src/router/routes.js
Port http://build.kiva.org/docs/research page to kiva.org/build
=> Add research page

src/pages/Build/Research.vue
taking out the redundancy in the template v1  
added years array to data ()
=> refactor template with nested loops

src/components/Kv/KvPillToggle.vue
toggle functionality and styles in place for this new reusable pill toggle component.
=> reuseable pill toggle component

src/pages/AlgoliaPOC.vue
Here's a stub by which to start the sort drop down once we get to it.
=> Setup basic sort selector to use new dev replica indexes.

src/pages/Lend/Filter/FilterSectionCategories.vue, src/pages/Lend/Filter/LendFilterMenu.vue
Matt can you test to see if this fixes the issue on your machine too?
=> Wrap filters in their own file to allow DOM manipulation without resetting filters

src/components/Checkout/DonationItem.vue, src/graphql/query/checkout/donationData.graphql
```
uiexp.checkout_donation_100_text
{"name": "CheckoutDonation100Text","enabled": true,"startTime": "2018-08-29T00:00","endTime": "2020-02-05T17:00","control": {"key": "variant-a","name": "Control (variant-a)"},"variants": {"variant-b": {"name": "Checkout Donation 100 Text Exp"}},"distribution": {"variant-a": 0.5,"variant-b": 0.5}}
string
CASH-570: Checkout donation 100 Text
```
=> CASH-570: Use 100% language in tip text

src/components/LoansYouMightLike/lymlContainer.vue
=> updating exp name for lyml 4card

src/components/LoansYouMightLike/lymlContainer.vue
FYI @mcstover missed this previously somehow. Just gonna merge it in. Tested on my VM
=> One small fix to get this exp up and running correctly

src/components/Checkout/BraintreeCheckout.vue, src/components/Checkout/PaymentWrapper.vue
small change to satisfy request in cash-689
=> cash-689 sentence case

src/components/LoansYouMightLike/lymlContainer.vue
Another small change that fixes cash-568
=> cash-568 fixing alignment of lyml header

src/components/Kv/KvCheckbox.vue, src/pages/AlgoliaPOC.vue, src/pages/Lend/Filter/LendFilterPage.vue, src/plugins/algolia-config-mixin.js, src/plugins/algolia-init-mixin.js
Went ahead a broke out the Algolia config from the Algolia Init and updated in Lend/Filter (everything seems to be working fine there)
I'll have another PR later which activates counts on the custom categories.
=> Algolia refinement list research

src/components/LoanCards/ListLoanCard.vue
* This PR Also includes SASS/Foundation cleanups
=> CASH-404: Add FundraisingStatus to ListLoanCard

package.json, src/pages/AlgoliaPOC.vue, src/pages/Lend/Filter/LendFilterPage.vue, src/plugins/algolia-init-mixin.js, src/router/routes.js
Demo of how to create custom formatted url segments as a store for the page state and source for instantiating the page with a specified state.
=> Cash 634 algolia url state

src/components/Checkout/DonationNudge/DonationNudgeIntro.vue, src/components/Checkout/DonationNudge/DonationNudgeLightbox.vue, src/components/Kv/KvCharityNavigator.vue
Here are the spacing changes from Thuan for cash-721
=> Cash 721 padding

src/pages/Lend/Filter/ClearAllRefinements.vue, src/pages/Lend/Filter/LendFilterPage.vue, src/pages/Lend/Filter/SelectedRefinements.vue
* We also need to clear our custom refinements when we clear all refinements
=> CASH-552: Clear all fix

src/components/LoansYouMightLike/MinimalLoanCard.vue, src/pages/Checkout/CheckoutPage.vue
~@emuvente I think Matt and Josh are out today, can you take a look at this tiny bugfix?~
Oh cool @mcstover just reviewed, thanks Matt
=> CASH-232: Update basket when adding loan

src/components/Checkout/BraintreeCheckout.vue
Quick fix for something Talea noticed during demos.
=> fix senetence case Talea caught in demos

src/components/Checkout/BraintreeCheckout.vue
A text updated came down from product today, we'll have to get this into production once approved.
=> cash-814 text updated as requested from product

src/assets/scss/global/page-layout.scss, src/pages/Lend/AlgoliaPagination.vue, src/pages/Lend/Filter/FilterMenuSection.vue, src/pages/Lend/Filter/LendFilterMenu.vue, src/pages/Lend/Filter/LendFilterPage.vue, src/pages/Lend/Filter/SelectedRefinements.vue
This approach should work in more browsers than CSS based `smooth-scroll` and it lets us set the animation time (this timing is much more pleasant in my opinion). If we like it we can easily add an `xPosition` scrolling option in the future as well.
=> CASH-802: Filters design cleanup

src/components/LoanCards/Buttons/ActionButton.vue, src/components/LoanCards/Buttons/LoanExpiredText.vue, src/components/LoanCards/ListLoanCard.vue, src/components/LoanCards/LoanCardController.vue, src/components/LoanCards/MatchingText.vue
* There are still some questions left on the ticket but this is done for now
=> CASH-822: Correct loan cards for expired loans

src/components/WwwFrame/TheFooter.vue
Found this when happening to adjust styles for a random h1 caused the footer to act up
=> Use h2 for multiple headings

src/assets/scss/global/page-layout.scss, src/pages/Lend/Filter/FilterComponents/LendFilterMenu.vue
* Note: This needs to be tested on an iPhone once on Dev
=> CASH-824: Allow inertia scrolling of filter menu on mobile

src/components/LoanCards/ListLoanCard.vue, src/pages/Lend/Filter/FilterComponents/LendFilterMenu.vue, src/pages/Lend/Filter/LendFilterPage.vue, src/pages/Lend/LendByCategoryPage.vue, src/pages/Lend/LendHeader.vue, src/util/experimentPreFetch.js
```
uiexp.pinned_filter
string
{"name": "PinnedFilter","enabled": true,"startTime": "2018-08-29T00:00","endTime": "2020-02-16T15:00","control": {"key": "variant-a","name": "Control (variant-a)"},"variants": {"variant-b": {"name": "Pinned Filter Enabled"}},"distribution": {"variant-a": 0.5,"variant-b": 0.5}}
CASH-851: Pinned Filter Experiment
```
=> CASH-851: Pinned Filters experiment

src/graphql/query/fundedBorrowerProfile.graphql, src/pages/BorrowerProfile/fundedBorrowerProfile.vue, src/router/routes.js
These changes get the basic frame for the funded borrower profile constructed. New route created. Graphql query to get the data we need for the page in place. Another pull request for the /kiva/main site changes needed to configure this new route is coming momentarily.
=> Funded borrower profile

src/graphql/query/fundedBorrowerProfile.graphql, src/pages/BorrowerProfile/fundedBorrowerProfile.vue
These changes get all the graphql data populating in the skeleton of the funded borrower profile page.
=> cash-885 populating loan data on the funded borrower profile

server/auth-router.js, src/pages/ProcessBrowserAuth.vue, src/util/KvAuth0.js
I think this is what it would be needed in here to match up with kiva/kiva#7216
=> Redirect to handle post-authentication actions

src/components/LoanCards/ExpandableLoanCard/ExpandableLoanCard.vue, src/components/LoanCards/ExpandableLoanCard/ExpandableLoanCardCollapsed.vue, src/components/LoanCards/ExpandableLoanCard/ExpandableLoanCardExpanded.vue, src/components/LoanCards/ExpandableLoanCard/expandableLoanCardMixin.js, src/components/LoanCards/FundraisingStatus.vue, src/components/LoanCards/GridMicroLoanCard.vue, src/components/LoanCards/LoanCardController.vue, src/components/LoansByCategory/CategoryRow.vue, src/pages/Lend/LendByCategoryPage.vue, src/plugins/active-loan-mixin.js
* Design tweaks: Hide fundraising meter when loan is expiring soon
* Desktop tweak: Disable expansion on hover when card is under an arrow, add listener to collapse card when window is resized
* Cleanup see all loan cards
* Consolidate styles for ExpandableLoanCard
* Fix row scrolling distance
* Add more lifecycle hooks to cleanup visuals
* Animation tweaks
=> CASH-676: Polish

src/components/WwwFrame/EndOfYearAppealBanner/AppealBanner.vue
Kiva/ui side changes for midyear appeal banner update.
=> cash-943 midyear appeal bonus language updated

src/components/LoansByCategory/CategoryRowHover.vue
I just copy/pasted it for now so we both have a place for us to add our content
=> CASH-960: Duplicate CategoryRow.vue to separate hover logic

src/components/LoanCards/HoverLoanCard/HoverLoanCardSmall.vue, src/components/LoanCards/HoverLoanCard/hoverLoanCardMixin.js
* Cleanup HoverLoanCardSmall styling, cleanup outdated code, and extract props/methods shared with HoverLoanCard and HoverLoanCardLarge
=> CASH-961: Cleanup

src/components/Kv/KvFlag.vue, src/pages/BorrowerProfile/fundedBorrowerProfile.vue, src/pages/LendingStats/ItemList.vue
=> CASH-1019: Make Kv-Flag Scalable

src/components/LoanCards/FundraisingStatus.vue
* When a child component has a bound class, a class placed on that child by the parent is ignored
* This was worked around using a wrapper div
=> Fix a visual bug from mixing classes

src/pages/Lend/LendByCategoryPage.vue, src/util/experimentPreFetch.js
Settings Manager:
```
uiexp.hover_loan_cards
string
{"name": "HoverLoanCards","enabled": false,"startTime": "2018-08-29T00:00","endTime": "2022-02-16T15:00","control": {"key": "variant-a","name": "Control (variant-a)"},"variants": {"variant-b": {"name": "Hover Loan Cards"}},"distribution": {"variant-a": 0.5,"variant-b": 0.5}}
CASH-521: Hover Loan Cards
```
=> CASH-955: Hover Loan Cards Experiment

src/components/Kv/KvFlag.vue
* Prevents oddly shaped flags when using flex
=> Disallow flex-shrink on KvFlag

src/components/LoanCards/HoverLoanCard/HoverLoanCard.vue, src/components/LoanCards/HoverLoanCard/HoverLoanCardLarge.vue, src/components/LoanCards/HoverLoanCard/HoverLoanCardSmall.vue, src/components/LoanCards/LoanCardController.vue, src/components/LoansByCategory/CategoryRowHover.vue
* Greatly improve hover animation (left old transition for design review)
* Add functionality for switching expanded cards
* Add expansion arrow, expansion functionality, expansion animation
* Notify row of hover and detailed selection
=> CASH-960: Create structure for CategoryRowHover

src/components/Checkout/DonateRepaymentsToggle.vue
=> cash-1037 fixing up Cannot read property 'donationTotal' of undefined

src/pages/Checkout/CheckoutPage.vue
=> sentry-error-q fix.

src/assets/scss/components/loan-cards/hover-loan-card.scss, src/components/LoanCards/HoverLoanCard/HoverLoanCard.vue, src/components/LoanCards/HoverLoanCard/HoverLoanCardLarge.vue, src/components/LoanCards/HoverLoanCard/HoverLoanCardSmall.vue
Additions:
* Modularize hover cards so that dimensions can be changed and all transforms/animations will automatically update
* Increase SASS reuse
=> CASH-960: Modularize Hover Cards SASS

src/assets/scss/components/loan-cards/hover-loan-card.scss, src/components/LoansByCategory/CategoryRowHover.vue
* Cleanup and greatly simplify leftmost card behavior
* Update rightmost card behavior based on new width (220px collapsed) from upcoming design
* Force new widths from upcoming design (design breaking change)
=> Cleanup hover row logic preparing for new design

src/assets/scss/components/loan-cards/hover-loan-card.scss, src/graphql/query/lendByCategory/lendByCategory.graphql, src/pages/Lend/LendByCategoryPage.vue, src/util/experimentPreFetch.js
* Update timing of fetching experiment data to allow new image size
* Update image size, update animations base SASS height
=> CASH-1053: Update HoverLoanCardSmall design

src/components/LoanCards/HoverLoanCard/DetailedLoanCard.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/BorrowerStoryPanel.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/InfoPanel.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/LoanDetailsPanel.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/OverviewPanel.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/PartnerInfoPanel.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/TrusteeInfoPanel.vue, src/components/LoanCards/HoverLoanCard/LoanStoryPanel.vue, src/components/LoansByCategory/CategoryRowHover.vue, src/pages/Lend/LendByCategoryPage.vue
mobile & desktop are covered in this while tablet size will be getting a separate treatment
=> CASH-953 CASH-954 Basic expanded panel wierframes with animation

src/pages/BorrowerProfile/fundedBorrowerProfile.vue
=> capitalize loan status

src/components/LoanCards/HoverLoanCard/InfoPanels/BorrowerStoryPanel.vue
Reworked this after Shua's PR and suggestion.
=> destroying created, replaced with apollo call

src/components/LoanCards/HoverLoanCard/DetailedLoanCard.vue, src/components/LoanCards/LoanCardImage.vue
* Cleanup location/sector on tablet
* Cleanup image on desktop
* Support full width, vertically centered images to prep for tablet
=> Cleanup DetailedLoanCard

src/components/LoanCards/HoverLoanCard/HoverLoanCard.vue
I started simple. Once @rschoenbeck tests in dev we can add more details as necessary.
=> CASH-975: Hover Card Interaction Tracking (Large)

src/pages/Search/SentenceSearch.vue
a couple more spacing adjustments that came down from Adam
=> cash-1124 adjusting margins and placements

src/pages/Search/SentenceSearch.vue
Hopefully the last PR related to these tweaks.
=> cash-1124 more spacing tweaks from adam

src/pages/Search/SentenceSearch.vue
Hotfix pr to get cash-1124 changes into the release branch.
=> Cash 1124 changes

src/pages/Search/SentenceSearch.vue
Adding itemsInBasket to data return, fixes the reactivity of the lend now button on /start
=> adding itemsInBasket to data return

src/components/LoanCards/BorrowerInfo/BorrowerInfo.vue, src/components/LoanCards/BorrowerInfo/BorrowerInfoHeader.vue, src/components/LoanCards/ExpandableLoanCard/ExpandableLoanCard.vue, src/components/LoanCards/HoverLoanCard/DetailedLoanCard.vue
* Update event passing of `BorrowerInfoHeader` and `BorrowerInfo` components
* Handle events from `BorrowerInfoBody` in `ExpandableLoanCard` and `DetailedLoanCard`
=> CASH-976: Update trackInteraction event handling

src/components/LoanCards/HoverLoanCard/HoverLoanCard.vue, src/components/LoanCards/HoverLoanCard/HoverLoanCardLarge.vue, src/components/LoanCards/HoverLoanCard/HoverLoanCardSmall.vue
HoverLoanCardLarge:
* Add interaction tracking for BorrowerInfoName
* Enable basket interstitial
* Remove interaction tracking on image as we are tracking that interaction on the level of HoverLoanCard
HoverLoanCardSmall:
* Remove interaction tracking on image as we are tracking that interaction on the level of HoverLoanCard
=> Cleanup interaction tracking of HoverLoanCards

src/components/LoanCards/GridMicroLoanCard.vue, src/components/LoanCards/LoanCardController.vue
=> PIP-9 Change 'Expiring now!' alert text to 'Ending now!' on loan cards / borrower profile

src/components/LoanCards/HoverLoanCard/DetailedLoanCard.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/BorrowerStoryPanel.vue
Events Tracked:
All Panels
* Click close
* Click borrower name
* Click Lend Now
Overview Panel:
* Click Read full details
Borrower Story Panel:
* Read full story
=> CASH-976: Expanded Area Tracking

src/components/LoanCards/Buttons/ActionButton.vue, src/components/LoanCards/Buttons/CheckoutNowButton.vue, src/components/LoanCards/Buttons/Lend25Button.vue, src/components/LoanCards/Buttons/LendButton.vue, src/components/LoanCards/HoverLoanCard/HoverLoanCardLarge.vue
* 2 new props for `ActionButton`: `hideAddingToBasketText` and `minimalCheckoutButton`
=> CASH-1116: Ensure Checkout Now button and Loading state of HoverCardLarge stays on one line

src/components/LoansByCategory/CategoryRowHover.vue, src/pages/Lend/LendByCategoryPage.vue
* Add bound classes to CategoryRowHover, move classes from <CategoryRow> to parent div in LendByCategory page to prevent them from being overwritten
=> CASH-1140: Structural changes to Hover row

src/components/LoanCards/HoverLoanCard/HoverLoanCardLarge.vue, src/components/LoanCards/ListLoanCard.vue
These are related to the fixes in #1048
=> Cleanup trackInteraction in ListLoanCard and HoverLoanCardLarge

src/components/LoanCards/HoverLoanCard/DetailedLoanCard.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/InfoPanel.vue
* Adjust font-sizes, weights, and line-heights to match mockup
=> CASH-1143: Expandable section styling

src/components/LoanCards/HoverLoanCard/DetailedLoanCard.vue
* Generate tabs from an array to reduce code repetition
* Track clicking on tabs on desktop
=> CASH-976: Track Desktop Tabs

src/components/LoanCards/HoverLoanCard/InfoPanels/BorrowerStoryPanel.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/PartnerInfoPanel.vue
@BoulderBrains let's merge this into #1111, it'll restore the spinner and fix the CI issue
=> Restore loading spinner, use v-html

src/components/LoanCards/HoverLoanCard/InfoPanels/BorrowerStoryPanel.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/LoanDetailsPanel.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/PartnerInfoPanel.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/TrusteeInfoPanel.vue
Well, I wasn't able to figure out the loading spinner issue. But here are some spacing tweaks to the data displayed on the partner/trustee, story & detail panels so it looks cleaner.
=> Cleaning up spacing

src/components/LoanCards/HoverLoanCard/InfoPanels/InfoPanel.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/LoanDetailsPanel.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/PartnerInfoPanel.vue, src/components/LoanCards/HoverLoanCard/InfoPanels/TrusteeInfoPanel.vue
Some tweaks for the hover loan card that's launching monday.
=> Hover card tweaks

src/pages/BorrowerProfile/fundedBorrowerProfile.vue
Cleaning up remaining cash-847 experiment.
=> scash-1189 cleaning up remaining code from cash-847 experiment

src/pages/Homepage/Homepage.vue
=> adding ID to homepage for automation hook for david

src/components/Checkout/DonationNudge/DonationNudgeBoxes.vue
* Fix NaN being sent with custom donations
=> CASH-1175: Clean up tip lightbox tracking

src/components/Homepage/CategoryGrid.vue
This is going to be brought up to production once reviewed.
=> cash-1217 fixing category card links

src/components/WwwFrame/TheHeader.vue
Tested this out on my vm and it does work. Weird side effect: pop-up is shown really quickly before the redirect to the /login url. 
popup is shown, then closed and user is left on login page.
=> cash-1247 if user logins from homepage, redirect them to the login URL

package-lock.json, package.json
This includes a fix for catching the SyntaxError that we've been seeing on the checkout page https://sentry.io/organizations/kiva/issues/1048827483/ 
https://github.com/auth0/auth0.js/pull/948
=> Upgrade auth0-js to v9.11.3

src/api/apollo.js
See https://github.com/apollographql/apollo-client/pull/4543
=> Freeze apollo cache results for performance

src/components/WwwFrame/TheHeader.vue, src/pages/Checkout/CheckoutPage.vue, src/util/KvAuth0.js
Hotfix #1193 and #1194 to production
=> AUTH-243 hotfix

src/components/Checkout/DonationItem.vue
Brandon messaged me this morning saying the final text for the donation line exp had been updated since I last looked. This commit gets the final text in for this experiment.
=> cash-1282 text update came in hot

src/components/Kv/KvCharityNavigator.vue
Hides this from both the tip nudge and the protocol page
=> WEBBUG-2755 hide this for now

src/api/localResolvers/experiment.js, src/util/experimentPreFetch.js, src/util/settingsUtils.js, test/unit/specs/util/settingsUtils.spec.js
This function will produce a one-way hash representing the value of a passed string.
=> Add hashCode function for use in creating the uiab cookie

src/pages/Homepage/HeroSlideshow.vue
switched double arrow characters: ">>" -> "»"
=> double arrow exp character fix

src/assets/scss/_settings.scss, src/components/Styleguide/StyleguideColors.vue
New green defined to be used for the kv-toggle component
=> new green color

Developer_Tools.md
* Fixed some minor MD linting warnings
* Small formatting changes
* Added optional workspace settings for VSCode and VSCode 1 liner to install extensions
=> Updated Developer_Tool.md

src/api/localResolvers/autolending.js, src/components/Kv/KvToggle.vue, src/graphql/query/autolending/countryList.graphql, src/pages/Autolending/AutolendingPage.vue, src/pages/Autolending/CheckList.vue, src/pages/Autolending/CountryFilter.vue, src/pages/Autolending/LightboxFilter.vue
This includes a `LightboxFilter` component that will also be used for the sector, partner, and attribute filters.
=> CASH-1371 autolending country filter

src/graphql/query/autolending/partnerList.graphql, src/pages/Autolending/AutolendingPage.vue, src/pages/Autolending/CheckList.vue, src/pages/Autolending/FloatingCounter.vue, src/pages/Autolending/LightboxFilter.vue, src/pages/Autolending/PartnerFilter.vue, src/pages/Autolending/SaveButton.vue, src/plugins/apollo-plugin.js
This also includes a fix for logging readQuery errors for queries without names, and the hide/show advanced settings toggle.
=> CASH-1373 Partner filter

src/components/Checkout/PaymentWrapper.vue, src/graphql/query/checkout/checkoutSettings.graphql, src/graphql/query/checkout/initializeCheckout.graphql, src/pages/Checkout/CheckoutPage.vue
* Cleaned up experiment code from CASH-627 - Braintree vs Paypal default checkout
=> CASH-1468 Clean Up Experiment Code

src/pages/Legal/PromoTermsOfUse.vue, src/pages/Legal/TermsOfUse.vue
=> Updated links on menu for new Promo TOU and TOU

src/pages/Autolending/AutolendingPage.vue
CASH-1494 is complete so this can be enabled
=> CASH-1462 enable loan increment filter

src/pages/Lend/LoanChannelCategoryPage.vue
* If the page query param is out of range in the lend by category page, instead of throwing a 500 error, navigate to last page and display a tip message
=> VUE-169 Page out of range in lend by category

.stylelintrc, src/api/fixtures/AutolendProfile.js, src/graphql/fragments/autolendProfile.graphql, src/pages/Autolending/AutolendingPage.vue, src/pages/Autolending/LendTimingDropdown.vue
* Adds auto lend timing dropdown to new autolend settings page
CASH-1198
=> CASH-1198 Auto lend timing settings dropdown

src/pages/Build/Research.vue
add new research paper to Kiva's research page
=> add research paper about Kiva images

src/pages/Possibility/Possibility.vue, src/router/routes.js
=> Create Possibility page frame. Redirect to certain campaign pages depending on date

build/webpack.base.conf.js, config/dev-vm.js, config/dev.js, config/index.js, package-lock.json, package.json, src/api/localResolvers/contentfulCMS.js, src/api/localSchema.graphql, src/components/WwwFrame/PromotionalBanner/Banners/GenericPromoBanner.vue, src/components/WwwFrame/PromotionalBanner/GlobalPromotionalBannerContentful.vue, src/components/WwwFrame/WwwPage.vue, src/graphql/fragments/experimentVersion.graphql, src/graphql/query/promotionalBanner.graphql, src/main.js, src/util/settingsUtils.js, test/unit/jest.conf.js, test/unit/specs/util/settingsUtils.spec.js
* Added local resolvers/schema to fetch content from contentful
* Added GlobalPromotionalBanner component to fetch banner settings and banner content from contentful
* Added contentful dependencies and alias to allow them to work
* Modified settingsUtils to handle dates from contentful
* Added contentful settings to app config
VUE-167
=> Get content from Contentful

src/pages/Possibility/Possibility.vue
if you land on /possibility and it's before dec3
=> Default to /possibility/giving-tuesday 

src/util/KvAuth0.js
VUE-176
Fixes a server compile warning about superagent in a non-browser environment
=> Vue 176 auth0 superagent warning

src/api/apollo.js, src/api/localResolvers/contentfulCMS.js, src/main.js
Contentful local resolver wasn't getting the proper config file to determine environment, it was just getting the values in the index.js config. This fixes that
=> Fixes contentful environment config on the ui

src/components/WwwFrame/EndOfYearAppealBanner/AppealBanner.vue
=> cash-1551 updating feature.endoyyear appeal banner text

src/pages/Possibility/KivaContentBlock.vue
Found a bug in dev for the /possibility/giving-tuesday page.
=> fixing img alignment on medium down screens

src/pages/Possibility/GivingTuesday.vue
While doing QA on this page, I found this small link issue, this fixes it up.
=> fixing CTA on /giving/tuesday

src/pages/Possibility/KivaContentBlock.vue
Found an IE 10 issue with my slideshow, this fixes it!
=> fix for kivaContentBlock on IE

src/api/localResolvers/contentfulCMS.js, src/components/LoanCards/BorrowerInfo/BorrowerInfoBody.vue, src/components/LoansByCategory/FeaturedHeroLoan.vue, src/plugins/index.js, src/plugins/loan-use-filter.js, test/unit/specs/plugins/loanUseFilter.spec.js
=> Added vue filter for taking loan params and returning loan use string

package-lock.json
* Updated dependency dependencies browserslist and caniuse-lite to get rid of outdated warning on build
VUE-177
=> Updated browserslist and caniuse-lite dependencies

package-lock.json, package.json
- Implemented husky git hooks for linting before pre-push, and destroy cache on branch checkout. 
- Updated several deep dependencies to fix 'npm audit' security issues
VUE-183 VUE-182
=> Husky githooks

config/index.js, config/stage.js, src/api/localResolvers/contentfulCMS.js
=> Added enable property for Contentful, disabled contentful in stage

src/api/localResolvers/contentfulCMS.js, src/components/WwwFrame/PromotionalBanner/GlobalPromotionalBannerContentful.vue, src/graphql/query/contentfulCMS.graphql, src/graphql/query/promotionalBanner.graphql, src/pages/Homepage/Homepage.vue, src/pages/Possibility/12DaysOfLending.vue
Implements local caching in localStorage and reduction of calls to contentful API. Client should not make same contentful request more than once every 30 minutes. 
CASH-1627
=> Cash 1627 contentful local caching

src/components/WwwFrame/EndOfYearAppealBanner/AppealBanner.vue, src/components/WwwFrame/PromotionalBanner/GlobalPromotionalBannerContentful.vue, src/components/WwwFrame/TheBannerArea.vue, src/components/WwwFrame/WwwPage.vue
* Consolidates logic of what should be shown above the header in 1 place.
* Fixes bug CASH-1629
* Removes duplicate code between appeal banner and global promo banner
=> New Component banner area

src/pages/Possibility/KivanSlider.vue
Just had to make a couple spacing adjustments once it was in place on the page.
=> spacing adjustments to fit within page correctly

.storybook/stories/KvCheckbox.stories.js, .storybook/stories/KvDropdownRounded.stories.js, .storybook/stories/KvPillToggle.stories.js, .storybook/stories/KvRadio.stories.js, .storybook/stories/KvToggle.stories.js, src/assets/scss/_settings.scss, src/components/Checkout/BraintreeCheckout.vue, src/components/Kv/KvPillToggle.vue
- Change from @ clicks on spans to radio buttons for a11y. Add disabled, hover, active, and focus styles
- Add .stories for KvPillToggle
- Create Form Elements subfolder in Storybook
No visual differences from the previous component aside from the hover, focus, and active states being added. No changes to the props or events. Now usable with a keyboard. 
Verified on 
https://www.kiva.org/checkout
https://www.kiva.org/lend/filter?gender=female&sortBy=popularity
=> VUE-188 KvPillToggle Storybook and a11y improvements

src/components/LoanCards/LoanCardImage.vue
=> Lazy load images on load cards

server/index.js
=> Add long term cache headers for static files

src/components/WwwFrame/CookieBanner.vue
Removing the h3 header from the /kiva/ui side
=> cash-1471 removing h3 in banner

src/components/Kv/KvResponsiveImage.vue, src/components/LoanCards/PromoGridLoanCard.vue
=> Added ImageDensity check for MG promo grid cards

.storybook/stories/KvFormKitchenSink.stories.js, .storybook/stories/KvPillToggle.stories.js, src/components/Checkout/PaymentWrapper.vue, src/components/Kv/KvPillToggle.vue, src/pages/Lend/Filter/FilterSections/Gender/PillToggleWrapper.vue
=> Use label for="id" pattern instead of wrapping with label

.storybook/stories/KvCheckbox.stories.js, .storybook/stories/KvFormKitchenSink.stories.js, .storybook/stories/KvToggle.stories.js, src/assets/scss/_settings.scss, src/components/Kv/KvCheckbox.vue, src/components/Kv/KvRadio.vue, src/components/Kv/KvToggle.vue, src/pages/Autolending/CheckList.vue, src/pages/Autolending/MainToggle.vue
- Make KvToggle's props and events mirror KvCheckbox. 
- Add focus, active, and disabled styling
- Add to storybook
- Update usage within the site
=> VUE-198 KvToggle 

.storybook/config.js, .storybook/stories/GenericPromoBanner.stories.js, .storybook/stories/GlobalPromoBanner.stories.js, .storybook/stories/GlobalPromoBannerContentful.stories.js, .storybook/stories/PromoGridLoanCard.stories.js, .storybook/webpack.config.js, src/components/WwwFrame/PromotionalBanner/Banners/GenericPromoBanner.vue, src/components/WwwFrame/PromotionalBanner/GlobalPromotionalBannerContentful.vue
* Story clean  up
* Added apollo mocking for global promo component
* Added svg sprite generation for storybook
VUE-196
=> Sample story for component that depends on Apollo

.storybook/stories/KvFormKitchenSink.stories.js, .storybook/stories/KvRangeSlider.stories.js, src/components/Kv/KvRangeSlider.vue, src/pages/Lend/Filter/FilterComponents/FilterRangeSlider.vue
- Create a presentational component based on the slider in the lend filter page.
- Allow v-model or :value binding
- Ensure a label element is used and that the value of the slider is not part of the label.
- Update usage in the site
=> VUE-199 KvRangeSlider

config/dev-vm.js, config/dev.js, config/index.js, config/qa.js, config/stage.js, src/App.vue, src/components/WwwFrame/IntercomMessenger.vue, src/util/experimentPreFetch.js
* Implements intercom messenger on all pages based on build setting to enable it, and also experiment setting to control distribution
CASH-1680
=> Intercom Messenger

Developer_Tools.md
change link to the official plugin (the previous one linked is no longer available)
=> update link to stylelint plugin

src/pages/Build/Research.vue
updating links
adding intro text to research page
=> update Build research page

src/components/WwwFrame/IntercomMessenger.vue, src/graphql/query/userInfo.graphql
* Added userId, Name, Email to intercom initialization code if available
* Added kvTrackEvent when widget is opened
CASH-1723
=> Inhance Intercom Integration

src/pages/MonthlyGood/MonthlyGoodPage.vue, src/router/routes.js
=> Added temporary route for development of new monthly good page

.storybook/stories/KvCurrencyInput.stories.js, .storybook/stories/KvFormKitchenSink.stories.js, package-lock.json, package.json, src/components/Kv/KvCurrencyInput.vue, src/pages/MonthlyGood/LandingForm.vue, src/pages/MonthlyGood/MonthlyGoodPage.vue
* Implemented MG form that is repeated twice on the page, forms sync values
* Form has validation using vuelidate library
* Form amount input is a currency type input with input sanitation and formatting and rounding
CASH-1734
** Remember to add - `RewriteCond %{REQUEST_URI} ^/monthlygood-ui$ [OR]` - to your server side .htaccess to be able to see the new page.
=> Cash 1734 mg landing form

src/pages/Thanks/ThanksPage.vue
Perhaps you only had a donation
=> Prevent errors when checking out without a purchased loan

src/components/Checkout/CheckoutReceipt.vue
=> Add nodes for QA automation

.storybook/stories/CheckoutReceipt.stories.js, .storybook/stories/SocialShare.stories.js, server/auth-router.js, server/session-router.js, src/components/Checkout/SocialShare.vue, src/graphql/query/checkoutReceipt.graphql, src/pages/Thanks/ThanksPage.vue
=> Team invite functionality for social share

src/pages/Thanks/ThanksPage.vue
=> Remove "hide receipt" button

.storybook/stories/CheckoutReceipt.stories.js, src/components/Checkout/CheckoutReceipt.vue, src/graphql/query/checkoutReceipt.graphql
=> Hook up KivaCard print button

src/pages/MonthlyGood/AlreadySubscribedNotice.vue, src/pages/MonthlyGood/LandingForm.vue, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue, src/pages/MonthlyGood/MonthlyGoodSetupPage.vue, src/router/routes.js
* Wired up going from MG Landing page to MG Setup page, including use cases for visitors and users who are already signed up for MG
CASH-1800
=> MG Landing Page to Setup Page Interaction

src/components/Homepage/CategoryGrid.vue
=> Fix up IE homepage category grid

src/assets/inline-svgs/icons/pencil.svg, src/pages/MonthlyGood/LandingForm.vue, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue, src/pages/MonthlyGood/MonthlyGoodSetupPage.vue, src/plugins/loan-group-categories.js, src/router/routes.js
* Implemented monthly good setup form. Replicating the behavior of the legacy form mobile version. No submit functionality.
Included functionality: 
* Form validation for donation amount and mg amount. 
* Validation and formatting of day of month. 
* Drop down % calculation based on initial values, 
* Freezing of drop down values once user has interacted with it. 
* Toggle between dropdown and input based on certain conditions
* Checkbox and input interactions. 
URL: 
https://dev-vm-01.kiva.org/monthlygood-ui/setup?amount=100&group=default
query params are optional but should be populated from landing page. 
Required /kiva/kiva htaccess lines to test: 
```
RewriteCond %{REQUEST_URI} ^/monthlygood-ui$ [OR]
RewriteCond %{REQUEST_URI} ^/monthlygood-ui/setup$ [OR]
```
CASH-1738
=> Monthly Good Setup Form

src/pages/Build/Research.vue
add Bin Wang research paper to 2019 papers.
=> update research page with new citation

src/components/Checkout/CheckoutReceipt.vue
Let's QA differentiate between a loan, a kiva card, and a donation on the receipt.
=> Add a selector for QA

src/pages/Autolending/LendTimingDropdown.vue, test/e2e/specs/AutolendingPage.spec.js
Fix for webbug-2812 (https://kiva.atlassian.net/browse/WEBBUG-2812)
=> webbug-2812 adding a null check for display of text

src/pages/MonthlyGood/MonthlyGoodSetupPage.vue, src/pages/MonthlyGood/PayPalMG.vue
* Will correctly setup a monthly good subscription for
users with paypal either through checkout if no
billing agreement present or through confirm if
they have a billing agreement
* Displays a series of messages on form depending on user flags
CASH-1795, CASH-1739
=> Add checkout functionality to the MG Setup form

src/pages/Autolending/LendTimingDropdown.vue, test/e2e/specs/AutolendingPage.spec.js
=> Cash 1745 90 day setting messages

config/dev-vm.js, config/dev.js, config/index.js, config/qa.js, config/stage.js, src/components/Checkout/PayPalExpress.vue, src/pages/MonthlyGood/AlreadySubscribedNotice.vue, src/pages/MonthlyGood/LegacySubscriberNotice.vue, src/pages/MonthlyGood/MonthlyGoodSetupPage.vue, src/pages/MonthlyGood/PayPalMG.vue
* Added a legacy subscription notice for users who have a legacy sub.
* Removed some unused css classes
* Added paypal url and environment variable
CASH-1736
=> MG Legacy Subscription Notice

src/pages/MonthlyGood/MonthlyGoodSetupPage.vue
* Adds kvtrack event for legacy sub and has monthly good on the monthly good setup page.
CASH-1810
=> Additional MG Setup Form Events

src/util/apolloPreFetch.js
This adds 2 things to the apollo error handling
- Checking for the error code in both `error.extensions.code` and `error.code`
- Warning when an error is unhandled
=> VUE-214 Refactor apollo error handling

.storybook/stories/TheHeader.stories.js, src/components/WwwFrame/TheHeader.vue
* Allows[ theming of the header](https://github.com/kiva/ui/pull/1482/commits/cc8ca5bcbf7c5e81a6776f67d67a5f3e1e20a1a2) using any colors you like. Browsers who don't support CSS custom properties (IE11 and below) get the default colors
* Wraps much of the header contents in a <nav> element as an accessibility landmark
* Storybook it up
=> CASH-1860 header theming

server/session-router.js
Making these changes based on these docs
https://www.npmjs.com/package/express-session#cookiesecure
=> Trust cookies from proxy and set secure state based on connection type

src/components/WwwFrame/PromotionalBanner/Banners/GenericPromoBanner.vue
* Made link in global promo banner not be required, if link is missing, banner will render correctly
* Also fixed banner icon shrinking
VUE-216
=> Fix for Link in Global Promo Banner

src/graphql/query/lendByCategory/experimentAssignment.graphql, src/pages/BorrowerProfile/fundedBorrowerProfile.vue, src/pages/Lend/LendByCategoryPage.vue, src/pages/Lend/LoanChannelCategoryPage.vue, src/pages/MonthlyGood/KivaAsExpert.vue, src/pages/MonthlyGood/LandingForm.vue, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue, src/pages/MonthlyGood/MonthlyGoodSetupPage.vue, src/pages/MonthlyGood/MonthlyGoodThanksPage.vue, src/router/routes.js
* Minor CSS adjustments to current MG landing page.
* New CSS for experiment version of MG Landing Hero
* Added Experiment flag to toggle MG Landing page hero layout
CASH-1774
=> Monthly Good Landing Page Hero Experiment

config/index.js, config/qa.js, server/index.js, server/session-router.js
This should pull the updates we made with the migration into master.
=> Migrate prod updates

src/components/WwwFrame/Menus/CustomSecondaryMenu.vue, src/components/WwwFrame/Menus/DeveloperSecondaryMenu.vue, src/components/WwwFrame/SecondaryMenu.vue, src/pages/Legal/Legal.vue, src/pages/Legal/PromoTermsOfUse.vue, src/pages/Legal/TermsOfUse.vue, src/router/routes.js
* Implemented nested templates for legal pages
* Added secondary navigation menu on mobile for terms of use and promo terms
* Fixed CSS of 'basically' arrow not being aligned properly.
VUE-218
=> Terms Mobile Navigation and cleanup

src/pages/MonthlyGood/EmailPreview.vue, src/pages/MonthlyGood/LandingForm.vue, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue, src/pages/MonthlyGood/MonthlyGoodSetupPage.vue
* Design only changes for CASH-1774
=> Design Changes for Monthly Good Landing and Setup Form

src/components/LoansByCategory/FeaturedHeroLoanWrapper.vue
=> topSectorId too

src/components/Checkout/DonationItem.vue
* Added donation language for matched donation based on retired exp setting
CASH-1855
=> Donation language for matched donations in checkout

config/stage.js
Updating the memcache location in stage
=> Use stage memcache cname

src/api/fixtures/AutolendProfile.js, src/graphql/fragments/autolendProfile.graphql, src/pages/Autolending/AutolendingPage.vue, src/pages/Autolending/DonationDropdown.vue, src/pages/Autolending/FloatingCounter.vue, src/pages/Autolending/KivaChoosesRadios.vue, src/pages/Autolending/LendTimingDropdown.vue, src/pages/Autolending/MainToggle.vue, test/e2e/specs/AutolendingOptOutPage.spec.js, test/e2e/specs/AutolendingPage.spec.js, test/e2e/specs/Example.spec.js
This adds the ui elements and cypress tests for CASH-1204 the Kiva Chooses For Me toggle on the autolending settings page. This pairs with https://github.com/kiva/kiva/pull/8361
=> CASH-1204 Add Kiva Chooses toggle to Autolending settings page

deploy/charts/templates/deployment.yaml, deploy/charts/templates/service.yaml, deploy/charts/values.yaml, deploy/dev/values.yaml
- Consolidating port configurations to a single value
- remove unnecessary port 443 inclusion
- reduce duplication in ingress configuration, so common values are in main chart, overrides at environment level
=> Ingress config

src/pages/Build/Research.vue
=> fix researcher's name

src/components/WwwFrame/TheFooter.vue
=> webbug-2811 updating link in ui footer

src/pages/Autolending/AutolendingMessagingPage.vue
=> Copy changes to oneclick autolending disable copy

.storybook/stories/GlobalPromoBannerContentful.stories.js, src/api/localResolvers/contentful.js, src/api/localSchema.graphql, src/components/WwwFrame/PromotionalBanner/GlobalPromotionalBannerContentful.vue, src/graphql/query/contentful.graphql, src/graphql/query/contentfulCMS.graphql, src/pages/Autolending/AutolendingSettingsPage.vue, src/pages/Homepage/DefaultHomepage.vue, src/pages/MonthlyGood/EmailPreview.vue, src/pages/PageTwo.vue, src/pages/Possibility/12DaysOfLending.vue, src/util/contentfulUtils.js
* Changes contentful local resolver schema to match federation contentful
* Changes response handling to match federation responses
VUE-227
=> Contentful Schema Change

src/pages/Autolending/LendTimingDropdown.vue, test/e2e/specs/AutolendingPage.spec.js
* Change autolending start date messaging to May 21
AUTO-12
=> Change autolending date

src/pages/MonthlyGood/MonthlyGoodSetupPage.vue
Attempt to set up a monthly good subscription. It will fail
=> ENG-2925: Fixing strict typing error in monthly good setup

src/pages/Autolending/AutolendingMessagingPage.vue, src/router/routes.js
* Added messaging/route for 1 click autolending pause for x days
AUTO-27
=> Implemented 1 click autolend pause

src/pages/BorrowerProfile/fundedBorrowerProfile.vue
* /funded/ page will sometimes error, this changes the redirect to use the router instead of window.location
VUE-174
=> Fixes window undefined in server side catch for redirect

src/plugins/loan-group-categories.js
Added US Borrowers Category for MG landing/setup pages
AUTO-74
Do not merge until backend work is also complete
=> AUTO-74 Added US Borrowers Category for MG landing/setup pages

src/pages/Build/Research.vue
updated Research Page with new link
=> add Cynthia Cryder paper

src/components/Checkout/PaymentWrapper.vue, src/graphql/query/checkout/braintreePayWithData.graphql
=> Add experiment to show/hide "Pay With" on the braintree payment form

src/components/Checkout/OrderTotals.vue
=> Fix checkout page regression brought in with icon overhaul

src/components/WwwFrame/TheAppInstallBanner.vue, src/components/WwwFrame/WwwPage.vue, src/plugins/app-install-mixin.js
Remove custom android button, use stock.
Since we no longer have a template element, convert to a mixin.
GROW-59
=> App install banner 

src/components/Kv/KvLightbox.vue, src/components/Lightboxes/ContentfulLightbox.vue, src/pages/Thanks/ThanksPage.vue
VUE-258
This is a contentful lightbox wrapper which takes content from contentful, and puts it in a kv-lightbox component.
Does not yet support embedding of videos in the lightbox. 
Sample lightbox is on contentful dev.
=> Contentful powered lightbox for thanks page

src/components/WwwFrame/TheHeader.vue, src/pages/Checkout/CheckoutPage.vue
reverts 9c02a222d34ebc9a96e8d834dabba9a51906f9ce
=> VUE-255 Re-enable popup login

src/pages/MonthlyGood/LandingFormExperiment.vue, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
https://kiva.atlassian.net/browse/GROW-11
```
mg_amount_selector
```
```
{"name":"MonthlyGoodAmountSelector”,”enabled":true,"startTime":"2020-01-01T10:00","endTime":"2025-01-02T10:00","control":{"key":"control","name":"Control"},"distribution":{"control”:0.5,”shown”:0.5}}
```
=> Expui grow 11 monthly good landing amount selector

src/components/Checkout/DonationItem.vue, src/graphql/query/checkout/donationData.graphql
Change the tip line item in /checkout to include copy tied to our COVID-19 relief efforts
=> Experiment grow 74 covid 19 text to tip line

.storybook/stories/TheHeader.stories.js, src/components/WwwFrame/PromotionalBanner/Banners/BonusBanner.vue, src/components/WwwFrame/PromotionalBanner/Banners/LendingRewardsBanner.vue, src/components/WwwFrame/PromotionalBanner/PromoBannerLarge.vue, src/components/WwwFrame/TheHeader.vue, src/pages/LandingPages/MGCovid19/MGCovid19.vue, src/pages/LandingPages/MGCovid19/MGCovidExplained.vue, src/pages/LandingPages/MGCovid19/MGCovidFAQ.vue
If we have a custom theme, use those colors in header promo banners.
=> Header theme updates, COV feedback tweaks

src/components/Forms/MultiAmountSelector.vue
Fixes a bug where the validation message could be incorrect for one-time contributors.
=> COV custom amount validation fix

src/pages/LandingPages/MGCovid19/MGCovid19.vue, src/pages/LandingPages/MGCovid19/MGCovidHero.vue
=> Break COV hero into it's own component for reuse

.storybook/stories/KvCheckoutSteps.stories.js, src/components/Kv/KvCheckoutSteps.vue, src/pages/Checkout/CheckoutPage.vue, src/pages/Thanks/ThanksPage.vue
For re-use in the new Monthly Good Setup page design
=> Convert CheckoutSteps component to a generic KvComponent

src/pages/Homepage/DefaultHomepage.vue, src/pages/LandingPages/MGCovid19/MGCovidHero.vue
=> GROW-79 Replace home page hero with MG sign-up form

src/pages/Autolending/AutolendingSettingsPage.vue, src/pages/Autolending/AutolendingWho.vue, src/pages/Autolending/DefaultRateDropdown.vue, src/pages/Autolending/GenderRadios.vue, src/pages/Autolending/GroupRadios.vue, src/pages/Autolending/InlineCounter.vue, src/pages/Autolending/LightboxFilter.vue, src/pages/Autolending/LoanIncrementRadios.vue, src/pages/Autolending/LoanTermDropdown.vue, src/pages/Autolending/PartnerDelRateDropdown.vue, src/pages/Autolending/RiskRatingDropdown.vue, src/pages/Autolending/WhoYoullSupportText.vue, test/e2e/specs/AutolendingPage.spec.js
Added Who you'll lend to section on autolend settings page with updated who youll lend to text, component and style cleanup for modal AUTO-132
Still left to be done is to modify the modal advanced settings interactions so that instead of modals within modals they conform to new design.
I apologize for the size of this PR, I should've done a better job breaking this into smaller PR's. 
I have annotated the changes as best as I could. 
See:
https://kiva.atlassian.net/browse/AUTO-56
https://kiva.atlassian.net/browse/AUTO-132
https://kiva.atlassian.net/browse/AUTO-121
For the context on the copy and the who you'll lend to box.
=> AUTO-132 Autolend settings - Who You'll Lend To 

src/pages/Autolending/AutolendingSettingsPage.vue, src/pages/Autolending/AutolendingWho.vue, src/pages/Autolending/SaveButton.vue, test/e2e/specs/AutolendingPage.spec.js
* Reuse save button in autolend settings who component
* Added warning for loan criteria for who modal
* Hide number of loans in modal if kivachooses is selected
* Fixed tests
AUTO-132
=> Bug Fixes and Improvements for Autolend Settings Who

src/pages/Autolending/AutolendingWho.vue, src/pages/Autolending/CheckList.vue, src/pages/Autolending/CountryFilter.vue, src/pages/Autolending/CountryRadios.vue, src/pages/Autolending/GroupRadios.vue, src/pages/Autolending/SaveButton.vue
* Implemented 'slide' filter within modal for country filters
* Small CSS tweaks
* Changed all 'specific' filters to be checkboxes instead of KvToggles
AUTO-132
=> Implemented new design for specific filter section

src/pages/Autolending/AutolendingWho.vue, src/pages/Autolending/CountryFilter.vue, src/pages/Autolending/CountryRadios.vue, src/pages/Autolending/SaveButton.vue
hid warning if saving 'kiva chooses', removed unused css variables, hid criteria on kivachooses, added better resetting of modal specific country options when saving AUTO-132
=> AUTO-132 - fixes

src/pages/Autolending/CountryRadios.vue
This mutation got lost in the refactor. This fixes going from some countries to any
=> Fix for selecting any country AUTO-132

src/pages/Autolending/AutolendingWho.vue, src/pages/Autolending/CountryFilter.vue, src/pages/Autolending/SectorFilter.vue, src/pages/Autolending/SectorRadios.vue
* Added new UI for sector filter.
AUTO-132
=> Sector Filter - AUTO-132

src/pages/MonthlyGood/MonthlyGoodSetupPageVariant.vue
A few touchups I missed the first time around.
=> GROW-82 touchups

src/pages/Autolending/AttributeFilter.vue, src/pages/Autolending/CountryFilter.vue, src/pages/Autolending/PartnerFilter.vue, src/pages/Autolending/SectorFilter.vue, src/plugins/any-or-selected-autolending-filter-mixin.js
=> Cleaned up some duplicate code for autolend settings filters

src/components/WwwFrame/LendMenu/LendListMenu.vue, src/components/WwwFrame/LendMenu/LendMegaMenu.vue, src/components/WwwFrame/LendMenu/TheLendMenu.vue, src/graphql/query/categoryRows.graphql, src/graphql/query/lendMenuData.graphql
* Display 'all' categories in the lend menu
* Prefetch my info and regions info in the lend menu
* Show loader for categories query which takes a long time
VUE-222
There was some pretty extensive discussion on VUE-222, I gave this a shot, looks good to me, but interested in everyones thoughts.
=> Prefetch some items in the lend menu

src/pages/LandingPages/MGCovid19/MGCovidHero.vue
=> Fix landing form being above nav dropdown

src/components/WwwFrame/TheFooter.vue
=> Add explicit widths and heights to appease IE11

src/components/WwwFrame/TheHeader.vue
=> Fix IE11 header icons

src/components/Forms/MultiAmountSelector.vue, src/components/Kv/KvLightbox.vue, src/pages/LandingPages/MGCovid19/CovidLandingForm.vue, src/pages/LandingPages/MGCovid19/MGCovid19.vue, src/pages/LandingPages/MGCovid19/MGCovidFAQ.vue, src/pages/LandingPages/MGCovid19/MGCovidHero.vue
GROW-104
Add a prop to show one-time donation in lightbox. 
Add ID prop to <multi-amount-selector so we can have multiple instances on one page.
=> Experiment for only recurring donations on covid19response form

src/pages/Subscriptions/SubscriptionsPage.vue, src/pages/Subscriptions/SubscriptionsSettingsPage.vue, src/router/routes.js
* Added page frame and route in the UI for new subscription page.
* Not accessible in production currently
VUE-307
=> VUE-307 Subscriptions Page Frame

src/pages/Subscriptions/SubscriptionsMonthlyGood.vue, src/pages/Subscriptions/SubscriptionsPage.vue, src/pages/Subscriptions/SubscriptionsSettingsPage.vue
* Added Monthly good 'status' to new settings/subscriptions. Will display appropriate messaging if onetime subscriber or mg subscriber or not a subscriber.
* No edit functionality yet.
VUE-308
=> VUE-308 Added Monthly Good Status to settings/subscriptions

src/pages/Subscriptions/SubscriptionsMonthlyGood.vue, src/pages/Subscriptions/SubscriptionsOneTime.vue, src/pages/Subscriptions/SubscriptionsSettingsPage.vue
* Implement styling and form validation for MG subscription edit Lightbox form.
* Added dumb component to display messaging if isOneTime subscriber.
* Does not include any mutations on MG yet.
VUE-308
=> Monthly Good Subscription Edit

test/e2e/specs/AutolendingPage.spec.js
=> removed outdated tests

src/pages/Subscriptions/SubscriptionsMonthlyGood.vue, src/pages/Subscriptions/SubscriptionsSettingsPage.vue
* Adds mutations for modifying MG parameters in lightbox and updating status card on subscription settings page
* Adds mutations for cancelling subscriptions
* Adds lightbox to prompt for confirmation of cancelling subscription
VUE-308
=> VUE-308 Subscription Settings Mutations

src/pages/Subscriptions/SubscriptionsMonthlyGood.vue, src/pages/Subscriptions/SubscriptionsSettingsPage.vue
* Cleaned up CSS
* Added 'are you sure you' warnings
* Added save button on subscriptions page to save settings when changes are made in the modal and the modal is closed.
VUE-308
=> VUE-308 Subscription Settings Additional UI Behavior

src/pages/Subscriptions/SubscriptionsAutoDeposit.vue, src/pages/Subscriptions/SubscriptionsOneTime.vue, src/pages/Subscriptions/SubscriptionsSettingsPage.vue
* Added ability to edit one time contribution
* Added component to display message and edit auto deposits
VUE-308
=> VUE-308 Subscription Settings - One Time & Auto

src/pages/Subscriptions/SubscriptionsLegacy.vue, src/pages/Subscriptions/SubscriptionsSettingsPage.vue
* Added messaging for legacy autodeposit subscribers
VUE-308
=> VUE-308 Subscriptions Settings for legacy subscribers

src/pages/Subscriptions/SubscriptionsAutoDeposit.vue, src/pages/Subscriptions/SubscriptionsSettingsPage.vue
* Fixes issue with multiple save methods being called.
* Fixes save button still showing up after cancelling subscription
VUE-308
=> VUE-308 Bug Fixes

server/auth-router.js
Similar code already exists for the monolith side of things.
=> GROW-117 send unknown users to register by default instead of login

src/pages/Legal/TermsOfUse.vue
Updated our terms of use to show our new mission st. address.
=> LW-1955-updated address in terms of use from howard to mission st

src/pages/Homepage/DefaultHomepage.vue, src/pages/Homepage/Homepage.vue, src/pages/Homepage/iwd/IWDHomepage.vue, src/pages/Homepage/wrd/WRDHomepage.vue
* Uses a contentful setting to drive homepage content
LW-1956
=> WRD Homepage Takeover Driven by contentful setting

src/components/WwwFrame/TheFooter.vue
* Fixes footer CSS issue causing a big white margin on right side of page. At about 850 px wide
VUE-335
=> VUE-335 Footer CSS Issue

src/pages/Donate/DonateFromMacro.vue, src/pages/LandingPages/MGCovid19/MGCovidAbout.vue
Moved impact section of /donate/support-kiva over to contentful
=> vue-333 moved impact section to contentful

Dockerfile.jenkins, deploy/charts/templates/deployment.yaml, deploy/test/values.yaml
This is the first of several transfer PRs to cover incremental config updates.
=> K8 setup test 1

package-lock.json, package.json, src/components/Checkout/DropInPaymentWrapper.vue, src/components/Checkout/PaymentWrapper.vue, src/graphql/query/checkout/checkoutSettings.graphql, src/graphql/query/checkout/initializeCheckout.graphql, src/pages/Checkout/CheckoutPage.vue
Work for the drop in interface. I'm making an effort to split up some of the sub tasks for SUBS-141 into manageable PR's. The scope of this PR is:
- The UI styling and CSS cleanup of the braintree drop in interface. 
It also includes:
- @mcstover original work for the braintree drop in interface. 
The drop-in interface is hardcoded off. A followup PR will include the experiment gating so we can verify in dev. I'm hoping we can merge this in and verify my changes to PaymentWrapper and CheckoutPage
I was able to accomplish most of the design from SUBS-6
=> BrainTree Checkout Dropin Interface Styling and UI Cleanup - SUBS-294

src/graphql/query/checkout/checkoutSettings.graphql, src/graphql/query/checkout/initializeCheckout.graphql, src/pages/Checkout/CheckoutPage.vue
* Made braintree dropin ui active if braintree_dropin experiment and feature flag are active
* Cleaned up checkout queries a little.
SUBS-295
=> SUB-295 Added Experiment Gate to Braintree Dropin UI

src/components/Checkout/DropInPaymentWrapper.vue
* Added device to braintree dropin checkout
* Minor CSS tweaks for dropin UI when more than 1 saved credit card
* Minor drop in component code cleanup
SUBS-290
=> Added deviceData and minor CSS tweaks

src/pages/Autolending/CheckList.vue, src/pages/Autolending/CountryFilter.vue
https://kiva.atlassian.net/browse/AUTO-43
=> Add Select/Deselect All in country selection UI

config/audit.js, config/dev-vm.js, config/dev.js, config/index.js, config/qa.js, config/stage.js, config/test.js, server/auth-router.js, server/vue-middleware.js, src/api/Auth0Link.js, src/pages/Error.vue
Also add messaging for forced password reset.
=> ENG-2987 Redirect to Error page for rule errors

server/live-loan-router.js
* Ensure url params are numeric before proceeding
* Cache loan card images for 10 minutes
=> GROW-118 optimizations

src/components/Checkout/DropInPaymentWrapper.vue
* Added payment type to successful transaction event
* Added error response to snowplow event instead of sentry
SUBS-293
=> SUBS-293 Added Analytics to BT DropIn Payment

src/components/LoanCards/Buttons/ActionButton.vue, src/pages/Checkout/CheckoutPage.vue, src/util/experimentPreFetch.js
* Experiment to redirect users straight to basket when adding a first loan.
GROW-127
=> GROW-127 Experiment Redirect To Basket

src/components/Checkout/DropInPaymentWrapper.vue
* Fixed lock icon not showing up, which was causing button to not render correctly in Safari
* Made checkout button be disabled when payment method in invalid state
* Removed top margin from bt drop in holder
* Small tweak so when credit card icons align, they align with left of form
* Fixed "save" checkbox having the slightest gray background
SUBS-314
=> SUBS-314 Additional Styling for BT Drop in

src/components/MonthlyGood/DropInPaymentWrapperMG.vue, src/components/MonthlyGood/PayPalMG.vue, src/graphql/mutation/braintreeCreateMonthlyGoodSubscription.graphql, src/graphql/query/checkout/initializeCheckout.graphql, src/pages/Checkout/CheckoutPage.vue, src/pages/MonthlyGood/MonthlyGoodSetupPageControl.vue, src/pages/MonthlyGood/MonthlyGoodSetupPageVariant.vue
* Adds BT Drop In interface to MG setup page.
* Gated by exp and feature flag
* Rename exp to differentiate between checkout and mg and allow independent control of each
SUBS-9
=> SUBS-9 Add BT Drop In Payment options to MG Setup Page

src/components/LoanCards/Buttons/ActionButton.vue
* There was an issue, possibly a race condition, where itemsInBasket was inaccurate at the
handleAddToBasket method used to determine if we should execute the redirect to basket.
GROW-127
=> Fix for GROW-127

src/components/LoanCards/Buttons/ActionButton.vue, src/util/experimentPreFetch.js
* To include the GROW-127 changes, but we can bring in along the experiment setuiab query params too
=> Merge down master into release

src/components/LoanCards/Buttons/ActionButton.vue, src/pages/Checkout/CheckoutPage.vue, src/util/experimentPreFetch.js
Hotfix for GROW-127 Experiment
=> Hotfix for GROW-127 Redirect to basket experiment

src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBanner.vue
=> Lw 1972 tracking

src/pages/Homepage/Homepage.vue
=> GROW-138 lend-by-category as homepage experiment

src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue, src/pages/MonthlyGood/MonthlyGoodSetupPageControl.vue
* Fixes innocuous prop type error in mg bt drop in
=> SUBS-9 Fixed prop type error with monthly good drop in payment wrapper

src/pages/Homepage/Homepage.vue
See https://github.com/kiva/ui/pull/1913
=> GROW-138 Add prefetch function

src/pages/Homepage/LendByCategoryHomepage.vue
How it works (GROW-133)
Final CTA (GROW-136)
Loan not donation sections. (GROW-132)
Typography updates per comps. 
First pass at flourishes.
=> Various homepage sections

src/components/Homepage/LendByCategory/LoanCategoriesSection.vue, src/components/Homepage/LendByCategory/LoanCategory.vue, src/components/LoanCards/LendHomepageLoanCard.vue, src/components/LoanCards/LoanCardController.vue, src/graphql/query/lendByCategoryHomepageCategories.graphql, src/graphql/query/loanChannelInfo.graphql, src/pages/Homepage/LendByCategoryHomepage.vue
* Rough work in progress for GROW-131
=> GROW-131 Initial work for Category Rows Section

.storybook/stories/KvButton.stories.js, src/components/Kv/KvButton.vue
=> Add class to make buttons appear as text links

src/components/Homepage/LendByCategory/LoanCategoriesSection.vue, src/components/Homepage/LendByCategory/LoanCategory.vue, src/components/LoansByCategory/FeaturedHeroLoanWrapper.vue, src/graphql/query/lendByCategoryHomepageCategories.graphql
* Styled component
* Reworked to fix invariant error
* Added touch scrolling and related
* Added cleaning up category names
GROW-131
=> GROW-131 Loan Categories Section Component

src/components/Homepage/LendByCategory/LoanCategoriesSection.vue, src/components/Homepage/LendByCategory/LoanCategory.vue, src/components/LoanCards/LendHomepageLoanCard.vue
* Various style and functionality fixes to LoanCategory component
=> GROW-131 Loan Category Component

.storybook/mixins/apollo-story-mixin.js, .storybook/stories/GridLoanCard.stories.js, .storybook/stories/IWDHomepage.stories.js, .storybook/stories/LendByCategoryHomepage.stories.js, .storybook/stories/MGCovid19Response.stories.js
* Fixes Storybook Grid Loan Card story
* Create Storybook reusable apollo mixin to mock apollo functions
=> Storybook Fixes and Improvements

.storybook/stories/KvCarousel.stories.js, src/assets/icons/sprite/fat-chevron.svg, src/components/Kv/KvCarousel.vue
Pass at colors. Add fat chevron to sprite. Fix odd click issue on Chrome.
=> KvCarousel visual improvements

src/components/Homepage/LendByCategory/LoanCategoriesSection.vue, src/components/Homepage/LendByCategory/LoanCategory.vue, src/components/LoanCards/LendHomepageLoanCard.vue, src/pages/Homepage/LendByCategoryHomepage.vue
* Styling and cleanup for the loan card on the lend by category homepage.
=> GROW-131 Loan Card

.storybook/mixins/loan-data-prop-story-mixin.js, .storybook/stories/LendHomepageLoanCard.stories.js, src/components/Homepage/LendByCategory/LoanCategory.vue, src/components/LoanCards/LendHomepageLoanCard.vue, src/pages/Homepage/LendByCategoryHomepage.vue
* Added loan card story.
* Fixed a couple of issues discovered using the storybook story
=> GROW-131 Story & Small Fixes

src/pages/Homepage/LendByCategoryHomepage.vue
Adding get started link at the top of the LBChomepage. Put some dummy kvtracking data in there until I hear back from brandon about new tracking variables.
=> adding Get started link

src/pages/Homepage/Homepage.vue
=> Revert "Dynamically import homepage component"

src/components/Homepage/LendByCategory/FeaturedLoansCarousel.vue
Guarding some of these queries to avoid apollo error. Also forgot to include the category id in the prefetch for the first loan 🤦
=> Fixed some issues with queries in this component

src/components/Homepage/LendByCategory/FeaturedLoansCarousel.vue, src/components/Homepage/LendByCategory/LoanCategory.vue
* Refactor Featured loans carousel to filter funded loans and fetch loans in sets of 3 until a featured loan is found.
* Removed unnecessary props
* Fixed link destination and styling above featured loans carousel GROW-189
* Made featured loans carousel get loans for next slide
GROW-130 GROW-189
=> GROW-130 Filter Funded Loans

src/components/Homepage/LendByCategory/FeaturedLoansCarousel.vue, src/components/Homepage/LendByCategory/LoanCategory.vue, src/pages/Homepage/LendByCategoryHomepage.vue
* Fixes most issues in GROW-189
=> GROW-189 LBC Homepage Fixes

src/components/Homepage/LendByCategory/LoanCategoriesSection.vue, src/pages/Homepage/LendByCategoryHomepage.vue
* Fixed focus style for get started link and category links
=> GROW-189 Focus Styles Fix on Homepage Links

src/components/Homepage/LendByCategory/FeaturedLoansCarousel.vue, src/components/LoanCards/LendHomepageLoanCard.vue
* CSS tweaks after QA pass on dev - having to do with extra long matching text, extra long loan descriptions, missing border-radius
=> GROW-189 CSS Tweaks

src/components/Homepage/LendByCategory/FeaturedLoansCarousel.vue, src/components/Homepage/LendByCategory/LoanCategoriesSection.vue, src/components/Homepage/LendByCategory/LoanCategory.vue, src/components/Kv/KvCarousel.vue, src/pages/Homepage/LendByCategoryHomepage.vue
This gets the lend by category homepage tracking in place for links laid out in [GROW-164](https://kiva.atlassian.net/browse/GROW-164). 
I'll be running a final QA check on all these events in the morning.
=> auto-164 page tracking in place

src/pages/Homepage/LendByCategoryHomepage.vue
Minor, but would be nice to get in
=> Make header more understandable for screenreaders

src/components/LoanCards/LendHomepageLoanCard.vue
* Lowered max use length to prevent loan info bodies from being 4 lines
=> Minor LBC Homepage fixes

src/pages/Legal/TermsOfUse.vue
**TOU:**
Updates to the TOU laid out in [LW-1961](https://kiva.atlassian.net/browse/LW-1961)
- Removes highlighting and *statement
- updates address
**Privacy Policy**
Updates to the Privacy Policy were made within pages.dev.kiva.org and pages.kiva.org. This was a simple address update. 
https://pages.dev.kiva.org/legal/privacy
https://pages.kiva.org/legal/privacy
=> LW-1961 TOU updated

.storybook/stories/KvSettingsCard.stories.js, src/components/Kv/KvSettingsCard.vue, src/pages/Autolending/AutolendingSettingsPage.vue, src/pages/Autolending/AutolendingStatus.vue, src/pages/Autolending/AutolendingWhen.vue, src/pages/Autolending/AutolendingWho.vue, src/pages/Subscriptions/SubscriptionsAutoDeposit.vue, src/pages/Subscriptions/SubscriptionsLegacy.vue, src/pages/Subscriptions/SubscriptionsMonthlyGood.vue, src/pages/Subscriptions/SubscriptionsOneTime.vue, src/pages/Subscriptions/SubscriptionsSettingsPage.vue
* Refactor card used on settings pages into a new component
* Add component story
* Remove duplicate CSS and component imports
=> Settings Card Component

src/pages/Legal/TermsOfUse.vue
Updates the last edited date to today (August 8th 2020), the last day this was edited.
=> lw-1961 updating last edited date

config/index.js, src/components/Checkout/CheckoutDropInPaymentWrapper.vue, src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue, src/components/Payment/BraintreeDropInInterface.vue
* Adds Google Pay checkout option for Braintree Drop In UI  based on experiment setting.
=> GROW-168 Google Pay

src/pages/Legal/TermsOfUse.vue
Added back in edited qualifying text. 
Highlighted most recent change which was the mailing address.
Same changes have been made in drupal for the /legal/privacy page.
=> adding back in highlighting and highlighting address updated

src/pages/Thanks/ThanksPage.vue
* Prevents 500 error if receipt query fails for some reason
=> VUE-372 Fix for 500 error on receipt page

.storybook/stories/MonthlyGoodUpdateForm.stories.js, src/components/Forms/MonthlyGoodUpdateForm.vue, src/pages/Subscriptions/SubscriptionsMonthlyGood.vue
* Adds Monthly Good update form component to remove validation and form logic from SubscriptionsMonthlyGood.vue
* Adds story for the component.
* Save button was displaying on parent when lightbox was closed without editing values
* Add disabled state to entire form while saving is in progress
=> SUBS-373 Monthly Good Form Component

src/components/Forms/MonthlyGoodUpdateForm.vue, src/pages/Subscriptions/SubscriptionsMonthlyGood.vue
* Displays MG API errors in the UI if theres an error in MG update mutations
=> SUBS-380 Display Errors Correctly If MG Update Fails

src/components/Checkout/CheckoutDropInPaymentWrapper.vue, src/components/Checkout/PaymentWrapper.vue, src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue, src/components/MonthlyGood/PayPalMG.vue, src/pages/MonthlyGood/FrequentlyAskedQuestions.vue, src/pages/MonthlyGood/MonthlyGoodSetupPageVariant.vue, src/pages/MonthlyGood/MoreAboutKiva.vue, src/pages/Subscriptions/SubscriptionsMonthlyGood.vue
Hotfix for:
SUBS-380
SUBS-374
SUBS-370
=> Hotfix 20200820

.storybook/stories/KvSettingsCard.stories.js, src/components/Kv/KvButton.vue, src/components/Kv/KvSettingsCard.vue, src/pages/Autolending/AutolendingSettingsPage.vue, src/pages/Autolending/AutolendingStatus.vue, src/pages/Autolending/AutolendingWhen.vue, src/pages/Autolending/AutolendingWho.vue, src/pages/Autolending/LendTimingMessaging.vue, src/pages/Autolending/WhoYoullSupportText.vue, src/pages/Subscriptions/SubscriptionsAutoDeposit.vue, src/pages/Subscriptions/SubscriptionsLegacy.vue, src/pages/Subscriptions/SubscriptionsMonthlyGood.vue, src/pages/Subscriptions/SubscriptionsOneTime.vue, src/pages/Subscriptions/SubscriptionsSettingsPage.vue
* Removed *-area class
* Removed unused classes
* Fixed spacing issues on settings cards
* Removed wrapper div on settings cards
* Added bottom spacing on subs settings
=> VUE 385 CSS Tweaks

src/components/Kv/KvPillToggle.vue, src/pages/Lend/Filter/FilterSections/Gender/PillToggleWrapper.vue
* Fix bug where PillToggle on lend/filter was not resetting correctly
* Remove use of lodash filter in PillToggleWrapper
=> VUE-356 Reset All Filter Bug

src/pages/MonthlyGood/EmailPreview.vue, src/pages/MonthlyGood/ExpandableQuestion.vue, src/pages/MonthlyGood/FrequentlyAskedQuestions.vue, src/pages/MonthlyGood/HowItWorks.vue, src/pages/MonthlyGood/KivaAsExpert.vue, src/pages/MonthlyGood/MoreAboutKiva.vue
* Allows linking to page sections on monthly good using a hash in the url. If a FAQ question slug is linked to that question will be opened in the faq section
=> SUBS-485 Allow linking to specific sections on monthly good

src/api/fixtures/AutolendProfile.js, src/api/fixtures/LoanSearchCriteria.js, src/api/fixtures/LoanSearchFilters.js, src/api/localResolvers/experiment.js, src/pages/Checkout/CheckoutPage.vue
* Removed lodash methods omit and pick in favor of native JS
VUE-362
VUE-396
=> VUE-362 VUE-396 Remove lodash omit and pick

.storybook/stories/KvCarousel.stories.js, package-lock.json, package.json, src/components/Homepage/LendByCategory/FeaturedLoansCarousel.vue, src/components/Kv/KvCarousel.vue, src/components/Kv/KvCarouselSlide.vue
Allows for smooth dragging and multiple slides in view.
Carousels no longer require a height, they adapt to the slide contents.
=> VUE-386 - Implement EmblaCarousel into KvCarousel 

src/pages/AutoDeposit/AutoDepositLandingPage.vue, src/pages/AutoDeposit/AutoDepositThanksPage.vue, src/router/routes.js
* Added temp route for new UI auto deposit page
=> VUE-387 Added Temporary Route for Auto Deposit

.storybook/stories/KvExpandableQuestion.stories.js, src/components/AutoDeposit/FrequentlyAskedQuestions.vue, src/components/Kv/KvExpandableQuestion.vue, src/components/MonthlyGood/FrequentlyAskedQuestions.vue, src/pages/AutoDeposit/AutoDepositLandingPage.vue, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue, src/pages/PageTwo.vue
* Add Auto Deposit FAQ section and organize some components
=> VUE-388 Auto Deposit FAQ

src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBanner.vue
Got those suggested changes in place from: https://github.com/kiva/ui/pull/2052
Removed ref and replaced with a dynamic class
=> GROW-230 removing ref and using dynamic bound dynamic class

src/components/AutoDeposit/FrequentlyAskedQuestions.vue, src/pages/AutoDeposit/AutoDepositLandingPage.vue, src/pages/Subscriptions/SubscriptionsAutoDeposit.vue
* AutoDeposit what to expect, general page layout and CSS
=> VUE-389 Auto Deposit What To Expect

src/pages/MonthlyGood/MonthlyGoodSetupPageControl.vue
This is 100% in prod already, lets default to true, and remove exp toggle.
=> SUBS-378 Removed MG Setup DropIn Exp Setting

src/pages/AutoDeposit/AutoDepositLandingPage.vue, src/pages/Subscriptions/SubscriptionsAutoDeposit.vue, src/pages/Subscriptions/SubscriptionsMonthlyGood.vue
* Implemented conditional messaging for auto deposit landing page.
=> VUE-390 Auto Deposit Landing Page

src/components/AutoDeposit/FrequentlyAskedQuestions.vue, src/components/MonthlyGood/FrequentlyAskedQuestions.vue
https://kiva.atlassian.net/browse/SUBS-491
=> Fixed console error on FAQ components when route hash is missing

src/components/AutoDeposit/AutoDepositSignUpForm.vue, src/pages/AutoDeposit/AutoDepositLandingPage.vue, src/pages/MonthlyGood/MonthlyGoodSetupPageControl.vue, src/pages/Subscriptions/SubscriptionsAutoDeposit.vue
* Implemented auto deposit sign up form.
* Fix other forms with day of month to avoid GQL validation errors in federation
=> VUE-390 Auto Deposit Sign Up Form

src/components/AutoDeposit/AutoDepositDropInPaymentWrapper.vue, src/components/AutoDeposit/AutoDepositSignUpForm.vue, src/components/Payment/BraintreeDropInInterface.vue, src/graphql/mutation/braintreeCreateAutoDepositSubscription.graphql, src/pages/MonthlyGood/MonthlyGoodSetupPageControl.vue
* Implements drop in UI for auto deposit setup
* Fixes issue with drop in loader only displaying on page center, it should display centered on the component, swapped it out for kv-loader instead of loading-overlay
=> VUE-394 Auto Deposit Drop In UI

src/components/AutoDeposit/AutoDepositSignUpForm.vue, src/components/Forms/MonthlyGoodUpdateForm.vue, src/pages/MonthlyGood/MonthlyGoodSetupPageControl.vue, src/pages/Subscriptions/SubscriptionsAutoDeposit.vue, src/pages/Subscriptions/SubscriptionsMonthlyGood.vue
* Replace IconPencil for KvIcon usage. 
* Fixed bug where if form was invalid, day of month input would have red outline, it should only outline if dayOfMonth itself is invalid.
=> Drop in pencil icon improvement

src/components/GetStarted/FrequentlyAskedQuestions.vue, src/components/Kv/KvExpandableQuestion.vue, src/pages/GetStarted/GetStartedResults.vue
* Adds FAQ component to get started results page
=> GROW-180 Get Started Results FAQs

src/server-entry.js
I wanted to use Vue's `serverPrefetch` method to get some data for a component after the component instance was created. That allows me to use the instance's prop values as variables for queries, something we can't do with our home-grown apollo prefetch method.
I think of the `serverPrefetch` method the same as being in the browser and showing a loading state while fetching data to render a component (e.g. how classic /lend behaves with loading the page first and then showing a loading spinner while the loans are fetched). The difference is that the data fetching happens server-side and the final html isn't created until after that completes, allowing the fully-loaded and rendered page to be sent from the server.
To enable the usage of this in our app, we only needed to change when we set …
=> Enable usage of serverPrefetch

src/components/GetStarted/FrequentlyAskedQuestions.vue, src/components/WwwFrame/TheHeader.vue, src/pages/GetStarted/GetStarted.vue, src/pages/GetStarted/GetStartedResults.vue
* Adds how it works section and flourish next to FAQs on the results page
=> GROW-179 GetStarted Results - How It Works

config/audit.js, config/dev.js, config/index.js, config/qa.js, config/stage.js, config/test.js, src/pages/Error.vue
This is necessary for https://github.com/kiva/kiva/pull/9226
=> AUTH-293 Update login redirect url and forgot password text for admin & pa2

src/pages/GetStarted/GetStarted.vue, src/pages/GetStarted/GetStartedCauses.vue, src/router/routes.js
* Adds mutations and cleans up route for cause selection page
=> GROW-175 Cause Selection Page

src/pages/GetStarted/GetStarted.vue, src/pages/GetStarted/GetStartedCauses.vue
* Made some styling and content changes
=> GROW-175 Styling Changes

.storybook/stories/SwashieFace.stories.js, src/components/Kv/KvProgressCircle.vue, src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBanner15.vue
=> Show percentage number on the circle that flips to remain most legible

src/components/GetStarted/EditPreferences.vue, src/pages/GetStarted/GetStartedCauses.vue, src/pages/GetStarted/GetStartedResults.vue
* Edit preferences block on results page.
* Capitalize causes on cause selection page
There is a chance that this page can be reached without causes and/or places, see screenshot ^
=> GROW-177 Edit Preferences Results

src/components/LoanCards/Buttons/LendButton2.vue, src/components/LoanCards/RecommendedLoanCard.vue
This also addresses Invariant Violation errors when the Recommended Loan Card is loading on a client-rendered page, and should also address improperly changing styles on that loan card when interacting with the page.
=> GROW-267 Fix lend button not updating

src/pages/GetStarted/GetStartedCauses.vue, src/pages/GetStarted/GetStartedPlaces.vue
* Get Started Causes and Places pages now show previously selected items if there are any
=> GROW-266 Causes & Places Previous Selection

.storybook/stories/15years.stories.js
Adds the icon sprite inline to the 15 year story decorator so we can get feedback from product on the github pages storybook now.
=> SVG icon sprite + storybook temporary hack

.storybook/mock-data/loan-channels-data-mock.js, .storybook/stories/KvCarousel.stories.js, .storybook/stories/LendByCategoryHomepage.stories.js, .storybook/utils.js, src/components/Homepage/LendByCategory/LoanCategoriesSection.vue, src/components/Kv/KvCarousel.vue
* allows kv carousel to slide by the amount of slides visible.
* storybook fixes
=> GROW-270 KvCarousel Slide Visible Improvement

src/components/LoanCards/RecommendedLoanCard.vue, src/pages/GetStarted/GetStartedResults.vue
This also partially reverts f327f2021e87c73a126cf8203c6e1ac353a76b65, as that removed styles that were still in use. I'll cherry-pick these commits to `release-20200921` after this is merged.
=> GROW-271 Get Started Results page fixes

src/components/15Years/15YearsButton.vue, src/components/15Years/15YearsHeader.vue, src/components/15Years/15YearsIndividuals.vue, src/components/15Years/15YearsSponsors.vue, src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBanner15.vue
Component to keep buttons consistent on 15yr page and global banner.
=> 15yr button component

src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBanner15.vue
Added smoother transition for kiva 15 banner
=> GROW-256 Banner Transition

src/components/15Years/15YearsPartners.vue
* Changed behavior of partner expansion
* Changed stategic partner CSS and text styling
* Refactored partner template
=> GROW-250 Revisions

package-lock.json, package.json, src/components/15Years/15YearsPartners.vue, src/plugins/index.js, src/plugins/observe-visibility-plugin.js
* Animated total impact numbers with the intersection observer plugin.
=> GROW-281 Animated Total Impact

src/components/15Years/15YearsIndividualsData.js, src/components/15Years/15YearsIndividualsProfile.vue
Content updated for the featured people section of the kiva 15 page. 
- Some of the videoIds updated
- Body copy added to people
- People reordered
- Location added to each person
=> content update for featured people section of kiva 15

src/components/15Years/15YearsIndividualsData.js
Country wide links gathered and updated. Went with links to the old stack page so we could include countries that don't currently have fundraising loans, but may in the future.
=> links gathered and updated

src/components/15Years/15YearsGlobe.vue, src/components/15Years/15YearsHeader.vue
Comments left to highlight locations where analytics events might be added.
=> RALLY-005 Globe analytics comments

src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBanner15.vue
* Removed animation on load, animated % fill, made % query only happen on client, switched from store2 to cookies to prevent unwanted flash of banner state
=> GROW-256 Appeal 15 Banner Changes

src/components/15Years/15YearsGlobe.vue, src/components/15Years/15YearsHeader.vue, src/components/15Years/15YearsHeaderCard.vue, src/components/15Years/15YearsHowKivaWorks.vue, src/components/15Years/15YearsIndividuals.vue, src/components/15Years/15YearsIndividualsProfile.vue, src/components/15Years/15YearsPartners.vue, src/components/15Years/15YearsTimeline.vue
=> GROW-285 15Year Tracking Events

src/components/15Years/15YearsTimeline.vue
if the link contains 'http' we render an <a> with an href
Otherwise we render the <router-link> component how it was previously.
=> Kiva15 link fix

src/pages/Homepage/Homepage.vue
Didn't form it correctly the first time.
=> Search console verification take 2

src/pages/AutoDeposit/AutoDepositThanksPage.vue, src/pages/MonthlyGood/MonthlyGoodThanksPage.vue, src/router/routes.js
* Adds new thanks page for auto deposit
=> VUE-393 Auto Deposit Thanks Page

src/components/15Years/15YearsGlobe.vue
I'm very much on the fence about this; interested in other opinions. Would be perfectly happy to abandon for now
=> RALLY-007 Globe scroll to top

src/pages/Lend/LendByCategoryPage.vue
* Removes lodash _drop in favor of native js option
=> VUE-367 Remove Lodash Drop

src/pages/AutoDeposit/AutoDepositThanksPage.vue, src/router/routes.js
* Changed AD route from temp route to final
=> VUE-397 New Auto Deposit Routing

src/components/15Years/15YearsGlobe.vue, src/components/15Years/15YearsGlobePinCallout.js
Show flag instead of pin marker. Enlarge flag dots and make them red.
=> GROW-290 globe flag markers

src/components/15Years/15YearsHeader.vue
Remove flag from left text. Tweak sizing to fix long country name overlap.
=> 15 year touchups

src/components/15Years/15YearsHeader.vue, src/components/15Years/15YearsHeaderCard.vue, src/components/15Years/15YearsPartners.vue, src/components/15Years/15YearsSupportingPartners.vue, src/pages/15Years/15Years.vue, src/pages/Homepage/15YearHomepage.vue, src/pages/Homepage/Homepage.vue, src/router/index.js
CTA updates will be coming in a later PR, pending discussion.
=> GROW-289 GROW-238 Kiva 15 Years Homepage

src/pages/Legal/TermsOfUse.vue
=> lw-1993 date update

src/pages/Build/Research.vue
add new articles,
fix some broken links & typos
=> update research page

src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue, src/graphql/mutation/braintreeUpdateSubscriptionPaymentMethod.graphql, src/pages/Subscriptions/SubscriptionsMonthlyGood.vue
* Update for update MG. Now updates billing agreement instead of recreating it. Small UI changes as well.
=> SUBS-493 MG Update Payment Method Enhancement

src/api/localResolvers/verificationLightbox.js, src/api/localSchema.graphql, src/components/Checkout/BasketVerification.vue, src/components/Checkout/OrderTotals.vue, src/graphql/mutation/checkout/closeVerificationLightbox.graphql, src/graphql/mutation/checkout/showVerificationLightbox.graphql, src/graphql/query/checkout/basketVerificationState.graphql, src/pages/Checkout/CheckoutPage.vue, src/plugins/checkout-utils-mixin.js
This depends on kiva/kiva#9342, and so this shouldn't be merged until that is in development. This should also probably not be merged until after any expected ui hotfixes have been made.
=> GROW-262 Delay showing basket verification lightbox until credit is applied and verification is required

src/assets/icons/inline/share.svg, src/assets/scss/_settings.scss, src/components/Checkout/CheckoutReceipt.vue, src/components/Checkout/SocialShare.vue, src/pages/Thanks/ThanksPage.vue
* Design and layout changes to thanks page.
* These design changes are in preparation for the CTA in SUBS-519 but were decided to be made permanent and not part of the proposed experiment.
=> SUBS-519 Thanks Page Design Changes

src/pages/Thanks/ThanksPage.vue, src/util/joinArray.js, test/unit/specs/util/joinArray.spec.js
We do this type of thing in several places: get-started causes list, get-started country lists, autolending filters list come to mind.
I did not refactor the old use cases, but going forward we can use this util function
=> Moved custom join array function into utils, added unit test

src/components/Checkout/MonthlyGoodCTA.vue, src/graphql/query/thanksPage.graphql, src/pages/Thanks/ThanksPage.vue
* Implements MG Thanks page upsell based on experiment
See SUBS-320 for specs. 
Still TODO:
* Amount drop down should have "other" option that enables user to input custom amount. 
* For should populate to start on today minus 1, so that MG won't kick in until approximately 30 days from now
=> SUBS-320 MG Thanks Page Upsell

src/assets/scss/global/forms.scss, src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue, src/components/Payment/BraintreeDropInInterface.vue, src/pages/Subscriptions/SubscriptionsMonthlyGood.vue
* Small styling tweaks to MG update form
* Made MG Update form not preselect vaulted payment method
* Display error messaging and not call mutation if user selects to update payment method to his current payment method.
=> SUBS-493 Improvements

src/components/AutoDeposit/AutoDepositDropInPaymentWrapper.vue, src/components/Checkout/CheckoutDropInPaymentWrapper.vue, src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue, src/graphql/mutation/braintreeCreateAutoDepositSubscription.graphql, src/graphql/mutation/braintreeCreateMonthlyGoodSubscription.graphql, src/graphql/mutation/braintreeUpdateSubscriptionPaymentMethod.graphql
* Add device data to remaining Braintree DropIn instances
=> SUBS-498 Device Data

package-lock.json, package.json
=> Revert "Bump isomorphic-fetch from 2.2.1 to 3.0.0"

build/webpack.server.conf.js, server/util/errorLogger.js, src/api/Auth0Link.js, src/components/WwwFrame/PromotionalBanner/GlobalPromotionalBannerContentful.vue, src/plugins/app-install-mixin.js
Replace white/blacklist with allow/deny
=> phrasing changes

src/components/WwwFrame/Menus/TheMyKivaSecondaryMenu.vue, src/components/WwwFrame/Menus/TheSettingsTertiaryMenu.vue, src/components/WwwFrame/SecondaryMenu.vue, src/components/WwwFrame/TertiaryMenu.vue, src/pages/Autolending/AutolendingPage.vue, src/pages/Settings/SecuritySettings.vue, src/pages/Settings/TwoStepVerificationPage.vue, src/pages/Subscriptions/SubscriptionsPage.vue
=> Settings pages: add secondary nav and tertiary nav as a dropdown

src/components/Checkout/CheckoutDropInPaymentWrapper.vue
* Made googlePay/applePay permanent options for checkout Braintree DropIn UI
=> GROW-311 Removed googlePay applePay Experiment Code

package-lock.json, package.json, server/util/getSessionCookies.js
* Bump dependency
* Fix deprecated headers.getAll()
=> Bump isomorphic-fetch to v3.0.0

.storybook/stories/KvButton.stories.js, src/components/Kv/KvButton.vue, src/components/Subscriptions/SubscriptionsMonthlyGoodCancellationFlow.vue, src/pages/Subscriptions/SubscriptionsMonthlyGood.vue, src/pages/Subscriptions/SubscriptionsSettingsPage.vue
* Adds monthly good cancellation flow modal with snowplow event tracking mapped to the same events used in the mobile app
Snowplow tracking events are the same as the events from the mobile app, they can be seen here: https://kiva.looker.com/explore/events/event_derived_view_mobile_event?toggle=fil&qid=CAS9VR2UXGvoooFVCYCQYH
=> SUBS-533 Monthly Good Cancellation Flow

src/components/Checkout/BraintreeCheckout.vue, src/components/Checkout/CheckoutDropInPaymentWrapper.vue, src/components/Checkout/CheckoutItemImg.vue, src/components/Checkout/DonationItem.vue, src/components/Checkout/LoanPrice.vue, src/components/Checkout/PayPalExpress.vue, src/components/Homepage/CategoryGrid.vue, src/components/Homepage/LendByCategory/NoClickLoanCard.vue, src/components/LoanCards/AdaptiveMicroLoanCard.vue, src/components/LoanCards/BorrowerInfo/BorrowerInfoBody.vue, src/components/LoanCards/BorrowerInfo/BorrowerInfoName.vue, src/components/LoanCards/Buttons/CheckoutNowButton.vue, src/components/LoanCards/Buttons/LendButton.vue, src/components/LoanCards/Buttons/LendButton2.vue, src/components/LoanCards/FavoriteStar.vue, src/components/LoanCards/HoverLoanCard/DetailedLoanCard.vue, src/components/LoanCards/LoanCardImage.vue, src/components/LoanCards/RecommendedLoanCard.vue, src/components/LoansByCategory/FeaturedHeroLoan.vue, src/components/LoansByCategory/RecentlyViewedLoans.vue, src/components/LoansYouMightLike/MinimalLoanCard.vue, src/components/WwwFrame/Menus/CustomSecondaryMenu.vue, src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBanner.vue, src/pages/Checkout/CheckoutPage.vue, src/pages/Donate/DonateForm.vue, src/pages/Lend/LendByCategoryPage.vue, src/plugins/kv-analytics-plugin.js
* Removed unncessary 5th param for kvTrackEvent
* Removed support for string type with | for kvTrackEvent
* Refactors trackEvent, add support for snowplow value
=> Kv Analytics Refactor

src/components/Checkout/InContext/InContextCheckout.vue, src/components/ContentGroups/CampaignHeader.vue, src/components/ContentGroups/CampaignLoanDisplay.vue, src/components/ContentGroups/CampaignThanks.vue, src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
Relevant updates:
- Moved Campaign Loan Display and pagination handling into it's own component
- Checkout is now embedded in the page after a loan is added to basket rather than showing in a lightbox
- InContext Checkout component has some new options to control showing or hiding the donation row and whether to redirect to thanks automatically.
- In context Thanks is shown after completion of checkout
=> Wire up in context thanks and improve style of in context checkout.

src/components/AutoDeposit/AutoDepositDropInPaymentWrapper.vue, src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue, src/pages/Subscriptions/SubscriptionsAutoDeposit.vue, src/pages/Subscriptions/SubscriptionsMonthlyGood.vue
* Adds ability to update auto deposit payment method
* Fixes minor bugs/styling
=> SUBS-494 Auto Deposit Update Payment Method

.storybook/stories/KvProgressCircle.stories.js
=> Spec out how to make a C shaped meter

src/components/WwwFrame/TheHeader.vue, src/pages/Checkout/CheckoutPage.vue, src/plugins/kv-analytics-plugin.js, src/util/experimentPreFetch.js, test/unit/specs/components/WwwFrame/TheHeader.spec.js
Also adds ability to track multiple events when using `v-kv-track-event`
=> GROW-282 Experiment with removing the popup login

src/components/Settings/TwoStepVerification.vue
These changes get the MFA status section of the /settings/security page displaying on/off based on if the user has MFA enabled or not. 
Enabled: 
Disabled:
=> grow-329 hooking up status to mfa endpoint

src/components/AutoDeposit/FrequentlyAskedQuestions.vue, src/pages/AutoDeposit/AutoDepositLandingPage.vue, src/util/contentfulUtils.js, test/unit/fixtures/AutoDepositPageRawNoSettings.json, test/unit/specs/util/contentfulUtils.spec.js
* Connects auto deposit page to contentful making all text on the page editable in contentful
* Modifies contentful utils to allow for more flexibility of optional settings object and rich text blocks
Also up for this review is the content structure on contentful found here: 
https://app.contentful.com/spaces/j0p9a6ql0rn7/environments/development/entries/2AT4yRl97Od1Olx9REbrHZ
Adds a new idea of content groups, like for faqs which are just a collection of rich text items.
=> VUE-398 AutoDeposit Contentful

src/graphql/fragments/shopTotals.graphql, src/pages/Checkout/CheckoutPage.vue, src/plugins/kv-analytics-plugin.js
Use new isFirstTimeDepositor flag in transaction analytics and add new analytics events if a transaction includes a Kiva card.
Depends on https://github.com/kiva/kiva/pull/9458
=> Add facebook events for ftd and kiva cards during transaction

src/components/Subscriptions/SubscriptionsMonthlyGoodCancellationFlow.vue, src/pages/Subscriptions/SubscriptionsMonthlyGood.vue
* Added id to snowplow event on MG cancellation
* Refactored component to remove _get
=> SUBS-578 Add AutoDeposit ID to MG cancellation snowplow event

src/components/LoanCards/Buttons/LendIncrementButton.vue
=> Add missing parseFloat call

src/util/loanUtils.js
It turns out #2378 was necessary but not sufficient.
Sorry for the PR spam; I could not reproduce this issue on my VM.
=> Fix buildPriceArray bug: Switch to simpler implementation.

src/components/WwwFrame/TheFooter.vue
Tracking events have been added to all clicks within TheFooter.vue based on the structure laid out in grow-363
=> grow-363 adding tracking links into footer

src/pages/Homepage/LendByCategoryHomepage.vue
Small copy update for the sub-heading on the homepage
Copy now reads: 
With Kiva you can lend as little as $25 and make a big change in someone's life.
=> grow-358 subhead copy update

src/components/WwwFrame/PromotionalBanner/Banners/GenericPromoBanner.vue
* Added ability for global banner links to route to external sites
=> VUE-370 External Links for Global Banner

.storybook/stories/KvFormKitchenSink.stories.js, .storybook/stories/KvPhoneInput.stories.js, package-lock.json, package.json, src/components/Kv/KvPhoneInput.vue
If you have a moment, please pull down, run a local storybook and take a look at the stories.
=> GROW-316 international phone number input

.storybook/stories/KvFormKitchenSink.stories.js, .storybook/stories/KvVerificationCodeInput.stories.js, src/components/Kv/KvVerificationCodeInput.vue
=> GROW-355 Initial pass at verification code input

src/assets/scss/_settings.scss, src/assets/scss/app.scss, src/assets/scss/global/drop-in.scss, src/components/AutoDeposit/AutoDepositDropInPaymentWrapper.vue, src/components/Checkout/CheckoutDropInPaymentWrapper.vue, src/components/Checkout/OrderTotals.vue, src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue, src/components/Payment/BraintreeDropInInterface.vue
* Restyled DropIn UI according to new design specs
=> SUBS-587 ReStyle BT DropIn UI

src/components/Checkout/DonationItem.vue
* Added contentful driven donation item text with variable that gets replaced on the UI
=> SUBS-595 Donation Item

src/components/Payment/BraintreeDropInInterface.vue
* Drops cc icons to a new row.
=> SUBS-587 BT Drop In Style Tweak

.storybook/stories/TheHeader.stories.js, .storybook/stories/WwwPageCorporate.stories.js, src/components/WwwFrame/TheHeader.vue, src/components/WwwFrame/WwwPageCorporate.vue, src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
ML2-136, ML2-137
I think there may be some more styling to do on mobile, but wanted to get this pushed up before the break. Open to taking some new directions with this also.
=> Corporate campaign header

.storybook/stories/KvButton.stories.js, src/components/Checkout/MonthlyGoodCTA.vue, src/components/Forms/MonthlyGoodUpdateForm.vue, src/components/Kv/KvButton.vue, src/components/Kv/KvSettingsCard.vue, src/pages/MonthlyGood/MonthlyGoodSetupPage.vue, src/pages/Settings/PaymentSettings.vue, src/pages/Settings/SettingsPage.vue, src/pages/Subscriptions/SubscriptionsAutoDeposit.vue, src/pages/Subscriptions/SubscriptionsMonthlyGood.vue, src/pages/Subscriptions/SubscriptionsOneTime.vue, src/router/routes.js
Implements new payment settings card in settings, as well as the ability to change default card and also remove saved payment methods
SUBS-377
SUBS-612
SUBS-613
New route will need to be added /settings/payments in PR
*Does not include add a card functionality* 
This functionality is independent of the add a card functionality and we can proceed with merging this as is and follow-up with a PR to add a card.
=> SUBS-56 Manage Payment Methods Interface

src/pages/Settings/PaymentSettings.vue
* Design called for a cancel button on the modal
=> SUBS-56 Cancel Button

src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBannerCircularContainer.vue
=> Donation banner: Add more optional chaining to prevent 500 errors

src/pages/MonthlyGood/MonthlyGoodSetupPage.vue, src/router/routes.js, src/util/authenticationGuard.js, src/util/experimentPreFetch.js
* On entering `/monthlygood/setup` check for experiment value. 
* If value is control, redirect to login page. 
* If value is shown, display setup page, replacing braintree drop in with "Continue" button
* When clicking continue button, save all form values as query params, redirect to login page
=> SUBS-609 Monthly Good Login Experiment

src/components/Settings/TwoStepFaq.vue
added .native.prevent in order to get the mfa FAQ lightboxes working
=> added .native.prevent to the click handler to open FAQ lightboxes

src/pages/MonthlyGood/LandingForm.vue, src/pages/MonthlyGood/LandingFormExperiment.vue, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue, src/pages/MonthlyGood/MonthlyGoodSetupPage.vue
* Adds distinct tracking to monthlygood landing page buttons - SUBS-615
* Adds tracking to continue button for SUBS-609
=> SUBS-609 SUBS-615 Add tracking to MG Buttons

src/components/Checkout/DonationItem.vue, src/components/Checkout/LoanPrice.vue, src/components/Checkout/LoanReservation.vue
Found during a voiceover audit
=> Fix misc checkout a11y errors

.storybook/stories/KvLightbox.stories.js, src/components/Kv/KvLightbox.vue, src/components/Lightboxes/AddToBasketInterstitial.vue
Removes "fullWidth" prop, since the only place it was used was on the interstitial, and it wasn't really helping anything there.
Fixes max-width problem that came in during re-ordering of nodes last week.
=> Lightbox fixes

src/components/CorporateCampaign/CampaignLogoGroup.vue, src/components/WwwFrame/TheFooterCorporate.vue, src/components/WwwFrame/TheHeader.vue
Break logo group into its own component (since we need this in the lightbox too), make it smaller on mobile.
=> ML2-161 smaller brand logos on mobile

src/components/Payment/BraintreeDropInInterface.vue
* Display an error in tip message when BT Drop In has a fatal error
=> SUBS-616 BT DropIn Fatal Error

src/components/Checkout/MonthlyGoodCTA.vue, src/components/WwwFrame/TheBannerArea.vue, src/pages/Thanks/ThanksPage.vue
* Fixed padding and removed promo banner and monthly good upsell from thanks page
=> VUE-461 Removed Items from thanks page for print

package.json
Default in v15 is no timeout. This flag was removed in v13
=> Remove timeout flag

src/pages/Borrow/BorrowHowLong.vue
LW-2019 Add back in kiva us application form link change
This should go out with next production release
=> LW-2019 Add back in url change for kiva us application link to new form

src/graphql/query/whyKivaData.graphql, src/pages/MonthlyGood/KivaAsExpert.vue
* Small copy change to KivaExpert section on mg landing page
* Use kivaStats endpoint to power stats on MG Landing page
=> GROW-391 MG Landing Copy Change & Live KivaStats

.storybook/stories/KvButton.stories.js, src/components/Kv/KvButton.vue
* Added 'Kiva Classic' Button solid and hollow style for future use
=> GROW-397 Kiva Classic Button Style

src/components/Checkout/InContext/InContextCheckout.vue, src/components/CorporateCampaign/CampaignThanks.vue, src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue, src/pages/Thanks/ThanksPage.vue
ML2-154, ML2-153, ML2-156
Put thanks in lightbox. Put social share and receipt in accordion. Fix up confetti.
TODO: Some styling refinements in the basket. Add contentful block next.
=> Thanks in lightbox

src/components/Settings/AppAuthentication.vue
=> grow-399 simple text update

src/pages/Settings/TwoStepVerificationPage.vue
I removed the bullet points and tightened up the spacing of each list item. I also added slightly more space between methods to help better visually differentiate them.
=> grow-403 tighting up list item spacing.

src/components/Homepage/MonthlyGoodSelector.vue, src/components/Kv/KvButton.vue, src/pages/Homepage/MonthlyGoodHomepage.vue, src/plugins/loan-group-categories.js
* Implemented MG Homepage sticky selector component
* Minor fixes around MG homepage
STILL TODO:
* Add icons to cause buttons
* Sort cause buttons according to order in design
* Finalize tracking params
* Fix sticky positioning on window resize
=> GROW-395 MG Homepage Sticky Selector

src/components/CorporateCampaign/CampaignLoanGridDisplay.vue, src/components/CorporateCampaign/CampaignLoanRow.vue, src/components/Kv/KvLightbox.vue, src/components/LoanCards/HoverLoanCard/DetailedLoanCard.vue, src/components/LoanCards/LendHomepageLoanCard.vue, src/components/LoanCards/LoanCardController.vue, src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
Not perfect but gets us something to discuss.
=> ML2-122 loan details

src/components/Homepage/MonthlyGoodSelector.vue, src/pages/Homepage/MonthlyGoodHomepage.vue, src/plugins/loan-group-categories.js
* Sorted lending categories, small styling changes, fixed resizing issues
STILL TO DO:
* Replace icons in info section
* Add icons to causes buttons
=> GROW-395 Revisions

src/components/Homepage/MonthlyGoodSelector.vue
- Capitalization fix and hover state
- Hover state on "Students" button:
=> GROW-395 Add a hover state

src/components/Homepage/MonthlyGoodSelector.vue, src/plugins/click-outside.js
* Close MG Selector pop ups on pressing escape
* CLose MG pop ups when clicking outside
=> GROW-419 GROW-420 MG Selector Interactions

src/pages/Homepage/Homepage.vue
Remove stale commented out experiment
=> Remove home_lenderpreferences exp which is not used anymore

.storybook/stories/KvSettingsCard.stories.js, src/components/Kv/KvSettingsCard.vue, src/pages/Autolending/AutolendingStatus.vue, src/pages/Autolending/AutolendingWhen.vue, src/pages/Autolending/AutolendingWho.vue, src/pages/Settings/PaymentSettings.vue, src/pages/Subscriptions/SubscriptionsAutoDeposit.vue, src/pages/Subscriptions/SubscriptionsLegacy.vue, src/pages/Subscriptions/SubscriptionsMonthlyGood.vue, src/pages/Subscriptions/SubscriptionsOneTime.vue
* Removed settings card icon slots, fixed KvSettingsCard story
=> VUE-469 Remove KvSettingsCard Icon

src/components/WwwFrame/LendMenu/ExpandableListItem.vue, src/components/WwwFrame/LendMenu/LendListMenu.vue, src/components/WwwFrame/LendMenu/LendMegaMenu.vue, src/components/WwwFrame/PromotionalBanner/Banners/GenericPromoBanner.vue
ticket: https://kiva.atlassian.net/browse/GROW-362
Added a tracking event to Region name within the nav. 
- Added tracking to triggers from the promoBanner, if tracking is not set in contentful. 
/kiva/styleguide changes that are related: 
https://github.com/kiva/styleguide/pull/846
=> grow-362 tracking attempts

src/assets/scss/components/15-years/15-years.scss, src/components/15Years/15YearsHowKivaWorks.vue, src/components/15Years/15YearsHowKivaWorksCarousel.vue, src/components/15Years/15YearsStyles.vue, src/components/CorporateCampaign/CampaignHowKivaWorks.vue
* Breaks the carousel into its own component to prevent duplication.
* Fixes line wrap on small screens.
* Allows theming so 15 year page doesn't change, but we don't have mint colors and different fonts on ML page.
=> ML2-143 how it works carousel

src/pages/Settings/TwoStepVerificationPage.vue
=> grow-429 typo fixed

src/components/LoanCards/BorrowerInfo/BorrowerInfo.vue, src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
Fix scoping issue, hide learn more and close x on borrower info popup
=> Styling fixes for ML page

src/components/WwwFrame/Menus/TheSettingsTertiaryMenu.vue
Added Payments link TheSettingsTertiaryMenu.vue for SUBS-626
=> SUBS-626 adding payments to tertiary nav

src/pages/Homepage/Homepage.vue
This adds back experiment code for keeping around a way to view the legacy homepage. That homepage still outperforms the other versions of the homepage in paid ad experiments, so it continues to be used as the control.
This allows the legacy homepage to be viewed by using `kiva.org?setuiab=home_legacy.a`. By default all users are assigned to the `b` variant, meaning users not using the special url will see the contentful homepage by default (or the 'new' default homepage if the contentful homepage isn't active).
If this looks good I'd like to add it to Monday's release.
=> GROW-442 add back experiment to allow viewing legacy homepage

src/pages/Settings/TwoStepVerificationPage.vue
Flipped auth method order and updated Recommended -> Most Secure
=> grow-465 switched order of auth methods, recommended -> most secure

src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
So we don't have to clean up the hash, just scroll into view without changing it.
=> ML2-213 Jump to loans hash

src/pages/Homepage/MonthlyGoodHomepage.vue, src/pages/Settings/TwoStepVerificationPage.vue
Hotfix contains changes for: 
Grow-465: https://kiva.atlassian.net/browse/GROW-465
Grow-471: https://kiva.atlassian.net/browse/GROW-471
Grow-470: https://kiva.atlassian.net/browse/GROW-470
=> Hotfix for grow-465, 471, 470

src/pages/Homepage/MonthlyGoodHomepage.vue
* Fixes DOM getBoundingClientRect error if MG element does not exist
=> GROW-470 JS Error

src/assets/scss/global/forms.scss, src/components/Checkout/MonthlyGoodCTA.vue, src/components/Forms/MonthlyGoodUpdateForm.vue, src/pages/Thanks/ThanksPage.vue
* Changes to the thanks page to get ready for thanks page v2
* Added ability to drive MG CTA block body text and button through contentful
* Fixed MG CTA Block CTA so that it can be inserted in different layout contexts
* Fixed form error input minor issue
* Minor styling tweaks and added labels to MG CTA block.
* Switched dropdowns to default dropdowns
SUBS-633
SUBS-632
Tweaked design approved by Nick/Nathan
=> SUBS Thanks Page Enhancements

src/components/CorporateCampaign/LoanSearch/AttributeFilter.vue, src/components/CorporateCampaign/LoanSearch/GenderFilter.vue, src/components/CorporateCampaign/LoanSearch/LoanSearchFilters.vue, src/components/CorporateCampaign/LoanSearch/LocationFilter.vue, src/components/CorporateCampaign/LoanSearch/SectorFilter.vue, src/components/CorporateCampaign/LoanSearch/TagFilter.vue
* Use pill toggles for gender filter
* Add a fixed-width wrapper for filters. Spread filters into columns.
=> ML2-177 filter visual touchups

src/components/CorporateCampaign/CampaignLoanRow.vue, src/components/CorporateCampaign/LoanSearch/LoanSearchFilters.vue, src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
Fixes a handful of carousel bugs and reduces code duplication by converting homespun carousel to KvCarousel.
Similar homepage carousel PR coming shortly.
=> ML2-211 ML2-229 carousel

src/components/Subscriptions/SubscriptionsMonthlyGood.vue, src/components/Subscriptions/SubscriptionsMonthlyGoodCancellationFlow.vue
* Added tracking for starting MG cancel flow
* Added tracking event for cancelling MG cancel flow
=> SUBS-630 Tracking Events for MG Cancel Flow

src/pages/Homepage/Homepage.vue, src/pages/Homepage/iwd/IWD2021Homepage.vue
Layout component for IWD 2021. See ticket for link to contentful page layout.
=> GROW-476 IWD 2021 contentful page component

.storybook/stories/IWD2021Homepage.stories.js
Just added the 2021 International Women's Day page to storybook. Updated the file structure of the IWD folder to the following:
=> 2021 IWD into storybook, updated structure of IWD folder in storybook

src/graphql/mutation/completeGuestAccountClaim.graphql, src/pages/LoginAndRegister/GuestAccountClaim.vue, src/router/routes.js
=> Feature grow 486 guest acc claim

src/components/CorporateCampaign/LoanSearch/LoanSearchFilters.vue, src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
Added an excludedTags array on the stover-ct page for testing
=> ML2-233 Filter out any contentful excluded tag names

src/pages/Donate/DonateFromMacro.vue, src/pages/Donate/DonateFromMacroHero.vue, src/util/contentfulUtils.js
* Get images from contentful (VUE-326)
* Add contentful util helper which converts contentful responsive image into kv-responsive-image array
* Remove _get from page
* Remove usage of 'content' from contentful use, contents instead.
=> VUE-326 Refactor donate from macro site page

src/api/localResolvers/experiment.js, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue, src/pages/MonthlyGood/MonthlyGoodSetupPage.vue
* Add tracking event for creating funnels for this experiment from entry on /monthlygood/ or /setup/
* Remove unnecessary exp queries since experiment is prefetched in exp prefetch
=> SUBS-636 MG Login Experiment Fix

.github/workflows/lighthouse.yml, lighthouserc.js
Was able to lighthouse CI running with UI locally. Will have to see how things go as a github action.
=> VUE-221 Starting point for lighthouse CI

src/components/WwwFrame/TheFooter.vue
* New Footer design for new stack UI desktop resolution with MG link in footer and lend link.
Only includes the new design for new stack desktop resolutions.
Still TODO in upcoming PR's - 
- New stack mobile 
- Minimal legacy reskin
=> SUBS-619 New Footer and MG Link in Footer

src/components/Homepage/HomepageGeneralStats.vue, src/pages/Homepage/iwd/IWD2021Homepage.vue
=> GROW-437 Contentful homepage statistics component

src/components/Homepage/HomepageTestimonials.vue
I've removed all those media queries and reworked how these flourish images are placed. Much cleaner now.
=> Grow 438 fixes

src/pages/Homepage/15YearHomepage.vue, src/pages/Homepage/DefaultHomepage.vue, src/pages/Homepage/Homepage.vue, src/pages/Homepage/LendByCategoryHomepage.vue, src/pages/Homepage/MonthlyGoodHomepage.vue, src/pages/Homepage/TopMessageContentful.vue, src/pages/Homepage/iwd/IWD2021Homepage.vue, src/pages/Homepage/iwd/IWDHomepage.vue, src/pages/Homepage/wrd/WRDHomepage.vue
This is meant to improve the loading time and resource usage for the homepage by only loading the homepage component that is going to be active.
I saw very noticeable loading improvements in the VM:
Before change:
After change:
=> VUE-499 Dynamically import + prefetch active homepage

src/components/Homepage/HomepageHowItWorks.vue, src/components/Homepage/HomepageTestimonials.vue, src/pages/Homepage/LendByCategoryHomepage.vue, src/pages/Homepage/MonthlyGoodHomepage.vue
After rearranging the wrappers for the homepage, I came across issues with a couple versions of the homepage either not scrolling at all or having extra horizontal scroll. This pr cleans that up.
=> VUE-499 fix overflow scrolling homepage issues

src/components/Homepage/HomepageBottomCTA.vue, src/components/Homepage/HomepageCorporateSponsors.vue
After completing the previous grid fixes, I went back into the pieces of the IWD page I built and implemented the grid consistently. Visually it looks the same, but this is better and more consistent. 🧹
=> IWD grid fixes for bottom cta, sponsors sections

config/dev-vm.js, config/dev.js, src/components/WwwFrame/CookieBanner.vue, src/head/script.js
* Adds the oneTrust tool for dev environments
=> GDPR-27 OneTrust in Dev

src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
* Added button text and headline from contentful
=> VUE-501 Added Additional Elements from Contentful to MG Landing

.storybook/stories/KvContentfulImg.stories.js, src/components/CorporateCampaign/CampaignLogoGroup.vue, src/components/CorporateCampaign/CampaignPartner.vue, src/components/CorporateCampaign/CampaignPartnerThanks.vue, src/components/Homepage/HomepageHero.vue, src/components/Homepage/HomepageHowItWorks.vue, src/components/Homepage/HomepageMidrollCTA.vue, src/components/Homepage/HomepageTestimonials.vue, src/components/Kv/KvContentfulImg.vue
A component to give devs good image sizing and compression without much thought when using images from Contentful.
Implements the component on the homepage and managed lending pages.
=> VUE-483 kv-contentful-img

lighthouserc-prod.js
* Increase number of runs to reduce variability.
* Run a prod report nightly regardless of if our dev code has changed.
=> VUE-494 LHCI prod tweaks

.storybook/mixins/cookie-store-story-mixin.js, .storybook/stories/GetStarted.stories.js, .storybook/stories/IWD2021Homepage.stories.js, .storybook/stories/IWDHomepage.stories.js, .storybook/stories/LendByCategoryHomepage.stories.js, .storybook/stories/MonthlyGoodHomepage.stories.js, .storybook/stories/RecommendedLoanCard.stories.js, .storybook/stories/SecuritySettings.stories.js
Fixes issues with stories not loading because of missing injections.
=> VUE-502 Add cookieStore mixin for storybook

src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
Since `simpleCheckoutEligible` is always true now we can remove a few lines
=> Remove unused code

src/components/Homepage/HomepageStatistics.vue, src/pages/Homepage/LendByCategoryHomepage.vue
- Text now centered again on the 100% donation text
- Altered content group key
- Added ? to statsHeadline() incase the content isn't there and headline is undefined
=> cleanup, text center, corrected content group, verified working on & off

src/pages/Checkout/CheckoutPage.vue, src/pages/LoginAndRegister/GuestAccountRedirect.vue, src/router/routes.js
Handles redirecting guest users who have just created their passwords through login and then on to either /portfolio or /checkout, and shows a tip message confirming the creation of the account.
=> GROW-454 handle guest account claim completion redirection

src/components/Checkout/InContext/InContextCheckout.vue, src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
* Show donation field for matching campaigns. Show cart lightbox after logging in for matching campaigns.
* Showing a loading state on page load if loans are in cart
=> ML donation and loading state hotfixes

src/pages/Settings/PaymentSettings.vue
=> LW-2056 full story payments

src/client-entry.js, src/plugins/kv-analytics-plugin.js
Creates a polling mechanism and promise based setup for analytics initialization before attempting to fire the page view events.
=> Gdpr 38 asyn analytics setup

src/client-entry.js, src/plugins/kv-analytics-plugin.js
=> Gdpr 38 async analytics setup

src/components/Checkout/CheckoutDropInPaymentWrapper.vue
=> GROW-512 Change guest checkout checkbox colors

src/components/Checkout/CheckoutDropInPaymentWrapper.vue, src/graphql/mutation/shopValidateGuestPreCheckout.graphql, src/plugins/checkout-utils-mixin.js
=> Feature grow 520 guest marketing emails

src/components/Checkout/GuestUpsell.vue, src/components/Checkout/SocialShare.vue, src/components/Thanks/ThanksLayoutV2.vue, src/graphql/query/thanksPage.graphql, src/pages/Thanks/ThanksPage.vue, src/router/routes.js
https://kiva.atlassian.net/browse/GROW-444
Depends on kiva/kiva#9766
=> GROW-444 Add the guest upsell component to the thanks page

src/pages/Donate/DonateFromMacroHero.vue
* Get responsive sources using single image from contentful
* Uses new KvContentfulImg capabilities to create a set of responsive image sources using the image from contentful
* Allows us to have a single asset on contentful as opposed to 9
=> VUE-498 Refactor DonateFromMacro Hero Image

README.md, package-lock.json, package.json
* Removes husky prepare script in favor of manual install-husky script
* remove is-ci dependency
=> Remove Husky Prepare Script

src/pages/Donate/DonateFromMacro.vue, src/pages/Thanks/ThanksPage.vue
* processPageContent was only being used on 2 pages, removed in favor of processPageContentFlat.
* This will make it easier to improve the processPageContentFlat function to process pages with multiple layout references
=> VUE-513 Remove processPageContent

server/auth-router.js
=> GROW-536 Fix guest checkout login redirect

src/pages/MonthlyGood/MonthlyGoodSetupPage.vue
* Fixes error when on monthly good landing page, and you lose active login, then click the CTA button
=> Fix error when navigating from monthly good landing to setup page

src/pages/Settings/EmailSettings.vue
* Email settings for borrowers and trustees
=> VUE-524 VUE-525 Additional Email Settings

src/pages/LoginAndRegister/GuestAccountRedirect.vue
Previous redirect url:
```
/ui-login?claimed=1&login_hint=login&doneUrl=%2Fportfolio
```
New redirect url:
```
/ui-login?login_hint=login&doneUrl=%2Fportfolio%3Fclaimed%3D1
```
=> GROW-555 Ensure query params are included in doneUrl

server/auth-router.js
I'm not certain that this will fox the GROW-556 error, but I highly suspect that it will, and it's worth having anyway even if it doesn't fix the problem.
=> GROW-556 Add additional registration paths to login sync bypass list

src/pages/Settings/EmailSettings.vue
* Adds per team email settings to the email settings page
I keep unearthing hidden functionality on this page. This lets a user change their per-team email settings if they have teams and they are getting team digests
This component has definitely gotten larger than is ideal.....
=> VUE-529 Team Email Settings

server/live-loan-router.js, server/util/log.js, server/util/memJsUtils.js
Adds ability to hit loan-to-loan recommendation urls like 
`/live-loan/l/*loanid*/img/1` &
`/live-loan/l/*loanid*/url/1`
Retains loginid recommendation urls like
`/live-loan/u/*loginid*/img/1` &
`/live-loan/u/*loginid*/url/1`
Refactor to reduce duplicate code.
=> VUE-512 live loan images, loan-to-loan

server/auth-router.js
The cause of this issue comes from Auth0 not returning an access token with the correct audience and scopes for the first authorization request that happens after a guest user has set their first and last names. There is no difference between that request and the authorization request for other logins, so the exact cause beyond that is unknown. 
As a workaround, this attempts to start a new authorization request, which so far has always resolved the issue. In case there is a genuine error, this only does one retry to avoid an endless loop of failed authorization requests.
=> GROW-556 Reattempt login once if profile fails to be fetched

server/auth-router.js
Second hotfix for Guest Checkout. Will move out of draft once we have confirmed what we want to include in this hotfix.
=> Hotfix Guest Checkout part 2

src/components/Homepage/HomepageBottomCTA.vue, src/components/Homepage/HomepageCorporateSponsors.vue, src/components/Homepage/HomepageGeneralStats.vue, src/components/Homepage/HomepageHero.vue, src/components/Homepage/HomepageHowItWorks.vue, src/components/Homepage/HomepageLenderQuotes.vue, src/components/Homepage/HomepageLoanCategories.vue, src/components/Homepage/HomepageMidrollCTA.vue, src/components/Homepage/HomepageStatistics.vue, src/components/Homepage/HomepageTestimonials.vue, src/components/Homepage/HomepageVerticalCTA.vue, src/pages/ContentfulPage.vue, src/pages/Homepage/Homepage.vue, src/router/routes.js
Also changes the homepage to use ContentfulPage.
=> GROW-432 Add contentful based components to default homepage

src/pages/Checkout/CheckoutPage.vue
=> GROW-573  Hide guest checkout for kiva cards

src/components/Settings/PushRepaymentUpdates.vue, src/pages/Settings/EmailSettings.vue, src/util/pushNotificationsManager.js
* Added push notifications util and component
* Push notificication will still use legacy service worker
=> VUE-526 Push notifications for new email settings page

src/pages/ContentfulPage.vue
* New FAQ component type, for now just returns MG FAQ, but should be expanded via contentful to hold a dynamic set of FAQs
=> SUBS-676 Adds MG FAQ Component to Contentful Page

src/components/Homepage/HomepageHero.vue, src/components/MonthlyGood/MonthlyGoodSelector.vue, src/pages/ContentfulPage.vue
* Adds ability for ContentfulPage to pass down props into components
* Reads key for MG Hero and passes down options for cta function and button class
* Fix some event handling on MG Selector. Open selector when root event is fired from MG Hero
=> SUBS-669 Added MG Dynamic Landing Page Hero

src/components/WwwFrame/LendMenu/LendListMenu.vue, src/components/WwwFrame/LendMenu/LendMegaMenu.vue, src/util/experimentPreFetch.js
Setup initial assignment and access to assigned version where needed for upcoming navigation experiment.
=> Setup experiment assignment for monthly good in the header

src/components/MonthlyGood/MonthlyGoodSelector.vue, src/components/MonthlyGood/MonthlyGoodSelectorMobile.vue, src/components/MonthlyGood/MonthlyGoodSelectorWrapper.vue
* Implements new MG Cause/Amount selector for mobile web for MG LP
* Fix issue with cause/amount selection firing event listener for click outside
=> SUBS-671-694 Monthly Good LP Mobile MG Selector

src/graphql/query/thanksPage.graphql, src/pages/Thanks/ThanksPage.vue
* Cleans up thanks page to only use version `b` of the thanks page exp. Also known as thanks page V2
=> SUBS-698 Clean up Thanks Page V2 Exp

src/components/MonthlyGood/MonthlyGoodSelectorMobile.vue, src/components/MonthlyGood/MonthlyGoodSelectorWrapper.vue
* Fixes an issue where the hidden MG mobile selector, is opening a modal, which is scroll locking the body on desktop
=> SUBS-671 Bug Fix

src/pages/ContentfulPage.vue, src/router/routes.js
* Fix for MG LP Landing page dynamic route and meta tag
=> SUBS-663 Dynamic MG LP route

src/components/Homepage/HomepageBottomCTA.vue, src/components/MonthlyGood/MonthlyGoodSelector.vue, src/pages/ContentfulPage.vue
* Add transition to MG Selector
* Add bottom cta with custom CTA function to HomepageBottomCTA
=> SUBS-702 Monthly Good Landing Page - Bottom CTA

Developer_Tools.md, config/local.js, src/graphql/query/flssQuery.graphql, src/pages/FlssPrototypes/FlssLoanRow.vue, src/pages/FlssPrototypes/SampleLoanDisplay.vue
Jira Ticket:
https://kiva.atlassian.net/browse/PSD-137
What does it do:
sets up route, page and independent graphql queries for flss test demo page. 
How to test:
spinning up ui server should be able to navigate to 
`localhost:8888/flss`
then the page should render with loans from trending now sort from dev graphql endpoint
=> PSD-137: create test page for displaying flss queries

src/components/WwwFrame/LendMenu/LendMegaMenu.vue, src/components/WwwFrame/LendMenu/MonthlyGoodExpMenuWrapper.vue, src/components/WwwFrame/TheHeader.vue, test/unit/specs/components/WwwFrame/TheHeader.spec.js
* Implements MG Lend Menu Experiment for Desktop
=> SUBS-697 MG Lend Menu Experiment Desktop

src/components/WwwFrame/LendMenu/LendListMenu.vue, src/components/WwwFrame/LendMenu/MonthlyGoodExpMenuWrapper.vue, src/components/WwwFrame/TheHeader.vue
* Adds monthly good menu exp to mobile
* Change menu exp button capitalization
=> SUBS-696 MG Menu Exp Mobile

src/components/WwwFrame/LendMenu/MonthlyGoodExpMenuWrapper.vue, src/components/WwwFrame/TheHeader.vue
* Fixes issues with the lend menu experiment caused by duplicate refs.
=> SUBS-679 Rework

src/pages/Settings/RecoveryCodeConfirm.vue
Grow-466
- In order to get the  showTipMsg() working that I added, I needed to inject Apollo into the file.
=> adding apollo inject to file for showTipMsg() works.

src/components/Kv/KvSettingsCard.vue, src/pages/Settings/PaymentSettings.vue
* Add missing icon to payment settings
* Remove left padding on settings card content
=> Minor Settings Card Fixes

src/api/localResolvers/my.js, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue, src/pages/MonthlyGood/MonthlyGoodSetupPage.vue, src/util/experimentPreFetch.js
* Use hasEverLoggedIn to determine if the user should login before or after the MG setup form.
=> SUBS-659 Monthly Good Page Login Flow

src/components/Checkout/DonationItem.vue
=> GROW-584 Updated lightbox copy

src/components/Checkout/DonationItem.vue
Reverts kiva/ui#2880
Need to fix lint errors
=> Revert "GROW-584 Updated lightbox copy"

src/components/Checkout/DonationItem.vue
Reverted https://github.com/kiva/ui/pull/2883 in order to fix lint errors
=> Feature grow 584 guest checkout lightbox copy

src/pages/StartVerification.vue
Added some data-test tags to 3 elements to make it easier for our test to work for this page.
=> Add data-test tags for QA use

build/webpack.base.conf.js, build/webpack.client.base.conf.js, build/webpack.server.conf.js, package-lock.json, package.json
Alternative to https://github.com/kiva/ui/pull/2890. This is also a "blunt" solution to fouc, though this sends all styles to vue-style-loader.
=> VUE-577 Use vue-style-loader for all styles

src/components/Contentful/DynamicHero.vue
I think this will keep the Carousel component and its dependencies from loading for non Carousel use cases?
=> Dynamically import KvCarousel component

.storybook/mock-data/contentful-data-mock.js, .storybook/stories/DynamicHero.stories.js, src/components/Contentful/DynamicHero.vue, src/components/Contentful/SectionWithBackground.vue
* Adds stories for dynamic hero and dynamic hero with background
* Refactor SectionWithBackground CSS to remove the requirement of explicit css height.
=> SUBS-708 Stories & Improvements

src/components/Homepage/HomepageVerticalCTA.vue
=> GROW-612 Vertical CTA experiment

src/pages/Checkout/CheckoutPage.vue
=> Feature grow 614 guest checkout cts

src/components/BorrowerProfile/BorrowerName.vue, src/pages/BorrowerProfile/BorrowerProfile.vue
=> GROW-659 Borrower name component

src/components/BorrowerProfile/LoanUse.vue, src/plugins/loan-use-filter.js, test/unit/specs/plugins/loanUseFilter.spec.js
[grow-619](https://kiva.atlassian.net/browse/GROW-619) Loan use statement for borrower profile. 
Component that accepts some props and returns the formatted loan use (up to 100 characters length) based on the status of the loan.
=> build: Loan use component for borrower profile

.storybook/mock-data/contentful-data-mock.js, .storybook/stories/DynamicHero.stories.js, src/components/Contentful/DynamicHero.vue, src/components/Contentful/SectionWithBackground.vue
Depends on (includes: https://github.com/kiva/ui/pull/2970)
=> Vue 749 responsive adaptive dynamic hero

src/components/BorrowerProfile/LoanDescription.vue, src/components/BorrowerProfile/MoreAboutLoan.vue
=> Feature grow 636 more about this loan

src/components/BorrowerProfile/LendCta.vue
=> GROW-628 Lending ineligibility for free credit

src/pages/Lend/FilterAlpha/LendFilterAlpha.vue
Created a page titled Lend Filter Alpha and imported the Wwwpage component.
Not testable yet. 
https://kiva.atlassian.net/browse/PSD-262
=> Psd 262 lend filter frame setup

src/router/routes.js
Created a route on a page titled Lend Filter Alpha.
The way that you can test this ticket is by running the dev server locally, navigating to: http://localhost:8888/lend/filter-alpha
https://kiva.atlassian.net/browse/PSD-261
=> Created route for lend filter alpha

src/components/AutoDeposit/AutoDepositDropInPaymentWrapper.vue, src/components/Checkout/CheckoutDropInPaymentWrapper.vue, src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue, src/pages/Checkout/CheckoutPage.vue, src/pages/Donate/DonateFormDropInPaymentWrapper.vue, src/pages/Settings/PaymentSettings.vue
The braintree-dropin-lib doesn't play nice with NodeJS 16. This ensures that all is well with the impending update.
=> Vue 625 braintree client init

src/components/BorrowerProfile/TrusteeDetails.vue
Text update to complete the requirements for [grow-721](https://kiva.atlassian.net/browse/GROW-721)
=> grow-721 updating the trustee description text

src/components/BorrowerProfile/MoreAboutLoan.vue
[Grow-714](https://kiva.atlassian.net/browse/GROW-714)
Running more about this loan content through v-html to translate html.
=> grow-714 running content through v-html to translate HTML tags

src/components/BorrowerProfile/FieldPartnerDetails.vue, src/components/BorrowerProfile/MoreAboutLoan.vue
[Grow-716](https://kiva.atlassian.net/browse/GROW-716)
I altered the field partner disclaimer text and moved it into the "More about this loan section"
=> grow-716 field partner disclaimer text atered and moved

src/components/BorrowerProfile/SummaryCard.vue, src/pages/BorrowerProfile/BorrowerProfile.vue
[Grow-701](https://kiva.atlassian.net/browse/GROW-701)
Added a tracking event for borrower profile page load, which contains the loan status.
=> grow-701 tracking event for borrowerProfile page load

build/webpack.base.conf.js, package-lock.json, package.json, src/App.vue, src/assets/scss/tailwind/tailwind.css, src/pages/BorrowerProfile/BorrowerProfile.vue
- break tailwind into a static css file since they're global styles
- prepend all of the tailwind resets and utility classes with .kv-tailwind to give enough specificity to win over foundation resets
=> Test: Nest Tailwind classes in a container to add specificity.

src/components/BorrowerProfile/MoreAboutLoan.vue, src/components/BorrowerProfile/SummaryCard.vue, src/components/WwwFrame/TheTipMessage.vue, src/pages/BorrowerProfile/BorrowerProfile.vue
Needed now that tailwind's reset takes precedence
=> Borrower profile layout tweaks

src/components/BorrowerProfile/DetailsTabs.vue, src/components/BorrowerProfile/LoanDetails.vue
[Grow-697](https://kiva.atlassian.net/browse/GROW-697)
Added disbursalDate to the Loan Details tab on the borrower profile.
=> grow-697 disbursalDate added to Loan details tab

src/components/BorrowerProfile/LoanDescription.vue, src/components/BorrowerProfile/MoreAboutLoan.vue
[Grow-745](https://kiva.atlassian.net/browse/GROW-745)
- Moved the loan story from a {{ paragraph }} => v-html="paragraph" which should fix the issues in the loan story portion of the page.
=> grow-745 passing loan description paragraph through v-html

src/pages/Lend/FilterAlpha/LendFilterAlpha.vue
We had to make some Tailwind changes to prevent conflicts in other areas of the site. This PR should get your styling working again.
=> Fix for tailwind classes on lend filter alpha page

src/components/MonthlyGood/MonthlyGoodSelectorMobile.vue
- Redesigned the flow of the sticky monthly good selector on mobile. 
- Refactored to use kv-ui elements and tailwinds
TODO:
- Copy should come from contentful
Reference figma: 
https://www.figma.com/file/weQAkMDYoBA5ZnuHf4TPOA/Cause-Based-Landing-Page-Templates?node-id=136%3A1442
Minor differences between the figma and implementation to use our kv-ui-elements kvlightbox standards. (button position, title position, height of lightbox on mobile, etc)
SUBS-783
=> feat: redesign and refactor mobile sticky monthly good selector

build/webpack.base.conf.js, package-lock.json, package.json, src/components/Contentful/DynamicHero.vue, src/components/Contentful/DynamicRichText.vue, src/util/contentful/richTextRenderer.js
Adds a dynamic rich text renderer which will render rich text fields with embedded content. 
- Will render images, video, and rich text fields embedded in rich text fields, either as entries or inline entries. 
TODO:
- Implement support for other embedded content types. (Kv-Button) 
- Possibly fine tune document nodes for our styleguide typography classes
=> VUE-642 Rich Text Renderer

src/components/MonthlyGood/MonthlyGoodSelectorMobile.vue, src/components/MonthlyGood/MonthlyGoodSelectorWrapper.vue
Get main marketing copy from contentful for the mobile monthly good selector
SUBS-782
=> feat: mobile monthly good sticky selector copy from contentful

src/router/routes.js
This change didn't get included in the last PR. 
homepage -> homepage-classic
=> core-14 updated routing data

package-lock.json, package.json
* **KvTabs:** Make inactive tab color black to prevent users from thinking its disabled ([ec28ce2](https://github.com/kiva/kv-ui-elements/commit/ec28ce26f43716b1d5290b23676a1d7b9c24302f))
**Note:** Version bump only for package @kiva/kv-components
* **KvLightbox:** Fix minimum height 50% of screen on mobile. ([6abcd6b](https://github.com/kiva/kv-ui-elements/commit/6abcd6b432a42c7ab1133e2bee05f05e06f001d1))
* **KvSelect:** fixes issue where chevron wasn't visible in safari ([f01c9f5](https://github.com/kiva/kv-ui-elements/commit/f01c9f502035cdc9d2d39dd493121879afb3eff1))
* **KvTabs:** fix unselected tab panel color ([3b5146a](https://github.com/kiva/kv-ui-elements/commit/3b5146afe22a95b2dadb7cd0580873f0d26d602c))
* **KvTabs:** Prevent different height tab contents from overflowing their …
=> chore: pull in latest kv-components

package-lock.json, package.json, src/components/WwwFrame/SearchBar.vue, test/unit/helpers/byTextContent.js, test/unit/specs/components/RouteListing.spec.js, test/unit/specs/components/WwwFrame/SearchBar.spec.js, test/unit/specs/components/WwwFrame/TheHeader.spec.js
Testing Library is the current official recommendation by the Vue.js guide for testing Vue components https://vuejs.org/v2/guide/testing.html#Vue-Testing-Library-testing-library-vue
=> VUE-648 migrate from @vue/test-utils to @tesing-library/vue

src/components/Contentful/DynamicRichText.vue, src/util/contentful/richTextRenderer.js
Test page: https://www.dev.kiva.org/lp/eddie-test-landing
- Renders kvButton components from embedded or inline button entries
- Wraps rich text output in kv-tailwind class to fix rendering
SUBS-789
=> feat: Adds the ability of the rich text renderer to render KvButtons

package-lock.json, package.json
All notable changes to this project will be documented in this file.
See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
* Adds KvCarousel component ([#100](https://github.com/kiva/kv-ui-elements/issues/100)) ([05a57b5](https://github.com/kiva/kv-ui-elements/commit/05a57b552d1e884a2cebb3d4e1b9a093d8c9834e))
* Adds KvCarousel component ([#100](https://github.com/kiva/kv-ui-elements/issues/100)) ([05a57b5](https://github.com/kiva/kv-ui-elements/commit/05a57b552d1e884a2cebb3d4e1b9a093d8c9834e))
**Note:** Version bump only for package @kiva/kv-components
* **KvTextInput:** Kiva Classic input type=text ([6d17b96](https://github.com/kiva/kv-ui-elements/commit/6d17b96c7b397f2764e45a97029c36a47012654e))
=> chore: update kv-components to latest

src/components/Contentful/HeroWithCarousel.vue, src/components/Contentful/StoryCard.vue, src/util/contentfulUtils.js
Test on dev: 
https://www.dev.kiva.org/lp/eddie-test-landing
- Adds util to process story card content
- Adds mock story card template
- Adds story card template and carousel to hero component
=> feat: Added mock story card template and carousel to landing page hero

package-lock.json, package.json, tailwind.config.js
During development sometimes I'd add a new Tailwind class that hadn't been used yet and it wouldn't be added to the CSS file. Came across a few issues on Github with similar symptoms: https://github.com/tailwindlabs/tailwindcss/issues/4081. 
Then found some more info on the Tailwind JIT docs. https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files
Bumping Tailwind and adding the `TAILWIND_MODE=watch` var seems to work for me now. Though not always with HMR.
=> Tailwind JIT/purge fix

build/webpack.client.dev.conf.js, package-lock.json, package.json, server/dev-server.js
=> Revert "Bump webpack-dev-middleware from 3.7.3 to 5.1.0"

src/components/Contentful/DynamicRichText.vue, src/components/MonthlyGood/MonthlyGoodSelectorMobile.vue, src/components/MonthlyGood/MonthlyGoodSelectorWrapper.vue, src/pages/ContentfulPage.vue, src/util/contentful/richTextRenderer.js
Hotfix for landing pages
GD-116
GD-121
=> Hotfix 20210913

src/components/WwwFrame/WwwPageDesign.vue
Since our nav is sticky at the top we need to scroll a little farther down the page.
=> Design site: Ensure the top nav isn't covering the content when clicked

package-lock.json, package.json
Features
KvButton: Add active state prop and styling 
Bug Fixes
Remove unnecessary lightbox class and webkit fix, make lightbox stories initialize with open lightboxes for better visual diffs
Fix lightboxes being cut off vertically on mobile
=> chore: bump kv-components version

src/components/WwwFrame/WwwPageDesign.vue
Pre-populates an email with a message from design. Also added as a contentful button.
=> VUE-667 feat: Add font request email

src/components/MonthlyGood/MonthlyGoodSelectorWrapper.vue
* Determine if mobile on page load
Would like to hotfix
=> fix: Additional fix for GD-128

src/components/LoanCollections/KivaClassicLoanCarousel.vue
[Core-109](https://kiva.atlassian.net/browse/CORE-109)
Simple update of the tracking events happening on the carousel arrows. 
Once this gets to development, i'll be testing clicks as well as touch interactions for these tracking events.
=> Core-109 updating tracking interaction for carousel

src/api/localResolvers/loan.js, test/unit/specs/api/localResolvers/loan.spec.js
Hotfix for [Core-239](https://kiva.atlassian.net/browse/CORE-239)
=> Hotfix core 239

server/auth-router.js
* Take query param in ui-login route and pass it on to auth0
GD-153
=> feat: added cause query param to auth server

src/components/Kv/KvCurrencyInput.vue, src/components/MonthlyGood/AlreadySubscribedNotice.vue, src/components/MonthlyGood/LegacySubscriberNotice.vue, src/pages/MonthlyGood/EmailPreview.vue, src/pages/MonthlyGood/HowItWorks.vue, src/pages/MonthlyGood/KivaAsExpert.vue, src/pages/MonthlyGood/LandingForm.vue, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue, src/pages/MonthlyGood/MonthlyGoodSetupPage.vue, src/pages/MonthlyGood/MonthlyGoodThanksPage.vue, src/pages/MonthlyGood/MoreAboutKiva.vue
Covers the monthly good flow
https://test.kiva.org/monthlygood/
https://test.kiva.org/monthlygood/setup?amount=25&category=default
https://test.kiva.org/monthlygood/thanks
https://www.kiva.org/monthlygood/
https://www.kiva.org/monthlygood/setup?amount=25&category=default
https://www.kiva.org/monthlygood/thanks
May want to pull down this branch and do testing on your VM to go through the whole flow.
=> typography: Monthly good

src/components/Checkout/BasketItem.vue, src/components/Checkout/BasketItemsList.vue, src/components/Checkout/BasketVerification.vue, src/components/Checkout/CheckoutDropInPaymentWrapper.vue, src/components/Checkout/CheckoutHolidayPromo.vue, src/components/Checkout/CheckoutItemImg.vue, src/components/Checkout/DonateRepaymentsToggle.vue, src/components/Checkout/DonationItem.vue, src/components/Checkout/DonationNudge/DonationNudgeBoxes.vue, src/components/Checkout/DonationNudge/DonationNudgeIntro.vue, src/components/Checkout/DonationNudge/DonationNudgeLightbox.vue, src/components/Checkout/KivaCardItem.vue, src/components/Checkout/KivaCardRedemption.vue, src/components/Checkout/KivaCreditPayment.vue, src/components/Checkout/LoanMatcher.vue, src/components/Checkout/LoanPrice.vue, src/components/Checkout/LoanPromoCredits.vue, src/components/Checkout/LoanReservation.vue, src/components/Checkout/OrderTotals.vue, src/components/Checkout/TeamAttribution.vue, src/components/Checkout/VerifyRemovePromoCredit.vue, src/components/Kv/KvCheckoutSteps.vue, src/components/LoansYouMightLike/MinimalLoanCard.vue, src/components/RandomLoanSelector/randomLoanSelector.vue, src/pages/Checkout/CheckoutPage.vue
https://www.test.kiva.org/checkout
Note, this PR does not include the thanks page, only checkout.
=> feat: Kiva Classic typography and form element updates for /checkout

.eslintrc.js
This fixed up that squiggly error for `graphql-tag` with a more explicit path and the lint "issues" in that file.
=> fix: update eslint import path to fix eslint error for package case

build/webpack.base.conf.js, src/components/Payment/BraintreeDropInInterface.vue
* Styles the BT drop in interface component to look closer to KivaClassic
GD-168
=> feat: style braintree drop-in to match KivaClassic

src/components/AutoDeposit/AutoDepositDropInPaymentWrapper.vue, src/components/AutoDeposit/AutoDepositSignUpForm.vue, src/pages/AutoDeposit/AutoDepositLandingPage.vue, src/pages/AutoDeposit/AutoDepositThanksPage.vue
https://www.test.kiva.org/auto-deposit
https://www.kiva.org/auto-deposit
https://www.test.kiva.org/auto-deposit/thanks
https://www.kiva.org/auto-deposit/thanks
=> typography: /auto-deposit and /auto-deposit/thanks

src/components/Kv/KvBaseInput.vue, src/components/SystemFrame/SystemPage.vue, src/pages/LoginAndRegister/GuestAccountClaim.vue, src/pages/LoginAndRegister/RegisterSocial.vue
https://test.kiva.org/register/guest
https://www.kiva.org/register/guest
/register/social is harder to test, screenshot below
=> typography: /register pages

src/assets/scss/global/forms.scss, src/components/Checkout/CheckoutReceipt.vue, src/components/Checkout/GuestUpsell.vue, src/components/Checkout/MonthlyGoodCTA.vue, src/components/Checkout/SocialShare.vue, src/components/CorporateCampaign/CampaignThanks.vue, src/components/Kv/KvIconButton.vue, src/components/Thanks/ThanksLayoutV2.vue, src/pages/Thanks/ThanksPage.vue
https://www.test.kiva.org/checkout/thanks
https://www.kiva.org/checkout/thanks
To get the full receipt to show up, you'll need to make a purchase on your vm. Screenshots below
=> typography:  /checkout/thanks

src/components/Forms/MultiAmountSelector.vue, src/pages/Donate/DonateForm.vue, src/pages/Donate/DonateFormDropInPaymentWrapper.vue, src/pages/Donate/DonateSupportUsRightRail.vue
https://test.kiva.org/donate/supportus
https://www.kiva.org/donate/supportus
=> feat: typography and layout tweaks for /donate/supportus

src/components/Kv/KvCustomDonation.vue, src/pages/Protocol.vue
https://test.kiva.org/protocol
https://www.kiva.org/protocol
=> feat: typography and colors for /protocol

src/components/AutoDeposit/AutoDepositDropInPaymentWrapper.vue, src/components/Forms/MonthlyGoodUpdateForm.vue, src/components/Settings/SubscriptionsSettingsCards.vue, src/components/Subscriptions/SubscriptionsAutoDeposit.vue, src/components/Subscriptions/SubscriptionsMonthlyGood.vue, src/components/Subscriptions/SubscriptionsMonthlyGoodCancellationFlow.vue, src/pages/Settings/SubscriptionsSettings.vue
https://www.test.kiva.org/settings/subscriptions
https://www.kiva.org/settings/subscriptions
=> typography: settings/subscriptions

src/pages/LendingStats/ItemList.vue, src/pages/LendingStats/LendingStatsPage.vue, src/pages/LendingStats/StatsSection.vue
http://test.kiva.org/portfolio/lending-stats
http://www.kiva.org/portfolio/lending-stats
=> feat: kiva classic typography for /portfolio/lending-stats

src/pages/Donate/DonateForm.vue, src/pages/Donate/DonateFromMacro.vue, src/pages/Donate/DonateFromMacroHero.vue
Donate components were updated to have tw classes for typography in /donate/suppport-kiva page
=> Typography vue 845 donate supportkiva

src/pages/Causes/Signup.vue, src/pages/Causes/SignupForm.vue, src/pages/Causes/SignupWaitlist.vue
* adds dynamic withdrawal date to causes signup, based on todays date
* fix eligibility for causes
* minor styling fix for when we have the users email
GD-166
GD-161
=> feat: adds dynamic date to causes signup form

src/pages/Causes/SignupForm.vue
=> fix: changed month end copy for causes signup

src/components/AutoDeposit/AutoDepositDropInPaymentWrapper.vue, src/components/Causes/CausesDropInPaymentWrapper.vue, src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue, src/components/Payment/BraintreeDropInInterface.vue, src/pages/Causes/SignupForm.vue, src/pages/Donate/DonateFormDropInPaymentWrapper.vue, src/pages/Settings/PaymentSettings.vue
* Fixes issue with BT drop in wrappers stuck on button loading
* Minor visual fixes to causes signup form
=> fix: fixes issues with BT drop in and causes signup

src/components/AutoDeposit/AutoDepositDropInPaymentWrapper.vue, src/components/Causes/CausesDropInPaymentWrapper.vue, src/components/Checkout/CheckoutDropInPaymentWrapper.vue, src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue, src/components/Payment/BraintreeDropInInterface.vue, src/pages/Donate/DonateFormDropInPaymentWrapper.vue, src/pages/Settings/PaymentSettings.vue
=> fix: fixes issue with double initializing of BT drop in

src/components/Causes/CausesDropInPaymentWrapper.vue, src/pages/Causes/SignupForm.vue, src/pages/Causes/SignupWaitlist.vue
* Add separate iterable lists for waitlist signup for existing and current users
* Force day of month to be max 28
* Change day of month messaging
GD-162
=> feat: causes form and waitlist improvements

src/components/Kv/KvAccordionItem.vue, src/components/WwwFrame/DisclaimersContentful.vue
KvAccordionItem was updated to have tw classes and no more custom classes.
Note: Negative rotation for icon is not working with tw classes, so, is working with positive rotation.
_tw--rotation-180_
=> Kvaccordion vue 875

src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
=> feat: show donation row when lendingRewardOffered

package-lock.json, package.json
1.3.0 (2021-12-13)
Features
KvTextInput: adds a button which clears the search form (bf4166e)
=> chore: bump kv-components to latest

src/components/Settings/SubscriptionsSettingsCards.vue, src/components/Subscriptions/SubscriptionsCauses.vue, src/components/Subscriptions/SubscriptionsCausesCancellationFlow.vue, src/pages/Causes/Signup.vue
TODO: 
To avoid the settings page from looking like a mismatch of old styles and KivaClassic. After this gets merged I will merge into typography branch and style these new components with KivaClassic
- Refactor styles/html to align with kivaClassic
=> feat: allow a causes subscription user to cancel their subscription

src/pages/Causes/SignupForm.vue
Allows changing the category name in the future and still getting the correct category id based on the dataObject of the contentful entry
GD-185
=> feat: map causes category id in signup form using contentful entry key

src/components/Checkout/CheckoutReceipt.vue, src/components/WwwFrame/DisclaimersContentful.vue
=> fix: guard lendingRewardOffered and receipt.values before usage

src/components/Checkout/KivaCardRedemption.vue, src/components/Forms/JoinTeamForm.vue, src/pages/Legal/Legal.vue, src/pages/LendingStats/LendingStatsPage.vue, src/pages/LendingStats/StatsSection.vue, src/pages/Settings/SettingsPage.vue
data-testid attribute was added to some required components
=> feat: datatestid attribute was added to some elements

src/components/Forms/CausesUpdateForm.vue, src/components/Settings/SubscriptionsSettingsCards.vue, src/components/Subscriptions/SubscriptionsCauses.vue, src/graphql/mutation/updateSubscription.graphql, src/pages/Causes/SignupForm.vue
=> feat: allow a user to modify their causes subscription

src/components/AutoDeposit/AutoDepositDropInPaymentWrapper.vue, src/components/Forms/CausesUpdateForm.vue, src/components/Forms/MonthlyGoodUpdateForm.vue, src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue, src/components/Subscriptions/SubscriptionsAutoDeposit.vue, src/components/Subscriptions/SubscriptionsCauses.vue
=> feat: add kiva classic style to causes settings components

src/components/BorrowerProfile/PreviousLoanDescription.vue, src/components/BorrowerProfile/RepaymentSchedule.vue
Another step toward [core-148](https://kiva.atlassian.net/browse/CORE-148)
Repayment schedule
These changes cover the repayment schedule for Field Partner loans that are payingBack. 
If a repayment is received on time, that month's repayment is marked as paid. If the borrower is delinquent on their repayments we also mark that on the repayment schedule.
**Paying back loan in good standing:**
**Paying back loan that's delinquent:** (page data was manipulated to get a delinquent row to show because we strip out repayment data in dev and our local dbs)
=> Core 148 paying back repayment schedule

src/components/Subscriptions/SubscriptionsCauses.vue
=> fix: causes subscription day of month edit not working

src/components/Causes/CausesDropInPaymentWrapper.vue, src/components/Subscriptions/SubscriptionsCauses.vue, src/graphql/mutation/updateSubscriptionPaymentMethod.graphql
GD-194
See ticket for more details
=> feat: update causes subscription payment method

src/components/MonthlyGood/MonthlyGoodDropInPaymentWrapper.vue, src/components/Subscriptions/SubscriptionsCauses.vue, src/components/Subscriptions/SubscriptionsMonthlyGood.vue
=> feat: causes update payment method kiva classic styling

src/components/Contentful/StoryCard.vue
=> fix: add storycard spacing between storycard content and cta

src/components/BorrowerProfile/RepaymentSchedule.vue
[Core-249](https://kiva.atlassian.net/browse/CORE-249)
Tracking for repayment schedule click. 
To test: 
go to the borrower profile and click the "detailed repayment schedule" link in the loan details section of the page. 
tracking event should be triggered.
=> feat: core-248 Tracking for repayment schedule

src/pages/Causes/SignupForm.vue
=> feat: add FB tracking event for Causes signup

src/pages/ContentfulPage.vue
This seem to have come back somehow after the typography merge
=> fix: remove wrapperClass from contentfulPage

src/components/Contentful/StoryCard.vue, src/util/contentful/richTextRenderer.js
=> fix: fixes extra spacing created by images in RTF's from contentful

src/components/WwwFrame/LendMenu/LendListMenu.vue, src/components/WwwFrame/LendMenu/LendMegaMenu.vue, src/components/WwwFrame/LendMenu/SearchList.vue, src/components/WwwFrame/SearchBar.vue, src/components/WwwFrame/TheHeader.vue
https://user-images.githubusercontent.com/187937/148857795-c5c725e6-a136-4576-8a9f-91901abd1dab.mov
=> VUE-914, VUE-920: Topnav, My Kiva and Saved Searches

src/components/WwwFrame/TheBasketBar.vue
=> feat: convert TheBasketBar to Kiva Classic

src/components/BorrowerProfile/LoanBookmark.vue
After you asked me to clean up the last PR, I realized that I could clean up this component too.
=> fix: refactor loanBookmark component to decrease redundancy

src/components/BorrowerProfile/DetailsTabs.vue
Adding two missing data points
=> fix: core-148 adding data points to complete the data loop

src/components/WwwFrame/TheFooter.vue
Found from the lighthouse report
=> fix: add accessible text to social media icons

src/components/LoanCards/HoverLoanCard/HoverLoanCardLarge.vue
=> VUE-952 fixes for loans that another lender has selected

src/components/BorrowerProfile/BorrowerBusinessDetails.vue
Explanation here: https://kiva.atlassian.net/browse/VUE-923?focusedCommentId=323887
=> fix: allow website link to be processed, fire sentry in the client only

src/pages/Causes/Signup.vue
ACK-184
This is ok to go out with the next release. Technically anyone with the link will be able to signup for causes before the launch on Feb 7, but we won't be driving traffic to the signup page until then
=> feat: remove beta query param for causes

src/components/BorrowerProfile/SummaryCard.vue
[Core-411](https://kiva.atlassian.net/browse/CORE-411)
Before calling fundraising related data (fundraisingPercent, fundraisingTimeLeft & unreservedAmount) I'm now looking at the loan.status to verify it is fundraising.
=> fix: core-411 only fetching fundraising loan data if loan is fundraising

src/assets/scss/global/typography.scss, src/components/Checkout/OrderTotals.vue, src/components/Forms/CausesUpdateForm.vue, src/components/Forms/MonthlyGoodUpdateForm.vue, src/components/Homepage/CategoryGrid.vue, src/components/Kv/KvCarousel.vue, src/components/Kv/KvFlag.vue, src/components/Kv/KvPagination.vue, src/components/Kv/KvPhoneInput.vue, src/components/LoanCards/AdaptiveMicroLoanCard.vue, src/components/LoansByCategory/ViewToggle.vue, src/components/LoansYouMightLike/MinimalLoanCard.vue, src/components/Settings/TwoStepVerification.vue, src/components/Styleguide/StyleguideIntro.vue, src/components/Subscriptions/SubscriptionsAutoDeposit.vue, src/components/Subscriptions/SubscriptionsOneTime.vue, src/components/WwwFrame/PromotionalBanner/Banners/AppealBanner/AppealBanner.vue, src/components/WwwFrame/TheBrowserCheck.vue, src/pages/AlgoliaPOC.vue, src/pages/MonthlyGood/MonthlyGoodSetupPage.vue
=> Remove remaining Foundation typography classes

src/components/CorporateCampaign/LoanSearch/LoanSearchFilters.vue, src/components/CorporateCampaign/LoanSearch/TagFilter.vue
This keeps them out of the filter lightbox on /cc pages
=> fix: exclude private tags from the tag filter list

src/components/Contentful/StoryCard.vue
=> fix: remove gradient from imageCard link storycards

src/components/Contentful/StoryCard.vue
* Don't force storycard title to be h4
ACK-218
=> feat: storyCard component enhancements

src/pages/AutoDeposit/AutoDepositLandingPage.vue, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
=> fix: remove guards for new subs service from MG and AD landing pages

src/api/ExperimentIdLink.js, src/graphql/query/lendByCategory/lendByCategory.graphql, src/pages/Lend/LendByCategoryPage.vue
The settings manager entry for this has been added to prod and dev under the key `uiexp.EXP-VUE-937-recommended-row-algo`, however only the dev version is enabled.
=> feat: tracking for recommended row algorithm experiment VUE-937

src/pages/MonthlyGood/PersonalizedMonthlyGoodLandingPage.vue
[Core-404](https://kiva.atlassian.net/browse/CORE-404)
**SMALL**
**MED**
**LARGE**
=> feat: core-404 personalized mg hero in place, only cleanup needed

src/pages/MonthlyGood/PersonalizedMonthlyGoodLandingPage.vue
[Core-405](https://kiva.atlassian.net/browse/CORE-405)
Getting this piece into place, will need a little polish once all the page is put together.
=> feat: core-405 MG personalized value prop

src/components/LoanCards/GridLoanCard.vue
=> fix: fix margin on funded text in loan card

src/components/MonthlyGood/PersonalizedMgLightbox.vue, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue, src/pages/MonthlyGood/PersonalizedMonthlyGoodLandingPage.vue
**Not yet fully complete.**
Working on fixes for the MG personalized hero. 
- Now passing monthly good amount though to mothlygood/setup page.
Remaining:
- large screens, getting the cta overlay box to sit in the right place on the screen.
=> Mg personal

src/components/WwwFrame/LendMenu/TheLendMenu.vue
mixed this up in the previous commit :(
=> fix: update address of date from query for mg lend menu setting

src/components/CorporateCampaign/LoanSearch/LoanSearchFilters.vue, src/components/WwwFrame/TheFooterCorporate.vue, src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue
The updated logic and settings around which loan display is visible and how we move between them is to resolve [MRKT-493](https://kiva.atlassian.net/browse/MRKT-493).
The Footer theme update just needed to be done as it wasn't resolved when we removed themes ;(
Before:
After:
=> Ml landing loan display

src/pages/Lend/LoanChannelCategoryExperiment.vue, src/pages/Lend/LoanChannelCategoryPage.vue
ACK-227
* TODO - activate experiment switching in parent template
Working great. 
* Copied paging  functionality from Control template
* Added loading and query watching to load loans. 
* Added all categories and sub categories mapped to their query params. 
Ok to merge since template is still disabled. After follow up PR for experiment assigning we can test in dev
=> feat: lbc experiment layout category definitions and functionality

src/pages/Lend/LoanChannelCategoryControl.vue, src/pages/Lend/LoanChannelCategoryExperiment.vue, src/pages/Lend/LoanChannelCategoryPage.vue
ACK-227
Test URL: 
dev.kiva.org/lend-by-category/women?setuiab=lend_by_category_v2.shown
=> feat: toggle experimental layout in lend by category page

src/components/BorrowerProfile/LoanUse.vue, src/components/LoanCards/KivaClassicBasicLoanCardExp.vue, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
Carousel controls were hidden and cards were resized
=> Hero section core 454

src/components/LoanCards/KivaClassicBasicLoanCardBundleExp.vue, src/components/LoanCollections/KivaClassicLoanCarouselExp.vue, src/graphql/query/getRelatedLoans.graphql, src/pages/Lend/LoanChannelCategoryControl.vue, src/pages/Lend/LoanChannelCategoryPage.vue
Loan bundles were added for the lend by category page
=> Add bundles core 461

src/pages/Lend/LoanChannelCategoryExperiment.vue
* Remove hero header with background
* add breadcrumbs back
* add more button to link to filter page
ACK-272
=> feat: lend by category v3 layout adjustments

src/pages/BorrowerProfile/BorrowerProfile.vue
These are the ids we talked about for CORE-412, should be all of them in conjunction with Davids PR
=> chore: add some data-testids for borrower page

src/components/BorrowerProfile/LoanDescription.vue, src/components/BorrowerProfile/LoanProgress.vue, src/components/BorrowerProfile/LoanStory.vue, src/components/BorrowerProfile/PreviousLoanDescription.vue, src/components/BorrowerProfile/SummaryCard.vue, src/pages/BorrowerProfile/BorrowerProfile.vue
@mcstover and @SqueakAttack here are my data-testids for the summary, story and description sections of the page.
=> chore: add data-testids for some sections of the borrower profile page

src/components/BorrowerProfile/BorrowerBusinessDetails.vue, src/components/BorrowerProfile/BorrowerCountry.vue, src/components/BorrowerProfile/CountryInfo.vue, src/components/BorrowerProfile/DescriptionListItem.vue, src/components/BorrowerProfile/DetailsTabs.vue, src/components/BorrowerProfile/FieldPartnerDetails.vue, src/components/BorrowerProfile/LendCta.vue, src/components/BorrowerProfile/LoanDetails.vue, src/components/BorrowerProfile/MoreAboutLoan.vue, src/components/BorrowerProfile/RepaymentSchedule.vue, src/components/BorrowerProfile/TrusteeDetails.vue
These should be all the data-testids need.
=> chore: add more data-testids for borrower profile page

src/components/WwwFrame/PromotionalBanner/Banners/PromoCreditBanner.vue, src/components/WwwFrame/SearchBar.vue, src/components/WwwFrame/TheHeader.vue, test/unit/specs/components/WwwFrame/SearchBar.spec.js
This should be the last of the changes for VUE-980.
=> fix: added needed testid for header and banner

src/graphql/query/thanksPage.graphql, src/pages/Thanks/ThanksPage.vue
Now  that the subscriptions service is available in testing environments, we can clean this up to solve layout issues for modern subs users. 
ACK-270
=> fix: thanks page layout and upsell for new subscription service users

src/components/Checkout/CheckoutDropInPaymentWrapper.vue, src/components/Payment/BraintreeDropInInterface.vue
updates braintree drop-in styles per design request
* update headers to centered and normal casing / standard font
* update `Choose a way to pay` link style
* update for rounded corners
=> Core 374 update checkout styles

server/available-routes-middleware.js, server/dev-server.js, server/index.js, server/sitemap/generators/contentful-pages.js, server/sitemap/generators/index.js, server/sitemap/generators/lending-categories.js, server/sitemap/generators/static.js, server/sitemap/middleware.js, server/util/fetchGraphQL.js, server/util/live-loan/live-loan-fetch.js, src/router/routes.js, test/e2e/specs/Sitemap.spec.js
This adds an XML sitemap for search engine crawlers to read so that they know where the content on our site is! Any routes that require authentication or are otherwise not meant to be "public" (like corporate campaign pages) are not included in the sitemap. This sitemap is only for the routes handled by UI; other routes are in other sitemaps.
The sitemap will be cached for 1 hour, so that the api is not touched frequently. With that cache time it will take up to 2 hours for any changes to the route list to show up in the sitemap.
This is the sitemap that would be generated by this PR currently, please review it and call out anything that's missing or that shouldn't be included:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset
xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url> …
```
=> UI XML sitemap MARS-42

src/pages/Lend/LendByCategoryPage.vue, src/pages/Lend/LoanChannelCategoryPage.vue, test/e2e/specs/MetaInfo.spec.js
Update specific meta titles and descriptions depending on the category visited.
=> feat: add meta info to lend-by-category pages

package-lock.json, src/pages/MonthlyGood/LandingFormOptionalChoiceExp.vue, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue
- implements false door experience/lightbox for monthly good optional choice experiment
- also updates `max-width` for mg optional choice landing page to be wider per design request
mobile:
desktop:
=> feat: monthly good optional choice exp false door lightbox

src/components/Checkout/KivaCardRedemption.vue
Updated component with TW classes
=> fix: update kiva card to tw CORE-534

src/components/LoanCards/Buttons/ActionButton.vue, src/components/LoanCards/Buttons/LendAmountButton.vue
A new lend button to be implemented across marketplace when a loan has <$25 left.
=> feat: dynamic lend amount button

src/components/Checkout/LoanPrice.vue
LoanPrice component was updated to hide the dropdown element if the price is less than 25.
=> Stranded loans checkout core 554

src/components/Lend/LoanSearch/LoanSearchInterface.vue, src/pages/Lend/LoanSearchPage.vue
**Steps to test:**
1. Goto [http://localhost:8888/lend/filter-alpha](http://localhost:8888/lend/filter-alpha)
2. It should display the **LoanSearchPage** correctly
=> feat: extract func from filteralpha to loansearch VUE-1001

package-lock.json, src/pages/AutoDeposit/AutoDepositLandingPage.vue, src/pages/MonthlyGood/MonthlyGoodLandingPage.vue, test/e2e/specs/MetaInfo.spec.js
Added meta info to Auto Deposit and Monthly Good pages.
=> feat: added meta information
